hibernate/hibernate-search

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4364

HSEARCH-4364 Upgrade to the latest version of Eclipse ECJ

---

documentation/src/main/asciidoc/reference/coordination.asciidoc
integrationtest/mapper/orm-coordination-database-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/coordination/databasepolling/DatabasePollingAutomaticIndexingBackendFailureIT.java
integrationtest/mapper/orm-coordination-database-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/coordination/databasepolling/DatabasePollingAutomaticIndexingBaseIT.java
integrationtest/mapper/orm-coordination-database-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/databasepolling/FilteringOutboxEventFinder.java
mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/cfg/HibernateOrmMapperDatabasePollingSettings.java
mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/event/impl/DatabasePollingOutboxEventAdditionalJaxbMappingProducer.java
mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/event/impl/DefaultOutboxEventFinder.java
mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/event/impl/EntityIdHashRangeOutboxEventPredicate.java
mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/event/impl/OutboxEvent.java
mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/event/impl/OutboxEventAndPredicate.java
mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/event/impl/OutboxEventBackgroundProcessor.java
mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/event/impl/OutboxEventPredicate.java
mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/event/impl/OutboxEventUpdater.java
mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/impl/DatabasePollingCooordinationStrategy.java
mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/logging/impl/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-4194

HSEARCH-4194 Guarantee a minimum delay on processing retries of outbox events

---

integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingDynamicShardingRebalancingIT.java
integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/PerSessionFactoryIndexingCountHelper.java
mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/AgentInstructions.java
mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxPollingEventProcessor.java
mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxPollingEventProcessorClusterLink.java
mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/impl/OutboxPollingCooordinationStrategy.java
mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/AbstractClusterLinkBaseTest.java
mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/AbstractClusterLinkTest.java
mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/ClusterLinkLeaveClusterTest.java
mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/ClusterLinkStaticShardingEdgeCasesTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4369

HSEARCH-4369 The outbox event processors apply the polling interval even when there are still events to process

---

documentation/src/main/asciidoc/reference/coordination.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4368

HSEARCH-4368 Follow-up: link fixes

---

integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingDynamicShardingRebalancingIT.java
mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxPollingEventProcessorClusterLink.java
mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/AbstractClusterLinkBaseTest.java
mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/AgentRepositoryMockingHelper.java
mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/ClusterLinkPulseExpectations.java

https://hibernate.atlassian.net/browse/HSEARCH-4370

HSEARCH-4370 Event processing triggers deadlock with Oracle database

---

integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/OutboxPollingOrmSetupHelperConfig.java
integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingBaseIT.java
integrationtest/mapper/orm-coordination-outbox-polling/src/test/resources/META-INF/services/org.hibernate.search.util.impl.integrationtest.mapper.orm.OrmSetupHelperConfig
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingElementCollectionIT.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmSetupHelper.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmSetupHelperConfig.java

https://hibernate.atlassian.net/browse/HSEARCH-4373

HSEARCH-4373 Use a java service to set the coordinationStrategyExpectations

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4371
Backported to 5.10 as #2716

HSEARCH-4371 Upgrade to Byteman 4.0.18

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4371
Backport of #2715 to branch 5.10

Backport HSEARCH-4371 to branch 5.10 - Upgrade to Byteman 4.0.18

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4367

HSEARCH-4367 Upgrade to Lucene 8.11

---

.github/dependabot.yml

https://hibernate.atlassian.net/browse/HSEARCH-4377

HSEARCH-4377 Enable GitHub's Dependabot

---

documentation/src/main/asciidoc/reference/architecture.asciidoc
documentation/src/main/asciidoc/reference/components/incubating-warning.asciidoc
documentation/src/main/asciidoc/reference/coordination.asciidoc
mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/HibernateOrmMapperOutboxPollingSettings.java

https://hibernate.atlassian.net/browse/HSEARCH-4375

HSEARCH-4375 Mark the outbox-polling coordination strategy as incubating in the documentation

---

integrationtest/performance/backend/elasticsearch/pom.xml
integrationtest/performance/backend/lucene/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4378

HSEARCH-4378 Follow-up: various fixes related to the upgrade of build dependencies to the latest version

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4398

HSEARCH-4398 Remove the unnecessary transitive dependency to lucene-sandbox

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4400

HSEARCH-4400 Upgrade to Hibernate ORM 5.6.2.Final

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/LuceneAnalysisConfigurationContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/model/dsl/LuceneAnalysisOptionalComponentsStep.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/model/dsl/LuceneAnalyzerTokenizerStep.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/model/dsl/impl/AbstractLuceneAnalysisComponentParametersStep.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/model/dsl/impl/LuceneAnalysisConfigurationContextImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/model/dsl/impl/LuceneAnalyzerComponentsStep.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/model/dsl/impl/LuceneNormalizerComponentsStep.java
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/reference/backend-lucene.asciidoc
documentation/src/main/asciidoc/reference/getting-started.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/analysis/AdvancedLuceneAnalysisConfigurer.java
documentation/src/test/java/org/hibernate/search/documentation/analysis/CustomSimilarityLuceneAnalysisConfigurer.java
documentation/src/test/java/org/hibernate/search/documentation/analysis/LuceneAnalysisIT.java
documentation/src/test/java/org/hibernate/search/documentation/analysis/LuceneClassesAnalysisConfigurer.java
documentation/src/test/java/org/hibernate/search/documentation/analysis/MyLuceneAnalysisConfigurer.java
documentation/src/test/java/org/hibernate/search/documentation/gettingstarted/withhsearch/customanalysis/MyLuceneAnalysisConfigurer.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/analysis/LuceneAnalysisConfigurerIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/index/LuceneIndexManagerIT.java
util/internal/integrationtest/backend/lucene/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/lucene/LuceneAnalysisUtils.java

https://hibernate.atlassian.net/browse/HSEARCH-4404

HSEARCH-4404 Methods in Lucene analysis configurers to define analyzers/normalizers without referring to Lucene classes

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4405

Backport HSEARCH-4405 to branch 6.0 - Upgrade to log4j 2.15

---

CONTRIBUTING.md
Jenkinsfile
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
parents/integrationtest/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4412

HSEARCH-4412 Compatibility with OpenSearch 1.2.1

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4421
Backport of #2802

Backport HSEARCH-4421 to branch 6.0 - Upgrade to Log4j 2.17.1

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DependencyIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorMonomorphicDirectValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-4423

HSEARCH-4423 False positive in detection of cycles in indexing dependency graph

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DependencyIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-4423
Backport of #2809

Backport HSEARCH-4423 to branch 6.0 - False positive in detection of cycles in indexing dependency graph

---

.github/dependabot.yml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4424
Follow-up to #2802

HSEARCH-4424 Follow-up: Upgrade to latest version of build dependencies (continued)

---

mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxPollingOutboxEventAdditionalJaxbMappingProducer.java

https://hibernate.atlassian.net/browse/HSEARCH-4425

HSEARCH-4425 Mark non-nullable properties in OutboxEvent definition

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4427

HSEARCH-4427 Run tests against Elasticsearch 6.8.22

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchTextRegexpPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextRegexpPredicate.java
documentation/src/main/asciidoc/reference/search-dsl-predicate.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/RegexpPredicateOptionsStep.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/RegexpQueryFlag.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/RegexpPredicateFieldMoreStepImpl.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/RegexpPredicateBuilder.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RegexpPredicateSpecificsIT.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubSearchPredicate.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubSearchPredicateBuilderFactory.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/types/impl/StubIndexValueFieldType.java

https://hibernate.atlassian.net/browse/HSEARCH-4362

HSEARCH-4362 Customizable optional operators for the regexp query

---

.github/dependabot.yml
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/gson/spi/GsonClasses.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/gson/spi/GsonClassesTest.java
integrationtest/performance/backend/base/pom.xml
integrationtest/performance/backend/base/src/main/java/org/hibernate/search/integrationtest/performance/backend/base/testsupport/filesystem/TemporaryFileHolder.java
mapper/orm/pom.xml
pom.xml
util/internal/test/common/pom.xml
util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/file/FileUtils.java
util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/jar/JandexAnnotationUtils.java
util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/jar/JandexIndexingUtils.java
util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/jar/JarUtils.java
util/internal/test/common/src/test/java/org/hibernate/search/util/impl/test/jar/JandexIndexingUtilsTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4428

HSEARCH-4428 Add missing classes to org.hibernate.search.backend.elasticsearch.gson.spi.GsonClasses

---

.github/workflows/contributor-build.yml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4430

HSEARCH-4430 Upgrade to latest version of build dependencies

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4436

HSEARCH-4436 Upgrade to Hibernate ORM 5.6.3.Final

---

integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingCustomEntityMappingIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4439

HSEARCH-4439 Fix tests involving overrides of outbox-polling entity mapping on MySQL

---

integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendHelper.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckBackendHelper.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryTimeoutIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendHelper.java
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/query/timeout/Clock.java
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/query/timeout/JPATimeoutTest.java
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/query/timeout/TimeoutTest.java
util/internal/integrationtest/backend/lucene/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/lucene/query/SlowQuery.java

https://hibernate.atlassian.net/browse/HSEARCH-4440

HSEARCH-4440 Fix OutOfMemoryError thrown by Elasticsearch in tests

---

documentation/src/main/asciidoc/reference/coordination.asciidoc
mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/HibernateOrmMapperOutboxPollingSettings.java

https://hibernate.atlassian.net/browse/HSEARCH-4442

HSEARCH-4442 Fix errors and clarify documentation of outbox-polling configuration

---

mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cluster/impl/OutboxPollingAgentAdditionalJaxbMappingProducer.java
mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxPollingOutboxEventAdditionalJaxbMappingProducer.java
orm6/mapper/orm-coordination-outbox-polling/ant-src-changes.patch

https://hibernate.atlassian.net/browse/HSEARCH-4443

HSEARCH-4443 Enum properties in outbox-polling entities (agent, outboxevent) have a weird type in database

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4445

HSEARCH-4445 Test against Elasticsearch 7.16.3

---

documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/reference/coordination.asciidoc
documentation/src/main/asciidoc/reference/search-dsl-predicate.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4452

HSEARCH-4452 Fix formatting of documentation about regexp predicate's optional operators

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4457

HSEARCH-4457 Upgrade to Hibernate ORM 5.6.4.Final

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainedSideIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainingSideIT.java

https://github.com/fax4ever/hibernate-search/tree/HSEARCH-4417

HSEARCH-4417 Force classloader precedence to EnhancingClassLoader

---

Jenkinsfile
build-config/pom.xml
distribution/pom.xml
documentation/pom.xml
integrationtest/elasticsearch/pom.xml
integrationtest/jdk9-modules/pom.xml
integrationtest/jms/pom.xml
integrationtest/jsr352/pom.xml
integrationtest/narayana/pom.xml
integrationtest/osgi/karaf-features/pom.xml
integrationtest/osgi/karaf-it/pom.xml
integrationtest/performance/engine-elasticsearch/pom.xml
integrationtest/performance/engine-lucene/pom.xml
integrationtest/performance/orm/pom.xml
integrationtest/performance/sandbox/pom.xml
integrationtest/spring/pom.xml
integrationtest/wildfly/pom.xml
jbossmodules/testing/pom.xml
pom.xml
reports/pom.xml
sharedtestresources/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4415

Backport HSEARCH-4415 to branch 5.11 - Sign published artifacts

---

Jenkinsfile
build-config/pom.xml
distribution/pom.xml
documentation/pom.xml
integrationtest/elasticsearch/pom.xml
integrationtest/jdk9-modules/pom.xml
integrationtest/jms/pom.xml
integrationtest/jsr352/pom.xml
integrationtest/narayana/pom.xml
integrationtest/osgi/karaf-features/pom.xml
integrationtest/osgi/karaf-it/pom.xml
integrationtest/performance/engine-elasticsearch/pom.xml
integrationtest/performance/engine-lucene/pom.xml
integrationtest/performance/orm/pom.xml
integrationtest/performance/sandbox/pom.xml
integrationtest/spring/pom.xml
integrationtest/wildfly/pom.xml
jbossmodules/testing/pom.xml
pom.xml
reports/pom.xml
sharedtestresources/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4415

Backport HSEARCH-4415 to branch 5.10 - Sign published artifacts

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4462

HSEARCH-4462 Upgrade to Hibernate ORM 5.6.5.Final

---

documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/entityindexmapping/User.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/reindexing/reindexonupdate/no/correct/Sensor.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/reindexing/reindexonupdate/no/incorrect/Sensor.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontaining/AutomaticIndexingManyToManyOwnedByContainingMapKeysBaseIT.java
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/query/nullValues/Value.java
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/query/validation/QueryValidationTest.java
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/spatial/SpatialSearchSortByDistanceAndPagingTest.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4463

HSEARCH-4463 Upgrade to H2 2.1.210 in tests

---

Jenkinsfile
jenkins/release.groovy

https://hibernate.atlassian.net/browse/HSEARCH-4472

HSEARCH-4472 Move the release job to a separate Jenkinsfile

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4467
Follow-up on #2874

HSEARCH-4467 Follow-up: Upgrade build dependencies to the latest version

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4484
Follows up on #2895, #2902

HSEARCH-4484 Upgrade build dependencies to the latest version

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/PropertyBridgeRuntimePolymorphismHackIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/TypeBridgeRuntimePolymorphismHackIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4491

HSEARCH-4491 Test hack involving fromOtherEntity and getSelf to support runtime polymorphism in bridges

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingAssociationDeletionIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/MultiValuedPropertyAccessor.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontained/AutomaticIndexingManyToManyOwnedByContainedCollectionBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontained/AutomaticIndexingManyToManyOwnedByContainedListBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontaining/AutomaticIndexingManyToManyOwnedByContainingCollectionBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontaining/AutomaticIndexingManyToManyOwnedByContainingListBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontaining/AutomaticIndexingManyToManyOwnedByContainingMapKeysBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontaining/AutomaticIndexingManyToManyOwnedByContainingMapValuesBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontaining/AutomaticIndexingManyToManyOwnedByContainingSortedMapValuesBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontaining/AutomaticIndexingManyToManyOwnedByContainingSortedSetBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytoone/AutomaticIndexingManyToOneBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetomany/AutomaticIndexingOneToManyCollectionBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetomany/AutomaticIndexingOneToManyListBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedEagerOnBothSidesIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedLazyOnContainedSideIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedLazyOnContainingSideIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingEagerOnBothSidesIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainedSideIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainingSideIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4466

HSEARCH-4466 Test automatic indexing of bags as well as lists

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4504

HSEARCH-4504 Upgrade to JBeret 1.4.6.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4506

HSEARCH-4506 Upgrade to Elasticsearch client 8.1.0

---

build/config/src/main/resources/forbidden-runtime.txt
build/config/src/main/resources/forbidden-tests.txt
engine/src/test/java/org/hibernate/search/engine/cfg/SystemConfigurationPropertySourceTest.java
integrationtest/performance/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/performance/backend/elasticsearch/SmokeIT.java
jqassistant/rules.xml
pom.xml
util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/SystemHelper.java
util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/annotation/SuppressForbiddenApis.java
util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/annotation/SuppressJQAssistant.java

https://hibernate.atlassian.net/browse/HSEARCH-4507

HSEARCH-4507 Use a (safer) helper to set system properties in tests

---

orm6/mapper/orm/ant-src-changes.patch
orm6/mapper/orm/pom.xml
orm6/v5migrationhelper/orm/ant-src-changes.patch
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4509

HSEARCH-4509 Upgrade -orm6 artifacts to Hibernate ORM 6.0.0.CR2

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/collector/impl/DocumentReferenceCollector.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/collector/impl/IdentifierCollector.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/collector/impl/StoredFieldsCollector.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/facet/impl/LongMultiValueRangeCounter.java

https://hibernate.atlassian.net/browse/HSEARCH-4511

HSEARCH-4511 Use hppc collections where possible in low-level Lucene-related code

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4512

HSEARCH-4512 Upgrade to Hibernate ORM 5.6.7.Final

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/collector/impl/CollectorExecutionContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/join/impl/NestedDocsProvider.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/query/impl/Queries.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/aggregation/impl/AggregationExtractContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/ExtractionRequirements.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/LuceneCollectors.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneNestedPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneExtractableSearchResult.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/comparatorsource/impl/LuceneFieldComparatorSource.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/impl/AbstractLuceneDocumentValueSort.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/DistanceSortBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSortBaseIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4513

HSEARCH-4513 Using a SearchSort instance in multiple queries with the Lucene backend has side effects and leads to unexpected results

---

documentation/src/main/asciidoc/reference/getting-started.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4519
- use asciidoc link markup

HSEARCH-4519 Update link markup in Getting Started

---

build/config/src/main/resources/forbidden-internal.txt
build/config/src/main/resources/forbidden-public.txt
build/config/src/main/resources/forbidden-tests.txt
parents/internal/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4521

HSEARCH-4521 Upgrade to forbidden-apis 3.3+ and clean up configuration

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4523

HSEARCH-4523 Upgrade -orm6 artifacts to Hibernate ORM 6.0.0.Final

---

integrationtest/mapper/orm-envers/src/test/java/org/hibernate/search/integrationtest/mapper/orm/envers/EnversIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/mapping/definition/AnnotationMappingDiscoveryIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/GenericPropertyIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/PropertyInheritanceIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/TransientPropertyIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/smoke/AnnotationMappingSmokeIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/smoke/ProgrammaticMappingSmokeIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/workspace/AbstractSearchWorkspaceSimpleOperationIT.java
integrationtest/mapper/orm/src/test/java17/org/hibernate/search/integrationtest/mapper/orm/model/IndexedEmbeddedRecordIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/AnnotationMappingDiscoveryIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/model/GenericPropertyIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/model/PropertyInheritanceIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/smoke/AnnotationMappingSmokeIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/smoke/ProgrammaticMappingSmokeIT.java
integrationtest/mapper/pojo-base/src/test/java17/org/hibernate/search/integrationtest/mapper/pojo/model/IndexedEmbeddedRecordIT.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4526

HSEARCH-4526 Test mapping of Java Records

---

README.md
lgtm.yml

https://hibernate.atlassian.net/browse/HSEARCH-4530

HSEARCH-4530 Remove LGTM integration from the Hibernate Search GitHub repository

---

jakarta/mapper/orm/pom.xml
orm6/mapper/orm/pom.xml
pom.xml

* [HSEARCH-4529](https://hibernate.atlassian.net/browse/HSEARCH-4529): Upgrade to Hibernate Commons Annotations 6.0.0.Final for -orm6 artifacts
* [HSEARCH-4528](https://hibernate.atlassian.net/browse/HSEARCH-4528): Upgrade to latest version of Jakarta dependencies for -orm6/-jakarta artifacts
* [HSEARCH-4527](https://hibernate.atlassian.net/browse/HSEARCH-4527): Upgrade to jackson-databind 2.13.2.2 (this is a test dependency only)

HSEARCH-4527 + HSEARCH-4528 + HSEARCH-4529 Dependency upgrades

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSimpleQueryStringPredicate.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchTextRegexpPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneSimpleQueryStringPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextRegexpPredicate.java
documentation/src/main/asciidoc/reference/search-dsl-predicate.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RegexpPredicateSpecificsIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SimpleQueryStringPredicateSpecificsIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4536

HSEARCH-4536 .flags(Collections.emptySet()) doesn't disable all flags as expected for SimpleQueryPredicate

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4539

HSEARCH-4539 Upgrade to JBeret 1.4.7.Final

---

jakarta/mapper/orm/pom.xml
orm6/mapper/orm/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4540

HSEARCH-4540 Upgrade to the latest version of Jakarta dependencies in -orm6/-jakarta artifacts

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4543

HSEARCH-4543 Upgrade to Hibernate ORM 5.6.8.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4547

HSEARCH-4547 Upgrade Elasticsearch client to 8.1.3 and test against Elasticsearch 8.1.3

---

documentation/src/main/asciidoc/reference/search-dsl-projection.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/projection/ProjectionDslIT.java
engine/src/main/java/org/hibernate/search/engine/search/projection/dsl/CompositeProjectionAsStep.java
engine/src/main/java/org/hibernate/search/engine/search/projection/dsl/impl/AbstractCompositeProjectionAsStep.java
engine/src/main/java/org/hibernate/search/engine/search/projection/spi/ProjectionCompositor.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/CompositeProjectionMultiStepIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryResultLoadingOrTransformingIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/ValueWrapper.java
v5migrationhelper/engine/src/main/java/org/hibernate/search/query/engine/impl/HSQueryImpl.java

https://hibernate.atlassian.net/browse/HSEARCH-4553

HSEARCH-4553 Option to return composite/object projections as an object array

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4557

[5.10] HSEARCH-4557 Upgrade to Hibernate ORM 5.3.26.Final

---

.github/dependabot.yml
pom.xml

* [HSEARCH-4570](https://hibernate.atlassian.net/browse/HSEARCH-4570): Upgrade -orm6 artifacts to HCANN 6.0.1.Final
* [HSEARCH-4569](https://hibernate.atlassian.net/browse/HSEARCH-4569): Upgrade -orm6 artifacts to Hibernate ORM 6.0.1.Final

HSEARCH-4569 + HSEARCH-4570 Upgrade -orm6 artifacts to Hibernate ORM 6.0.1.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4585

HSEARCH-4585 Upgrade to Hibernate ORM 5.6.9.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4585
Backport of  #3057

Backport HSEARCH-4585 to branch 6.1 - Upgrade to Hibernate ORM 5.6.9.Final

---

engine/src/main/java/org/hibernate/search/engine/common/resources/spi/SavedState.java
engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-4589

[6.1] HSEARCH-4589 Safer closing of resources in SavedState

---

documentation/src/main/asciidoc/migration/index.asciidoc
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4587

HSEARCH-4587 Initialize migration guide with 6.2 changes so far

---

documentation/src/main/asciidoc/reference/search-dsl-projection.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/projection/ProjectionDslIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4553
Follows up on #3022

HSEARCH-4553 Follow-up: fix documentation of asArray() for composite/object projections

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4593

HSEARCH-4593 Upgrade to Elasticsearch client 8.2.1 and test against Elasticsearch 8.2.1

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4596

HSEARCH-4596 Upgrade to Hibernate ORM 6.0.2.Final for -orm6 artifacts

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4595
Backport of #3076 to branch 5.10

Backport HSEARCH-4595 to branch 5.10 - Upgrade to Byteman 4.0.19

---

integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingEventSendingIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4600

HSEARCH-4600 Fix flaky assertion in OutboxPollingAutomaticIndexingEventSendingIT

---

backend/elasticsearch-aws/src/main/java/org/hibernate/search/backend/elasticsearch/aws/impl/AwsSigningRequestInterceptor.java

- https://hibernate.atlassian.net/browse/HSEARCH-4604
It'll probably be cleaner to have a new PR for this issue, and I suppose we can close the other one - https://github.com/hibernate/hibernate-search/pull/3086

HSEARCH-4604 Add port while building an AWS request

---

integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingCustomEntityMappingIT.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4606

HSEARCH-4606 Upgrade to Hibernate ORM 6.1.0.Final for -orm6 artifacts

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4605

[5.10] HSEARCH-4605 Upgrade to Hibernate ORM 5.3.27.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4608

Backport HSEARCH-4608 to branch 6.1 - Upgrade to the latest version of Jakarta dependencies in -orm6/-jakarta artifacts

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4625

HSEARCH-4625 Upgrade to Elasticsearch client 8.3.1 and test against Elasticsearch 8.3.1

---

Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4626

HSEARCH-4626 Run tests against OpenSearch 2.0.1

---

.github/dependabot.yml
pom.xml

HSEARCH-4642 Upgrade build dependencies to the latest version

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4657

HSEARCH-4657 Upgrade to Elasticsearch client 8.3.3 and test against Elasticsearch 8.3.3

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4662

HSEARCH-4662 Test against AWS OpenSearch Service 1.3

---

Jenkinsfile
README.md
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4624

HSEARCH-4624 Move from Coveralls to Sonarcloud for code coverage

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4664

HSEARCH-4664 Upgrade to Hibernate ORM 6.1.2.Final for -orm6 artifacts

---

.github/dependabot.yml
parents/integrationtest/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4666

HSEARCH-4666 Change JDBC driver dependencies so that dependabot can update them

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4668

HSEARCH-4668 Avoid error logs when logging compiler/VM version during the build

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4671

[5.10] HSEARCH-4671 Upgrade to Hibernate ORM 5.3.28.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4672

HSEARCH-4672 Upgrade -orm6 artifacts to hibernate-commons-annotations 6.0.3.Final

---

mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMapping.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmDynamicMapRawTypeModel.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/scope/impl/HibernateOrmScopeMappingContext.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/scope/impl/SearchScopeImpl.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/spi/PojoTypeExtendedMappingCollector.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/spi/AbstractPojoMappingImplementor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/AbstractPojoRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PojoRawTypeModel.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/AbstractStandalonePojoTypeContext.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMapping.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/scope/impl/SearchScopeImpl.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/scope/impl/StandalonePojoScopeMappingContext.java

https://hibernate.atlassian.net/browse/HSEARCH-4552

HSEARCH-4552 Simplify some mapper SPIs

---

documentation/src/main/asciidoc/reference/architecture.asciidoc
documentation/src/main/asciidoc/reference/configuration.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4682

HSEARCH-4682 Fix heading levels in the Configuration section of the documentation

---

documentation/src/main/asciidoc/reference/architecture.asciidoc
documentation/src/main/asciidoc/reference/configuration.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4682
Backport of #3211 to branch 6.1

Backport HSEARCH-4682 to branch 6.1 - Fix heading levels in the Configuration section of the documentation

---

parents/integrationtest/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4684

HSEARCH-4684 Fix tests starting before postgresql containers are ready on CI

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/spi/ElasticsearchBackendImplSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientFactoryImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendFactory.java
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
engine/src/main/java/org/hibernate/search/engine/environment/bean/BeanHolder.java
engine/src/main/java/org/hibernate/search/engine/environment/bean/CloseableBeanHolder.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchContentLengthIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/mapping/ElasticsearchFieldAttributesIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/mapping/ElasticsearchFieldTypesIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/mapping/ElasticsearchTypeNameMappingSchemaIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/search/query/ElasticsearchSearchQueryIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/search/query/ElasticsearchSearchQueryRequestTransformerIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchClientSpy.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/work/ElasticsearchIndexingIT.java
util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/rule/TestElasticsearchClient.java

https://hibernate.atlassian.net/browse/HSEARCH-4683

HSEARCH-4683 Configuration property to provide an external RestClient to Hibernate Search

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4689

HSEARCH-4689 Upgrade to HCANN 6.0.4.Final for -orm6 artifacts

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneObjectProjection.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/impl/LuceneIndexCompositeNodeType.java
engine/src/main/java/org/hibernate/search/engine/backend/document/model/spi/AbstractIndexNode.java
engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java
engine/src/main/java/org/hibernate/search/engine/search/common/spi/AbstractMultiIndexSearchIndexNodeContext.java
engine/src/main/java/org/hibernate/search/engine/search/common/spi/SearchIndexNodeContext.java
engine/src/main/java/org/hibernate/search/engine/search/common/spi/SearchIndexSchemaElementContextHelper.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/ObjectStructureIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/dynamic/ObjectFieldTemplateIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/AbstractProjectionInObjectProjectionIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/DistanceProjectionBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/FieldProjectionBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/ObjectProjectionBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/ObjectProjectionSpecificsIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
integrationtest/v5migrationhelper/engine/src/test/java/org/hibernate/search/test/projection/ProjectionConversionTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4591

HSEARCH-4591 Allow object projections on single-valued, flattened object fields with the Lucene backend

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4693

HSEARCH-4693 Upgrade to Elasticsearch client 8.4.1 and test against Elasticsearch 8.4.1

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4692

HSEARCH-4692 Upgrade to Hibernate ORM 5.6.11.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4692

Backport HSEARCH-4692 to branch 6.1 - Upgrade to Hibernate ORM 5.6.11.Final

---

.github/dependabot.yml
distribution/pom.xml
distribution/src/main/assembly/dist.xml
integrationtest/mapper/orm-cdi/pom.xml
integrationtest/mapper/orm-spring/pom.xml
integrationtest/showcase/library/pom.xml
jakarta/integrationtest/mapper/orm-cdi/pom.xml
jakarta/mapper/orm-batch-jsr352/jberet/pom.xml
jakarta/mapper/orm/pom.xml
jakarta/parents/integrationtest/pom.xml
jakarta/parents/internal/pom.xml
jakarta/parents/public/pom.xml
jakarta/util/internal/integrationtest/jberet-se/pom.xml
mapper/orm-batch-jsr352/jberet/pom.xml
mapper/orm/pom.xml
mapper/pojo-base/pom.xml
orm6/integrationtest/mapper/orm-cdi/pom.xml
orm6/mapper/orm-batch-jsr352/jberet/pom.xml
orm6/mapper/orm-coordination-outbox-polling/pom.xml
orm6/mapper/orm/pom.xml
orm6/parents/integrationtest/pom.xml
orm6/parents/internal/pom.xml
orm6/parents/public/pom.xml
orm6/util/internal/integrationtest/jberet-se/pom.xml
pom.xml
util/common/pom.xml
util/internal/integrationtest/jberet-se/pom.xml
util/internal/integrationtest/v5migrationhelper/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4691

HSEARCH-4691 Remove dependency management for dependencies in common with Hibernate ORM

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4698

HSEARCH-4698 Upgrade to Hibernate ORM 6.1.3.Final for -orm6 artifacts

---

integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/FieldTypeDescriptor.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
pom.xml
util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/dialect/Elasticsearch712TestDialect.java
util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/dialect/ElasticsearchTestDialect.java

https://hibernate.atlassian.net/browse/HSEARCH-4704

HSEARCH-4704 Upgrade to Elasticsearch client 8.4.2 and test against Elasticsearch 8.4.2

---

documentation/src/main/asciidoc/reference/mapping-indexedembedded.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/filteredassociation/Book.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/filteredassociation/BookEdition.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/filteredassociation/FilteredAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/FilteredAssociationIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4710

HSEARCH-4710 Test and document how to apply @IndexedEmbedded to "filtered" associations

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4711

HSEARCH-4711 Upgrade -orm6 artifacts to Hibernate ORM 6.1.4.Final

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/IncorrectPropertyNameObjectPathIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4714
This should address the CI failure on JDK8

HSEARCH-4714 Use pattern in tests for asserting the message content

---

integrationtest/spring/pom.xml
orm/src/main/java/org/hibernate/search/impl/FullTextSessionImpl.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4107

Backport HSEARCH-4107 to branch 5.10 - Session cast fails when creating a FullTextSession with Spring Boot 2.4.0

---

documentation/src/main/asciidoc/reference/further-reading.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-getting-started.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4655

HSEARCH-4655 Add more links to the "Further reading" section of the documentation

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4717

[5.11] HSEARCH-4717 Upgrade to Byteman 4.0.20

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4717

Backport HSEARCH-4717 to branch 5.10 - Upgrade to Byteman 4.0.20

---

Jenkinsfile
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontained/AutomaticIndexingManyToManyOwnedByContainedCollectionBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontained/AutomaticIndexingManyToManyOwnedByContainedListBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontaining/AutomaticIndexingManyToManyOwnedByContainingCollectionBaseIT.java
mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cluster/impl/OutboxPollingAgentAdditionalJaxbMappingProducer.java
mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxPollingOutboxEventAdditionalJaxbMappingProducer.java
pom.xml

* [HSEARCH-4727](https://hibernate.atlassian.net/browse/HSEARCH-4727) OutboxEvent "payload" column created as blob(255) with DB2
* [HSEARCH-4732](https://hibernate.atlassian.net/browse/HSEARCH-4732) Run tests against DB2 and DB2 JDBC driver version 11.5.8.0

HSEARCH-4727 + HSEARCH-4732 OutboxEvent "payload" column created as blob(255) with DB2

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/SyntheticPropertyIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4733

HSEARCH-4733 Adapt SyntheticPropertyIT to Hibernate ORM 6.2

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4734

HSEARCH-4734 Upgrade -orm6 artifacts to Hibernate ORM 6.1.5.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4739

HSEARCH-4739 Upgrade to jackson-databind 2.13.4.2

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4747
the local build passed with no errors let's see if CI will too 😃

HSEARCH-4747 Upgrade to Hibernate ORM 5.6.14.Final

---

build/parents/integrationtest/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4722

HSEARCH-4722  Fix postgresql container start timing out on CI

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4751

HSEARCH-4751 Add compatibility with OpenSearch 2.4

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4758

HSEARCH-4758 Upgrade -orm6 artifacts to Hibernate ORM 6.1.6.Final

---

documentation/pom.xml
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4760

HSEARCH-4760 Update compatibility table in backend section

---

Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4762

HSEARCH-4762 Test against latest OpenSearch 1.3.7/2.4.1 versions

---

pom.xml

For HSEARCH-4642, folllows up on https://github.com/hibernate/hibernate-search/pull/3313, https://github.com/hibernate/hibernate-search/pull/3294, https://github.com/hibernate/hibernate-search/pull/3146, https://github.com/hibernate/hibernate-search/pull/3148, https://github.com/hibernate/hibernate-search/pull/3157, https://github.com/hibernate/hibernate-search/pull/3176, https://github.com/hibernate/hibernate-search/pull/3189, https://github.com/hibernate/hibernate-search/pull/3194, https://github.com/hibernate/hibernate-search/pull/3208, https://github.com/hibernate/hibernate-search/pull/3219, https://github.com/hibernate/hibernate-search/pull/3234, https://github.com/hibernate/hibernate-search/pull/3239, …

HSEARCH-4642 Upgrade build dependencies to the latest version 

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/session/SearchIndexingPlanBaseIT.java

https://hibernate.atlassian.net/browse/HSEARCH-939
Add a test for the scenario from the ticket

HSEARCH-939 Add test for IndexingPlan updating contained entity

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DocumentIdBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DocumentIdDefaultBridgeAdditionIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-4617

HSEARCH-4617 Update error message for missing identifier bridge

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchBooleanPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneBooleanPredicate.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/BooleanPredicateOptionsCollector.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/SimpleBooleanPredicateClausesCollector.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/AbstractBooleanPredicateClausesStep.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/AbstractSimpleBooleanPredicateClausesStep.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/BooleanPredicateBuilder.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/AndPredicateSpecificsIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/BoolPredicateSpecificsIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/OrPredicateSpecificsIT.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubSearchPredicate.java

https://hibernate.atlassian.net/browse/HSEARCH-4618

HSEARCH-4618 Add an hasClause() accessor in BooleanPredicateOptionsCollector/SimpleBooleanPredicateClausesCollector

---

engine/src/test/java/org/hibernate/search/engine/backend/orchestration/spi/BatchingExecutorTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4750
Supersedes #3336

HSEARCH-4750 Fix a flaky test for BatchExecutor

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingEmbeddableIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/AbstractAutomaticIndexingAssociationBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingEagerOnBothSidesIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainedSideIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainingSideIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4757

HSEARCH-4757 Adjust tests to address ORM changes introduced in HHH-15767

---

documentation/src/main/asciidoc/migration/index.asciidoc
engine/src/main/java/org/hibernate/search/engine/environment/classpath/spi/DefaultResourceResolver.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/JavaNetURLPropertyTypeDescriptor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultJavaNetURLBridge.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
util/common/src/main/java/org/hibernate/search/util/common/jar/impl/CodeSource.java
util/common/src/test/java/org/hibernate/search/util/common/jar/impl/CodeSourceTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4763

HSEARCH-4763 Replace usage of URL constructors with URI where possible

---

documentation/src/main/asciidoc/reference/configuration.asciidoc
documentation/src/main/asciidoc/reference/indexing-massindexer.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexing/HibernateOrmMassIndexerMultiTenancyIT.java
documentation/src/test/java/org/hibernate/search/documentation/testsupport/DocumentationSetupHelper.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingBaseIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMapping.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/HibernateOrmMassIndexingContext.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/scope/SearchScope.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/scope/impl/SearchScopeImpl.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/impl/HibernateOrmSearchSession.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoDefaultMassIndexer.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingBatchCoordinator.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingBatchIndexingWorkspace.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingEntityIdentifierLoadingRunnable.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingEntityLoadingRunnable.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/spi/PojoMassIndexingEntityLoadingContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/spi/PojoMassIndexingIdentifierLoadingContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/scope/impl/PojoScopeDelegateImpl.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/scope/spi/PojoScopeDelegate.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/loading/MassLoadingOptions.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/loading/SelectionLoadingOptions.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/loading/impl/StandalonePojoLoadingContext.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMapping.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/massindexing/impl/StandalonePojoMassIndexingLoadingStrategy.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/massindexing/impl/StandalonePojoMassIndexingMappingContext.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/scope/SearchScope.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/scope/impl/SearchScopeImpl.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/scope/impl/StandalonePojoScopeMappingContext.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/session/impl/StandalonePojoSearchSession.java

https://hibernate.atlassian.net/browse/HSEARCH-4321
To check with Yoann - I'm not sure about those loops in `PojoMassIndexingBatchCoordinator` over `coordinatorContexts` 😃

HSEARCH-4321 Mass indexing for multiple tenants at once

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4753

HSEARCH-4753 Run tests against OpenSearch 2.3 AWS

---

CONTRIBUTING.md
Jenkinsfile
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/LongFieldTypeDescriptor.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java

https://hibernate.atlassian.net/browse/HSEARCH-4740
[HSEARCH-4740]: https://hibernate.atlassian.net/browse/HSEARCH-4740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HSEARCH-4740 Run tests against Elasticsearch 7.17.8

---

MAINTAINERS.md
ci/dependency-update/Jenkinsfile
ci/list-container-images.sh
ci/list-dependent-integration-tests.sh

https://hibernate.atlassian.net/browse/HSEARCH-4770

HSEARCH-4770 Only update dependencies for test modules in dependency-update builds

---

engine/src/main/java/org/hibernate/search/engine/search/common/spi/AbstractMultiIndexSearchIndexCompositeNodeContext.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/ExistsPredicateObjectsSpecificsIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java

https://hibernate.atlassian.net/browse/HSEARCH-4050
Removing the restrictions seems to work fine. Need to check with Yoann to see what additional tests we should add.

HSEARCH-4050 Remove restriction on exists() predicate

---

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/ZonedDateTimeFieldTypeDescriptor.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexingFieldTypesIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4756

HSEARCH-4756 Use more timezone IDs in TCK tests

---

documentation/pom.xml
pom.xml

Move documentation to Google Analytics 4

---

documentation/pom.xml
pom.xml

[Backport - 6.1] Move documentation to Google Analytics 4

---

documentation/pom.xml
pom.xml

[Backport - 6.0] Move documentation to Google Analytics 4

---

documentation/pom.xml
pom.xml

[Backport - 5.11] Move documentation to Google Analytics 4

---

documentation/pom.xml
pom.xml

[Backport - 5.10] Move documentation to Google Analytics 4

---

Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4780

HSEARCH-4780 Test Hibernate Search against JDK 21

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/DefaultDecimalScaleMappingIT.java
integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/mapping/DecimalScaleMappingIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMappingConfigurationContributor.java

https://hibernate.atlassian.net/browse/HSEARCH-4782

HSEARCH-4782 Retrieve decimal scale automatically from entity identifiers

---

documentation/src/main/asciidoc/migration/index.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4786

[6.0] HSEARCH-4786 Fix non-compiling code in migration guide

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingEnvironmentIT.java

https://hibernate.atlassian.net/browse/HSEARCH-1809
We have this in the coordinator:
```java
Futures.unwrappedExceptionGet( Futures.firstFailureOrAllOf( allFutures ) );
```
And from what it looks on CI:
```
Expecting throwable message:
"HSEARCH700042: 1 failure(s) occurred during mass indexing. See the logs for details. First failure: don't call me."
```
It managed only to throw one exception before the coordinator thread took over and stopped everything. 
Hence I've made a slight change to only fail in one runnable to have a predictable result. An alternative could've been to remove the `2` from the message check and just look for
```
failure(s) occurred during mass indexing",
```

HSEARCH-1809 Follow-up: Only make the failure within one operation for predictable results

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4798
For HSEARCH-4642, folllows up on https://github.com/hibernate/hibernate-search/pull/3403, https://github.com/hibernate/hibernate-search/pull/3389, https://github.com/hibernate/hibernate-search/pull/3387, https://github.com/hibernate/hibernate-search/pull/3383, https://github.com/hibernate/hibernate-search/pull/3364, https://github.com/hibernate/hibernate-search/pull/3351, https://github.com/hibernate/hibernate-search/pull/3339, https://github.com/hibernate/hibernate-search/pull/3322, https://github.com/hibernate/hibernate-search/pull/3313, https://github.com/hibernate/hibernate-search/pull/3294, https://github.com/hibernate/hibernate-search/pull/3146, …

HSEARCH-4642 Upgrade build dependencies/HSEARCH-4798 Upgrade AWS SDK

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4797

HSEARCH-4797 Run tests against Elasticsearch 7.17.9

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4799

HSEARCH-4799 Fix deprecation warnings in tests with JDK 21

---

engine/src/main/java/org/hibernate/search/engine/environment/classpath/spi/DefaultServiceResolver.java
engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-4803
see https://github.com/hibernate/hibernate-search/pull/3421

[Backport - 6.1] HSEARCH-4803 Ignore service loading errors from non aggregated classloader

---

orm6/integrationtest/mapper/orm/ant-src-changes.patch

https://hibernate.atlassian.net/browse/HSEARCH-4721
See https://hibernate.atlassian.net/browse/HSEARCH-4721?focusedCommentId=110953S
See https://hibernate.atlassian.net/browse/HHH-16219

Revert HSEARCH-4721, re-disable tests because of HHH-16219 

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4809

HSEARCH-4809 Upgrade to Hibernate ORM 6.2.0.CR3

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/CustomConnectionKeepAliveStrategy.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientFactoryImpl.java
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
engine/src/main/java/org/hibernate/search/engine/cfg/impl/KeyContextImpl.java
engine/src/main/java/org/hibernate/search/engine/cfg/spi/KeyContext.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java
util/common/src/main/java/org/hibernate/search/util/common/impl/Contracts.java

https://hibernate.atlassian.net/browse/HSEARCH-4808
If you'd have an idea on how we can test a positive scenario for this property - that would be great 😃

HSEARCH-4808 Add keep alive configuration property

---

pom.xml

follows up on https://github.com/hibernate/hibernate-search/pull/3441, https://github.com/hibernate/hibernate-search/pull/3435, https://github.com/hibernate/hibernate-search/pull/3428, https://github.com/hibernate/hibernate-search/pull/3419

HSEARCH-4801 update build dependencies

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4821
TCK tests passed locally 🥳

HSEARCH-4821 Test against latest OpenSearch 1.3.9

---

orm6/build/parents/integrationtest/pom.xml
orm6/build/parents/internal/pom.xml
orm6/build/parents/public/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4829

HSEARCH-4829 Upgrade -orm6 artifacts to Hibernate ORM 6.2.0.CR4

---

ci/dependency-update/Jenkinsfile
ci/dependency-update/rules-orm6.3.xml

https://hibernate.atlassian.net/browse/HSEARCH-4830
Backport to branch 6.1: #3461

HSEARCH-4830 Test Hibernate Search regularly against Hibernate ORM 6.3.0-SNAPSHOT

---

pom.xml

follows up on https://github.com/hibernate/hibernate-search/pull/3465, https://github.com/hibernate/hibernate-search/pull/3456, https://github.com/hibernate/hibernate-search/pull/3446, https://github.com/hibernate/hibernate-search/pull/3441, https://github.com/hibernate/hibernate-search/pull/3435, https://github.com/hibernate/hibernate-search/pull/3428, https://github.com/hibernate/hibernate-search/pull/3419

HSEARCH-4801 Update build dependencies 

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/sort/impl/ElasticsearchDistanceSort.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/sort/impl/ElasticsearchStandardFieldSort.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/comparatorsource/impl/LuceneTextFieldComparatorSource.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/impl/LuceneGeoPointDistanceSort.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/impl/LuceneStandardFieldSort.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/impl/SortMissingValue.java
documentation/src/main/asciidoc/reference/search-dsl-sort.asciidoc
engine/src/main/java/org/hibernate/search/engine/search/sort/dsl/DistanceSortMissingValueBehaviorStep.java
engine/src/main/java/org/hibernate/search/engine/search/sort/dsl/FieldSortMissingValueBehaviorStep.java
engine/src/main/java/org/hibernate/search/engine/search/sort/dsl/impl/DistanceSortOptionsStepImpl.java
engine/src/main/java/org/hibernate/search/engine/search/sort/dsl/impl/FieldSortOptionsStepImpl.java
engine/src/main/java/org/hibernate/search/engine/search/sort/spi/DistanceSortBuilder.java
engine/src/main/java/org/hibernate/search/engine/search/sort/spi/FieldSortBuilder.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/DistanceSortBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSortBaseIT.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/sort/impl/StubSearchSort.java

https://hibernate.atlassian.net/browse/HSEARCH-4149

HSEARCH-4149 Add lowest/highest missing() sort options

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4842

HSEARCH-4842 Upgrade -orm6 artifacts to Hibernate ORM 6.2.1.Final

---

.github/dependabot.yml
backend/lucene/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4844

HSEARCH-4844 Add hppc to explicit dependencies

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4846

HSEARCH-4846 Upgrade -orm6 artifacts to Hibernate ORM 6.2.2.Final

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4850

HSEARCH-4850 Add compatibility with OpenSearch 2.7

---

ci/dependency-update/Jenkinsfile
ci/dependency-update/rules-lucene9.xml

https://hibernate.atlassian.net/browse/HSEARCH-4839

HSEARCH-4839 Test Hibernate Search regularly against Lucene 9.*.*

---

integrationtest/jsr352/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4854
Backport of #3504 to branch 5.10.

Backport HSEARCH-4854 to branch 5.10 - Work around build errors caused by the Maven Pipeline Integration Plugin on Jenkins CI

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4855

HSEARCH-4855 Run tests against Elasticsearch 7.17.10

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4858

HSEARCH-4858 Upgrade to Hibernate ORM 6.2.3.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4860

HSEARCH-4860 Upgrade -orm6 artifacts to Hibernate ORM 6.2.4.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4862

[5.10] HSEARCH-4862 Upgrade to Hibernate ORM 5.3.30.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4865

HSEARCH-4865 Bump maven-project-info-reports-plugin from 3.4.3 to 3.4.4

---

documentation/src/main/asciidoc/reference/indexing-automatic.asciidoc
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingDirtyCheckIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/cfg/HibernateOrmMapperSettings.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/impl/ConfiguredAutomaticIndexingStrategy.java

https://hibernate.atlassian.net/browse/HSEARCH-4866

HSEARCH-4866 Deprecate the dirty check property

---

.github/dependabot.yml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4865
follows up on https://github.com/hibernate/hibernate-search/pull/3524

HSEARCH-4865 Update build dependencies

---

ci/dependency-update/Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4872

HSEARCH-4872 Rebuild only some of the modules to speedup the build

---

Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4873

HSEARCH-4873 Test Hibernate Search against JDK 22

---

orm6/mapper/orm/ant-src-changes.patch
orm6/v5migrationhelper/orm/ant-src-changes.patch

https://hibernate.atlassian.net/browse/HSEARCH-4875

HSEARCH-4875 Follow-up: Simplify Search/ORM query adapters for ORM 6.2

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4880

HSEARCH-4880 Upgrade to Hibernate ORM 5.6.15.Final

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedCycleIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4876
😞  https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/main/702/pipeline/

HSEARCH-4876 Make tests compile on JDK21/22

---

build/parents/integrationtest/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4556

HSEARCH-4556 Follow up: Use a correct group id for the mysql driver

---

build/jqassistant/rules.xml

Only impacts the build, no Jira issue.

Update XML schema of JQAssistant rules

---

Jenkinsfile
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4885
https://hibernate.atlassian.net/browse/HSEARCH-4885
https://hibernate.atlassian.net/browse/HSEARCH-4887

HSEARCH-4885 / HSEARCH-4886 / HSEARCH-4887 Test against latest Opensearch/Elasticsearch / Upgrade Elasticsearch client

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4888

HSEARCH-4888 Upgrade to Hibernate ORM 6.2.6.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4888

Bakcport 6.2: HSEARCH-4888 Upgrade to Hibernate ORM 6.2.6.Final

---

mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/MutableEntityLoadingOptions.java

https://hibernate.atlassian.net/browse/HSEARCH-4890
~~Bassed on #3562 , which must be merged first.~~ => Done

HSEARCH-4890 Adapt calls to RootGraph#appliesTo() to Hibernate ORM 6.3

---

orm6/mapper/orm/ant-src-changes.patch

https://hibernate.atlassian.net/browse/HSEARCH-4890

Backport HSEARCH-4890 to branch 6.2 - Adapt calls to RootGraph#appliesTo() to Hibernate ORM 6.3

---

.github/hibernate-github-bot.yml

Since it should support multiple rules, I thought let's keep the regex simple 😃

Add Hibernate GitHub Bot ignore rules

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4394

HSEARCH-4394 Fix typos in excludes

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4555

HSEARCH-4555 Revert: Bump jboss-logging from 3.5.1.Final to 3.5.2.Final

---

.github/hibernate-github-bot.yml

Add Hibernate GitHub Bot ignore rules for JDBC drivers

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4891

HSEARCH-4891 Bump version.org.jberet from 2.1.1.Final to 2.1.2.Final

---

bom/build/pom.xml
ci/dependency-update/Jenkinsfile
pom.xml

- so that they are visible and upgradable by a maven version plugin
followup on https://github.com/hibernate/hibernate-search/pull/3588

HSEARCH-4861 Add properties to the build BOM

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4903

HSEARCH-4903 Upgrade to Hibernate ORM 6.2.7.Final

---

documentation/src/main/asciidoc/migration/index.adoc

https://hibernate.atlassian.net/browse/HSEARCH-4907
See also #3616 (similar, but not identical)

HSEARCH-4907 Fix links and formatting in the migration guide

---

documentation/src/main/asciidoc/public/getting-started/orm/index.adoc
documentation/src/main/asciidoc/public/getting-started/standalone/index.adoc
documentation/src/main/asciidoc/public/reference/_getting-started.adoc

https://hibernate.atlassian.net/browse/HSEARCH-4898

HSEARCH-4898 Update Getting Started guides

---

integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingOutOfOrderIdsIT.java
integrationtest/mapper/orm-spring/src/test/java/org/hibernate/search/integrationtest/spring/jta/entity/Box.java
mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/mapping/spi/HibernateOrmMapperOutboxPollingClassesTest.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4908

HSEARCH-4908 Upgrade to Hibernate ORM 6.3.0.CR1

---

.github/dependabot.yml
.github/hibernate-github-bot.yml

A few more rules based on PRs from this week 😃

Add more dependency bot rules

---

integrationtest/mapper/orm-spring-uberjar/application/pom.xml
integrationtest/mapper/orm-spring-uberjar/application/src/main/java/org/hibernate/search/integrationtest/spring/repackaged/application/Config.java
integrationtest/mapper/orm-spring-uberjar/application/src/main/java/org/hibernate/search/integrationtest/spring/repackaged/application/RepackagedApplication.java
integrationtest/mapper/orm-spring-uberjar/application/src/main/resources/application.yaml
integrationtest/mapper/orm-spring-uberjar/application/src/test/java/org/hibernate/search/integrationtest/spring/repackaged/application/RepackagedApplicationIT.java
integrationtest/mapper/orm-spring-uberjar/model/pom.xml
integrationtest/mapper/orm-spring-uberjar/model/src/main/java/acme/org/hibernate/search/integrationtest/spring/repackaged/model/MyEntity.java
integrationtest/mapper/orm-spring-uberjar/model/src/main/java/acme/org/hibernate/search/integrationtest/spring/repackaged/model/MyOtherEntity.java
integrationtest/mapper/orm-spring-uberjar/model/src/main/java/acme/org/hibernate/search/integrationtest/spring/repackaged/model/MyProjection.java
integrationtest/mapper/orm-spring-uberjar/pom.xml
integrationtest/mapper/orm-spring-uberjar/test/pom.xml
integrationtest/mapper/orm-spring-uberjar/test/src/test/java/org/hibernate/search/integrationtest/spring/repackaged/test/RepackagedAppIT.java
integrationtest/pom.xml
util/common/src/main/java/org/hibernate/search/util/common/jar/impl/CodeSource.java
util/common/src/main/java/org/hibernate/search/util/common/logging/impl/Log.java
util/common/src/test/java/org/hibernate/search/util/common/jar/impl/CodeSourceTest.java
util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/jar/JarTestUtils.java

https://hibernate.atlassian.net/browse/HSEARCH-4744
backport of https://github.com/hibernate/hibernate-search/pull/3619
now that the running the app can fail there's a ` <spring.exec.success.code>1</spring.exec.success.code>` property to set the expectation and exec plugin is using the `<executable>${java-version.test.launcher}</executable>` to run with the JDK we test with

HSEARCH-4744 [Backport 6.2] Try to read a nested jar on JDK13

---

documentation/src/main/asciidoc/public/reference/_mapper-pojo-standalone.adoc
documentation/src/test/java/org/hibernate/search/documentation/mapper/pojo/standalone/entrypoints/StandalonePojoReadPropertiesFromFileIT.java
documentation/src/test/resources/configuration/standalone-test.properties
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/bootstrap/ConfiguringPropertiesInSearchMappingBuilderIT.java
integrationtest/mapper/pojo-base/src/test/resources/standalone-test.properties
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/SearchMappingBuilder.java

https://hibernate.atlassian.net/browse/HSEARCH-4742

HSEARCH-4742 Add an option to add property source to Standalone POJO mapper builder

---

backend/elasticsearch-aws/pom.xml
backend/elasticsearch/pom.xml
backend/lucene/pom.xml
bom/public/pom.xml
build/config/pom.xml
build/enforcer/pom.xml
build/enforcer/src/main/java/org/hibernate/search/build/enforcer/DependencyManagementIncludesAllPublicArtifactsRule.java
build/enforcer/src/main/java/org/hibernate/search/build/enforcer/MavenProjectUtils.java
build/enforcer/src/main/java/org/hibernate/search/build/enforcer/PublicModuleIsDeployedRule.java
build/enforcer/src/main/java/org/hibernate/search/build/enforcer/PublicModuleIsSignedAndPublishedRule.java
build/parents/build/pom.xml
build/parents/internal/pom.xml
build/parents/public/pom.xml
distribution/pom.xml
engine/pom.xml
mapper/orm-batch-jsr352/core/pom.xml
mapper/orm-batch-jsr352/jberet/pom.xml
mapper/orm-coordination-outbox-polling/pom.xml
mapper/orm/pom.xml
mapper/pojo-base/pom.xml
mapper/pojo-standalone/pom.xml
pom.xml
util/common/pom.xml
v5migrationhelper/engine/pom.xml
v5migrationhelper/orm/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4902

HSEARCH-4902 Flatten all public POMs

---

documentation/src/main/asciidoc/public/reference/_mapping-indexedembedded.adoc
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/includeembeddedobjectid/Department.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/includeembeddedobjectid/Employee.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/includeembeddedobjectid/IndexedEmbeddedIncludeEmbeddedObjectIdIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/IndexedEmbedded.java

https://hibernate.atlassian.net/browse/HSEARCH-4816

HSEARCH-4816 Document `@IndexedEmbedded#includeEmbeddedObjectId`

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4911

[5.10] HSEARCH-4911 Upgrade to Hibernate ORM 5.3.31.Final

---

build/parents/public/pom.xml
mapper/orm-batch-jsr352/jberet/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4913

HSEARCH-4913 Generate module-info for `hibernate-search-mapper-orm-batch-jsr352-jberet`

---

.github/hibernate-github-bot.yml
pom.xml

since there are a lot of updates today, let's see if they will build OK

Update build dependencies

---

Jenkinsfile
build/parents/build/pom.xml
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4921

HSEARCH-4921 Upgrade to Elasticsearch client 8.9.1 and test against Elasticsearch 8.9.1

---

backend/elasticsearch-aws/pom.xml
documentation/pom.xml
documentation/src/main/asciidoc/public/getting-started/orm/index.adoc
documentation/src/main/asciidoc/public/getting-started/standalone/index.adoc
documentation/src/main/asciidoc/public/reference/_backend-elasticsearch.adoc
documentation/src/main/asciidoc/public/reference/_compatibility.adoc
documentation/src/main/asciidoc/public/reference/_schema.adoc
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerUpdateAnalyzerIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerUpdateCustomMappingIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerUpdateCustomSettingsIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerUpdateNormalizerIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java

https://hibernate.atlassian.net/browse/HSEARCH-4925

HSEARCH-4925 Improve documentation of Elasticsearch/OpenSearch compatibility

---

Jenkinsfile
build/parents/build/pom.xml
pom.xml

This config seems to make sense to me 😃, we'd build the entire project. Then, for any non-default env, we enable the incremental profile where this new plugin lives, and depending on the type of the env or what parameters we are passing to maven, we'd tweak the plugin properties. I've added some inline comments explaining the choice of params 😃

HSEARCH-4924 Configure a simple gitflow incremental build for non-default envs

---

Jenkinsfile

See https://hibernate.zulipchat.com/#narrow/stream/132092-hibernate-search-dev/topic/Git.20incremental.20builder.20and.20sonar
Creating as draft, I'll need to test this in a PR that actually changes only part of the code.

HSEARCH-4924 Follow-up: fix Sonar analysis

---

Jenkinsfile

I was looking at this: https://www.jenkins.io/blog/2018/07/02/whats-new-declarative-piepline-13x-sequential-stages/ (Running Multiple Stages with the Same agent, or environment, or options) Let's see if this builds 😃 🙈

HSEARCH-4924 Run pre-build and build stages on the same node

---

.github/dependabot.yml

Add more test/build dependencies to the `build-dependencies` group

---

Jenkinsfile

Some minor syntax changes + we'll mark stages as skipped if the incremental builds skips all relevant modules.
I only tested the various options/commands locally, I'm hoping to test it for real in another PR.

HSEARCH-4924 Follow-up: minor improvements to incremental builds

---

Jenkinsfile

This is to fix the fact that all non-default environments are marked as skipped as soon as one of them is, like here: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-3679/22/pipeline
Let's see if it works...

HSEARCH-4924 Follow-up: Fix markStageSkipped() marking all parallel executions as skipped

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4933

[6.2] HSEARCH-4933 Upgrade -orm6 artifacts to Hibernate ORM 6.2.8.Final

---

jakarta/mapper/orm/pom.xml
mapper/orm/pom.xml
orm6/mapper/orm/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4936

[6.2] HSEARCH-4936 Align bytebuddy dependency on Hibernate ORM

---

documentation/src/main/asciidoc/migration/index.adoc

- so that the list is displayed correctly

Tweak the migration guide formatting

---

MAINTAINERS.md

@marko-bekhta Please don't merge yet as it'll get in the way of the release, but feel free to point to other mistakes and I'll push new changes here.

Fix a few gaps and mistakes in MAINTAINERS.md

---

documentation/src/main/asciidoc/migration/index.adoc
orm6/build/parents/integrationtest/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4943

HSEARCH-4943 Add notes on differences between ORM 5 and ORM 6 outbox tables updates

---

util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/H2LazyMultiTenantConnectionProvider.java

HSEARCH-4944 Adjust tests to address ORM changes introduced in a recent ORM 6.3 snapshot

---

util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/H2LazyMultiTenantConnectionProvider.java

[Backport to 6.2] HSEARCH-4944 Adjust tests to address ORM changes introduced in a recent ORM 6.3 snapshot

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchTextRegexpPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextRegexpPredicate.java
documentation/src/main/asciidoc/migration/index.adoc
documentation/src/main/asciidoc/public/reference/_search-dsl-predicate.adoc
documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/RegexpQueryFlag.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RegexpPredicateSpecificsIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4937

HSEARCH-4937 Deprecate complement regex operator

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchTextRegexpPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextRegexpPredicate.java
documentation/src/main/asciidoc/migration/index.adoc
documentation/src/main/asciidoc/public/reference/_search-dsl-predicate.adoc
documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/RegexpQueryFlag.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RegexpPredicateSpecificsIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4938

HSEARCH-4938 Remove support for the complement operator

---

Jenkinsfile
build/container/elasticsearch/env-8.10.properties
build/parents/build/pom.xml
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4946

HSEARCH-4946 Upgrade to Elasticsearch client 8.10.0 and test against Elasticsearch 8.10.0

---

ci/dependency-update/Jenkinsfile
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/configuration/LobTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4920

Follow-up:  HSEARCH-4920 Do not check for source modifications in Elasticsearch upgrade job

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
build/container/elasticsearch/env-7.0.properties
build/container/elasticsearch/env-7.1.properties
build/container/elasticsearch/env-7.2.properties
build/container/elasticsearch/env-7.3.properties
build/container/elasticsearch/env-7.4.properties
build/container/elasticsearch/env-7.5.properties
build/container/elasticsearch/env-7.6.properties
build/container/elasticsearch/env-7.7.properties
build/container/elasticsearch/env-7.8.properties
build/container/elasticsearch/env-7.9.properties
build/parents/build/pom.xml
documentation/src/main/asciidoc/public/reference/_compatibility.adoc
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/document/DocumentElementDynamicFieldNameIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSortDynamicFieldIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexingFieldTypesIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4934

HSEARCH-4934 Drop compatibility with older versions of Elasticsearch/OpenSearch

---

ci/dependency-update/Jenkinsfile

HSEARCH-4944 Use correct project id to recompile for ORM 6.3 upgrade tests

---

.github/dependabot.yml

https://github.com/hibernate/hibernate-search/pull/3726
This one is for ^

Add Eclipse jdt dependency rule to dependabot

---

backend/elasticsearch/pom.xml
build/parents/build/pom.xml
mapper/orm-coordination-outbox-polling/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4957

HSEARCH-4957 Upgrade to Jackson 2.15.2

---

backend/elasticsearch/pom.xml
jakarta/mapper/orm-coordination-outbox-polling/pom.xml
mapper/orm-coordination-outbox-polling/pom.xml
orm6/mapper/orm-coordination-outbox-polling/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4957
Backport #3731 to branch 6.2

Backport HSEARCH-4957 to branch 6.2 - Upgrade to Jackson 2.15.2

---

Jenkinsfile
build/parents/build/pom.xml
build/reports/pom.xml
integrationtest/pom.xml
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/MultitenancyTestHelper.java

https://hibernate.atlassian.net/browse/HSEARCH-4959
https://hibernate.atlassian.net/browse/HSEARCH-4935

HSEARCH-4959 Upgrade to ORM 6.3.1 / HSEARCH-4935 Re-enable Spring integration tests after next 6.3 ORM upgrade

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4968

[Backport 6.2] HSEARCH-4968 Test against latest OpenSearch 1.3.13

---

integrationtest/mapper/orm-realbackend/pom.xml
integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/schema/management/ElasticsearchSchemaManagerExporterIT.java
integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/schema/management/LuceneSchemaManagerExporterIT.java
jakarta/integrationtest/mapper/orm-realbackend/pom.xml
orm6/integrationtest/mapper/orm-realbackend/pom.xml
util/common/src/main/java/org/hibernate/search/util/common/jar/impl/CodeSource.java
util/common/src/test/java/org/hibernate/search/util/common/jar/impl/CodeSourceTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4947
Backport of #3730 to branch 6.2
I've added the schema export test updates too, so it'll be easier to backport things in the future 😃

[Backport 6.2] HSEARCH-4947 Make sure that nested jars can be read on Windows

---

.github/dependabot.yml

I don't know about you, but my mailbox is already pretty full on Monday, so I'd rather it happened another day.

Dependabot: send PRs on Tuesday

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4978

HSEARCH-4978 Add compatibility with OpenSearch 2.10.0

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4978

[Backport 6.2] HSEARCH-4978 Add compatibility with OpenSearch 2.10.0

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4979

[5.10] HSEARCH-4979 Upgrade to Hibernate ORM 5.3.32.Final

---

build/parents/build/pom.xml
ci/dependency-update/Jenkinsfile
ci/dependency-update/rules-lucene9.8.xml

https://hibernate.atlassian.net/browse/HSEARCH-4982

HSEARCH-4982 Upgrade to Lucene 9.8

---

integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/MassIndexingJobWithCompositeIdIT.java
mapper/orm-batch-jsr352/core/src/main/java/org/hibernate/search/batch/jsr352/core/massindexing/util/impl/CompositeIdOrder.java
orm6/mapper/orm-batch-jsr352/core/ant-src-changes.patch
orm6/mapper/orm-coordination-outbox-polling/ant-src-changes.patch
orm6/mapper/orm/ant-src-changes.patch

https://hibernate.atlassian.net/browse/HSEARCH-4980
We'll also have to update the WIP branch, see #3757

Backport HSEARCH-4980 to branch 6.2 - Jakarta Batch job fails for entities with embedded ids

---

ci/dependency-update/Jenkinsfile

As suggested in https://github.com/hibernate/hibernate-search/pull/3755#discussion_r1341009786 😃

Simplify the source check logic configuration in a CI upgrade job

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4984

HSEARCH-4984 Upgrade Avro to 1.11.3

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4984

[Backport 6.1] HSEARCH-4984 Upgrade Avro to 1.11.3

---

ci/dependency-update/Jenkinsfile

HSEARCH-4944 Add missing comma in upgrade settings

---

orm6/util/internal/integrationtest/mapper/orm/ant-src-changes.patch
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4987
We may need to create a new release in JIRA 😃🙈

HSEARCH-4987 Upgrade -orm6 artifacts to Hibernate ORM 6.2.11.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4987
Maybe we should somehow automate this as now there are going to be more ORM releases 🙈 😃

HSEARCH-4987 Upgrade -orm6 artifacts to Hibernate ORM 6.2.13.Final

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FieldContainerExtractorBaseIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmBootstrapIntrospector.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/extractor/impl/ContainerExtractorBinder.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnBootstrapIntrospector.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/PojoSimpleHCAnnPropertyModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/PojoSimpleHCAnnRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/GenericContextAwarePojoGenericTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PojoTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/SyntheticPojoGenericTypeModel.java
mapper/pojo-base/src/test/java/org/hibernate/search/mapper/pojo/extractor/impl/ContainerExtractorBinderDefaultExtractorTest.java
mapper/pojo-base/src/test/java/org/hibernate/search/mapper/pojo/model/typepattern/impl/TypePatternMatcherFactoryTest.java
mapper/pojo-base/src/test/java/org/hibernate/search/mapper/pojo/testsupport/TestBeanResolver.java
mapper/pojo-base/src/test/java/org/hibernate/search/mapper/pojo/testsupport/TestIntrospector.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/model/impl/StandalonePojoBootstrapIntrospector.java
util/common/src/main/java/org/hibernate/search/util/common/reflect/impl/GenericTypeContext.java
util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/reflect/TypeCapture.java

https://hibernate.atlassian.net/browse/HSEARCH-4988
Best reviewed commit by commit, especially because there's one refactoring in the middle to allow for better testing.
EDIT: Considering the extent of the changes, I wouldn't backport unless we really need to.

HSEARCH-4988 Container extractor resolution leads to StackOverflowError on properties of type Path

---

ci/dependency-update/Jenkinsfile

[Backport 6.2] Remove update dependencies job throttling

---

.github/hibernate-github-bot.yml

See https://github.com/hibernate/hibernate-github-bot/pull/196

Ignore JIRA checks for commits targeting only build-related files

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingPolymorphicAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingPolymorphicAssociationPropertyAccessIT.java
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/embedded/polymorphism/PolymorphicAssociationContainedInTargetTest.java

https://hibernate.atlassian.net/browse/HSEARCH-5000

HSEARCH-5000 Address test failure with ORM 6.4 in PolymorphicAssociationContainedInTargetTest

---

integrationtest/mapper/orm-outbox-polling/pom.xml
integrationtest/mapper/orm-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/outboxpolling/OutboxPollingStrategyPropertyValueIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5011

HSEARCH-5011 Fix some tests no longer being executed as part of the build

---

ci/dependency-update/Jenkinsfile

Since we are patching those modules ...

Rebuild additional modules for affected by Lucene update dependency job

---

mapper/orm-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/outboxpolling/event/impl/OutboxEvent.java
mapper/orm-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/outboxpolling/mapping/spi/HibernateOrmMapperOutboxPollingClassesTest.java

https://hibernate.atlassian.net/browse/HSEARCH-5015

HSEARCH-5015 Make OutboxEvent non-final

---

.github/dependabot.yml
build/parents/build/pom.xml
documentation/pom.xml
documentation/src/main/asciidoc/public/getting-started/orm/index.adoc
documentation/src/main/asciidoc/public/getting-started/standalone/index.adoc
documentation/src/main/asciidoc/public/reference/_compatibility.adoc
documentation/src/main/asciidoc/public/reference/_mapping-configuration.adoc

https://hibernate.atlassian.net/browse/HSEARCH-5022
I didn't add links about specifics (like outbox-polling); we'll need to add that to the WildFly documentation.
Also, I'll send a different PR to 6.0 to mention something in the migration guide.

HSEARCH-5022 Mention WildFly in the documentation

---

documentation/src/main/asciidoc/public/getting-started/orm/index.adoc
documentation/src/main/asciidoc/public/getting-started/standalone/index.adoc
documentation/src/main/asciidoc/public/reference/_compatibility.adoc
documentation/src/main/asciidoc/public/reference/_mapping-configuration.adoc

https://hibernate.atlassian.net/browse/HSEARCH-5022
Backport of #3840 to branch 6.2.

Backport HSEARCH-5022 to branch 6.2 - Mention WildFly in the documentation

---

build/parents/build/pom.xml
integrationtest/mapper/orm-spring-uberjar/application/src/test/java/org/hibernate/search/integrationtest/spring/repackaged/application/RepackagedApplicationIT.java
pom.xml
util/common/src/main/java/org/hibernate/search/util/common/jar/impl/CodeSource.java
util/common/src/test/java/org/hibernate/search/util/common/jar/impl/CodeSourceTest.java

https://hibernate.atlassian.net/browse/HSEARCH-5024
A backport of https://github.com/hibernate/hibernate-search/pull/3844 (with the dependabot commit 😃)

Backport HSEARCH-5024 to 7.0 branch - Adjust Jandex index reading and building for nested JARs

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5027

HSEARCH-5027 Upgrade -orm6 artifacts to Hibernate ORM 6.2.14.Final

---

util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmSetupHelperCleaner.java

https://hibernate.atlassian.net/browse/HSEARCH-5029
This won't solve the problem, but since I've been looking at this part of the code and noticed that both ORM tickets are now resolved, we can get rid of the if and make things a bit faster. I've tried to run a test on a cockroachdb: without changes  ~3min40sec, with changes ~3min.

HSEARCH-5029 Simplify entity removal in ReusableOrmSetupHolder

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5030
😃 ⌚

HSEARCH-5030 Upgrade -orm6 artifacts to Hibernate ORM 6.2.15.Final

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/codec/impl/HibernateSearchKnnVectorsFormat.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/codec/impl/HibernateSearchLuceneCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/comparator/impl/DoubleValuesSourceComparator.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/comparator/impl/FloatValuesSourceComparator.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/comparator/impl/IntValuesSourceComparator.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/comparator/impl/LongValuesSourceComparator.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/lowlevel/impl/LuceneDoubleDomain.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/lowlevel/impl/LuceneFloatDomain.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/lowlevel/impl/LuceneIntegerDomain.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/lowlevel/impl/LuceneLongDomain.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/lowlevel/impl/LuceneNumericDomain.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/comparatorsource/impl/LuceneGeoPointDistanceComparatorSource.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/comparatorsource/impl/LuceneNumericFieldComparatorSource.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/comparatorsource/impl/LuceneTextFieldComparatorSource.java
build/parents/build/pom.xml
ci/dependency-update/Jenkinsfile
ci/dependency-update/rules-lucene9.9.xml
ci/dependency-update/rules-lucene9.xml
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/query/sorting/SortTest.java

https://hibernate.atlassian.net/browse/HSEARCH-5010
I don't see any Lucene 9.10 so far, but I left the lucene9 update job just in case... Otherwise this is just the wip branch with the final dependency version and an update to the ci update Jenkins file. Once we get this in we can drop both lucene9/lucene10 wip branches as they were identical 😃 (except the version)

HSEARCH-5010 Upgrade to Lucene 9.9

---

documentation/src/main/asciidoc/migration/index.adoc
documentation/src/main/asciidoc/public/reference/_coordination.adoc
integrationtest/mapper/orm-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingOutOfOrderIdsIT.java
integrationtest/mapper/orm-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/outboxpolling/schema/OutboxPollingCustomEntityMappingIT.java
mapper/orm-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/outboxpolling/cfg/impl/UuidDataTypeUtils.java
mapper/orm-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/outboxpolling/cluster/impl/OutboxPollingAgentAdditionalJaxbMappingProducer.java
mapper/orm-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/outboxpolling/event/impl/OutboxPollingOutboxEventAdditionalJaxbMappingProducer.java
mapper/orm-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/outboxpolling/mapping/impl/AdditionalMappingBuilder.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateSearchCompositeMappingProducer.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/spi/HibernateSearchOrmMappingProducer.java

https://hibernate.atlassian.net/browse/HSEARCH-5004

HSEARCH-5004 Default to SqlTypes.UUID instead of CHAR for the OutboxEvent/Agent ID in databases supporting it

---

Jenkinsfile
build/container/search-backend/elastic.Dockerfile
build/parents/build/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5032

HSEARCH-5032 Upgrade to Elasticsearch client 8.11.2 and test against Elasticsearch 8.11.2

---

Jenkinsfile
build/container/search-backend/elastic.Dockerfile
build/parents/build/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5036
https://hibernate.atlassian.net/browse/HSEARCH-5037

HSEARCH-5036 Upgrade to Elasticsearch client 8.11.3 and test against Elasticsearch 8.11.3 / HSEARCH-5037 Test against latest Elasticsearch 7.17.16

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5041

HSEARCH-5041 Test against latest OpenSearch 1.3.14

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5042

HSEARCH-5042 Upgrade to Hibernate ORM 6.4.1.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5042

Backport of HSEARCH-5042 to 7.0 - Upgrade to Hibernate ORM 6.4.1.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5044

HSEARCH-5044 Upgrade -orm6 artifacts to Hibernate ORM 6.2.16.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5043

HSEARCH-5043 Upgrade to Lucene 9.9.1

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5046
https://hibernate.atlassian.net/browse/HSEARCH-5047

HSEARCH-5047 Upgrade JBeret to 2.2.0.Final / HSEARCH-5046 Upgrade to AWS SDK 2.22.1

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5049

HSEARCH-5049 Upgrade -orm6 artifacts to Hibernate ORM 6.2.17.Final

---

build/container/ryuk.Dockerfile
build/parents/build/pom.xml
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/ObsoletePropertiesIT.java
pom.xml

https://github.com/hibernate/hibernate-search/pull/3890
https://github.com/hibernate/hibernate-search/pull/3887

Bump the build-dependencies

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5053

HSEARCH-5053 Upgrade -orm6 artifacts to Hibernate ORM 6.2.18.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5054

HSEARCH-5054 Upgrade -orm6 artifacts to Hibernate ORM 6.2.19.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5057
https://github.com/hibernate/hibernate-search/pull/3904

HSEARCH-5057 Bump software.amazon.awssdk:auth from 2.22.1 to 2.23.3

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5058

HSEARCH-5058 Upgrade -orm6 artifacts to Hibernate ORM 6.2.20.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5060

HSEARCH-5060 Upgrade to Hibernate ORM 6.4.2.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5060

Backport of HSEARCH-5060 to 7.0 -  Upgrade to Hibernate ORM 6.4.2.Final

---

integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/multitenant/RealBackendDatabaseMultitenancyIT.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/H2LazyMultiTenantConnectionProvider.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/MultitenancyTestHelper.java

https://hibernate.atlassian.net/browse/HSEARCH-5031
Opening this as a draft for now, as this is just a test + a fix for a multitenancy helper

HSEARCH-5031 Mass indexing ID loading queries with discriminator multi-tenancy may cross tenant boundaries in some cases

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
build/container/search-backend/elastic.Dockerfile
build/parents/build/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5059

HSEARCH-5059 Add compatiblity with Elasticsearch 8.12.0 and upgrade to Elasticsearch client 8.12.0

---

integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/multitenant/RealBackendDatabaseMultitenancyIT.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/H2LazyMultiTenantConnectionProvider.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/MultitenancyTestHelper.java

https://hibernate.atlassian.net/browse/HSEARCH-5031

Backport of HSEARCH-5031 to 7.0 - Mass indexing ID loading queries with discriminator multi-tenancy may cross tenant boundaries in some cases

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5063

HSEARCH-5063 Upgrade -orm6 artifacts to Hibernate ORM 6.2.21.Final

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/bootstrap/StandalonePojoIntegrationBooterIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/bootstrap/UnusedPropertiesIT.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/bootstrap/impl/StandalonePojoIntegrationBooterImpl.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/bootstrap/impl/StandalonePojoIntegrationPartialBuildState.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/bootstrap/spi/StandalonePojoIntegrationBooter.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/bootstrap/spi/StandalonePojoIntegrationBooterBehavior.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/cfg/spi/StandalonePojoMapperSpiSettings.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/SearchMapping.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/SearchMappingBuilder.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoEntityTypeContributor.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMappingInitiator.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoTypeConfigurationContributor.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoTypeContextContainer.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/model/impl/StandalonePojoBootstrapIntrospector.java
util/internal/integrationtest/mapper/pojo-standalone/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/pojo/standalone/StandalonePojoMappingHandle.java

https://hibernate.atlassian.net/browse/HSEARCH-5065

HSEARCH-5065 Two-phase boot for the standalone POJO mapper

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5066
And I thought that it was going to be just a few releases 😃 we might want to automate this kind of update to our maintenance branches as well 😄

HSEARCH-5066 Upgrade -orm6 artifacts to Hibernate ORM 6.2.22.Final

---

documentation/src/main/asciidoc/public/reference/_entrypoints.adoc
documentation/src/test/java/org/hibernate/search/documentation/mapper/pojo/standalone/entrypoints/StandalonePojoEntryPointsIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/search/SearchQueryBaseIT.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/logging/impl/Log.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/SearchMapping.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMapperDelegate.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMapping.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoTypeContextContainer.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/session/SearchSession.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/session/impl/StandalonePojoSearchSession.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/session/impl/StandalonePojoSearchSessionMappingContext.java

https://hibernate.atlassian.net/browse/HSEARCH-5067

HSEARCH-5067 Allow targeting entities by name in the Standalone POJO Mapper

---

integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/multitenant/RealBackendDatabaseMultitenancyIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5031

HSEARCH-5031 Make massindexer tests more compatible with serverless env configuration

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5069

HSEARCH-5069 Upgrade to Lucene 9.9.2

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/codec/impl/HibernateSearchKnnVectorsFormat.java
documentation/src/main/asciidoc/public/reference/_mapping-directfieldmapping.adoc
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/mapping/LuceneVectorFieldIT.java
integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/mapping/VectorFieldIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5020

HSEARCH-5020 Increase the max allowed dimension for a Lucene backend

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5071

HSEARCH-5071 Upgrade to Hibernate ORM 6.4.3.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5071

Backport of HSEARCH-5071 to 7.0 - Upgrade to Hibernate ORM 6.4.3.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5074

HSEARCH-5074 Bump version.org.jberet from 2.2.0.Final to 2.2.1.Final

---

Jenkinsfile
build/container/search-backend/elastic.Dockerfile
build/parents/build/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5077

HSEARCH-5077 Upgrade to Elasticsearch client 8.12.1 and test against Elasticsearch 8.12.1

---

Jenkinsfile
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5078
byte buddy should get an update from the ORM's BOM

HSEARCH-5078 Upgrade to Hibernate ORM 6.4.4.Final

---

build/parents/build/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5078

Backport of HSEARCH-5078 to 7.0 - Upgrade to Hibernate ORM 6.4.4.Final

---

integrationtest/mapper/orm-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingOutOfOrderIdsIT.java

Sooo I was trying to reproduce that problem I mentioned in https://hibernate.zulipchat.com/#narrow/stream/132092-hibernate-search-dev/topic/HSEARCH-5004 🙈 
It turned out the problem was in our test... what was happening with MSSQL:
1. an event is saved with an instant value of `2024-02-07T16:40:00.000Z`
2. our select in prepare statement would return `2024-02-07T17:40:00.000Z` (+1h because of the timezone)
3. new value is saved back
4. the test would need to wait for an hour to find any events available 🙈 
this should let ORM figure out all the JDBC strangeness.... (detach/merge since we are changing the ids)

Do not use prepared statement to update instance column values in tests

---

ci/dependency-update/Jenkinsfile
ci/dependency-update/rules-orm6.4plus.xml

Speaking of 6.4 branching out .... (I think 5-9 should be enough for 7.1 😃)

Test against Hibernate ORM 6.5+ snapshots in dependency update jobs

---

documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4563
😭

HSEARCH-4563 Use a correct predicate in the docs example

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5083
https://github.com/hibernate/hibernate-search/pull/3962

HSEARCH-5083 Bump software.amazon.awssdk:auth from 2.23.3 to 2.24.1

---

build/config/src/main/resources/checkstyle.xml

So that I stop pushing these to the remote 😭 😞 😃

Add a rule to prevent updating TCK runner include patterns

---

util/common/src/test/resources/log4j2.properties

https://hibernate.atlassian.net/browse/HSEARCH-5081

Backport HSEARCH-5081 to branch 7.0 - Fix very slow unit tests

---

util/common/src/test/resources/log4j2.properties

https://hibernate.atlassian.net/browse/HSEARCH-5081

Backport HSEARCH-5081 to branch 7.1 - Fix very slow unit tests

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/HibernateOrmIntegrationBooterIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/bootstrap/StandalonePojoIntegrationBooterIT.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/bootstrap/impl/StandalonePojoIntegrationPartialBuildState.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMapperDelegate.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMappingInitiator.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMappingPartialBuildState.java

https://hibernate.atlassian.net/browse/HSEARCH-5089

HSEARCH-5089 Retrieve the schema management strategy on start for the Standalone Pojo Mapper

---

build/container/database/postgresql.Dockerfile
build/parents/build/pom.xml

Looks like Dependabot was struggling a bit with this one 🙈

Update PostgreSQL driver and image to latest versions

---

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/multitenancy/MultiTenancyBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/sharding/RoutingVectorSearchIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5039
😔

HSEARCH-5039 Follow up on: Disable some tests for OpenSearch/Elasticsearch that do not support vectors

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingInheritanceIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5062

Follow up on HSEARCH-5062 Update regexps to address mssql queries

---

build/container/database/cockroachdb.Dockerfile
build/container/database/mariadb.Dockerfile
integrationtest/mapper/orm-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingDynamicShardingRebalancingIT.java
integrationtest/mapper/orm-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingLifecycleIT.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/extension/BackendIndexingWorkExpectations.java

https://hibernate.atlassian.net/browse/HSEARCH-4981

HSEARCH-4981 Use shorter transactions/wait longer for indexing to complete

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5099

HSEARCH-5099 Test against latest OpenSearch 1.3.15

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5101

HSEARCH-5101 Test against latest Elasticsearch 7.17.18

---

ci/dependency-update/Jenkinsfile

Fix invalid Groovy code in dependency-update Jenkins job

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingPolymorphicAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingPolymorphicAssociationPropertyAccessIT.java
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/embedded/polymorphism/PolymorphicAssociationContainedInTargetTest.java

https://hibernate.atlassian.net/browse/HSEARCH-5009

HSEARCH-5009 Re-enable some tests when HHH-17408 gets fixed

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5104

HSEARCH-5104 Upgrade Jackson to 2.15.4

---

util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/SearchBackendContainer.java

https://hibernate.atlassian.net/browse/HSEARCH-5001

HSEARCH-5001 Set -Xmx on OpenSearch containers used for tests

---

.github/dependabot.yml
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5106

HSEARCH-5106 Upgrade Jackson to 2.17.0

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/ExtractionRequirements.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/dsl/DocumentTree.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/dsl/LuceneSearchProjectionFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/dsl/impl/LuceneSearchProjectionFactoryImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneDocumentTreeProjection.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneSearchProjectionBuilderFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/ProjectionRequestContext.java
documentation/src/main/asciidoc/public/reference/_search-dsl-projection.adoc
documentation/src/test/java/org/hibernate/search/documentation/search/projection/LuceneProjectionDslIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneExtensionIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/DocumentAssert.java

https://hibernate.atlassian.net/browse/HSEARCH-4964

HSEARCH-4964 Projection on the document tree for the Lucene backend

---

build/parents/build/pom.xml

https://hibernate.zulipchat.com/#narrow/stream/132092-hibernate-search-dev/topic/Awaitility.20update/near/427500834

Downgrade Awaitility to 4.2.0

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/AbstractElasticsearchAggregation.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchSearchAggregation.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/highlighter/impl/ElasticsearchSearchHighlighter.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicate.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/ElasticsearchSearchProjection.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/ElasticsearchSearchSort.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/aggregation/impl/LuceneSearchAggregation.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/highlighter/impl/LuceneAbstractSearchHighlighter.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneSearchPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneSearchProjection.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/sort/impl/LuceneSearchSort.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/AbstractLuceneBucketAggregation.java
engine/src/main/java/org/hibernate/search/engine/backend/scope/spi/AbstractSearchIndexScope.java
engine/src/main/java/org/hibernate/search/engine/reporting/spi/EventContexts.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/aggregation/SingleFieldAggregationTypeCheckingAndConversionIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/highlight/AbstractHighlighterIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/NamedPredicateMultiIndexCompatibilityIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SearchPredicateIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/SearchProjectionIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/SearchSortIT.java
util/common/src/main/java/org/hibernate/search/util/common/impl/CollectionHelper.java
util/common/src/test/java/org/hibernate/search/util/common/impl/CollectionHelperTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4572

HSEARCH-4572 Using SearchPredicate/SearchProjection/SearchSort with broader scope than the search query

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/highlighter/impl/ElasticsearchSearchHighlighter.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/highlighter/impl/ElasticsearchSearchHighlighterImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/ElasticsearchFieldHighlightProjection.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/ProjectionRequestRootContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryRequestContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/highlighter/impl/LuceneAbstractSearchHighlighter.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/highlighter/impl/LuceneFastVectorSearchHighlighter.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/highlighter/impl/LucenePlainSearchHighlighter.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/highlighter/impl/LuceneUnifiedSearchHighlighter.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneFieldHighlightProjection.java
documentation/src/main/asciidoc/public/reference/_search-dsl-projection.adoc
documentation/src/test/java/org/hibernate/search/documentation/search/projection/ProjectionDslIT.java
documentation/src/test/java17/org/hibernate/search/documentation/search/projection/MyBookHighlightedTitleProjection.java
documentation/src/test/java17/org/hibernate/search/documentation/search/projection/ProjectionDslJava17IT.java
engine/src/main/java/org/hibernate/search/engine/search/projection/dsl/HighlightProjectionOptionsStep.java
engine/src/main/java/org/hibernate/search/engine/search/projection/dsl/SingleHighlightProjectionFinalStep.java
engine/src/main/java/org/hibernate/search/engine/search/projection/dsl/impl/HighlightProjectionOptionsStepImpl.java
engine/src/main/java/org/hibernate/search/engine/search/projection/dsl/spi/HighlightProjectionBuilder.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/highlight/AbstractHighlighterIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorHighlightProjectionIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/search/definition/binding/builtin/HighlightProjectionBinder.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/projection/impl/StubFieldHighlightProjection.java

https://hibernate.atlassian.net/browse/HSEARCH-5016

HSEARCH-5016 Allow binding a @HighlightProjection to a single-valued String (instead of List<String>) when using numberOfFragments(1)

---

build/parents/build/pom.xml
ci/dependency-update/Jenkinsfile
ci/dependency-update/rules-orm6.5.xml
ci/dependency-update/rules-orm6.6plus.xml
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingInheritanceIT.java
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/query/objectloading/mixedhierarchy/School.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchQueryAdapter.java
v5migrationhelper/orm/src/main/java/org/hibernate/search/query/hibernate/impl/FullTextQueryImpl.java

https://hibernate.atlassian.net/browse/HSEARCH-5111

HSEARCH-5111 Upgrade to Hibernate ORM 6.5.CR1

---

.github/hibernate-github-bot.yml

List build scans in a GitHub check

---

.mvn/extensions.xml
.mvn/gradle-enterprise.xml

https://github.com/hibernate/hibernate-search-develocity-extension/compare/1.0.11.Final...1.0.13.Final

Upgrade to hibernate-search-develocity-extension 1.0.13.Final

---

ci/dependency-update/Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5094
Follows up on #4044

HSEARCH-5094 Follow-up:  Fix syntax for setting environment variable in dependency-update Jenkinsfile

---

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateSpecificsIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5113

HSEARCH-5113 Update asserts and vectors matched in knn predicates

---

ci/dependency-update/Jenkinsfile
ci/dependency-update/rules-orm6.6plus.xml

This reverts commit 1355e339529836d866b6119904aa71c6e9860f10.
😃

Add ORM 6.6+ upgrade job configuration

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
build/container/search-backend/elastic.Dockerfile
build/parents/build/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5114

HSEARCH-5114   Add compatiblity with Elasticsearch 8.13.0 and upgrade to Elasticsearch client 8.13.0

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5115

HSEARCH-5115 Upgrade -orm6 artifacts to Hibernate ORM 6.2.23.Final

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5116

HSEARCH-5116 Test against latest Elasticsearch 7.17.19

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5117

HSEARCH-5117 Upgrade -orm6 artifacts to Hibernate ORM 6.2.24.Final

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
build/container/search-backend/amazon-opensearch-serverless.Dockerfile
build/container/search-backend/opensearch.Dockerfile
build/parents/build/pom.xml
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java

https://hibernate.atlassian.net/browse/HSEARCH-5122

HSEARCH-5122 Add compatibility with OpenSearch 2.13.0

---

Jenkinsfile
build/container/search-backend/elastic.Dockerfile
build/parents/build/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5121

HSEARCH-5121 Upgrade to Elasticsearch client 8.13.1 and test against Elasticsearch 8.13.1

---

Jenkinsfile
build/container/search-backend/elastic.Dockerfile
build/parents/build/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5125
https://hibernate.atlassian.net/browse/HSEARCH-5126

HSEARCH-5125 Upgrade to Elasticsearch client 8.13.2 / HSEARCH-5126 test against Elasticsearch 8.13.2

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/HibernateSearchMultiCollectorManager.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/LuceneCollectors.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryTimeoutIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5119

HSEARCH-5119 Use `IndexSearcher#setTimeout` instead of a TimeLimitingCollector

---

Jenkinsfile
documentation/pom.xml
documentation/src/main/asciidoc/public/reference/_compatibility.adoc
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5128

HSEARCH-5128 Update the supported versions of Java in the documentation

---

documentation/pom.xml
documentation/src/main/asciidoc/internals/index.adoc
documentation/src/main/asciidoc/migration/index.adoc
documentation/src/main/asciidoc/public/getting-started/index.adoc
documentation/src/main/asciidoc/public/getting-started/orm/index.adoc
documentation/src/main/asciidoc/public/getting-started/standalone/index.adoc
documentation/src/main/asciidoc/public/reference/index.adoc
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5123

HSEARCH-5123 Update generated docs metadata

---

documentation/pom.xml
documentation/src/main/asciidoc/internals/index.adoc
documentation/src/main/asciidoc/migration/index.adoc
documentation/src/main/asciidoc/public/getting-started/index.adoc
documentation/src/main/asciidoc/public/getting-started/orm/index.adoc
documentation/src/main/asciidoc/public/getting-started/standalone/index.adoc
documentation/src/main/asciidoc/public/reference/index.adoc
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5123
backport of https://github.com/hibernate/hibernate-search/pull/4099

Backport of HSEARCH-5123 to 7.1 - Update generated docs metadata

---

.github/dependabot.yml
documentation/pom.xml
documentation/src/main/asciidoc/internals/index.adoc
documentation/src/main/asciidoc/migration/index.adoc
documentation/src/main/asciidoc/public/getting-started/index.adoc
documentation/src/main/asciidoc/public/getting-started/orm/index.adoc
documentation/src/main/asciidoc/public/getting-started/standalone/index.adoc
documentation/src/main/asciidoc/public/reference/index.adoc
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5123
backport of https://github.com/hibernate/hibernate-search/pull/4099

Backport of HSEARCH-5123 to 6.2 - Update generated docs metadata

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5129

HSEARCH-5129 Test against latest Elasticsearch 7.17.20

---

build/reports/pom.xml
documentation/src/main/asciidoc/public/reference/_mapper-orm-indexing-jakarta-batch.adoc
integrationtest/mapper/orm-jakarta-batch/src/test/java/org/hibernate/search/integrationtest/jakarta/batch/massindexing/MassIndexingJobIT.java
mapper/orm-jakarta-batch/core/src/main/java/org/hibernate/search/jakarta/batch/core/logging/impl/Log.java
mapper/orm-jakarta-batch/core/src/main/java/org/hibernate/search/jakarta/batch/core/massindexing/MassIndexingJob.java
mapper/orm-jakarta-batch/core/src/main/java/org/hibernate/search/jakarta/batch/core/massindexing/MassIndexingJobParameters.java
mapper/orm-jakarta-batch/core/src/main/java/org/hibernate/search/jakarta/batch/core/massindexing/spi/JobContextSetupListener.java
mapper/orm-jakarta-batch/core/src/main/java/org/hibernate/search/jakarta/batch/core/massindexing/step/beforechunk/impl/BeforeChunkBatchlet.java
mapper/orm-jakarta-batch/core/src/main/resources/META-INF/batch-jobs/hibernate-search-mass-indexing.xml
mapper/orm-jakarta-batch/core/src/test/java/org/hibernate/search/jakarta/batch/core/massindexing/MassIndexingJobParametersBuilderTest.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/spi/BatchMappingContext.java

https://hibernate.atlassian.net/browse/HSEARCH-4929
https://hibernate.atlassian.net/browse/HSEARCH-5124

HSEARCH-4929 Support dropAndCreateSchemaOnStart in JSR-352 integration

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5130

HSEARCH-5130 Upgrade to Hibernate ORM 6.5.0.CR2

---

Jenkinsfile
ci/dependency-update/Jenkinsfile
ci/performance/elasticsearch/Jenkinsfile
ci/performance/lucene/Jenkinsfile
ci/release/Jenkinsfile

Mainly to get finer trace for requireApprovalForPullRequest

Upgrade to jenkins-pipeline-helpers 1.11

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchNamedPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneNamedPredicate.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/binding/identifierbridge/param/string/OffsetIdentifierBinder.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/binding/namedpredicate/SkuIdentifierBinder.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/binding/propertybridge/param/string/InvoiceLineItemsSummaryBinder.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/binding/typebridge/param/string/FullNameBinder.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/binding/valuebridge/param/string/BooleanAsStringBinder.java
engine/src/main/java/org/hibernate/search/engine/search/common/spi/MapNamedValues.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/definition/PredicateDefinitionContext.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/NamedValuesBasedPredicateDefinitionContext.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/search/ElasticsearchKnnPredicateSpecificsIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/AbstractPredicateInObjectFieldIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/NamedPredicateBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/NamedPredicateMultiIndexCompatibilityIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/PredicateDefinitionContextIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DocumentIdBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FullTextFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/GenericFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/KeywordFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/MarkerBindingBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/PropertyBindingBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/RoutingBridgeBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ScaledNumberFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/TypeBindingBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/VectorFieldIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/BindingContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/impl/AbstractBindingContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/mapping/programmatic/identifiertovalue/impl/ValueBindingContextToIdentifierBindingContextAdapter.java

https://hibernate.atlassian.net/browse/HSEARCH-5075

HSEARCH-5075 Refactor parameter handling during binding

---

documentation/src/main/asciidoc/public/reference/_search-dsl-projection.adoc
documentation/src/test/java17/org/hibernate/search/documentation/search/projection/MyAuthorPlaceProjection.java
documentation/src/test/java17/org/hibernate/search/documentation/search/projection/ProjectionDslJava17IT.java
engine/src/main/java/org/hibernate/search/engine/search/projection/definition/spi/DistanceProjectionDefinition.java
integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/mapping/ProjectionConstructorDistanceProjectionIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/DistanceProjection.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/DistanceProjectionProcessor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/search/definition/binding/builtin/DistanceProjectionBinder.java

https://hibernate.atlassian.net/browse/HSEARCH-4807
only a draft as it is built on top of the other PR: https://github.com/hibernate/hibernate-search/pull/4061

HSEARCH-4807 @DistanceProjection to map a constructor parameter to a distance projection

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/AbstractAutomaticIndexingAssociationBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontaining/AutomaticIndexingManyToManyOwnedByContainingMapKeysBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytoone/AutomaticIndexingManyToOneBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetomany/AutomaticIndexingOneToManyCollectionBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetomany/AutomaticIndexingOneToManyListBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedEagerOnBothSidesIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedLazyOnContainedSideIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedLazyOnContainingSideIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingEagerOnBothSidesIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainedSideIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainingSideIT.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/DataClearConfig.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/DatabaseContainer.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmSetupHelperCleaner.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/MultitenancyTestHelper.java

https://hibernate.atlassian.net/browse/HSEARCH-5135

HSEARCH-5135 Improve test execution time for some of the orm-based tests

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4927

HSEARCH-4927 Followup: allow empty jacoco stashes

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4927

HSEARCH-4927 Followup: address PR build case with no default build execution

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4927

HSEARCH-4927 Followup: address PR build case with no default build execution OR not default ITs

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5138

HSEARCH-5138 Test against latest OpenSearch 1.3.16

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5139

HSEARCH-5139 Upgrade to Hibernate ORM 6.5.0.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5137

HSEARCH-5137 Upgrade -orm6 artifacts to Hibernate ORM 6.2.25.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5134

HSEARCH-5134 Upgrade to Hibernate ORM 6.4.8.Final : 7.1

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5134

HSEARCH-5134 Upgrade to Hibernate ORM 6.4.8.Final : 7.0

---

documentation/pom.xml
documentation/src/main/asciidoc/public/reference/_mapping-configuration.adoc
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/cfg/HibernateOrmMapperSettings.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMappingInitiator.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/reporting/impl/HibernateOrmMapperHints.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationMappingConfigurationContextImpl.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/spi/AbstractPojoMappingInitiator.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/reporting/spi/MapperHints.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/cfg/StandalonePojoMapperSettings.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMappingInitiator.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/reporting/impl/StandalonePojoMapperHints.java

https://hibernate.atlassian.net/browse/HSEARCH-5018

HSEARCH-5018 Better guidance for applications where classpath scanning does not work

---

Jenkinsfile
ci/dependency-update/Jenkinsfile
ci/performance/elasticsearch/Jenkinsfile
ci/performance/lucene/Jenkinsfile
ci/release/Jenkinsfile

For this: https://github.com/hibernate/hibernate-jenkins-pipeline-helpers/pull/25

Upgrade to jenkins-pipeline-helpers 1.13

---

Jenkinsfile
build/container/search-backend/elastic.Dockerfile
build/parents/build/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5141
https://hibernate.atlassian.net/browse/HSEARCH-5142

HSEARCH-5142 Upgrade to Elasticsearch 8.13.3 client / HSEARCH-5141 Test Elasticsearch 8.13.3 compatibility

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5145
https://github.com/hibernate/hibernate-search/pull/4151

HSEARCH-5145 Upgrade Jackson to 2.17.1

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicateBuilderFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchWithParametersPredicate.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/impl/ElasticsearchIndexCompositeNodeType.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneSearchPredicateBuilderFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneWithParametersPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/impl/LuceneIndexCompositeNodeType.java
engine/src/main/java/org/hibernate/search/engine/backend/types/IndexFieldTraits.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/WithParametersPredicateFinalStep.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/PredicateTypeKeys.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/SearchPredicateBuilderFactory.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubSearchPredicate.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubSearchPredicateBuilderFactory.java

https://hibernate.atlassian.net/browse/HSEARCH-4806
to address the discussion https://hibernate.zulipchat.com/#narrow/stream/132092-hibernate-search-dev/topic/WITH_PARAMETERS.20trait.2E.2E.2E.3F/near/436658786

Follow up on HSEARCH-4806 Remove with-parameters predicate trait

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/ElasticsearchLogCategories.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/reporting/impl/ElasticsearchEventContextMessages.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/reporting/impl/ElasticsearchSearchHints.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/reporting/impl/ElasticsearchValidationMessages.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/SearchWork.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/LuceneLogCategories.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/LoggerInfoStream.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/reporting/impl/LuceneSearchHints.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearcherImpl.java
build/parents/build/pom.xml
engine/src/main/java/org/hibernate/search/engine/backend/reporting/spi/BackendMappingHints.java
engine/src/main/java/org/hibernate/search/engine/backend/reporting/spi/BackendSearchHints.java
engine/src/main/java/org/hibernate/search/engine/reporting/impl/EngineEventContextMessages.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/reporting/impl/HibernateOrmEventContextMessages.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/reporting/impl/HibernateOrmMapperHints.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/reporting/impl/HibernateOrmMappingHints.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/reporting/impl/PojoConstructorProjectionDefinitionMessages.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/reporting/impl/PojoEventContextMessages.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/reporting/spi/MapperHints.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/reporting/impl/StandalonePojoEventContextMessages.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/reporting/impl/StandalonePojoMapperHints.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/reporting/impl/StandalonePojoMappingHints.java
util/common/src/main/java/org/hibernate/search/util/common/logging/impl/DefaultLogCategories.java
util/common/src/main/java/org/hibernate/search/util/common/logging/impl/LogCategory.java
util/common/src/main/java/org/hibernate/search/util/common/logging/impl/LoggerFactory.java
util/common/src/main/java/org/hibernate/search/util/common/reporting/impl/CommonEventContextMessages.java
util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/logging/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-5144
https://github.com/hibernate/hibernate-search/pull/4152

HSEARCH-5144 Upgrade to JBoss logging 3.6.0.Final

---

Jenkinsfile
build/container/search-backend/elastic.Dockerfile
build/parents/build/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5146
https://hibernate.atlassian.net/browse/HSEARCH-5147

HSEARCH-5146 Upgrade to Elasticsearch 8.13.4 client / HSEARCH-5147 Test Elasticsearch 8.13.4 compatibility

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5150

HSEARCH-5150 Upgrade to Hibernate ORM 6.5.1.Final

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
build/container/search-backend/amazon-opensearch-serverless.Dockerfile
build/container/search-backend/opensearch.Dockerfile
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5151
https://github.com/hibernate/hibernate-search/pull/4163

HSEARCH-5151 Add compatibility with OpenSearch 2.14.0

---

ci/release/Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5152

HSEARCH-5152 Use env variable name instead of the passphrase in GPG configuration

---

build/parents/build/pom.xml
build/parents/public/pom.xml
documentation/pom.xml
documentation/src/main/asciidoc/public/reference/_backend-lucene.adoc
documentation/src/main/asciidoc/public/reference/_search-dsl-predicate.adoc

https://hibernate.atlassian.net/browse/HSEARCH-5148

HSEARCH-5148 Update lucene analysis JavaDocs link

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5153
https://github.com/hibernate/hibernate-search/pull/4167

HSEARCH-5153 Upgrade to GSON 2.11.0

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5154

HSEARCH-5154 Upgrade to Hibernate ORM 6.5.2.Final

---

integrationtest/performance/backend/README.md

Loosely based on @franz1981's PR: https://github.com/hibernate/hibernate-orm-benchmark/pull/5/files
I tried to keep things short, at the expense of details :)

Update instructions to run JMH performance tests

---

.github/workflows/build.yml
Jenkinsfile

following the update for ORM: https://github.com/hibernate/hibernate-orm/commit/0f8ef48e7bd7a6f5a02cf23e1d1d3bdde0188e52

Don't fail the build if build scan publishing fails

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingBaseIT.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/scope/impl/SearchScopeImpl.java

https://hibernate.atlassian.net/browse/HSEARCH-5158

HSEARCH-5158 Return non-null mass indexer from a standalone search scope

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/highlighter/impl/LuceneAbstractSearchHighlighter.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/highlighter/impl/LuceneFastVectorSearchHighlighter.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/highlighter/impl/LucenePlainSearchHighlighter.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/highlighter/impl/LuceneUnifiedSearchHighlighter.java
engine/src/main/java/org/hibernate/search/engine/search/highlighter/dsl/HighlighterBoundaryScannerFastVectorHighlighterOptionsStep.java
engine/src/main/java/org/hibernate/search/engine/search/highlighter/dsl/impl/HighlighterFastVectorHighlighterOptionsStepImpl.java
engine/src/main/java/org/hibernate/search/engine/search/highlighter/spi/SearchHighlighterBuilder.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/highlight/HighlighterFastVectorIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5159

HSEARCH-5159 Use char array for highlighters

---

integrationtest/mapper/orm-jakarta-batch/src/test/java/org/hibernate/search/integrationtest/jakarta/batch/massindexing/MassIndexingJobIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/dynamicmap/DynamicMapBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingConditionalExpressionsIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/common/impl/HibernateOrmUtils.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/AbstractHibernateOrmLoadingStrategy.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/ConditionalExpressionQueryFactory.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/HibernateOrmQueryLoaderImpl.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/TypeQueryFactory.java

https://hibernate.atlassian.net/browse/HSEARCH-5162

HSEARCH-5162 Make ORM mass indexer work when JPA compliance is enabled

---

integrationtest/mapper/orm-jakarta-batch/src/test/java/org/hibernate/search/integrationtest/jakarta/batch/massindexing/MassIndexingJobIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/dynamicmap/DynamicMapBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingConditionalExpressionsIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/common/impl/HibernateOrmUtils.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/AbstractHibernateOrmLoadingStrategy.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/ConditionalExpressionQueryFactory.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/HibernateOrmQueryLoaderImpl.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/TypeQueryFactory.java

https://hibernate.atlassian.net/browse/HSEARCH-5162

Backport of HSEARCH-5162 to 7.1 - Make ORM mass indexer work when JPA compliance is enabled

---

build/parents/build/pom.xml
util/common/src/main/java/org/hibernate/search/util/common/jar/impl/CodeSource.java
util/common/src/test/java/org/hibernate/search/util/common/jar/impl/CodeSourceTest.java

https://hibernate.atlassian.net/browse/HSEARCH-5156
backport of https://github.com/hibernate/hibernate-search/pull/4183

Backport of HSEARCH-5156 to 7.1 - Address Spring Boot 3.3 upgrade nested JARs test failures 

---

build/parents/build/pom.xml
ci/dependency-update/Jenkinsfile
ci/dependency-update/rules-lucene9.11.xml

https://hibernate.atlassian.net/browse/HSEARCH-5166

HSEARCH-5166 Upgrade to Lucene 9.11

---

Jenkinsfile
pom.xml

see https://hibernate.zulipchat.com/#narrow/stream/132095-hibernate-infra/topic/JDK.2Ftools.20on.20CI/near/443732491

Add testing against JDK 24

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5168

HSEARCH-5168 Upgrade -orm6 artifacts to Hibernate ORM 6.2.26.Final

---

Jenkinsfile
build/container/search-backend/elastic.Dockerfile
build/parents/build/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5172
https://hibernate.atlassian.net/browse/HSEARCH-5173

HSEARCH-5172 Upgrade Elasticsearch client to 8.14.1 / HSEARCH-5173 Test against latest Elasticsearch 8.14.1

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5174

HSEARCH-5174 Test against latest OpenSearch 1.3.17

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/AbstractAutomaticIndexingAssociationBaseIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/event/impl/HibernateSearchEventListener.java

https://hibernate.atlassian.net/browse/HSEARCH-5170

HSEARCH-5170 Ensure that setting an association to null before removing an entity triggers indexing

---

documentation/src/main/asciidoc/public/reference/_coordination.adoc

https://hibernate.atlassian.net/browse/HSEARCH-5178

HSEARCH-5178 Reword confusing introduction to coordination in documentation

---

build/parents/build/pom.xml
documentation/pom.xml
documentation/src/main/asciidoc/public/reference/_compatibility.adoc

https://hibernate.atlassian.net/browse/HSEARCH-5176

HSEARCH-5176 Mark Hibernate Search 7.1 series as compatible with Hibernate ORM 6.5

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5177

HSEARCH-5177 Test against latest Elasticsearch 7.17.22

---

backend/elasticsearch-aws/src/main/java/org/hibernate/search/backend/elasticsearch/aws/impl/AwsSigningRequestInterceptor.java
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5179

HSEARCH-5179 Bump software.amazon.awssdk:auth from 2.25.2 to 2.26.4

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
build/container/search-backend/amazon-opensearch-serverless.Dockerfile
build/container/search-backend/opensearch.Dockerfile
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5181

HSEARCH-5181 Add compatibility with OpenSearch 2.15.0

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR template to include note on licensing

Update PR template to include note on licensing

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5184
Lucene upgrade

HSEARCH-5184 Upgrade to Lucene 9.11.1

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5206

HSEARCH-5206 Test against latest OpenSearch 1.3.18

---

distribution/src/main/assembly/dist.xml

- in particular, various .cache folders produced by the formatter/import plugins
- and various git-related files

Remove some of the files from the distribution package

---

mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/scope/impl/SearchScopeImpl.java

https://hibernate.atlassian.net/browse/HSEARCH-5211

HSEARCH-5211 Delegate to an Object version of the workspace(..)

---

MAINTAINERS.md

Mention the new CI job for reproducibility build check.

Update release steps notes

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5214

HSEARCH-5214 Test against latest Elasticsearch 7.17.23

---

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateSpecificsIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5194

HSEARCH-5194 Reduce the number of vectors in the test dataset

---

build/config/pom.xml
build/parents/build/pom.xml
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateSpecificsIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchQueryAdapter.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5217
https://hibernate.atlassian.net/browse/HSEARCH-5194

HSEARCH-5217 Upgrade to Hibernate ORM 6.6.0.CR2

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5216

HSEARCH-5216 Upgrade to Hibernate ORM 6.4.10.Final (7.1)

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5216

HSEARCH-5216 Upgrade to Hibernate ORM 6.4.10.Final (7.0)

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5215

HSEARCH-5215 Upgrade -orm6 artifacts to Hibernate ORM 6.2.30.Final

---

build/config/pom.xml
build/parents/build/pom.xml
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchQueryAdapter.java

https://hibernate.atlassian.net/browse/HSEARCH-5219

HSEARCH-5219 Upgrade to Hibernate ORM 6.6.0.Final

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5157

HSEARCH-5157 Run tests against OpenSearch 2.13 AWS (7.1)

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5157

HSEARCH-5157 Run tests against OpenSearch 2.13 AWS (7.2)

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5157

HSEARCH-5157 Run tests against OpenSearch 2.13 AWS (main)

---

ci/dependency-update/Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5222

HSEARCH-5222 Replace testing of elasticsearch-latest (7.2)

---

ci/dependency-update/Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5222

HSEARCH-5222 Replace testing of elasticsearch-latest (7.1)

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/FormulaPropertyIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMappingPropertiesMetadataContributor.java

https://hibernate.atlassian.net/browse/HSEARCH-5226

HSEARCH-5226 Ignore collecting scale on formula properties

---

README.md

see same for Validator https://github.com/hibernate/hibernate-validator/pull/1423

Update the reproducible badge in readme to use the dynamic data based on the build results

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5229

HSEARCH-5229 Test against latest OpenSearch 1.3.19

---

.github/hibernate-github-bot.yml

to address new formats in which the title is generated

Update hibernate GitHub bot title pattern

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5233

HSEARCH-5233 Update to new versions of hibernate-infra extensions/theme that depend on Asciidoctorj 3.0

---

build/configuration-properties-collector/src/main/java/org/hibernate/search/configuration/properties/collector/impl/ConfigurationPropertyProcessor.java
build/parents/public/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5234

HSEARCH-5234 Address the change of maven JavaDocs plugin output location

---

build/configuration-properties-collector/src/main/java/org/hibernate/search/configuration/properties/collector/impl/ConfigurationPropertyProcessor.java
distribution/src/main/assembly/dist.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5234
include the javadocs in the dist package + so that they will actually get uploaded during the release.

Follow up on HSEARCH-5234 Include the javadocs in the dist package

---

documentation/src/main/asciidoc/migration/index.adoc
documentation/src/test/java/org/hibernate/search/documentation/mapper/pojo/standalone/loading/mass/MyMassLoadingStrategy.java
integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/massindexing/MassIndexingMonitorIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/AbstractMassIndexingErrorIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/AbstractMassIndexingFailureIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingStreamingLoaderIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/HibernateOrmMassIdentifierLoader.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/loading/spi/PojoMassIdentifierLoader.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/MassIndexingMonitor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/MassIndexingType.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/MassIndexingTypeGroupMonitor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/MassIndexingTypeGroupMonitorContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/NoOpMassIndexingTypeGroupMonitor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingBatchCoordinator.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingBatchIndexingWorkspace.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingEntityIdentifierLoadingRunnable.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingEntityLoadingRunnable.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingLoggingMonitor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingNotifier.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/loading/MassIdentifierLoader.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/loading/impl/MapMassLoadingStrategy.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/loading/impl/StandalonePojoMassIdentifierLoader.java

https://hibernate.atlassian.net/browse/HSEARCH-5180

HSEARCH-5180 Better mass indexingsupport for data streams with an initially unknown total size

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5246

HSEARCH-5246 Test against latest Elasticsearch 7.17.24

---

Jenkinsfile
pom.xml

https://hibernate.zulipchat.com/#narrow/stream/132095-hibernate-infra/topic/JDK.20testing/near/471186137

Stop testing JDK 22

---

ci/dependency-update/Jenkinsfile
ci/release/Jenkinsfile

Ideally we'd switch to a mailing list someday; I have it on a to-do list.
In the meantime, since this isn't easily filterable, please leave me out :)

Remove Yoann from CI notifications

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5250
Bump version.com.fasterxml.jackson from 2.17.2 to 2.18.0
Bumps `version.com.fasterxml.jackson` from 2.17.2 to 2.18.0.
Updates `com.fasterxml.jackson.core:jackson-core` from 2.17.2 to 2.18.0
- [Commits](https://github.com/FasterXML/jackson-core/compare/jackson-core-2.17.2...jackson-core-2.18.0)
Updates `com.fasterxml.jackson.core:jackson-annotations` from 2.17.2 to 2.18.0
- [Commits](https://github.com/FasterXML/jackson/commits)
Updates `com.fasterxml.jackson.core:jackson-databind` from 2.17.2 to 2.18.0
- [Commits](https://github.com/FasterXML/jackson/commits)
---
- dependency-name: com.fasterxml.jackson.core:jackson-core dependency-type: direct:production update-type: version-update:semver-minor
- dependency-name: …

HSEARCH-5250 Upgrade to Jackson 2.18.0

---

ci/dependency-update/Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5210

Follow up on HSEARCH-5210 Allow no-change in the Lucene 9 update job

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5254

HSEARCH-5254 Upgrade to Avro 1.11.4

---

documentation/src/main/asciidoc/migration/index.adoc

Fix typos in migration guide SQL scripts

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5257

HSEARCH-5257 Upgrade jboss-logging-tools to 3.0.2.Final

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/dynamicmap/DynamicMapBaseIT.java
integrationtest/mapper/orm/src/test/resources/DynamicMapBaseIT/toone.hbm.xml

https://hibernate.atlassian.net/browse/HSEARCH-5260

HSEARCH-5260 Re-enable DynamicMapBaseIT#toOne

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5262

HSEARCH-5262 Test against latest Elasticsearch 7.17.25

---

.github/hibernate-github-bot.yml
.mvn/extensions.xml

https://hibernate.atlassian.net/browse/HSEARCH-5265

HSEARCH-5265 Switch to hibernate-develocity-maven-extension

---

util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/SearchBackendContainer.java

Disable swapping for Elasticsearch containers (tests)

---

integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/search/ElasticsearchKnnPredicateMultipleShardsIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateSpecificsIT.java
integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/mapping/VectorFieldIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5272

HSEARCH-5272 Adjust flaky knn test : SimilarityFilterKnnSearchIT

---

Jenkinsfile
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5267

HSEARCH-5267 Upgrade to Hibernate ORM 6.6.3.Final

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/ElasticsearchFieldProjection.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/FieldProjectionRequestContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/ProjectionRequestContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryRequestContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneDistanceToFieldProjection.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneFieldProjection.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneObjectProjection.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/ProjectionRequestContext.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/FieldProjectionBaseIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5255

HSEARCH-5255 Change how projection cardinality check is done on "request"

---

build/config/src/main/java/org/hibernate/search/build/report/loggers/LoggerCategoriesProcessor.java

https://hibernate.atlassian.net/browse/HSEARCH-798

HSEARCH-798 use the latest supported Java version in the annotation processor

---

build/parents/build/pom.xml

https://github.com/hibernate/hibernate-search/pull/4403
https://hibernate.atlassian.net/browse/HSEARCH-5279

HSEARCH-5279 Upgrade jboss-logging-tools to 3.0.3.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5283

HSEARCH-5283 Upgrade to JBeret 3.1.0.Final

---

documentation/src/main/asciidoc/public/reference/_compatibility.adoc
documentation/src/main/asciidoc/public/reference/_integrations.adoc

https://hibernate.atlassian.net/browse/HSEARCH-5082

HSEARCH-5082 Adjust `Standards and integrations` section for Hibernate ORM 7 upgrade

---

distribution/src/main/assembly/dist.xml

HSEARCH-5285 Exclude more files from the dist package

---

build/parents/build/pom.xml
build/parents/integrationtest/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5286

HSEARCH-5286 Switch to ojdbc17 driver for testing against an Oracle DB

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5291

HSEARCH-5291 Test against latest OpenSearch 1.3.20

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5292

HSEARCH-5292 Upgrade to Lucene 9.12.1

---

ci/dependency-update/Jenkinsfile
ci/dependency-update/rules-lucene-future.xml
lucene-next/build/parents/integrationtest/pom.xml
lucene-next/build/parents/internal/pom.xml
lucene-next/build/parents/public/pom.xml
lucene-next/build/parents/springtest/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5160

HSEARCH-5160 Adjust dependency update job configuration for Lucene 10+

---

CONTRIBUTING.md
Jenkinsfile
MAINTAINERS.md
ci/release/Jenkinsfile
ci/snapshot-publish/Jenkinsfile

backport of https://github.com/hibernate/hibernate-search/pull/4433

Release node backport to 7.2

---

Jenkinsfile

Stop snapshot publishing backport to 7.1

---

CONTRIBUTING.md
Jenkinsfile
MAINTAINERS.md
ci/release/Jenkinsfile
ci/snapshot-publish/Jenkinsfile

backport of https://github.com/hibernate/hibernate-search/pull/4433

Release node backport to 6.2

---

Jenkinsfile

Stop snapshot publishing backport to 6.1

---

Jenkinsfile

Stop snapshot publishing backport to 6.0

---

Jenkinsfile

Stop snapshot publishing backport to 5.11

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5294

HSEARCH-5294 Upgrade to Hibernate ORM 6.6.4.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5287

HSEARCH-5287 Skip running Spring tests on JDK 25

---

ci/nightly/Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5296

HSEARCH-5296 Add a step to build pdf documentation to the nightly CI job

---

build/parents/build/pom.xml
lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/codec/impl/HibernateSearchLuceneCodec.java
lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/ExtractionRequirements.java

https://hibernate.atlassian.net/browse/HSEARCH-5295

HSEARCH-5295 Upgrade to Lucene 10.1.0

---

build/parents/build/pom.xml
integrationtest/mapper/orm-spring/pom.xml
integrationtest/mapper/orm-spring/src/test/java/org/hibernate/search/integrationtest/spring/jta/timeout/RaisedTimeoutJtaAndSpringOutboxIT.java
integrationtest/mapper/orm-spring/src/test/java/org/hibernate/search/integrationtest/spring/jta/timeout/TransactionTimeoutJtaAndSpringOutboxIT.java
integrationtest/mapper/orm-spring/src/test/java/org/hibernate/search/integrationtest/spring/testsupport/AbstractMapperOrmSpringIT.java
integrationtest/mapper/orm-spring/src/test/java/org/hibernate/search/integrationtest/spring/transaction/TransactionIT.java
integrationtest/mapper/orm-spring/src/test/resources/application-jta.yaml
integrationtest/mapper/orm-spring/src/test/resources/application-transaction-timeout.yaml
integrationtest/mapper/orm-spring/src/test/resources/application.yaml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5297

HSEARCH-5297 Switch to narayana-spring-boot instead of atomikos

---

.github/hibernate-github-bot.yml

Enable the check of the license agreement in a PR

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5302

HSEARCH-5302 Test against latest Elasticsearch 7.17.27

---

Jenkinsfile

Stop snapshot publishing backport to 5.9

---

Jenkinsfile

Stop snapshot publishing backport to 5.8

---

Jenkinsfile

Stop snapshot publishing backport to 5.7

---

Jenkinsfile

Stop snapshot publishing backport to 5.6

---

Jenkinsfile

Stop snapshot publishing backport to 5.5

---

CONTRIBUTING.md
pom.xml

and adjust a few other things while at it.

Correct some JDK versions mentioned in the CONTRIBUTING.md

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5303

HSEARCH-5303 Upgrade to Hibernate ORM 6.6.5.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5311

HSEARCH-5311 Upgrade to Hibernate ORM 6.6.6.Final

---

.mailmap

Mainly to pick one email per contributor.

Add a few entries to .mailmap

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5313

HSEARCH-5313 Upgrade to Hibernate ORM 6.6.7.Final

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
build/container/search-backend/amazon-opensearch-serverless.Dockerfile
build/container/search-backend/opensearch.Dockerfile
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5317

HSEARCH-5317 Add compatibility with OpenSearch 2.19.0

---

build/parents/build/pom.xml
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/identifiermapping/customtype/Book.java
documentation/src/test/java/org/hibernate/search/documentation/testsupport/data/ISBNUserType.java
integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/bootstrap/BeanResolutionIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingElementCollectionIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/AbstractAutomaticIndexingAssociationBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/AbstractAutomaticIndexingMultiValuedAssociationBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToHibernateOrmQueryIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/AbstractHibernateOrmSelectionEntityLoader.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchQueryAdapter.java

https://hibernate.atlassian.net/browse/HSEARCH-5298
https://hibernate.atlassian.net/browse/HSEARCH-3204

HSEARCH-5298 Upgrade to Hibernate ORM 7.0.0.Beta4

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5320

HSEARCH-5320 Upgrade to Hibernate ORM 6.6.8.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5323

HSEARCH-5323 Upgrade to Hibernate ORM 6.6.9.Final

---

Jenkinsfile
build/container/search-backend/amazon-opensearch-serverless.Dockerfile
build/container/search-backend/opensearch.Dockerfile

https://hibernate.atlassian.net/browse/HSEARCH-5325

HSEARCH-5325 Test against the latest OpenSearch 2.19.1

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5324

HSEARCH-5324 Upgrade -orm6 artifacts to Hibernate ORM 6.2.34.Final

---

ci/dependency-update/Jenkinsfile

Do not use the build cache for dependency update jobs

---

.github/dependabot.yml
lucene-next/build/parents/integrationtest/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5327
https://hibernate.atlassian.net/browse/HSEARCH-5328

HSEARCH-5327/HSEARCH-5328 Dependency update jobs changes

---

integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/reader/LuceneIndexSegmentFilesIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/AbstractPredicateSingleFieldIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/FloatVectorFieldTypeDescriptor.java

https://hibernate.atlassian.net/browse/HSEARCH-5333

HSEARCH-5333 Better account for knn test flakiness

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5336

HSEARCH-5336 Upgrade to Hibernate ORM 6.6.10.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5337

HSEARCH-5337 Upgrade -orm6 artifacts to Hibernate ORM 6.2.35.Final

---

.github/workflows/simple-build.yml

Use SHA instead of versions in GH actions

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5340

HSEARCH-5340 Upgrade to Hibernate ORM 6.6.11.Final

---

engine/src/main/java/org/hibernate/search/engine/environment/classpath/spi/ClassResolver.java
engine/src/main/java/org/hibernate/search/engine/environment/classpath/spi/DefaultClassResolver.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateOrmClassLoaderServiceClassAndResourceAndServiceResolver.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/models/spi/AbstractPojoModelsBootstrapIntrospector.java
mapper/pojo-base/src/test/java/org/hibernate/search/mapper/pojo/testsupport/TestIntrospector.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/bootstrap/impl/StandalonePojoIntegrationBooterImpl.java
mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/model/impl/StandalonePojoBootstrapIntrospector.java

https://hibernate.atlassian.net/browse/HSEARCH-5342

HSEARCH-5342 Use a org.hibernate.models.spi.ClassLoading based on org.hibernate.search.engine.environment.classpath.spi.ClassResolver

---

Jenkinsfile
ci/dependency-update/Jenkinsfile

As these will come from the Nexus proxy now.

Don't use Docker credentials to pull build-related images

---

v5migrationhelper/orm/src/main/java/org/hibernate/search/query/hibernate/impl/FullTextQueryImpl.java

Use a raw typed variable to make the eclipse compiler happy

---

.mvn/develocity.xml
.mvn/extensions.xml
ci/dependency-update/Jenkinsfile
ci/nightly/Jenkinsfile

Update hibernate-develocity-maven-extension to 3.0.2.Final

---

.mvn/develocity.xml
Jenkinsfile
ci/dependency-update/Jenkinsfile
ci/nightly/Jenkinsfile

Switch to the Commonhaus Develocity instance / Don't use Docker credentials to pull build-related images

---

ci/dependency-update/Jenkinsfile
ci/nightly/Jenkinsfile

Use configFileProvider for declarative pipelines

---

.github/workflows/ci-report.yml
.github/workflows/ci.yml
.mvn/extensions.xml
CONTRIBUTING.md
Jenkinsfile
README.md
ci/dependency-update/Jenkinsfile
ci/nightly/Jenkinsfile

Update the Develocity config for 7.2

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5349

HSEARCH-5349 Upgrade to Hibernate ORM 6.6.12.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5350

HSEARCH-5350 Upgrade to Hibernate ORM 6.6.13.Final

---

build/parents/build/pom.xml
lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/HibernateSearchConcurrentMergeScheduler.java

https://hibernate.atlassian.net/browse/HSEARCH-5353

HSEARCH-5353 Upgrade to Apache Lucene 10.2.0

---

mapper/orm-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/outboxpolling/logging/impl/ConfigurationLog.java
mapper/orm-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/outboxpolling/logging/impl/OutboxPollingEventsLog.java
mapper/orm-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/outboxpolling/logging/impl/OutboxPollingLog.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/OrmMiscLog.java

https://hibernate.atlassian.net/browse/HSEARCH-5352

HSEARCH-5352 Clean up logger impls from misused imports

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5359

HSEARCH-5359 Upgrade to GSON 2.13.0

---

build/parents/build/pom.xml
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/embedded/Address.java
mapper/orm-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/outboxpolling/event/impl/OutboxPollingOutboxEventSendingPlan.java
mapper/orm-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/outboxpolling/mapping/impl/AdditionalMappingBuilder.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/ConditionalExpressionQueryFactory.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/CriteriaTypeQueryFactory.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/HqlTypeQueryFactory.java
mapper/orm/src/test/java/org/hibernate/search/mapper/orm/model/impl/AbstractHibernateOrmBootstrapIntrospectorPerReflectionStrategyTest.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/models/spi/AbstractPojoModelsBootstrapIntrospector.java
pom.xml
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmSoftAssertions.java
v5migrationhelper/orm/src/main/java/org/hibernate/search/impl/FullTextSharedSessionBuilderDelegator.java

https://hibernate.atlassian.net/browse/HSEARCH-5367
https://hibernate.atlassian.net/browse/HSEARCH-5368

HSEARCH-5367 Upgrade to Hibernate ORM 7.0.0.CR1 / HSEARCH-5368 Upgrade to Jandex 3.3

---

Jenkinsfile
build/container/search-backend/amazon-opensearch-serverless.Dockerfile
build/container/search-backend/opensearch.Dockerfile

https://hibernate.atlassian.net/browse/HSEARCH-5372

HSEARCH-5372 Test against the latest OpenSearch 2.19.2

---

Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
build/container/search-backend/amazon-opensearch-serverless.Dockerfile
build/container/search-backend/opensearch.Dockerfile
build/parents/build/pom.xml
documentation/src/test/java/org/hibernate/search/documentation/search/query/ElasticsearchQueryDslIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/custom/ElasticsearchCustomIndexSettingsIT.java
integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/mapping/VectorFieldIT.java
util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/SearchBackendContainer.java

https://hibernate.atlassian.net/browse/HSEARCH-5363

HSEARCH-5363 Add compatibility with OpenSearch 3.0.0

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5376

HSEARCH-5376 Test against latest Elasticsearch 8.18.1 / 8.17.6

---

documentation/pom.xml
pom.xml

Remove Google Analytics

---

documentation/pom.xml
pom.xml

see HIB-155
(cherry picked from commit 57c8731e7a080c656ac768c6e2932d895785eb2d)

HSEARCH-5377 Remove Google Analytics

---

documentation/src/main/asciidoc/public/reference/_static-metamodel.adoc

https://hibernate.atlassian.net/browse/HSEARCH-5300

HSEARCH-5300 Fix a typo in the docs

---

distribution/pom.xml
distribution/src/main/assembly/dist.xml

https://hibernate.atlassian.net/browse/HSEARCH-5300

HSEARCH-5300 Add processor to the dist package

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5378

HSEARCH-5378 Use a newer version of asciidoctor-extensions with fixed styles

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5381

HSEARCH-5381 Upgrade -orm6 artifacts to Hibernate ORM 6.2.37.Final

---

integrationtest/mapper/orm-spring/pom.xml
pom.xml

supersedes https://github.com/hibernate/hibernate-search/pull/4620

upgrade build dependencies (spring-boot-starter-actuator / jandex.plugin)

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5379

HSEARCH-5379 Upgrade to Hibernate ORM 6.6.15.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5382

HSEARCH-5382 Use OSSRH Releases Repository as a release repository in the distributionManagement section

---

integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/cache/LuceneQueryCacheConfigurerIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5388
@yrodiere IDK how intrested you'd be in this change in Lucene's defaults (but it looked interesting to me and I also wondered if it's something to mention in the migration guide... or at least to add some generic text, to go look at the lucene changes when switching to a more recent searc/lucene version)
For more information on licensing, please check …

HSEARCH-5388 Account (in tests) for Lucene query cache being disabled by default

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5386

HSEARCH-5386 Upgrade to Hibernate ORM 6.6.16.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5387

HSEARCH-5387 Upgrade -orm6 artifacts to Hibernate ORM 6.2.38.Final

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-5391

HSEARCH-5391 Test against latest Elasticsearch 8.18.2

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorObjectProjectionCycleIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5358

HSEARCH-5358 Make test JDK11 compatible

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5397

Backport of HSEARCH-5397 to 8.0 Upgrade to Hibernate ORM 7.0.1.Final

---

.mvn/wrapper/maven-wrapper.properties
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5398

HSEARCH-5398 Use Maven 3.9.10 as a required minimum version for the build

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5399

HSEARCH-5399 Upgrade to Hibernate ORM 7.0.2.Final

---

ci/release/Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5400

HSEARCH-5400 Switch to Maven Central publishing

---

ci/release/Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5400

Backport to 8.0 HSEARCH-5400 Switch to Maven Central publishing

---

Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5401

HSEARCH-5401 Test against JDK 26

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5402

HSEARCH-5402 Upgrade Jackson to 2.19.1

---

.github/dependabot.yml

@marko-bekhta Shall we merge and see if dependeabot behaves?

Clean up some obsolete entries in dependabot.yml

---

.github/workflows/ci.yml

This should be safe since PRs are run in an isolated environment, with no access to secrets.

Run CI on dependabot GitHub Actions updates

---

build/parents/public/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5404

HSEARCH-5404 Stop exporting logging/reporting.impl packages to org.jboss.logging

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5405

HSEARCH-5405 Upgrade to Lucene 9.12.2

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5413

Backport to 8.0 - HSEARCH-5413 Upgrade to Hibernate ORM 7.0.4.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5415

Backport to 8.0 : HSEARCH-5415 Upgrade to Hibernate ORM 7.0.5.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5418

HSEARCH-5418 Upgrade to Hibernate ORM 7.0.6.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5418

Backport to 8.0 : HSEARCH-5418 Upgrade to Hibernate ORM 7.0.6.Final

---

.mvn/wrapper/maven-wrapper.properties
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5422

HSEARCH-5422 Use Maven 3.9.11 as a required minimum version for the build

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5424

HSEARCH-5424 Upgrade to Hibernate ORM 6.6.22.Final

---

util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/SearchBackendContainer.java

i.e. set ingest.geoip.downloader.enabled = false

Disable GeoIP processor for Elasticsearch test containers

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5431

HSEARCH-5431 Upgrade to Hibernate ORM 7.0.7

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/AbstractElasticsearchBucketAggregation.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchCompositeAggregation.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchRangeAggregation.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchTermsAggregation.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/aggregation/MetricNumericFieldsAggregationsIT.java

https://hibernate.atlassian.net/browse/HSEARCH-5421

HSEARCH-5421 Make Elasticsearch nested aggregations work with composite/bucket aggregations

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5433

HSEARCH-5433 Update to Hibernate ORM 7.0.8.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5434

HSEARCH-5434 Update to Hibernate ORM 6.6.23.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5445

HSEARCH-5445 Update to Hibernate ORM 6.6.24.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5444

HSEARCH-5444 Update to Hibernate ORM 7.0.9.Final

---

bom/platform-common/pom.xml
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5439

HSEARCH-5439 Upgrade to Elasticsearch client 9.1.0 in platform BOM

---

build/parents/build/pom.xml
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/PersistenceContextThenSecondLevelCacheLookupStrategy.java

https://hibernate.atlassian.net/browse/HSEARCH-5446

HSEARCH-5446 Upgrade to Hibernate ORM 7.1.0.CR2

---

bom/platform-common/pom.xml
build/parents/build/pom.xml
integrationtest/mapper/orm-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingEventSendingIT.java
integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/multitenant/RealBackendDatabaseMultitenancyIT.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmSetupHelperCleaner.java

https://hibernate.atlassian.net/browse/HSEARCH-5447

HSEARCH-5447 Upgrade to Hibernate ORM 7.1.0.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5450

HSEARCH-5450 Update to Hibernate ORM 6.6.25.Final

---

documentation/src/main/asciidoc/migration/index.adoc
pom.xml

Reset migration guide and update previous/stable versions

---

CONTRIBUTING.md

- See also https://github.com/hibernate/hibernate-orm/pull/10826

Add statement from Commonhaus about U.S. laws and regulations to CONTRIBUTING.md

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5469

HSEARCH-5469 Update to Hibernate ORM 6.6.28.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5468

HSEARCH-5468 Upgrade -orm6 artifacts to Hibernate ORM 6.2.44.Final

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/AbstractLuceneMetricCompensatedSumAggregation.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/AbstractLuceneMetricNumericFieldAggregation.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneAvgCompensatedSumAggregation.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneAvgNumericFieldAggregation.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneSumCompensatedSumAggregation.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/aggregation/MetricNumericFieldsAggregationsIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/aggregation/MetricTemporalFieldsAggregationsIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/AbstractLuceneMetricCompensatedSumAggregation.java
lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/AbstractLuceneMetricNumericFieldAggregation.java
lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneAvgCompensatedSumAggregation.java
lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneAvgNumericFieldAggregation.java
lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneSumCompensatedSumAggregation.java

https://hibernate.atlassian.net/browse/HSEARCH-5471

[8.1] HSEARCH-5471 Account for null aggregated values

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5472

HSEARCH-5472 Upgrade Jackson to 2.20.0

---

pom.xml

[6.2] HSEARCH-5477 Update to Hibernate ORM 6.2.45.Final

---

bom/platform-next/pom.xml
build/parents/build/pom.xml
lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/codec/impl/HibernateSearchLuceneCodec.java

https://hibernate.atlassian.net/browse/HSEARCH-5478

HSEARCH-5478 Update to Lucene 10.3

---

bom/platform/pom.xml
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5488

HSEARCH-5488 Update to Lucene 9.12.3

---

ci/release/Jenkinsfile
distribution/pom.xml
distribution/src/main/assembly/docs.xml

https://hibernate.atlassian.net/browse/HSEARCH-5486

HSEARCH-5486 Stage documentation and javadocs to projectroot/target/staging-deploy/documentation

---

ci/release/Jenkinsfile
distribution/pom.xml
distribution/src/main/assembly/docs.xml

https://hibernate.atlassian.net/browse/HSEARCH-5486

[7.2] HSEARCH-5486 Stage documentation and javadocs to projectroot/target/staging-deploy/documentation

---

ci/release/Jenkinsfile
distribution/pom.xml
distribution/src/main/assembly/docs.xml

https://hibernate.atlassian.net/browse/HSEARCH-5486

[7.0] HSEARCH-5486 Stage documentation and javadocs to projectroot/target/staging-deploy/documentation

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5489

[6.2] HSEARCH-5489 Update to Hibernate ORM 6.2.46.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5490

[7.2] HSEARCH-5490 Update to Hibernate ORM 6.6.30.Final

---

bom/platform-common/pom.xml
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5491

[8.1] HSEARCH-5491 Update to Hibernate ORM 7.1.2.Final

---

build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5494

[7.2] HSEARCH-5494 Update to Hibernate ORM 6.6.31.Final

---

bom/platform-next/pom.xml
build/parents/build/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-5497

HSEARCH-5497 Update to Lucene 10.3.1
