hibernate/hibernate-search

- pom.xml
- util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/dialect/Elasticsearch712TestDialect.java
https://hibernate.atlassian.net/browse/HSEARCH-4713
> HSEARCH-4713 Upgrade to Elasticsearch client 8.4.3 and test against Elasticsearch 8.4.3

- build/config/src/main/resources/checkstyle-noparameters.xml
- documentation/src/main/asciidoc/reference/mapping-projection.asciidoc
- integrationtest/mapper/pojo-base/pom.xml
- integrationtest/mapper/pojo-base/src/test/java17-noparameters/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorRecordNoParametersCompilerFlagIT.java
- integrationtest/mapper/pojo-base/src/test/java17-noparameters/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/noparameters/ProjectionConstructorRecordNoParametersCompilerFlagIT.java
- parents/integrationtest/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4673
Hey Yoann! It's been a while 😑😃. I noticed this task on reflection, so I thought I'd look into it. From what I understand, it all starts inside `ProjectionConstructorProcessor#process()`, which led me to these SPI HCAnn classes... 
As these are SPI, I'm not sure where it would be better to put the utils for records and if it's ok to have two implementations for the constructor or if we should keep just one and hide the logic inside...
> HSEARCH-4673 Use record specific methods to get constructor parameter names when applicable

- parents/integrationtest/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4690
This seems suspiciously complex 😃. Here's the sample of startups for this container: 
```
old (11-slim) - 30sec:
08:24:36.416 Oracle Database:CONTAINER: starting up...
08:25:06.636 Oracle Database:DATABASE IS READY TO USE!
new (11-slim-faststart) - 29sec:
08:09:22.312 Oracle Database:CONTAINER: starting up...
08:09:51.890 Oracle Database:DATABASE IS READY TO USE!
new 2 (21-slim-faststart)
09:05:58.519 Oracle Database:CONTAINER: starting up...
09:06:57.819 Oracle Database:DATABASE IS READY TO USE!
```
and size:
```
REPOSITORY         TAG                 IMAGE ID       CREATED       SIZE
gvenzl/oracle-xe   21-slim-faststart   d0c4e41a4b77   5 weeks ago   4.94GB
gvenzl/oracle-xe   21-slim             20984e622219   5 weeks ago   2.07GB …
```
> HSEARCH-4690 Change to -faststart Oracle DB container

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4673
Update to make JDK 8/11 builds pass.
> HSEARCH-4673 Ignore noparameters tests for jdk 8/11

- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/IncorrectPropertyNameObjectPathIT.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/AbstractMappingAnnotationProcessorContext.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/path/PojoModelPath.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/path/PojoModelPathPropertyNode.java
- mapper/pojo-base/src/test/java/org/hibernate/search/mapper/pojo/model/path/PojoModelPathTest.java
- util/common/src/main/java/org/hibernate/search/util/common/impl/Contracts.java
- util/common/src/main/java/org/hibernate/search/util/common/logging/impl/Log.java
https://hibernate.atlassian.net/browse/HSEARCH-4714
this would produce something like the following:
```
3:41:28,715 (main) ERROR RootFailureCollector:231 - HSEARCH000521: Hibernate Search encountered a failure during bootstrap; continuing for now to list all problems, but the process will ultimately be aborted.
Context: Standalone POJO mapping, type 'org.hibernate.search.integrationtest.mapper.pojo.mapping.IncorrectPropertyNameObjectPathIT$PhoneNumber', path '.owner', annotation '@org.hibernate.search.mapper.pojo.mapping.definition.annotation.AssociationInverseSide(extraction=@org.hibernate.search.mapper.pojo.extractor.mapping.annotation.ContainerExtraction(value={}, extract=DEFAULT), inversePath=@org.hibernate.search.mapper.pojo.mapping.definition.annotation.ObjectPath({@org.hibernate.se …
```
> HSEARCH-4714 add property path value validation

- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorBaseIT.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/reporting/impl/PojoConstructorProjectionDefinitionMessages.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/search/definition/impl/ConstructorProjectionApplicationException.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/search/definition/impl/PojoConstructorProjectionDefinition.java
- util/common/src/main/java/org/hibernate/search/util/common/logging/impl/CommaSeparatedClassesFormatter.java
https://hibernate.atlassian.net/browse/HSEARCH-4669
Needed to bring `PojoConstructorModel` into `PojoConstructorProjectionDefinition` so that we can print a nicely formatted constructor string with `PojoConstructorModelFormatter` 😃 
I wasn't sure if we'd want to have the entire trace of nested constructors or just the only one where the initial problem occurred - so I've added that code in the separate commit so that we can drop it if we want the entire thing.
> HSEARCH-4669 add more context to constructor pojection exception

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetomany/AutomaticIndexingOneToManyListBaseIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4723
> HSEARCH-4723 Fix flakiness in AutomaticIndexingOneToManyListBaseIT caused by unpredictable collection order

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetomany/AutomaticIndexingOneToManyListBaseIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4723
Backport of #3275 to branch 6.1.
> Backport HSEARCH-4723 to branch 6.1 - Fix flakiness in AutomaticIndexingOneToManyListBaseIT caused by unpredictable collection order

- pom.xml
* [HSEARCH-4726](https://hibernate.atlassian.net/browse/HSEARCH-4726): Upgrade to AWS SDK 2.18
* [HSEARCH-4642](https://hibernate.atlassian.net/browse/HSEARCH-4642): Upgrade build dependencies to the latest version
For HSEARCH-4642, folllows up on #3146, #3148, #3157, #3176, #3189, #3194, #3208, #3219, #3234, #3239, #3249, #3255, #3262
> HSEARCH-4642 + HSEARCH-4726 Upgrade dependencies

- Jenkinsfile
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontained/AutomaticIndexingManyToManyOwnedByContainedCollectionBaseIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontained/AutomaticIndexingManyToManyOwnedByContainedListBaseIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontaining/AutomaticIndexingManyToManyOwnedByContainingCollectionBaseIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/manytomany/ownedbycontaining/AutomaticIndexingManyToManyOwnedByContainingListBaseIT.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cluster/impl/OutboxPollingAgentAdditionalJaxbMappingProducer.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxPollingOutboxEventAdditionalJaxbMappingProducer.java
- parents/integrationtest/pom.xml
- pom.xml
* [HSEARCH-4727](https://hibernate.atlassian.net/browse/HSEARCH-4727) OutboxEvent "payload" column created as blob(255) with DB2
* [HSEARCH-4732](https://hibernate.atlassian.net/browse/HSEARCH-4732) Run tests against DB2 and DB2 JDBC driver version 11.5.8.0
Backport of  #3282 to branch 6.1.
> Backport HSEARCH-4727 + HSEARCH-4732 to branch 6.1 - OutboxEvent "payload" column created as blob(255) with DB2

- ci/dependency-update/Jenkinsfile
- ci/dependency-update/rules-orm6.2.xml
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/SyntheticPropertyIT.java
* [HSEARCH-4735](https://hibernate.atlassian.net/browse/HSEARCH-4735): Test Hibernate Search 6.1 with Hibernate ORM 6.2
* [HSEARCH-4733](https://hibernate.atlassian.net/browse/HSEARCH-4733): Adapt SyntheticPropertyIT to Hibernate ORM 6.2
Tests already pass, as expected. I checked by triggering a test run on my branch: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-dependency-update-personal-yoann/detail/HSEARCH-4735/4/pipeline/247
> HSEARCH-4733 + HSEARCH-4735 Test Hibernate Search 6.1 with Hibernate ORM 6.2

- pom.xml
* [HSEARCH-4739](https://hibernate.atlassian.net/browse/HSEARCH-4739): Upgrade to jackson-databind 2.13.4.1
* [HSEARCH-4697](https://hibernate.atlassian.net/browse/HSEARCH-4697): Upgrade to Jackson 2.13.4
Backport of #3297 in particular
> Backport HSEARCH-4697 + HSEARCH-4739 to branch 6.1 - Upgrade to Jackson 2.13.4/2.13.4.2

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/parents/integrationtest/pom.xml
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/BigDecimalFieldTypeDescriptor.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
- pom.xml
* [HSEARCH-4738](https://hibernate.atlassian.net/browse/HSEARCH-4738): Add compatibility with Elasticsearch 8.5
* [HSEARCH-4737](https://hibernate.atlassian.net/browse/HSEARCH-4737): Upgrade to Elasticsearch client 8.5.0
> HSEARCH-4737 + HSEARCH-4738 Upgrade to Elasticsearch client 8.5.0 and add compatibility with Elasticsearch 8.5

- pom.xml
For HSEARCH-4642, folllows up on https://github.com/hibernate/hibernate-search/pull/3313, https://github.com/hibernate/hibernate-search/pull/3294, https://github.com/hibernate/hibernate-search/pull/3146, https://github.com/hibernate/hibernate-search/pull/3148, https://github.com/hibernate/hibernate-search/pull/3157, https://github.com/hibernate/hibernate-search/pull/3176, https://github.com/hibernate/hibernate-search/pull/3189, https://github.com/hibernate/hibernate-search/pull/3194, https://github.com/hibernate/hibernate-search/pull/3208, https://github.com/hibernate/hibernate-search/pull/3219, https://github.com/hibernate/hibernate-search/pull/3234, https://github.com/hibernate/hibernate-search/pull/3239, …
> HSEARCH-4642 Bump maven-dependency-plugin from 3.3.0 to 3.4.0

- Jenkinsfile
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/ZonedDateTimeFieldTypeDescriptor.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4752
https://hibernate.atlassian.net/browse/HSEARCH-4754
The bug with the scaled_float property hasn't been fixed yet, so I've updated `supportsMatchOnScaledNumericLossOfPrecision` to include this new version.
> HSEARCH-4752 Bump Elasticsearch version to test against the latest micro 8.5.2

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingAssociationDeletionBytecodeEnhancementIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedLazyOnContainedSideIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedLazyOnContainingSideIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainedSideIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainingSideIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/BytecodeEnhancementIT.java
- orm6/integrationtest/mapper/orm/ant-src-changes.patch
https://hibernate.atlassian.net/browse/HSEARCH-4759
Even if we remove `@RunWith(BytecodeEnhancerRunner.class)`, the current tests would still be successful; adding these tests would make sure that enhancement really happens.
> HSEARCH-4759 Add test to check that bytecode enhancement works

- Jenkinsfile
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4761
> HSEARCH-4761 Bump Elasticsearch version to test against the latest micro 8.5.3

- pom.xml
https://github.com/hibernate/hibernate-search/pull/3318 spring boot cannot be simply upgraded to 3.0 in the main code as Atomikos support, which some of our code relies on, was dropped from the main project and was supposed to be moved to Atmoikos team (I haven't seen a release for 3.0 there). But more important 3.0 moved to Jakarta EE 9 (https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0), so it doesn't make sense to update it in the main code. I wonder if we should add this update on top of our ORM 6 patches and keep it there for now...
For HSEARCH-4484, follows up on https://github.com/hibernate/hibernate-search/pull/3134, https://github.com/hibernate/hibernate-search/pull/2895, https://github.com/hibernate/hibernate-search/pull/2902, …
> HSEARCH-4484 Bump version.org.springframework.boot from 2.7.0 to 2.7.6

- pom.xml
For HSEARCH-4642, folllows up on https://github.com/hibernate/hibernate-search/pull/3322, https://github.com/hibernate/hibernate-search/pull/3313, https://github.com/hibernate/hibernate-search/pull/3294, https://github.com/hibernate/hibernate-search/pull/3146, https://github.com/hibernate/hibernate-search/pull/3148, https://github.com/hibernate/hibernate-search/pull/3157, https://github.com/hibernate/hibernate-search/pull/3176, https://github.com/hibernate/hibernate-search/pull/3189, https://github.com/hibernate/hibernate-search/pull/3194, https://github.com/hibernate/hibernate-search/pull/3208, https://github.com/hibernate/hibernate-search/pull/3219, https://github.com/hibernate/hibernate-search/pull/3234, …
> HSEARCH-4642 Bump mockito-core from 4.9.0 to 4.10.0

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/ElasticsearchIndexRootBuilder.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/ElasticsearchStringImplicitFieldContributor.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendImpl.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/mapping/impl/DiscriminatorTypeNameMapping.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/mapping/impl/IndexNameTypeNameMapping.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/mapping/impl/TypeNameMapping.java
- engine/src/main/java/org/hibernate/search/engine/backend/document/model/dsl/spi/ImplicitFieldCollector.java
- engine/src/main/java/org/hibernate/search/engine/backend/document/model/dsl/spi/ImplicitFieldContributor.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/metamodel/ElasticsearchIndexDescriptorIT.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/search/ElasticsearchImplicitFieldsIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/metamodel/IndexDescriptorIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4294
If I understood correctly, we don't want to make any changes to Lucene's backend. But just in case, I've placed the main interfaces under engine SPI, as that's where the other model builder-related interfaces are.
As for the implementation itself - because the fields are already present in the schema in one way or another, it seems that the only thing to do was to let HSEARCH know about their existence and adding them to static fields does the trick.
> HSEARCH-4294 Expose implicit fields through search DSL

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/IndexWriterDelegatorImpl.java
- build/config/src/main/resources/checkstyle.xml
- engine/src/main/java/org/hibernate/search/engine/common/resources/impl/EngineThreads.java
- engine/src/main/java/org/hibernate/search/engine/common/timing/impl/DefaultTimingSource.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingLoggingMonitor.java
https://hibernate.atlassian.net/browse/HSEARCH-4712
There weren't actually that many sync blocks inside of the methods. Ones inside `IndexWriterDelegatorImpl` looked like good candidates for replacement as they are somewhat using sync blocks to do I/O operations. But the underlying Lucene code is using the same pattern, so I suppose it won't help much until that is changed as well:
```java 
private long commitInternal(MergePolicy mergePolicy) throws IOException {
// .... 
synchronized(commitLock) {
ensureOpen(false);
// .... 
finishCommit();
}
// .... 
return seqNo;
}
```
The other sync blocks were either in test appenders or where sync only happens on the init stage and only performs in-memory operations, so doesn't look like candidates for replacement.
> HSEARCH-4712  Convert synchronized blocks to java.util.concurrent.Locks for better Loom compatibility

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4764
For HSEARCH-4642, folllows up on https://github.com/hibernate/hibernate-search/pull/3339, https://github.com/hibernate/hibernate-search/pull/3322, https://github.com/hibernate/hibernate-search/pull/3313, https://github.com/hibernate/hibernate-search/pull/3294, https://github.com/hibernate/hibernate-search/pull/3146, https://github.com/hibernate/hibernate-search/pull/3148, https://github.com/hibernate/hibernate-search/pull/3157, https://github.com/hibernate/hibernate-search/pull/3176, https://github.com/hibernate/hibernate-search/pull/3189, https://github.com/hibernate/hibernate-search/pull/3194, https://github.com/hibernate/hibernate-search/pull/3208, …
> HSEARCH-4642 Bump dependencies / HSEARCH-4764 Bump AWS SDK to 2.19.8

- integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingStaticShardingIncompatibleConfigurationIT.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cluster/impl/AgentReference.java
- mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/EventProcessorClusterLinkStaticShardingEdgeCasesTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4748
Follows up on #3305 .
Fixes logs like this:
```diff
-... Agent '#5fb45edb-bff4-43f5-b1a3-8dc40986cb81 - Outbox event processor': the persisted shard assignment ...
+... Agent '5fb45edb-bff4-43f5-b1a3-8dc40986cb81 - Outbox event processor': the persisted shard assignment ...
```
> HSEARCH-4748 follow-up: remove leading "#" from agent references

- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingBatchCoordinator.java
https://hibernate.atlassian.net/browse/HSEARCH-4773
So this is a place where it starts to cause problems with the Oracle build... I've tried to keep the  `applyToAllContexts(..)` but that becomes ugly pretty fast:
```java
applyToAllContexts(
context -> {
try {
Object result = Futures.unwrappedExceptionGet( context.agent().preStop() );
context.agent().stop();
return CompletableFuture.completedFuture( result );
}
catch (InterruptedException e) {
Thread.currentThread().interrupt();
throw new RuntimeException( e );
}
}
);
```
[HSEARCH-4773]: https://hibernate.atlassian.net/browse/HSEARCH-4773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HSEARCH-4773 Change how agents are stopped in massindexer

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/AbstractElasticsearchPredicate.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchBooleanPredicate.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchMatchAllPredicate.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/AbstractLuceneSearchPredicate.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneBooleanPredicate.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/NotPredicateFinalStep.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/SearchPredicateFactory.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/NotPredicateFinalStepImpl.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/spi/AbstractSearchPredicateFactory.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/search/query/ElasticsearchBoolSearchPredicateIT.java
- integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/search/LuceneBoolSearchPredicateIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/NotPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/NotPredicateSpecificsIT.java
- integrationtest/v5migrationhelper/engine/src/test/java/org/hibernate/search/test/dsl/DSLTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4645
I wasn't sure about the "simplification" part:
> optimize things such as f.bool().must(f.not(something)).must(somethingElse) into f.bool().mustNot(something).must(somethingElse), if possible. Or maybe we could do it ourselves.
so I've pushed it as a separate commit. It does reduce the nested predicates, but it looks so-so 😄 
[HSEARCH-4645]: https://hibernate.atlassian.net/browse/HSEARCH-4645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HSEARCH-4645 Syntactic sugar for negating predicates (NOT)

- documentation/src/main/asciidoc/migration/index.asciidoc
- documentation/src/main/asciidoc/reference/search-dsl-predicate.asciidoc
- documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4645
Add docs + note to migration guide on change behaviour of bool queries.
> HSEARCH-4645 Document `not` predicate

- ci/dependency-update/Jenkinsfile
- ci/list-container-images.sh
- ci/list-dependent-integration-tests.sh
https://hibernate.atlassian.net/browse/HSEARCH-4770
Backport of #3359 to branch 6.1.
> Backport HSEARCH-4770 to branch 6.1 - Only update dependencies for test modules in dependency-update builds

- pom.xml
For HSEARCH-4642, folllows up on https://github.com/hibernate/hibernate-search/pull/3351, https://github.com/hibernate/hibernate-search/pull/3339, https://github.com/hibernate/hibernate-search/pull/3322, https://github.com/hibernate/hibernate-search/pull/3313, https://github.com/hibernate/hibernate-search/pull/3294, https://github.com/hibernate/hibernate-search/pull/3146, https://github.com/hibernate/hibernate-search/pull/3148, https://github.com/hibernate/hibernate-search/pull/3157, https://github.com/hibernate/hibernate-search/pull/3176, https://github.com/hibernate/hibernate-search/pull/3189, https://github.com/hibernate/hibernate-search/pull/3194, https://github.com/hibernate/hibernate-search/pull/3208, …
> HSEARCH-4642 Bump assertj-core from 3.23.1 to 3.24.1

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingFailureIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureCustomBackgroundFailureHandlerIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureCustomMassIndexingFailureHandlerIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureDefaultBackgroundFailureHandlerIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/AbstractMassIndexingFailureIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingFailureCustomBackgroundFailureHandlerIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingFailureCustomMassIndexingFailureHandlerIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingFailureDefaultBackgroundFailureHandlerIT.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingEntityLoadingRunnable.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingIndexedTypeGroup.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingNotifier.java
https://hibernate.atlassian.net/browse/HSEARCH-4541
I'm not sure if that's what you expected, but while I was trying to create some reproducer of the problem, here are the changes I've made 😄 
The test fails two batches, but the remaining ones are still completed, and in the end, an exception is thrown by `indexer.startAndWait();`
As for the logging of failed IDs, there's already a trace log in place, so I assume that covers it.
[HSEARCH-4541]: https://hibernate.atlassian.net/browse/HSEARCH-4541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HSEARCH-4541 Catch load exception and pass to failure handler

- MAINTAINERS.md
- integrationtest/java/modules/pojo-standalone-elasticsearch/src/main/java/module-info.java
- integrationtest/java/modules/pojo-standalone-lucene/src/main/java/module-info.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/BytecodeEnhancementIT.java
- mapper/orm-batch-jsr352/core/src/main/java/org/hibernate/search/batch/jsr352/core/massindexing/util/impl/PersistenceUtil.java
- mapper/orm-coordination-outbox-polling/pom.xml
- orm6/README.md
- orm6/integrationtest/java/modules/orm-coordination-outbox-polling-elasticsearch/ant-src-changes.patch
- orm6/integrationtest/java/modules/orm-coordination-outbox-polling-elasticsearch/pom.xml
- orm6/integrationtest/java/modules/orm-elasticsearch/ant-src-changes.patch
- orm6/integrationtest/java/modules/orm-lucene/ant-src-changes.patch
- orm6/mapper/orm-coordination-outbox-polling/pom.xml
- orm6/mapper/orm/ant-src-changes.patch
- orm6/v5migrationhelper/orm/ant-src-changes.patch
* [HSEARCH-4775](https://hibernate.atlassian.net/browse/HSEARCH-4775): Improve source code compatibility of Hibernate Search with Hibernate ORM 6.2
* [HSEARCH-4768](https://hibernate.atlassian.net/browse/HSEARCH-4768): Fix JavaModulePathTest with ORM 6.2
[HSEARCH-4775]: https://hibernate.atlassian.net/browse/HSEARCH-4775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HSEARCH-4768]: https://hibernate.atlassian.net/browse/HSEARCH-4768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HSEARCH-4768 + HSEARCH-4775 Fix ORM 6.2 dependency update tests

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/model/singlefield/SingleFieldIndexBinding.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/BigDecimalFieldTypeDescriptor.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/LongFieldTypeDescriptor.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
- pom.xml
* [HSEARCH-4778](https://hibernate.atlassian.net/browse/HSEARCH-4778): Upgrade to Elasticsearch client 8.6.0
* [HSEARCH-4777](https://hibernate.atlassian.net/browse/HSEARCH-4777): Add compatibility with Elasticsearch 8.6
[HSEARCH-4778]: https://hibernate.atlassian.net/browse/HSEARCH-4778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HSEARCH-4777]: https://hibernate.atlassian.net/browse/HSEARCH-4777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HSEARCH-4777 + HSEARCH-4778 Elasticsearch 8.6.0

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingEmbeddableIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/AbstractAutomaticIndexingAssociationBaseIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingEagerOnBothSidesIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainedSideIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainingSideIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/BytecodeEnhancementIT.java
- jakarta/integrationtest/jdk/java-modules/orm-lucene/ant-src-changes.patch
- mapper/orm-batch-jsr352/core/src/main/java/org/hibernate/search/batch/jsr352/core/massindexing/util/impl/PersistenceUtil.java
- mapper/orm-coordination-outbox-polling/pom.xml
- orm6/integrationtest/jdk/java-modules/orm-coordination-outbox-polling-elasticsearch/ant-src-changes.patch
- orm6/integrationtest/jdk/java-modules/orm-coordination-outbox-polling-elasticsearch/pom.xml
- orm6/integrationtest/jdk/java-modules/orm-lucene/ant-src-changes.patch
- orm6/integrationtest/mapper/orm/ant-src-changes.patch
- orm6/mapper/orm-coordination-outbox-polling/pom.xml
- orm6/mapper/orm/ant-src-changes.patch
- orm6/v5migrationhelper/orm/ant-src-changes.patch
* [HSEARCH-4775](https://hibernate.atlassian.net/browse/HSEARCH-4775): Improve source code compatibility of Hibernate Search with Hibernate ORM 6.2
* [HSEARCH-4768](https://hibernate.atlassian.net/browse/HSEARCH-4768): Fix JavaModulePathTest with ORM 6.2
* [HSEARCH-4757](https://hibernate.atlassian.net/browse/HSEARCH-4757): Adjust tests to address ORM changes introduced in HHH-15767
Backport of #3323, #3366 to branch 6.1.
[HSEARCH-4775]: https://hibernate.atlassian.net/browse/HSEARCH-4775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HSEARCH-4768]: https://hibernate.atlassian.net/browse/HSEARCH-4768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HSEARCH-4757]: …
> Backport HSEARCH-4757 + HSEARCH-4768 + HSEARCH-4775 to branch 6.1 - Fix ORM 6.2 dependency update tests

- documentation/src/main/asciidoc/migration/index.asciidoc
- documentation/src/main/asciidoc/reference/migrating.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-4779
> HSEARCH-4779 Reference the Hibernate Search 6.0 migration guide from the reference documentation

- documentation/src/main/asciidoc/migration/index.asciidoc
- documentation/src/main/asciidoc/reference/getting-started.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-4779
Backport of #3370 to branch 6.1
> Backport HSEARCH-4779 to branch 6.1 - Reference the Hibernate Search 6.0 migration guide from the reference documentation

- pom.xml
For HSEARCH-4642, folllows up on https://github.com/hibernate/hibernate-search/pull/3387, https://github.com/hibernate/hibernate-search/pull/3383, https://github.com/hibernate/hibernate-search/pull/3364, https://github.com/hibernate/hibernate-search/pull/3351, https://github.com/hibernate/hibernate-search/pull/3339, https://github.com/hibernate/hibernate-search/pull/3322, https://github.com/hibernate/hibernate-search/pull/3313, https://github.com/hibernate/hibernate-search/pull/3294, https://github.com/hibernate/hibernate-search/pull/3146, https://github.com/hibernate/hibernate-search/pull/3148, https://github.com/hibernate/hibernate-search/pull/3157, https://github.com/hibernate/hibernate-search/pull/3176, …
> HSEARCH-4642 Bump assertj-core from 3.24.1 to 3.24.2

- engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/ByTermDeleteWorkExecutor.java
- engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/ByTermUpdateWorkExecutor.java
- engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/DeleteExtWorkExecutor.java
- engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/UpdateExtWorkExecutor.java
- orm/src/test/java/org/hibernate/search/test/batchindexing/DatabaseMultitenancyTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4789
Note this is Hibernate Search 5, so the code is completely different from 6.
This particular part of the code is... let's say interesting. I cleaned up what was reasonable, but the main goal here is really to just use a common implementation in the executors, one that handles tenant IDs correctly.
> HSEARCH-4789 [HSearch 5] Indexing entities with a shared id across tenants results in removal from those tenants

- Jenkinsfile
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4792
https://hibernate.atlassian.net/browse/HSEARCH-4793
Updated the client as well, as these usually come in a pair.
> HSEARCH-4792 Run tests against Elasticsearch 8.6.1

- documentation/src/main/asciidoc/reference/indexing-massindexer.asciidoc
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingEnvironmentIT.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/MassIndexer.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/HibernateOrmMassIndexer.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/MassIndexingEnvironment.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoDefaultMassIndexer.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingBatchCoordinator.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingBatchIndexingWorkspace.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingEntityIdentifierLoadingRunnable.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingEntityLoadingRunnable.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingFailureHandledRunnable.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/spi/PojoMassIndexer.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/massindexing/MassIndexer.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/massindexing/impl/StandalonePojoMassIndexer.java
https://hibernate.atlassian.net/browse/HSEARCH-1809
I was cleaning up some local branches and noticed this one lying around. IIRC this was asked by someone on discourse for `5->6 ` migration. I've rebased and cleaned it up a bit.
You'll notice `BatchingThreadContext` being passed all the way to `PojoMassIndexingFailureHandledRunnable`. While it is not necessarily needed for all the classes extending this runnable, it seemed simpler to have it stored there.
Also, I wasn't sure if we really need to have this context for a workspace (`PojoMassIndexingBatchIndexingWorkspace`). It seems to make more sense for identifier and entity loading. Which ... begs the question - would such generic context be ok, or should we be more granular and allow a user to tell us what to do when loading …
> HSEARCH-1809 Introduce the context for the massindexer batch thread work

- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingEnvironmentIT.java
https://hibernate.atlassian.net/browse/HSEARCH-1809
the failing line on CI was this one:
```java
assertThat( threadNames ).isEmpty();
```
where the `threadNames` is a `Queue`. The only reason I could think of why that happened is that the `afterExecution` wasn't yet called when `isEmpty` was checked. And the thread wasn't removed yet. But when it failed and was generating a message `afterExecution` finished and the queue was now empty. Based on this code from the assertj:
```java
public void assertEmpty(AssertionInfo info, Iterable<?> actual) {
assertNotNull(info, actual);
if (!isNullOrEmpty(actual)) throw failures.failure(info, shouldBeEmpty(actual));
}
```
I thought about changing the test so that we collect the names of failed threads and check if the ones called `afterExecution` does …
> HSEARCH-1809 Follow-up: Update asserts to check if failed threads didn't call `afterExecution()`

- build/parents/public/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4795
this should also help even if not in the dependency upgrade profile but someone still disables the Javadoc generation
> HSEARCH-4795 Follow-up: Don't collect configuration properties if javadoc generation is disabled

- documentation/src/main/asciidoc/reference/indexing-massindexer.asciidoc
- engine/src/main/java/org/hibernate/search/engine/reporting/FailureHandler.java
- engine/src/main/java/org/hibernate/search/engine/reporting/impl/FailSafeFailureHandlerWrapper.java
- engine/src/main/java/org/hibernate/search/engine/reporting/impl/LogFailureHandler.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingFailureIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingErrorCustomBackgroundFailureHandlerIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingErrorCustomMassIndexingFailureHandlerIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureCustomBackgroundFailureHandlerIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureCustomMassIndexingFailureHandlerIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureDefaultBackgroundFailureHandlerIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/AbstractMassIndexingFailureIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingErrorCustomBackgroundFailureHandlerIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingErrorCustomMassIndexingFailureHandlerIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingFailureCustomBackgroundFailureHandlerIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingFailureCustomMassIndexingFailureHandlerIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingFailureDefaultBackgroundFailureHandlerIT.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/MassIndexer.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/HibernateOrmMassIndexer.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/MassIndexingFailureHandler.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoDefaultMassIndexer.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingDelegatingFailureHandler.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingFailSafeFailureHandlerWrapper.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingNotifier.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/spi/PojoMassIndexer.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/massindexing/MassIndexer.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/massindexing/impl/StandalonePojoMassIndexer.java
https://hibernate.atlassian.net/browse/HSEARCH-4772
The initial idea was to allow users to set the limit on the `MassIndexer` interface level as that could be something that can change from mass indexer to mass indexer. And then, the work would happen in the notifier. (you'll find this in the first commit). But I didn't like that, as the notifier doesn't look like a good place to decide if something should or shouldn't be logged or handled otherwise. So that's when I've pushed this logic into our own `MassIndexingFailureHandler` (second commit). I liked this approach a tad better, but then if users don't like our default max number - then they would need to come up with their own handler 😃
> HSEARCH-4772 Add failsafe to prevent log flooding for mass indexing with lots of non-critical failures

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
- build/configuration-properties-collector/src/main/java/org/hibernate/search/configuration/properties/collector/impl/AsciiDocWriter.java
- build/configuration-properties-collector/src/main/java/org/hibernate/search/configuration/properties/collector/impl/ConfigurationPropertyCollector.java
- build/parents/public/pom.xml
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/AnnotationMappingConfigurationContext.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4800
```
[INFO] asciidoctor: INFO: reference/configuration-properties-aggregated.asciidoc: line 4: optional include dropped because include file not found: /hibernate-search-engine.asciidoc
[INFO] asciidoctor: INFO: reference/configuration-properties-aggregated.asciidoc: line 5: optional include dropped because include file not found: /hibernate-search-backend-lucene.asciidoc
[INFO] asciidoctor: INFO: reference/configuration-properties-aggregated.asciidoc: line 6: optional include dropped because include file not found: /hibernate-search-backend-elasticsearch.asciidoc
[INFO] asciidoctor: INFO: reference/configuration-properties-aggregated.asciidoc: line 7: optional include dropped because include file not found: …
```
> HSEARCH-4800 Update configuration property collection 

- pom.xml
I've checked if our property collection "plugin" still works with this Javadoc plugin update, and it seems it does. What... I can't say about the ORM version (probably not related to the Javadoc plugin) - https://docs.jboss.org/hibernate/orm/6.2/userguide/html_single/Hibernate_User_Guide.html#_list_of_all_available_configuration_properties (makes me sad 😭)
> HSEARCH-4801 Bump maven-javadoc-plugin from 3.4.1 to 3.5.0

- Jenkinsfile
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4802
> HSEARCH-4802 Upgrade to Elasticsearch client 8.6.2 and test against Elasticsearch 8.6.2

- engine/src/main/java/org/hibernate/search/engine/environment/classpath/spi/DefaultServiceResolver.java
- engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java
https://hibernate.atlassian.net/browse/HSEARCH-4803
this results in that other error in quarkus:
```
Caused by: java.io.IOException: HSEARCH900016: Cannot open filesystem for code source at 'quarkus:/': HSEARCH900017: Cannot interpret 'quarkus:/' as a local directory or JAR.
at org.hibernate.search.util.common.jar.impl.CodeSource.initFileSystem(CodeSource.java:130)
at org.hibernate.search.util.common.jar.impl.CodeSource.classesPathOrFail(CodeSource.java:96)
at org.hibernate.search.util.common.jar.impl.CodeSource.readOrNull(CodeSource.java:50)
... 68 more
Suppressed: java.lang.NullPointerException: Cannot read the array length because "buf" is null
at java.base/java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:108)
at io.quarkus.bootstrap.classloading.MemoryClassPathElement$Memo …
```
> HSEARCH-4803 Ignore service loading errors from non aggregated classloader

- integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingBackendFailureIT.java
- integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingEdgeCasesIT.java
- integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingLifecycleIT.java
- integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/testsupport/util/OutboxEventFilter.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/DefaultOutboxEventFinder.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/EntityIdHashRangeOutboxEventPredicate.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxEventAndPredicate.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxEventPredicate.java
https://hibernate.atlassian.net/browse/HSEARCH-4804
I'm going blind here since I couldn't reproduce the problem locally, but I think there's a decent chance of at least reducing, if not eliminating, flakiness.
See the commit messages for details.
> HSEARCH-4804 Fix flaky test OutboxPollingAutomaticIndexingLifecycleIT with postgresql 

- pom.xml
follows up on https://github.com/hibernate/hibernate-search/pull/3419
> HSEARCH-4801 Bump version.log4j from 2.19.0 to 2.20.0

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4812
https://hibernate.atlassian.net/browse/HSEARCH-4813
TCK tests passed locally; it doesn't look like any new bugs were found.
> HSEARCH-4812 Add compatibility with OpenSearch 2.6.0/HSEARCH-4813 Test against latest OpenSearch 1.3.8

- .github/dependabot.yml
- pom.xml
follows up on https://github.com/hibernate/hibernate-search/pull/3428, https://github.com/hibernate/hibernate-search/pull/3419
I've also added that ignore rule for the spring boot 3 as it seems that the Narayana starter won't be coming soon.
> HSEARCH-4801 Bump japicmp-maven-plugin from 0.17.1 to 0.17.2 /  Ignore spring boot upgrade for now

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/orchestration/impl/LuceneParallelWorkOrchestratorImpl.java
- engine/src/main/java/org/hibernate/search/engine/backend/orchestration/spi/BatchingExecutor.java
- engine/src/main/java/org/hibernate/search/engine/backend/work/execution/OperationSubmitter.java
- engine/src/test/java/org/hibernate/search/engine/backend/work/execution/OperationSubmitterExecutorTest.java
- engine/src/test/java/org/hibernate/search/engine/backend/work/execution/OperationSubmitterQueueTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4814
I might've missed the point, but I didn't find a use for the `T` in a `BiConsumer<T, Throwable>`, so I just went with a simple `Consumer<Throwable>`. 
I also went ahead and wrapped the call to the `executor.accept(..)` with a try/catch even though it should happen in the same thread, but since we already have a reporter in place... 
And replaced the offloading lambdas with a class.
BTW did this happen anywhere, or it's more of a precaution?
> HSEARCH-4814 Use failure reporter in offloading operation submitter

- integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/testsupport/util/OutboxEventFilter.java
https://hibernate.atlassian.net/browse/HSEARCH-4818
> HSEARCH-4818 Fix failures in tests caused by concurrent use of OutboxEventFilter#allowedIds

- pom.xml
follows up on https://github.com/hibernate/hibernate-search/pull/3435, https://github.com/hibernate/hibernate-search/pull/3428, https://github.com/hibernate/hibernate-search/pull/3419
> HSEARCH-4801 Bump groovy-jsr223 from 3.0.15 to 3.0.16

- integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingLifecycleIT.java
- util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/BackendMock.java
- util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/CallQueue.java
- util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/VerifyingStubBackendBehavior.java
https://hibernate.atlassian.net/browse/HSEARCH-4810
It was easier this time, as I was able to simply avoid hitting the database concurrently, as the concurrent access was an assertion in tests.
> HSEARCH-4810 Fix flaky test with MSSQL

- orm6/integrationtest/v5migrationhelper/orm/ant-src-changes.patch
https://hibernate.atlassian.net/browse/HSEARCH-4819
Searched for `org\.hibernate\.dialect\..+Dialect`, and only these two places that failed in the builds had the dialects for replacement... 
I thought we might get away y simply updating the dialects in the main code ... but the classes are on different sides of the hierarchy, so that check would fail 😞.
Changes are here https://github.com/hibernate/hibernate-search/commit/199b5f166aa9c866d3604cc9e30c0fc69965729c, and this PR is to update the patches. 
Should I backport this patch to 6.1 or just cherrypick the commit into `wip/6.1/dependency-update/orm6.2`
> HSEARCH-4819 Use the appropriate ORM 6 Dialects in v5 migration helper tests

- orm6/integrationtest/v5migrationhelper/orm/ant-src-changes.patch
https://hibernate.atlassian.net/browse/HSEARCH-4819
> [Backport - 6.1] HSEARCH-4819 Use the appropriate ORM 6 Dialects in v5 migration helper tests

- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerExporterIT.java
- integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/schema/management/ElasticsearchSchemaManagerExporterIT.java
- integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/schema/management/LuceneSchemaManagerExporterIT.java
- integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/schema/management/ElasticsearchSchemaManagerExporterIT.java
- integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/schema/management/LuceneSchemaManagerExporterIT.java
https://hibernate.atlassian.net/browse/HSEARCH-2366
- don't use 11+ Files API
- use a version of ES including the distribution part
follows up on https://github.com/hibernate/hibernate-search/pull/3437
> HSEARCH-2366 Follow-up: Make tests compatible with non-default build

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingErrorIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingFailureIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/AbstractMassIndexingErrorIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/AbstractMassIndexingFailureIT.java
- util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/reflect/RuntimeHelper.java
- util/internal/test/common/src/test/java/com/acme/ClassNotInHibernateSearchPackage.java
- util/internal/test/common/src/test/java/org/hibernate/search/util/impl/test/reflect/RuntimeHelperTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4831
Tested locally against the latest 6.2, and this fixes the problem.
Backport to 6.1: #3459
> HSEARCH-4831 Fix Hibernate Search tests against latest ORM 6.2/6.3

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingErrorIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingFailureIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/AbstractMassIndexingErrorIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/AbstractMassIndexingFailureIT.java
- util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/reflect/RuntimeHelper.java
- util/internal/test/common/src/test/java/com/acme/ClassNotInHibernateSearchPackage.java
- util/internal/test/common/src/test/java/org/hibernate/search/util/impl/test/reflect/RuntimeHelperTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4831
Backport of #3458 to branch 6.1
> Backport HSEARCH-4831 to branch 6.1 - Fix Hibernate Search tests against latest ORM 6.2/6.3

- ci/dependency-update/Jenkinsfile
- ci/dependency-update/rules-orm6.3.xml
https://hibernate.atlassian.net/browse/HSEARCH-4830
Backport of #3460 to branch 6.1
> Backport HSEARCH-4830 to branch 6.1 - Test Hibernate Search regularly against Hibernate ORM 6.3.0-SNAPSHOT

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4832
I guess we'll have to adjust the `ElasticsearchTckBackendFeatures`, but downloading ES 8.7 is taking forever in my remote country place, so I'll have have CI tell me what needs to be adjusted exactly.
> HSEARCH-4832 Upgrade to Elasticsearch client 8.7.0 and add compatibility with Elasticsearch 8.7.0

- pom.xml
follows up on https://github.com/hibernate/hibernate-search/pull/3456, https://github.com/hibernate/hibernate-search/pull/3446, https://github.com/hibernate/hibernate-search/pull/3441, https://github.com/hibernate/hibernate-search/pull/3435, https://github.com/hibernate/hibernate-search/pull/3428, https://github.com/hibernate/hibernate-search/pull/3419
> HSEARCH-4801 Bump groovy-jsr223 from 3.0.16 to 3.0.17

- Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-4840
The OpenSearch service is still being created on AWS, I'll launch a CI run on this PR when it's ready.
> HSEARCH-4840 Test against AWS OpenSearch Service 2.5

- pom.xml
follows up on https://github.com/hibernate/hibernate-search/pull/3473, https://github.com/hibernate/hibernate-search/pull/3465, https://github.com/hibernate/hibernate-search/pull/3456, https://github.com/hibernate/hibernate-search/pull/3446, https://github.com/hibernate/hibernate-search/pull/3441, https://github.com/hibernate/hibernate-search/pull/3435, https://github.com/hibernate/hibernate-search/pull/3428, https://github.com/hibernate/hibernate-search/pull/3419
> HSEARCH-4801 Update build dependencies

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/spi/ElasticsearchBackendSpiSettings.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientFactoryImpl.java
- documentation/src/main/asciidoc/internals/index.asciidoc
- documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4836
Since the property was added in HSEARCH-4683 (6.2.0.Alpha2)  I guess we can just move the property without keeping the "old" one.
> HSEARCH-4836 Move the ES client property to SPI settings

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneRootDocumentBuilder.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/collector/impl/DocumentReferenceValues.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/collector/impl/IdentifierValues.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/common/impl/MetadataFields.java
- documentation/src/main/asciidoc/migration/index.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-4845
I went with "recommendation" instead of "instruction" to recreate indexes for the Lucene backend since users not using ID or document reference projections will probably be ok with their indexes as is.
> HSEARCH-4845 Use a different field for retrieving a root object id in the Lucene backend

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetomany/AutomaticIndexingOneToManyCollectionBaseIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetomany/AutomaticIndexingOneToManyListBaseIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4848
> HSEARCH-4848 Fix unpredictable order of some associations in automatic reindexing tests

- Jenkinsfile
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4849
> HSEARCH-4849 Upgrade to Elasticsearch client 8.7.1 and test against Elasticsearch 8.7.1

- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/highlight/AbstractHighlighterIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/highlight/HighlighterPlainIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
https://hibernate.atlassian.net/browse/HSEARCH-2192
follows up on https://github.com/hibernate/hibernate-search/pull/3490
> HSEARCH-2192 Follow-up: Exclude the score order test for some ES versions

- pom.xml
follows up on https://github.com/hibernate/hibernate-search/pull/3482, https://github.com/hibernate/hibernate-search/pull/3473, https://github.com/hibernate/hibernate-search/pull/3465, https://github.com/hibernate/hibernate-search/pull/3456, https://github.com/hibernate/hibernate-search/pull/3446, https://github.com/hibernate/hibernate-search/pull/3441, https://github.com/hibernate/hibernate-search/pull/3435, https://github.com/hibernate/hibernate-search/pull/3428, https://github.com/hibernate/hibernate-search/pull/3419
> HSEARCH-4801 Bump maven-gpg-plugin from 3.0.1 to 3.1.0

- ci/dependency-update/Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-4839
follows up on https://github.com/hibernate/hibernate-search/pull/3495
> HSEARCH-4839 Follow-up: Make sure to rebuild the Lucene backend when running an upgrade job

- integrationtest/jsr352/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4854
If CI passes for this PR, I think we can consider the workaround is effective.
> HSEARCH-4854 Work around build errors caused by the Maven Pipeline Integration Plugin on Jenkins CI

- integrationtest/mapper/pojo-base/src/test/java17/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorRecordIT.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnRawTypeModel.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/PojoHCAnnMethodParameterModel.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PojoMethodParameterModel.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/search/definition/impl/PojoConstructorProjectionDefinition.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4853
> HSEARCH-4853 On JDK 21-ea+21, projection constructor relying on cannical record constructor result in all-null records

- ci/dependency-update/Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-4839
Just having the Lucene backend rebuilt is not enough since there are also changes in some test utils as well as changes in the batch module caused by the driver upgrade... It looks like it would be just safer to rebuild the entire project like we do for the orm6-in-main-code
> HSEARCH-4839 Follow-up: Make sure to rebuild everything when running a Lucene upgrade job

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4857
> HSEARCH-4857 Upgrade to Elasticsearch client 8.8.0 / Test against Elasticsearch 8.8.0 by default

- .mailmap
So that:
1. `git log` and similar commands stop displaying "Jenkins user <some random email>" for release commits from back when Jenkins was incorrectly configured, and just display "Hibernate-CI <ci@hibernate.org>" instead.
2. `git shortlog` correctly groups together commits of people who committed with multiple names (e.g. Sanne Grinovero vs. Sanne.Grinovero).
See https://git-scm.com/docs/gitmailmap
> Add .mailmap to the root of the repository

- documentation/src/main/asciidoc/reference/search-dsl-sort.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-4149
This was probably caused by some mixup while addressing review comments.
> HSEARCH-4149 Follow-up: Remove duplicate sentence in documentation

- documentation/src/main/asciidoc/reference/mapping-indexedembedded.asciidoc
- documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/excludepaths/Human.java
- documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/excludepaths/IndexedEmbeddedExcludePathsIT.java
- engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java
- engine/src/main/java/org/hibernate/search/engine/mapper/mapping/building/impl/ConfiguredIndexSchemaNestingContext.java
- engine/src/main/java/org/hibernate/search/engine/mapper/mapping/building/impl/IndexSchemaFilter.java
- engine/src/main/java/org/hibernate/search/engine/mapper/mapping/building/impl/PathFilter.java
- engine/src/main/java/org/hibernate/search/engine/mapper/mapping/building/spi/IndexedEmbeddedDefinition.java
- engine/src/main/java/org/hibernate/search/engine/mapper/mapping/building/spi/IndexedEmbeddedPathTracker.java
- engine/src/test/java/org/hibernate/search/engine/mapper/mapping/building/impl/ConfiguredIndexSchemaManagerNestingContextTest.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/document/DocumentElementDynamicFieldNameIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/document/DocumentElementFieldReferenceIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/document/DocumentElementStaticFieldNameIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java
- integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/embedded/path/validation/TestInvalidPaths.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/identity/impl/IdentityMappingCollectorValueNode.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/impl/PojoMapper.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/spi/PojoIndexMappingCollectorValueNode.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/IndexedEmbedded.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/IndexedEmbeddedProcessor.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/PropertyMappingIndexedEmbeddedStep.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/PropertyMappingIndexedEmbeddedStepImpl.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/processing/building/impl/PojoIndexingProcessorValueNodeBuilderDelegate.java
https://hibernate.atlassian.net/browse/HSEARCH-1182
Not going into recursion in `isPathIncludedInternal` when `!includedByThis` is messing up the path tracking, so I removed the change and added a note there so someone wouldn't try it in the future 😄
> HSEARCH-1182 Add `excludePaths` to IndexedEmbedded

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4870
https://hibernate.atlassian.net/browse/HSEARCH-4871
I've run the tests locally -- there's still a bug with BigDecimal in 8.8.1 😞😃
> HSEARCH-4870 Add compatibility with OpenSearch 2.8 / HSEARCH-4871 Upgrade to Elasticsearch client 8.8.1

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4875
Also added a commit to `orm6-in-main-code` - https://github.com/hibernate/hibernate-search/commit/66d230fd2328a43b66c9aa9e14a6fbf14ae2978c and rebased that branch since there were some merge conflicts.
> HSEARCH-4875 Upgrade -orm6 artifacts to Hibernate ORM 6.2.5.Final

- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/providedid/ProvidedIdIT.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/identity/impl/PojoRootIdentityMappingCollector.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/impl/PojoIndexModelBinder.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/impl/PojoIndexedTypeManagerBuilder.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/impl/PojoMapper.java
https://hibernate.atlassian.net/browse/HSEARCH-4877
> HSEARCH-4877 [Infinispan] Provided identifier bridge not applied in Search DSL and `id` projection

- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorObjectProjectionCycleIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4725
I've noticed that jdk 8/11 build didn't like static classes 😞 : 
https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/main/697/pipeline/106
> HSEARCH-4725 Follow-up: Make tests compatible with JDK 8/11

- documentation/src/main/asciidoc/public/reference/_mapping-configuration.adoc
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMappingInitiator.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/AnnotationMappingConfigurationContext.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationMappingConfigurationContextImpl.java
https://hibernate.atlassian.net/browse/HSEARCH-4882
If we overload the existing 'add' methods, then the compiler will fail when we call any 'add' method without Jandex in the classpath, even if it's not the one that uses Jandex.
> HSEARCH-4882 Avoid compilation failures when calling AnnotationMappingConfigurationContext#add without Jandex in the classpath

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cfg/LuceneBackendSettings.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneIdReader.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneIdReaderWriter.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneIdWriter.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneIndexEntryFactory.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneLegacyIdReaderWriter.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneModernIdReaderWriter.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneRootDocumentBuilder.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendFactory.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendImpl.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/IndexManagerBackendContext.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/collector/impl/DocumentReferenceValues.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/collector/impl/IdentifierValues.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/common/impl/MetadataFields.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/schema/SchemaIdStrategy.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneDocumentReferenceProjection.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneEntityLoadingProjection.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneEntityReferenceProjection.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneIdProjection.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/ProjectionExtractContext.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneExtractableSearchResult.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryBuilder.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearcherImpl.java
- documentation/src/main/asciidoc/public/reference/_backend-lucene.adoc
- integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/mapping/LuceneSchemaIdStrategyIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4884
That seems doable 😃, I've cherrypicked a first commit that originally introduced the change. And in the second commit, I've added a way we could pick which way to go. Do you have any suggestions for the property name? and how does this look overall?
> HSEARCH-4884   Configuration property to have a dedicated docvalue field for the root document id in the Lucene backend's document

- Jenkinsfile
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4885
https://hibernate.atlassian.net/browse/HSEARCH-4885
https://hibernate.atlassian.net/browse/HSEARCH-4887
this is a backport of https://github.com/hibernate/hibernate-search/pull/3565 to 6.2
> Backprot 6.2: HSEARCH-4885 / HSEARCH-4886 / HSEARCH-4887 Test against latest Opensearch/Elasticsearch / Upgrade Elasticsearch client 

- .github/dependabot.yml
- pom.xml
- Configure groovy upgrade rule
- and also bump groovy-jsr223 from 4.0.12 to 4.0.13
Bumps [groovy-jsr223](https://github.com/apache/groovy) from 4.0.12 to 4.0.13.
- [Commits](https://github.com/apache/groovy/commits)
---
- dependency-name: org.apache.groovy:groovy-jsr223 dependency-type: direct:production update-type: version-update:semver-patch ...
> Configure Groovy upgrade rule

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4555
I think we can reuse the 4555 since it wasn't released yet.
Bumps [jboss-logging](https://github.com/jboss-logging/jboss-logging) from 3.5.1.Final to 3.5.2.Final.
- [Release notes](https://github.com/jboss-logging/jboss-logging/releases)
- [Commits](https://github.com/jboss-logging/jboss-logging/compare/3.5.1.Final...3.5.2.Final)
---
- dependency-name: org.jboss.logging:jboss-logging dependency-type: direct:production update-type: version-update:semver-patch ...
> HSEARCH-4555 Bump jboss-logging from 3.5.1.Final to 3.5.2.Final

- .github/dependabot.yml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4602
https://hibernate.atlassian.net/browse/HSEARCH-4395
https://hibernate.atlassian.net/browse/HSEARCH-4891
Opening as a draft as this is based on https://github.com/hibernate/hibernate-search/pull/3562 
BTW do Weld and Jberet deserve their own tickets for an upgrade? 😃
> HSEARCH-4602 Upgrade to CDI 4 / HSEARCH-4395 cleanup dependabot rules

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4892
> HSEARCH-4892 Bump version.org.apache.avro from 1.11.1 to 1.11.2

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4892
backport of https://github.com/hibernate/hibernate-search/pull/3581
> Backport HSEARCH-4892 to branch 6.2 - Bump version.org.apache.avro from 1.11.1 to 1.11.2

- distribution/pom.xml
- integrationtest/java/modules/orm-coordination-outbox-polling-elasticsearch/pom.xml
- integrationtest/mapper/orm-spring/pom.xml
- integrationtest/showcase/library/pom.xml
- mapper/orm-coordination-outbox-polling/pom.xml
- mapper/orm/pom.xml
- mapper/pojo-base/pom.xml
- pom.xml
- util/common/pom.xml
- util/internal/integrationtest/jberet-se/pom.xml
- util/internal/integrationtest/v5migrationhelper/pom.xml
- util/internal/test/common/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4699
Should we ask the ORM team to add the following dependency to their bom:
```xml
<dependency>
<groupId>jakarta.enterprise</groupId>
<artifactId>jakarta.enterprise.cdi-api</artifactId>
<version>${version.jakarta.enterprise}</version>
</dependency>
```
> HSEARCH-4699 Rely on Hibernate ORM's BOM (hibernate-platform) to align on ORM's version of dependencies

- documentation/src/main/asciidoc/migration/index.adoc
- integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/schema/OutboxPollingCustomEntityMappingIT.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/HibernateOrmMapperOutboxPollingSettings.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/PayloadType.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/impl/PayloadMappingUtils.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/spi/HibernateOrmMapperOutboxPollingSpiSettings.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cluster/impl/OutboxPollingAgentAdditionalJaxbMappingProducer.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxPollingOutboxEventAdditionalJaxbMappingProducer.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/logging/impl/Log.java
https://hibernate.atlassian.net/browse/HSEARCH-4532
From what it looks, only Postgresql is affected by the changes. I've tried running the tests on other DBs we are testing against, and those didn't change their "create table scripts" keeping the same column type.
I was thinking if we should go with 1 or 2 config properties and went with 2 so that users could use a setting for one entity and replace the entire mapping for the other (hopefully nobody is going to do so 😆 but if they really wanted to -- they could)
> HSEARCH-4532 Change agent/event payload mapping

- build/parents/integrationtest/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4894
So using in-memory storage seems to help a bit with the schema operations (while before the change (for a specific test file), it was taking ~10 sec to create and drop the schema, now it is ~3sec)  See https://www.cockroachlabs.com/docs/stable/local-testing.html . Applying other options suggested under that link didn't do much so I haven't added those in this PR. 
Also, while at it, I've upgraded the DB version. It might be just me 😄 but it seemed that tests run a tod faster on this version 😆
> HSEARCH-4894 Use in-memory storage for CockroachDB

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4555
Bumps [jboss-logging](https://github.com/jboss-logging/jboss-logging) from 3.5.1.Final to 3.5.3.Final.
- [Release notes](https://github.com/jboss-logging/jboss-logging/releases)
- [Commits](https://github.com/jboss-logging/jboss-logging/compare/3.5.1.Final...3.5.3.Final)
---
- dependency-name: org.jboss.logging:jboss-logging dependency-type: direct:production update-type: version-update:semver-patch ...
> HSEARCH-4555 Bump jboss-logging from 3.5.1.Final to 3.5.3.Final

- build/configuration-properties-collector/src/main/java/org/hibernate/search/configuration/properties/collector/impl/AsciiDocWriter.java
- build/configuration-properties-collector/src/main/java/org/hibernate/search/configuration/properties/collector/impl/ConfigurationPropertyProcessor.java
- documentation/src/main/asciidoc/public/reference/_backend-elasticsearch.adoc
- documentation/src/main/asciidoc/public/reference/_backend-lucene.adoc
- documentation/src/main/asciidoc/public/reference/_configuration.adoc
- documentation/src/main/asciidoc/public/reference/_mapper-orm.adoc
- documentation/src/main/asciidoc/public/reference/_mapper-pojo-standalone.adoc
https://hibernate.atlassian.net/browse/HSEARCH-4899
I assume we'd want to backport this to 6.2 too, so if the changes are fine, I'll create a backport PR.
> HSEARCH-4899 Use the links to Appendix instead of Javadocs where possible in reference documentation

- build/configuration-properties-collector/src/main/java/org/hibernate/search/configuration/properties/collector/impl/AsciiDocWriter.java
- build/configuration-properties-collector/src/main/java/org/hibernate/search/configuration/properties/collector/impl/ConfigurationPropertyProcessor.java
- documentation/src/main/asciidoc/public/reference/_backend-elasticsearch.adoc
- documentation/src/main/asciidoc/public/reference/_backend-lucene.adoc
- documentation/src/main/asciidoc/public/reference/_configuration.adoc
- documentation/src/main/asciidoc/public/reference/_mapper-orm.adoc
- documentation/src/main/asciidoc/public/reference/_mapper-pojo-standalone.adoc
https://hibernate.atlassian.net/browse/HSEARCH-4899
backport of https://github.com/hibernate/hibernate-search/pull/3594
> Backport HSEARCH-4899 to branch 6.2 - Use the links to Appendix instead of Javadocs where possible in reference documentation

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4395
I've noticed that Depedabot was complaining that the version needs to be upgraded ... 
Using the switch-to-orm6 ticket since we've done "a few changes" to poms within that task 😄 
This property is also duplicated in the 6.2 branch, but since the version match for both properties there, it gives predictable results.
> HSEARCH-4395 Remove duplicated property for H2 version

- build/config/pom.xml
- build/parents/public/pom.xml
- distribution/pom.xml
- mapper/orm-batch-jsr352/core/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4901
- jakarta batch api is causing a warning when generating the javadocs (see more details in the POM comments)
- also noticed that `version.jakarta.persistence` wasn't parsed anymore, since that property wasn't present. I've added it back to the pom with some comments. I have looked for some plugins or how we could get the version coming from the ORM BOM. There is `dependencyversion-maven-plugin` but it doesn't seem to work. I've also tried to see if we could add these as properties to the hibernate-platform, but didn't find anything useful to do it in Gradle.
> HSEARCH-4901 Use `element-list` along side `package-list` for javadoc links

- bom/build/pom.xml
- bom/public/pom.xml
- build/config/pom.xml
- build/parents/integrationtest/pom.xml
- build/parents/internal/pom.xml
- build/parents/public/pom.xml
- build/reports/pom.xml
- distribution/pom.xml
- documentation/src/main/asciidoc/public/getting-started/orm/index.adoc
- documentation/src/main/asciidoc/public/getting-started/standalone/index.adoc
- documentation/src/main/asciidoc/public/reference/_compatibility.adoc
- integrationtest/showcase/library/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4896
Since I didn't want to move the properties from the root pom as those are grouped nicely there, I've ended up creating two BOMs with root as a parent. 
I've used the quarkus plugin to generate the effective public BOM and filtered out a few things from it that got into it only for build or dependency convergence resolution reasons. 
Let's see if this builds on CI 🙈 😄
> HSEARCH-4861 Add public BOM

- integrationtest/mapper/orm-spring/pom.xml
followup on https://github.com/hibernate/hibernate-search/pull/3588 / https://github.com/hibernate/hibernate-search/pull/3602
> HSEARCH-4861 Use expected hibernate version in spring mapper tests

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4904
https://hibernate.atlassian.net/browse/HSEARCH-4905
https://hibernate.atlassian.net/browse/HSEARCH-4906
> Backport to 6.2: HSEARCH-4904 /HSEARCH-4905 / HSEARCH-4906 Upgrade Elasticsarch client / Add compatibility with latest OpenSearch

- documentation/src/main/asciidoc/migration/index.adoc
https://hibernate.atlassian.net/browse/HSEARCH-4907
See also #3615 (similar, but not identical)
> [6.2] HSEARCH-4907 Fix links and formatting in the migration guide

- documentation/src/main/asciidoc/migration/index.adoc
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingDirtyCheckIT.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/cfg/HibernateOrmMapperSettings.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
https://hibernate.atlassian.net/browse/HSEARCH-4907
The previous wording was apparently confusing and made it seem like the property is already ignored; see https://github.com/quarkusio/quarkus-updates/pull/47#discussion_r1280427545
> [6.2] HSEARCH-4907 Follow-up: Clarify that hibernate.search.automatic_indexing.enable_dirty_check still works for now

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingDirtyCheckIT.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/cfg/HibernateOrmMapperSettings.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
https://hibernate.atlassian.net/browse/HSEARCH-4907
Same as #3620 but on the main branch, since it appears javadoc and runtime warnings were using a similar warning to the migration guide.
> HSEARCH-4907 Follow-up: Clarify that hibernate.search.automatic_indexing.enable_dirty_check still works for now

- build/config/pom.xml
- build/config/src/main/java/org/hibernate/checkstyle/report/AnnotationReportGenerator.java
- build/config/src/main/java/org/hibernate/checkstyle/report/InternalReportGenerator.java
- build/config/src/main/java/org/hibernate/checkstyle/report/ReportGenerator.java
- build/config/src/main/java/org/hibernate/checkstyle/report/ReportGeneratorHelper.java
- build/config/src/main/java/org/hibernate/checkstyle/report/ReportGeneratorRules.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4889
This is using Jandex to generate text files compatible with forbiddenapis. There are two report generators - one for incubating stuff and another for internal packages. 
I think this would be more flexible for us if for example, we'd need only to include some classes from an entire package marked as incubating in ORM, then we could ignore the package itself and look for all the classes in it to print in the file.
I have added regex rules per each thing currently "violating" the usage (and I was surprised to see some of them 😃).
> HSEARCH-4889 Forbid usage of internal/incubating Hibernate ORM code (API/SPI/...)

- bom/public/pom.xml
- build/config/pom.xml
- build/enforcer/pom.xml
- build/enforcer/src/main/java/org/hibernate/search/build/enforcer/DependencyManagementIncludesAllPublicArtifactsRule.java
- build/enforcer/src/main/java/org/hibernate/search/build/enforcer/VersionAlignData.java
- build/enforcer/src/main/java/org/hibernate/search/build/enforcer/VersionAlignRule.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4900
since we've changed what we include in the BOM, the original idea wasn't making sense anymore, so instead, I have added a couple of simple rules that would:
- check we've included all public artifacts in the BOM
- check the jakarta-persistence version property matches whatever the Hibernate ORM BOM tells us it should be.
Overall, it looks like these custom rules can be pretty flexible since they have access to the entire project structure and to Maven itself (to resolve dependencies from a repository, for example)
> HSEARCH-4900 Add custom enforcer rules

- integrationtest/mapper/orm-spring-uberjar/application/pom.xml
- integrationtest/mapper/orm-spring-uberjar/application/src/main/java/org/hibernate/search/integrationtest/spring/repackaged/application/Config.java
- integrationtest/mapper/orm-spring-uberjar/application/src/main/java/org/hibernate/search/integrationtest/spring/repackaged/application/RepackagedApplication.java
- integrationtest/mapper/orm-spring-uberjar/application/src/main/resources/application.yaml
- integrationtest/mapper/orm-spring-uberjar/application/src/test/java/org/hibernate/search/integrationtest/spring/repackaged/application/RepackagedApplicationIT.java
- integrationtest/mapper/orm-spring-uberjar/model/pom.xml
- integrationtest/mapper/orm-spring-uberjar/model/src/main/java/acme/org/hibernate/search/integrationtest/spring/repackaged/model/MyEntity.java
- integrationtest/mapper/orm-spring-uberjar/model/src/main/java/acme/org/hibernate/search/integrationtest/spring/repackaged/model/MyOtherEntity.java
- integrationtest/mapper/orm-spring-uberjar/model/src/main/java/acme/org/hibernate/search/integrationtest/spring/repackaged/model/MyProjection.java
- integrationtest/mapper/orm-spring-uberjar/pom.xml
- integrationtest/mapper/orm-spring-uberjar/test/pom.xml
- integrationtest/mapper/orm-spring-uberjar/test/src/test/java/org/hibernate/search/integrationtest/spring/repackaged/test/RepackagedAppIT.java
- integrationtest/pom.xml
- util/common/pom.xml
- util/common/src/main/java/org/hibernate/search/util/common/jar/impl/CodeSource.java
- util/common/src/main/java/org/hibernate/search/util/common/logging/impl/Log.java
- util/common/src/test/java/org/hibernate/search/util/common/jar/impl/CodeSourceTest.java
- util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/jar/JarTestUtils.java
https://hibernate.atlassian.net/browse/HSEARCH-4744
I've changed the exception from IO to Search one so that we wouldn't need a throwing bi function. Since the util tests do not run on JDK11 it seems safe to just update the test to expect that the jar will get processed OK. 
Also, I've tried these changes on a spring project -- worked fine when running as a repackaged jar.
> HSEARCH-4744 Try to read a nested jar on JDK13+

- .github/hibernate-github-bot.yml
- build/parents/build/pom.xml
Seem like dependabot couldn't find a newer version 🤷🏻‍♂️😃
> Bump version.org.google.guava from 31.1-jre to 32.1.2-jre

- build/parents/build/pom.xml
- integrationtest/mapper/orm-spring-uberjar/test/pom.xml
- pom.xml
follows up on https://github.com/hibernate/hibernate-search/pull/3618
> Followup HSEARCH-4861 Make tests work on nondefault JDKs

- .mvn/wrapper/maven-wrapper.properties
- Jenkinsfile
- ci/dependency-update/Jenkinsfile
- ci/performance/elasticsearch/Jenkinsfile
- ci/performance/lucene/Jenkinsfile
- ci/release/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4912
> HSEARCH-4912 Use Maven 3.9.4 in CI builds and as a required minimum version for the build

- Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-4916
TCK tests passed locally; let's see if they will also pass on CI
> HSEARCH-4916 Test against latest OpenSearch 1.3.12

- Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-4916
backport of https://github.com/hibernate/hibernate-search/pull/3638
> Backport to 6.2: HSEARCH-4916 Test against latest OpenSearch 1.3.12

- build/container/elasticsearch/env-7.0.properties
- build/container/elasticsearch/env-7.1.properties
- build/container/elasticsearch/env-7.10.properties
- build/container/elasticsearch/env-7.11.properties
- build/container/elasticsearch/env-7.12.properties
- build/container/elasticsearch/env-7.13.properties
- build/container/elasticsearch/env-7.14.properties
- build/container/elasticsearch/env-7.15.properties
- build/container/elasticsearch/env-7.16.properties
- build/container/elasticsearch/env-7.17.properties
- build/container/elasticsearch/env-7.2.properties
- build/container/elasticsearch/env-7.3.properties
- build/container/elasticsearch/env-7.4.properties
- build/container/elasticsearch/env-7.5.properties
- build/container/elasticsearch/env-7.6.properties
- build/container/elasticsearch/env-7.7.properties
- build/container/elasticsearch/env-7.8.properties
- build/container/elasticsearch/env-7.9.properties
- build/container/elasticsearch/env-8.0.properties
- build/container/elasticsearch/env-8.1.properties
- build/container/elasticsearch/env-8.2.properties
- build/container/elasticsearch/env-8.3.properties
- build/container/elasticsearch/env-8.4.properties
- build/container/elasticsearch/env-8.5.properties
- build/container/elasticsearch/env-8.6.properties
- build/container/elasticsearch/env-8.7.properties
- build/container/elasticsearch/env-8.8.properties
- build/container/elasticsearch/env-8.9.properties
- build/parents/build/pom.xml
- build/parents/integrationtest/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4910
Looking more at those templates being loaded, there's also `stack.templates.enabled` (https://www.elastic.co/guide/en/elasticsearch/reference/current/index-management-settings.html), but it seems to have no effect if passed as env variable (I guess it should be a part of elasticsearch.yml config? or maybe it just not related to the templates being loaded 😃)... 
for my local start with the changes:
```
[INFO] DOCKER> [elastic/elasticsearch:8.9.0] "elasticsearch": Waited on url http://localhost:9200 5609 ms
```
without the changes:
```
[INFO] DOCKER> [elastic/elasticsearch:8.9.0] "elasticsearch": Waited on url http://localhost:9200 6147 ms
```
soooo hopefully will be a tod better for CI builds too...
> HSEARCH-4910 Update Elasticsearch image config for tests

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch56ProtocolDialect.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch60ProtocolDialect.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch63ProtocolDialect.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch64ProtocolDialect.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch67ProtocolDialect.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch70ProtocolDialect.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch80ProtocolDialect.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch81ProtocolDialect.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/ElasticsearchProtocolDialect.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchLinkImpl.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/factory/impl/Elasticsearch56WorkFactory.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/factory/impl/Elasticsearch63WorkFactory.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/factory/impl/Elasticsearch67WorkFactory.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/factory/impl/Elasticsearch7WorkFactory.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/ElasticsearchRequestSuccessAssessor.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/SearchWork.java
- documentation/src/main/asciidoc/public/reference/_backend-elasticsearch.adoc
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/search/ElasticsearchShardsFailedExceptionIT.java
- integrationtest/backend/elasticsearch/src/test/resources/hsearch-4915/index1.json
- integrationtest/backend/elasticsearch/src/test/resources/hsearch-4915/index2.json
https://hibernate.atlassian.net/browse/HSEARCH-4915
A backport of https://github.com/hibernate/hibernate-search/pull/3652
> [Backport to 6.2] HSEARCH-4915 Errors returned by OpenSearch/ElasticSearch not forwarded to caller

- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/search/ElasticsearchShardsFailedExceptionIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4915
Since different ES versions will create a different number of shards by default 1/5/etc.. I thought that we've already removed the older versions of ES that were creating five shards as a default....  but apparently not, and the same goes for the older versions of Open Search ...
6.2 does not need any changes since the test adjustment is already present there.
> Followup: HSEARCH-4915 Do not rely on the number of shards in the error message

- .github/hibernate-github-bot.yml
- build/parents/build/pom.xml
- pom.xml
Since the marshalling dependency is used for ITs, let's run a build with it upgraded.
> Various build dependecy updates

- .github/dependabot.yml
- .github/hibernate-github-bot.yml
- build/parents/build/pom.xml
- util/common/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4917
I've tried to use `|` in the patterns, thinking it would allow me to combine some, but as you can see ... it didn't work, so patterns are listed in a more dependency-explicit way 😃 
I've also removed the jruby rule as now we have a config that does not need jruby dependency. And as we've upgraded our spring tests we can now do some upgrades of it from time to time, hence that version limit for it is gone. While testing it on my repo `org.bsc.maven:maven-processor-plugin` kept coming up with a jre8 version... so there's an ignore rule for it now too 😈😃
> HSEARCH-4917 Group build dependency updates in the Dependabot's config

- Jenkinsfile
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4921
backport of https://github.com/hibernate/hibernate-search/pull/3663
BTW... somewhat related to backporting 😃 -- I couldn't find any 6.2-something "unreleased" version
> [Backport 6.2] HSEARCH-4921 Upgrade to Elasticsearch client 8.9.1 and test against Elasticsearch 8.9.1

- documentation/src/main/asciidoc/public/reference/_indexing-plan.adoc
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
https://hibernate.atlassian.net/browse/HSEARCH-4909
I've scrolled through other log messages looking for conflicting configs and it seems mostly old/new property set at the same time, which I think we shouldn't document additionally 😃; indexing plan filter limitation is already mentioned in the reference; nothing else caught my eye 😃
> HSEARCH-4909 Add more info on indexing plan synchronization and coordination

- Jenkinsfile
To avoid this warning:
```
[WARNING] The property 'sonar.login' is deprecated and will be removed in the future. Please use the 'sonar.token' property instead when passing a token.
```
> Use sonar.token instead of sonar.login in Jenkinsfile

- util/common/src/main/java/org/hibernate/search/util/common/data/impl/HashTable.java
https://hibernate.atlassian.net/browse/HSEARCH-4926
This doesn't change the behavior in practice, but is slightly more
correct, and will avoid Sonar reporting a bug.
> HSEARCH-4926 Improve casts in HashTable

- build/parents/build/pom.xml
- pom.xml
Follows up on #3588 , #3602 , #3606 , #3618 , #3627 
Without this patch, we get this in build logs:
```
[WARNING] Failed to retrieve plugin descriptor for org.apache.avro:avro-maven-plugin:${version.org.apache.avro}: Plugin org.apache.avro:avro-maven-plugin:${version.org.apache.avro} or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.avro:avro-maven-plugin:jar:${version.org.apache.avro}
```
> HSEARCH-4861 Follow-up: Move Avro Maven plugin management to build/parents/build/pom.xml

- Jenkinsfile
- ci/list-dependent-integration-tests.sh
- pom.xml
I ended up always enabling the "pre-build", because it's simpler, possibly useful (I'd rather have formatting checks fail fast) and I don't expect it to impact non-incrementl builds too much (at worst we'll build integration tests twice, so will waste 3-4 minutes on a 1h build...)
> HSEARCH-4924 Follow-up: fix Sonar execution (hopefully)

- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerUpdateAnalyzerIT.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerUpdateCustomMappingIT.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerUpdateCustomSettingsIT.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerUpdateNormalizerIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4925
Follows up on #3671.
Looks like I made a very dumb mistake resulting in relevant tests never being executed.
I suppose we don't currently test on any platform where `supportsIndexClosingAndOpening()` would return `false`, and that's why the inverted assumption didn't cause any failure...
But let's leave the assumption anyway, because we'll need it to test Amazon OpenSearch Serverless.
> HSEARCH-4925 Follow-up: Improve documentation (and tests) of Elasticsearch/OpenSearch compatibility

- Jenkinsfile
Because this gets in the way when we run all tests: we always get failures for those few environments that we know cannot work.
> Remove a few build environments that are not actually available on CI

- bom/public/pom.xml
- build/parents/public/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4902
Follows up on #3603
This avoids weird URLs we're getting right now in flattened POMs:
```xml
<url>
http://hibernate.org/search/build/parents/hibernate-search-parent-build/hibernate-search-parent-public/hibernate-search-engine/
</url>
```
```xml
<scm>
<connection>
scm:git:git://github.com/hibernate/hibernate-search.git/build/parents/hibernate-search-parent-build/hibernate-search-parent-public/hibernate-search-engine
</connection>
<developerConnection>
scm:git:git@github.com:hibernate/hibernate-search.git/build/parents/hibernate-search-parent-build/hibernate-search-parent-public/hibernate-search-engine
</developerConnection>
<url>
http://github.com/hibernate/hibernate-search/build/parents/hibernate-search-parent-build/hibernate-search-paren …
```
> HSEARCH-4902 Follow-up: fix weird URLs in flattened POMs and use flattenMode

- Jenkinsfile
- build/enforcer/src/main/java/org/hibernate/search/build/enforcer/DependenciesIncludeAllTestCoverageModulesRule.java
- build/enforcer/src/main/java/org/hibernate/search/build/enforcer/MavenProjectUtils.java
- build/parents/build/pom.xml
- build/reports/pom.xml
- engine/pom.xml
- integrationtest/performance/backend/elasticsearch/pom.xml
- integrationtest/performance/backend/lucene/pom.xml
- integrationtest/pom.xml
- pom.xml
Test coverage is currently at 0 on Maven because the modules that contain classes that we need coverage numbers for *must* be included in the "default build - second round" that runs ITs. Otherwise the Jacoco execution will not report coverage for the corresponding classes.
This fixes that, and a bit more.
> HSEARCH-4924 Follow-up: ensure Jacoco coverage numbers are correct in default build + speed up some Maven executions on CI

- integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingConcurrencyIT.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxEventLoader.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxPollingEventProcessor.java
- mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/logging/impl/Log.java
https://hibernate.atlassian.net/browse/HSEARCH-4914
Essentially I'm giving up on avoiding deadlocks on CockroachDB. We'll retry instead, and will just avoid reporting errors.
> HSEARCH-4914 Handle transaction deadlocks more gracefully when retrieving outbox events (especially on CockroachDB)

- backend/elasticsearch-aws/src/main/java/org/hibernate/search/backend/elasticsearch/aws/impl/ElasticsearchAwsHttpClientConfigurer.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchVersionTest.java
- documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexing/HibernateOrmMassIndexerIT.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java
- integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/massindexing/MassIndexingManualSchemaManagementIT.java
- integrationtest/performance/backend/base/src/main/java/org/hibernate/search/integrationtest/performance/backend/base/testsupport/index/AbstractBackendHolder.java
- mapper/orm-batch-jsr352/core/src/main/java/org/hibernate/search/batch/jsr352/core/massindexing/step/afterchunk/impl/AfterChunkBatchlet.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoScopeWorkspaceImpl.java
- pom.xml
- util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/ElasticsearchBackendConfiguration.java
- util/internal/integrationtest/mapper/stub/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/stub/BulkIndexer.java
- add an execution for a formatter plugin
- reformat the project with an enabled plugin
Seems like with all the plugins moved around we've lost the execution of the formatter plugin 🙈
> Enable code formatting plugin in default build

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4933
I used the wrong version of bytebuddy and forgot that we also need to test against ORM 5, where we still need `net.bytebuddy.experimental=true` on Java 21...
> HSEARCH-4933 Follow-up: Fix incorrect bytebuddy changes

- build/parents/public/pom.xml
- pom.xml
- to prevent it from running after moditect, which causes issues otherwise
The other moditect goal (that we've talked about over Zulip) doesn't work for us since that one generates a java file for an already built jar ... so that somewhat does not meet our needs 😃 
I have tested this javadoc generation when a module has a module-info.java file in the root and it worked ok... 
I have also tried to add sources via `build-helper-maven-plugin` since moditect generates the file into target dir... but then the build was failing as the generated file was missing a "require" for jboss-logging-annotations ...
> Change when the default attach-javadocs execution runs

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/JoiningTextMultiValuesSource.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/TextMultiValues.java
https://hibernate.atlassian.net/browse/HSEARCH-4939
> HSEARCH-4939 Avoid uses of Lucene's NO_MORE_ORDS constant

- Jenkinsfile
- build/parents/build/pom.xml
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4941
https://hibernate.atlassian.net/browse/HSEARCH-4942
> HSEARCH-4941 Upgrade to Elasticsearch client 8.9.2 and test against Elasticsearch 8.9.2 / HSEARCH-4942 Test against latest Elasticsearch 7.17.13

- documentation/src/main/asciidoc/migration/index.adoc
https://hibernate.atlassian.net/browse/HSEARCH-4943
I guess since there can be these differences we could also give users these migration scripts if they'd want to make schema validation work ok... 😃
> HSEARCH-4943 Add migration to update id column types

- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- ci/dependency-update/rules-lucene10.xml
- ci/dependency-update/rules-lucene9.xml
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/dialect/ElasticsearchTestDialect.java
- util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/rule/TestElasticsearchClient.java
- util/internal/integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/dialect/ElasticsearchTestDialectVersionTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4920
I haven't found if there are snapshots for ES/OS images, so I haven't added anything for them...
As for the Lucene upgrade, I thought we could run the upgrade tests for the current 9 series as well as for the upcoming 10.
> HSEARCH-4920 Add CI jobs to test against the latest version of Lucene/Elasticsearch

- Jenkinsfile
I've initially thought about wrapping the line
```
-Dsonar.pullrequest.branch=${helper.scmSource.branch.name} \
```
with some double quotes, but then thought that maybe it'll be better to just not allow doing "crazy" branch names in the first place 😃
> Check that the branch name follows a simple pattern without any unexpected symbols that might need escaping

- ci/dependency-update/Jenkinsfile
- orm6/integrationtest/v5migrationhelper/orm/ant-src-changes.patch
> Follow-up: HSEARCH-4944 Update ORM6 patch to not use an array in a `@SkipForDialect`

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4920
I'd expect something along these lines to work: we iterate over various docker registries, and if the image cannot be pulled, it is added for an attempt to be pulled from the next registry and so on...
I've added the exact change with a different registry order to the main Jenkins file so we can test it in the PR..
> HSEARCH-4920 Follow-up: Don't pre-pull images from elastic docker registry

- Jenkinsfile
- build/parents/build/pom.xml
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4958
> HSEARCH-4958 Upgrade to Elasticsearch client 8.10.1 and test against Elasticsearch 8.10.1

- .github/workflows/build.yml
- CONTRIBUTING.md
- build/parents/build/pom.xml
- build/parents/integrationtest/pom.xml
- documentation/pom.xml
- integrationtest/backend/elasticsearch/pom.xml
- integrationtest/backend/lucene/pom.xml
- integrationtest/java/modules/orm-coordination-outbox-polling-elasticsearch/pom.xml
- integrationtest/java/modules/orm-elasticsearch/pom.xml
- integrationtest/java/modules/orm-lucene/pom.xml
- integrationtest/java/modules/pojo-standalone-elasticsearch/pom.xml
- integrationtest/java/modules/pojo-standalone-lucene/pom.xml
- integrationtest/mapper/orm-batch-jsr352/pom.xml
- integrationtest/mapper/orm-coordination-outbox-polling/pom.xml
- integrationtest/mapper/orm-realbackend/pom.xml
- integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/schema/management/ElasticsearchSchemaManagerExporterIT.java
- integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/schema/management/LuceneSchemaManagerExporterIT.java
- integrationtest/mapper/orm-spring-uberjar/application/pom.xml
- integrationtest/mapper/pojo-standalone-realbackend/pom.xml
- integrationtest/performance/backend/elasticsearch/pom.xml
- integrationtest/performance/backend/lucene/pom.xml
- integrationtest/showcase/library/pom.xml
- integrationtest/v5migrationhelper/engine/pom.xml
- integrationtest/v5migrationhelper/orm/pom.xml
- util/common/src/main/java/org/hibernate/search/util/common/jar/impl/CodeSource.java
- util/common/src/test/java/org/hibernate/search/util/common/jar/impl/CodeSourceTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4947
The idea here is that since we are trying to construct a URI then we should construct it from the URI 😃 
Since in the case of Linux `Path` path would have the same `/` that is needed for a URI, but then in Windows, it'll be `\`, and URI construction won't work...
And the same is about the test updates; the changes are to make the asserts compare the URIs rather than Path vs URI
I've reverted the ORM version to 6.2 series to test the spring boot uberjar module -- the tests passed with these changes.
> HSEARCH-4947 Make sure that nested jars can be read on Windows

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/JoiningLongMultiValuesSource.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/JoiningTextMultiValuesSource.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/LongMultiValues.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/TextMultiValues.java
https://hibernate.atlassian.net/browse/HSEARCH-4969
I also aligned the implementation of LongMultiValues, though I'm not sure that was strictly necessary. It's clearer anyway IMO.
> HSEARCH-4969 IndexOutOfBoundsException in TextMultiValues

- Jenkinsfile
- build/container/elasticsearch/env-8.10.properties
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/highlight/HighlighterUnifiedIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
- pom.xml
* [HSEARCH-4967](https://hibernate.atlassian.net/browse/HSEARCH-4967): Upgrade to Elasticsearch client 8.10.2 and test against Elasticsearch 8.10.2
* [HSEARCH-4958](https://hibernate.atlassian.net/browse/HSEARCH-4958): Upgrade to Elasticsearch client 8.10.1 and test against Elasticsearch 8.10.1
* [HSEARCH-4946](https://hibernate.atlassian.net/browse/HSEARCH-4946): Upgrade to Elasticsearch client 8.10.0 and test against Elasticsearch 8.10.0
@marko-bekhta Yes, I know, I said previously it wasn't worth it. But seeing the list of issues in the 6.2.2 release made me realize I was just dumb to force 6.2 users to get a warning as soon as they try to use the latest Elasticsearch (8.10). Especially since the client upgrade doesn't change anything, so integrators can certainly stick to the client …
> Backport HSEARCH-4946 + HSEARCH-4958 + HSEARCH-4967 to branch 6.2 - Upgrade to Elasticsearch client 8.10.2 and test against Elasticsearch 8.10.2

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessorImpl.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/IndexWriterProvider.java
https://hibernate.atlassian.net/browse/HSEARCH-4983
> HSEARCH-4983 Concurrency issues in Lucene IndexAccessor/IndexWriterProvider may lead to LockObtainFailedException: Lock held by this virtual machine

- ci/dependency-update/Jenkinsfile
I suppose with the next ORM upgrade, we can remove these additional build args as the changes will be in the main artifact already ...
> [Hibernate Search 6.2] HSEARCH-4944 Recompile util module to make the ORM6.2 upgrade work correctly

- ci/dependency-update/Jenkinsfile
- orm6/integrationtest/v5migrationhelper/orm/ant-src-changes.patch
- util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/H2LazyMultiTenantConnectionProvider.java
I don't see a `wip/6.1/dependency-update/orm6-in-main-code` ... so I didn't upgrade the wip branch for patches ...
> [Backport to 6.1] HSEARCH-4944 Adjust tests to address ORM changes

- documentation/src/main/asciidoc/public/reference/_indexing-workspace.adoc
https://hibernate.atlassian.net/browse/HSEARCH-4985
> Backport HSEARCH-4985 to branch 6.2 - Fix heading level of documentation section "Explicitly altering a whole index"

- integrationtest/mapper/orm-jakarta-batch/src/test/java/org/hibernate/search/integrationtest/jakarta/batch/component/HibernateSearchPartitionMapperComponentIT.java
- mapper/orm-jakarta-batch/core/src/main/java/org/hibernate/search/jakarta/batch/core/massindexing/step/impl/HibernateSearchPartitionMapper.java
- mapper/orm-jakarta-batch/core/src/main/resources/META-INF/batch-jobs/hibernate-search-mass-indexing.xml
https://hibernate.atlassian.net/browse/HSEARCH-4986
I had to completely give up on using scrolls for partition mapping, see commit messages.
We'll still use scrolls during mass indexing to load IDs though, that doesn't change.
> HSEARCH-4986 Mapping partitions fails in Jakarta Batch mass indexing job for some JDBC drivers (DB2, MSSQL, ...)

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4987
I assume it's okay just to reuse the same ticket since we haven't released this yet. I'll update the JIRA description.
> HSEARCH-4987 Upgrade -orm6 artifacts to Hibernate ORM 6.2.12.Final

- Jenkinsfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4990
https://hibernate.atlassian.net/browse/HSEARCH-4991
> HSEARCH-4990 Upgrade to Elasticsearch client 8.10.3 and test against Elasticsearch 8.10.3 / HSEARCH-4991 Test against latest Elasticsearch 7.17.14

- build/config/pom.xml
- build/enforcer/pom.xml
- build/reports/pom.xml
- integrationtest/v5migrationhelper/engine/pom.xml
- integrationtest/v5migrationhelper/orm/pom.xml
- util/internal/integrationtest/v5migrationhelper/pom.xml
- v5migrationhelper/engine/pom.xml
- v5migrationhelper/orm/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4989
The problem was coming from how the plugin decides if it is the last module in the execution run ... it expects to encounter all the modules, even those that skip plugin execution... but it still wants to see them as "executed" which never happens 😃 ...
using this other property `jqassistant.maven.module.skip` allows skipping the analysis of the module, which makes the plugin happy and it manages to correctly figure out when to run the analysis..
I have also looked into the rule for nested static class ... but the info is not there. from what it seems ASM does not add a static modifier to the descriptor and that field is never set to true in the generated DB, there's also no other info that can be used to cover that sooo I've just added …
> HSEARCH-4989 Use a different property to skip JQAssistant analysis of some modules

- ci/dependency-update/Jenkinsfile
The idea is to include only those jobs that do not require building ORM. Then since we are going to trigger this job from the ORM side passing the `UPGRADE_JOB` parameter, we don't really need to parse the version, I'd expect that once we build ORM from a specified branch, we'd get a fresh snapshot version in the maven repo, and maven should pick it up as it was doing so before...
I went with the `choice` parameter type for `UPGRADE_JOB` as I assume we'd only have one upgrade job for a particular ORM version...
> [6.2] Add job parameters to dependency upgrade pipeline

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4992
Bumps software.amazon.awssdk:auth from 2.20.2 to 2.21.1.
---
> HSEARCH-4992 Bump software.amazon.awssdk:auth from 2.20.2 to 2.21.1

- integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/sharding/AbstractSettingsPerShardIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/analysis/AnalysisBuiltinIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/AndPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/BoolPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/ExistsPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/ExistsPredicateObjectsBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/MatchAllPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/MatchIdPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/MatchPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/NotPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/OrPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/PhrasePredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RangePredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RegexpPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SimpleQueryStringPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SpatialWithinBoundingBoxPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SpatialWithinCirclePredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SpatialWithinPolygonPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/TermsPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/WildcardPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/CompositeProjectionBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/DistanceProjectionBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/FieldProjectionBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/ObjectProjectionBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexIndexingPlanIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/BytecodeEnhancementIT.java
- util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/extension/parameterized/ParameterizedClassPostDiscoveryFilter.java
https://hibernate.atlassian.net/browse/HSEARCH-3654
> [Follow up] HSEARCH-3654 Update some tests to work on JDK11

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4993
https://hibernate.atlassian.net/browse/HSEARCH-4994
I've noticed that I missed to bump the minor version in the ES check ... so added that to this patch.
> HSEARCH-4994 Upgrade to Elasticsearch client 8.10.4 and test against Elasticsearch 8.10.4 / HSEARCH-4993 Add compatibility with OpenSearch 2.11.0

- ci/dependency-update/Jenkinsfile
https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-marko/detail/build%2Fupdate-update-job-main/1/pipeline/
> Add job parameters to dependency upgrade pipeline

- ci/dependency-update/Jenkinsfile
E.g. in Jakarta Batch integration modules where we have one failsafe execution per backend.
@marko-bekhta FYI
> Skip Elasticsearch tests on ALL Lucene dependency-update jobs

- ci/dependency-update/Jenkinsfile
- ci/dependency-update/rules-orm6.4.xml
https://hibernate.atlassian.net/browse/HSEARCH-4997
> HSEARCH-4997 Compatibility with Hibernate ORM 6.4

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4996
Bumps `version.org.jberet` from 2.1.2.Final to 2.1.3.Final.
Updates `org.jberet:jberet-core` from 2.1.2.Final to 2.1.3.Final
- [Release notes](https://github.com/jberet/jsr352/releases)
- [Commits](https://github.com/jberet/jsr352/compare/2.1.2.Final...2.1.3.Final)
Updates `org.jberet:jberet-se` from 2.1.2.Final to 2.1.3.Final
- [Release notes](https://github.com/jberet/jsr352/releases)
- [Commits](https://github.com/jberet/jsr352/compare/2.1.2.Final...2.1.3.Final)
---
- dependency-name: org.jberet:jberet-core dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: org.jberet:jberet-se dependency-type: direct:production update-type: version-update:semver-patch ...
> HSEARCH-4996 Bump version.org.jberet from 2.1.2.Final to 2.1.3.Final

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4998
As far as I can tell the `docker.io/` prefix was the only useful change, and even then I'm not 100% sure it was required. It's probably better for CI though, to make sure we retrieve the container images from wherever we authenticated.
FWIW, `integrationtest/mapper/orm-realbackend` now builds fine on my laptop using podman, including with `-Pci-postgres` and/or with `-Dtest.elasticsearch.distribution=opensearch`.
> HSEARCH-4998 Make the build compatible with podman

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4998
Backport of #3803 to branch 6.2
> Backport HSEARCH-4998 to branch 6.2 - Make the build compatible with podman

- documentation/src/main/asciidoc/migration/index.adoc
https://hibernate.atlassian.net/browse/HSEARCH-5002
> HSEARCH-5002 Document dropped compatibility with older Elasticsearch/OpenSearch versions and Hibernate ORM 6.3 upgrade in migration guide

- ci/dependency-update/Jenkinsfile
Here's an ORM job triggering the Search dependency update job and waiting for the results: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-orm-personal-marko/detail/ci%2Fadd-hibernate-search-tests-to-build-test/15/pipeline/
I've tried `git` `checkout` as well as `git clone -c 'core.sshCommand=ssh -v ...` for cloning a repo using an ssh URL, but with no luck... it looks like git wasn't able to find the known_hosts that would contain the keys we had on CI... Hence I've just adapted the job to "convert" the URL instead 🙈 🙈 🙈 
I'll backport to 6.2 once we merge the changes to main and then update the ORM PR so it can actually trigger the correct build 😃
> Remove update dependencies job throttling

- ci/dependency-update/Jenkinsfile
That would've been to easy if that worked on the first try 😄 (with the repo and branch)
I've followed these commands https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally?tool=webui
There are two options now -- we can build from a fork repo using [repo URL + branch name] or we can build from a pull request [repo URL + PR id]
https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-marko/detail/build%2Fupdate-update-job-6-2/2/pipeline/7
> Make update depdendency job compatible with ORM pull requests

- .github/workflows/build.yml
*  Fix pattern order in GitHub Actions workflow 
*  Use a shorter workflow name
> GH Actions workflow fixes

- .github/dependabot.yml
- build/container/database/mssql.Dockerfile
https://hibernate.atlassian.net/browse/HSEARCH-4674
empty or `""` empty strings didn't work , but from the logs it looks like it can figure it out without any additional configs:
```
updater | 2023/11/08 10:43:01 INFO <job_746926390> Checking if db2_community/db2 11.5.8.0 needs updating
proxy | 2023/11/08 10:43:02 [108] GET https://icr.io:443/v2/db2_community/db2/tags/list
proxy | 2023/11/08 10:43:02 [108] 200 https://icr.io:443/v2/db2_community/db2/tags/list
proxy | 2023/11/08 10:43:02 [110] HEAD https://icr.io:443/v2/db2_community/db2/manifests/latest
proxy | 2023/11/08 10:43:02 [110] 200 https://icr.io:443/v2/db2_community/db2/manifests/latest
proxy | 2023/11/08 10:43:02 [112] HEAD https://icr.io:443/v2/db2_community/db2/manifests/11.5.8.0
proxy | 2023/11/08 10:43:02 [112] 200 …
```
> Followup: HSEARCH-4674 Change dependabot configuration for databases

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5005
Tests passed locally, let's see what CI will tell us.
Should we also backport to 6.2?
> HSEARCH-5005 Upgrade to Elasticsearch client 8.11.0 and test against Elasticsearch 8.11.0

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchGeoPointSpatialWithinPolygonPredicate.java
https://hibernate.atlassian.net/browse/HSEARCH-4999
Luckily, Elasticsearch 7.10 already support this query 🎉. I've tried using the relation operator (`WITHIN`/`CONTAINS`) 
(https://www.elastic.co/guide/en/elasticsearch/reference/8.11/query-dsl-geo-shape-query.html#geo-shape-spatial-relations) but since older Elasticsearch versions (e.g. 7.10 ...) can only work with the default `INTERSECTS` value I've removed it 😃 
tested it locally with Elasticsearch 7.10.1/7.17.14/8.11.0 and OpenSearch 1.3.13/2.11.0
> HSEARCH-4999 Use geo_shape instead of geo_polygon in Elasticsearch spatial predicates

- pom.xml
to work with non-docker-io registries (e.g. db2/mssql)
Right now, these won't be prefetched. It should still work out ok in the end as they can be downloaded without docker auth. But let's fetch them the same as we are doing for other  containters.
> Update Groovy script to list required test containers

- Jenkinsfile
- build/container/search-backend/amazon-opensearch-serverless.Dockerfile
- build/container/search-backend/opensearch.Dockerfile
https://hibernate.atlassian.net/browse/HSEARCH-5026
backport of https://github.com/hibernate/hibernate-search/pull/3850
> Backport of HSEARCH-5026 to 7.0 - Test against latest OpenSearch 2.11.1

- orm6/integrationtest/mapper/orm-spring-uberjar/application/ant-src-changes.patch
- orm6/integrationtest/mapper/orm-spring-uberjar/application/pom.xml
- orm6/integrationtest/mapper/orm-spring-uberjar/model/pom.xml
- orm6/integrationtest/mapper/orm-spring-uberjar/pom.xml
- orm6/integrationtest/pom.xml
- util/common/src/main/java/org/hibernate/search/util/common/jar/impl/CodeSource.java
https://hibernate.atlassian.net/browse/HSEARCH-5024
for 6.2 we didn't update spring integration tests, and they are still based on 2.7. Update would mean Jakarta, java17 and probably more, So I don't think we want to bump the version for the main build ... I've added a copy of the repackaged app to orm6 modules so we can still test the compatibility a bit.
> HSEARCH-5024 Adjust the CodeSource to be able to handle the new URL structure of the nested jars from Spring

- Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-5041
> Backport of HSEARCH-5041 to 7.0 - Test against latest OpenSearch 1.3.14

- .mvn/wrapper/maven-wrapper.properties
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5040
> HSEARCH-5040 Use Maven 3.9.6 in CI builds and as a required minimum version for the build

- build/parents/build/pom.xml
- pom.xml
I've just checked that the tests now compile and run OK with JDK 22. For JDK 23 it is:
```
Caused by: java.io.IOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [/home/marko/development/projects/opensource/hibernate-search/integrationtest/mapper/orm-spring/target/test-classes/org/hibernate/search/integrationtest/spring/transaction/TransactionIT$HelperService$MakeRollbackException.class]
at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:59)
at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:48)
at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataRead …
```
> Enable Spring tests on JDK 22

- engine/src/main/java/org/hibernate/search/engine/environment/bean/TypeBeanReference.java
- engine/src/main/java/org/hibernate/search/engine/environment/bean/impl/BeanConfigurationContextImpl.java
- engine/src/main/java/org/hibernate/search/engine/environment/bean/impl/BeanReferenceRegistryForType.java
- engine/src/main/java/org/hibernate/search/engine/environment/bean/spi/BeanConfigurationContext.java
- engine/src/test/java/org/hibernate/search/engine/environment/bean/impl/BeanResolverImplBaseTest.java
https://hibernate.atlassian.net/browse/HSEARCH-5034
> HSEARCH-5034 Allow passing BeanReference<? extends T> when registering beans to BeanConfigurationContext

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/impl/ElasticsearchIndexFieldTypeFactoryImpl.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/impl/AbstractLuceneVectorFieldTypeOptionsStep.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/impl/LuceneByteVectorFieldTypeOptionsStep.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/impl/LuceneFloatVectorFieldTypeOptionsStep.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/impl/LuceneIndexFieldTypeFactoryImpl.java
- engine/src/main/java/org/hibernate/search/engine/backend/reporting/spi/BackendMappingHints.java
- engine/src/main/java/org/hibernate/search/engine/backend/types/dsl/IndexFieldTypeFactory.java
- engine/src/main/java/org/hibernate/search/engine/backend/types/dsl/VectorFieldTypeOptionsStep.java
- integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/reader/LuceneIndexReaderCodecLoadingIT.java
- integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/mapping/LuceneVectorFieldIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateSpecificsIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/ByteVectorFieldTypeDescriptor.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/FloatVectorFieldTypeDescriptor.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/VectorFieldIT.java
- integrationtest/mapper/pojo-standalone-realbackend/pom.xml
- integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/mapping/VectorFieldIT.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/reporting/impl/HibernateOrmMappingHints.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/PropertyMappingVectorFieldOptionsStepImpl.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/reporting/impl/StandalonePojoMappingHints.java
- util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/types/dsl/impl/StubIndexFieldTypeFactory.java
- util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/types/dsl/impl/StubVectorFieldTypeOptionsStep.java
- util/internal/integrationtest/mapper/stub/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/stub/StubMappingHints.java
https://hibernate.atlassian.net/browse/HSEARCH-5021
This is just a draft for now so we can talk over the code 😃
> HSEARCH-5021 Improve support for custom value bridges for vector fields

- Jenkinsfile
- pom.xml
It EOL'd on Sept 19th, 2023.
See https://endoflife.date/oracle-jdk
Also, we already test against the next version (21).
> Stop testing against JDK 20

- Jenkinsfile
- pom.xml
It EOL'd on Sept 19th, 2023.
See https://endoflife.date/oracle-jdk
Also, we already test against the next version (21).
Backport of #3897 to branch 7.0.
> Backport to branch 7.0: Stop testing against JDK 20

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5055
> Backport of HSEARCH-5055 to 7.0 - Upgrade to Elasticsearch client 8.11.4 and test against Elasticsearch 8.11.4

- .github/dependabot.yml
Because let's be real, Marko is the one doing all that work lately.
> Assign dependabot PRs to Marko instead of Yoann

- Jenkinsfile
Luckily for 6.2 we have:
```
new OpenSearchLocalBuildEnvironment(version: '2.11.0', condition: TestCondition.AFTER_MERGE)
```
And 6.1 is only testing against 1.x (though it's 1.2 1.0 for them and not 1.3 that we are using for later versions ... )
any earlier versions do not run tests against OpenSearch
> Test against OpenSearch 2.11 on AWS [6.2]

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5059
do we want to add this to 6.2 as well ?
> Backport of HSEARCH-5059 to 7.0 - Add compatiblity with Elasticsearch 8.12.0 and upgrade to Elasticsearch client 8.12.0

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchKnnPredicate.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/query/impl/VectorSimilarityFilterQuery.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneKnnPredicate.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/AbstractLuceneVectorFieldCodec.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneVectorFieldCodec.java
- documentation/src/main/asciidoc/public/reference/_backend-elasticsearch.adoc
- documentation/src/main/asciidoc/public/reference/_search-dsl-predicate.adoc
- documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/KnnPredicateOptionsStep.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/spi/AbstractKnnPredicateFieldStep.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/KnnPredicateBuilder.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateSpecificsIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
https://hibernate.atlassian.net/browse/HSEARCH-5052
Hey Yoann 😃 
You've probably seen the discussion we had yesterday on Zulip here: https://infinispan.zulipchat.com/#narrow/stream/118645-infinispan/topic/vector.20search/near/407994976 
I thought I'd give it a try and see what can we do to filter things out on our side; I've looked into creating custom queries and that's what I've put together. Do you think this could be something useful to add?
> HSEARCH-5052 Filter out documents with vectors below a "similarity limit"

- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/bootstrap/StandalonePojoIntegrationBooterIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/bootstrap/UnusedPropertiesIT.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/bootstrap/impl/StandalonePojoIntegrationBooterImpl.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/bootstrap/impl/StandalonePojoIntegrationPartialBuildState.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/bootstrap/spi/StandalonePojoIntegrationBooter.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/bootstrap/spi/StandalonePojoIntegrationBooterBehavior.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/cfg/spi/StandalonePojoMapperSpiSettings.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/SearchMapping.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/SearchMappingBuilder.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoEntityTypeContributor.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMappingInitiator.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoTypeConfigurationContributor.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoTypeContextContainer.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/model/impl/StandalonePojoBootstrapIntrospector.java
- util/internal/integrationtest/mapper/pojo-standalone/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/pojo/standalone/StandalonePojoMappingHandle.java
https://hibernate.atlassian.net/browse/HSEARCH-5065
Backport of #3924 to branch 7.0
> Backport HSEARCH-5065 to branch 7.0 - Two-phase boot for the standalone POJO mapper

- documentation/src/main/asciidoc/public/reference/_entrypoints.adoc
- documentation/src/test/java/org/hibernate/search/documentation/mapper/pojo/standalone/entrypoints/StandalonePojoEntryPointsIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/search/SearchQueryBaseIT.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/logging/impl/Log.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/SearchMapping.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMapperDelegate.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMapping.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoTypeContextContainer.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/session/SearchSession.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/session/impl/StandalonePojoSearchSession.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/session/impl/StandalonePojoSearchSessionMappingContext.java
https://hibernate.atlassian.net/browse/HSEARCH-5067
Backport of #3927 to branch 7.0
> Backport HSEARCH-5067 to branch 7.0 - Allow targeting entities by name in the Standalone POJO Mapper

- .github/dependabot.yml
Yes it's ugly, but I'm out of ideas, and we can't keep using an old plugin forever.
> Dependabot: update maven-processor-plugin

- Jenkinsfile
- pom.xml
The hope is that whenever we add a new JDK version to test, we'll notice this setting, will try to remove it and upgrade bytebuddy if necessary. This would avoid mess-ups like the one that caused https://github.com/hibernate/hibernate-orm/pull/7790
> Move setting of net.bytebuddy.experimental to the Jenkinsfile

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5077
> Backport of HSEARCH-5077 to 7.0 - Upgrade to Elasticsearch client 8.12.1 and test against Elasticsearch 8.12.1

- documentation/src/main/asciidoc/public/reference/_search-dsl-projection.adoc
- documentation/src/test/java/org/hibernate/search/documentation/search/projection/ProjectionDslIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/highlight/AbstractHighlighterIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/highlight/HighlightProjectionTypeIndependentIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5033
I didn't find much to rename anymore, but I've moved tests out of an `AbstractHighlighterIT` that do not really need to be tested against different highlighter types.
> HSEARCH-5033 Better tests and documentation of limitations around nested fields for highlighting

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/analysis/impl/ElasticsearchAnalysisDescriptor.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/analysis/model/impl/ElasticsearchAnalysisDefinitionRegistry.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexModel.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/impl/LuceneAnalysisDescriptor.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/model/impl/LuceneAnalysisDefinitionRegistry.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/LuceneIndexRootBuilder.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexModel.java
- documentation/src/main/asciidoc/public/reference/_mapping-inspect.adoc
- documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedentities/SearchMappingIndexedEntitiesIT.java
- engine/src/main/java/org/hibernate/search/engine/backend/analysis/AnalysisDescriptor.java
- engine/src/main/java/org/hibernate/search/engine/backend/analysis/AnalyzerDescriptor.java
- engine/src/main/java/org/hibernate/search/engine/backend/analysis/NormalizerDescriptor.java
- engine/src/main/java/org/hibernate/search/engine/backend/analysis/spi/AnalysisDescriptorRegistry.java
- engine/src/main/java/org/hibernate/search/engine/backend/document/model/spi/AbstractIndexModel.java
- engine/src/main/java/org/hibernate/search/engine/backend/metamodel/IndexDescriptor.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/analysis/AnalysisBuiltinIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/analysis/AnalysisBuiltinOverrideIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
- util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/document/model/dsl/impl/StubIndexRootBuilder.java
- util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/document/model/impl/StubIndexModel.java
https://hibernate.atlassian.net/browse/HSEARCH-4961
WDYT?  😃 I've ended up adding backend-specific methods to backends since, in the case of the ES backend, we'd need to pass an index name + the name of the analyzer... so it won't match the Lucene case.. and forcing to pass index name for Lucene... I wasn't sure it would be ok 😃
> HSEARCH-4961 API to list all analyzer names

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/HibernateOrmIntegrationBooterIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/bootstrap/StandalonePojoIntegrationBooterIT.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/bootstrap/impl/StandalonePojoIntegrationPartialBuildState.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMapperDelegate.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMappingInitiator.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/mapping/impl/StandalonePojoMappingPartialBuildState.java
https://hibernate.atlassian.net/browse/HSEARCH-5089
Backport of #3977 to branch 7.1
> Backport HSEARCH-5089 to branch 7.1 - Retrieve the schema management strategy on start for the Standalone Pojo Mapper

- documentation/src/main/asciidoc/public/reference/_mapping-entitydefinition.adoc
https://hibernate.atlassian.net/browse/HSEARCH-5090
> HSEARCH-5090 Fix typos/headings in `@SearchEntity` documentation

- documentation/src/main/asciidoc/public/reference/_mapping-entitydefinition.adoc
https://hibernate.atlassian.net/browse/HSEARCH-5090
Backport of #3979 to branch 7.1
> Backport HSEARCH-5090 to branch 7.1 - Fix typos/headings in `@SearchEntity` documentation

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/model/impl/OpenSearch29ModelDialect.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/container/search-backend/amazon-opensearch-serverless.Dockerfile
- build/container/search-backend/opensearch.Dockerfile
- build/parents/build/pom.xml
- documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/TermsPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
- integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/mapping/VectorFieldIT.java
- util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/SearchBackendContainer.java
https://hibernate.atlassian.net/browse/HSEARCH-5087
https://hibernate.atlassian.net/browse/HSEARCH-5088
Let's see if this won't be the same as with the Lucene update PR 😏 😄
> HSEARCH-5087 Add compatibility with OpenSearch 2.12.0

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/model/impl/OpenSearch29ModelDialect.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/container/search-backend/amazon-opensearch-serverless.Dockerfile
- build/container/search-backend/opensearch.Dockerfile
- build/parents/build/pom.xml
- documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/TermsPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
- integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/mapping/VectorFieldIT.java
- util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/SearchBackendContainer.java
https://hibernate.atlassian.net/browse/HSEARCH-5087
https://hibernate.atlassian.net/browse/HSEARCH-5088
backport of https://github.com/hibernate/hibernate-search/pull/3973
> Backport of HSEARCH-5087 to 7.1 - Add compatibility with OpenSearch 2.12.0

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5091
backport of https://github.com/hibernate/hibernate-search/pull/3982
> Backport of HSEARCH-5091 to 7.1 - Upgrade to Elasticsearch client 8.12.2 and test against Elasticsearch 8.12.2

- integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/mapping/VectorFieldIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5087
- make sure that serverless is correctly included in the checks
> Follow up on: HSEARCH-5087 Disable some tests for OpenSearch 2.12

- integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/mapping/VectorFieldIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5087
- make sure that serverless is correctly included in the checks
backport of https://github.com/hibernate/hibernate-search/pull/3987
> Backport of follow up on HSEARCH-5087 to 7.1 -  Disable some tests for OpenSearch 2.12

- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchQueryAdapter.java
https://hibernate.atlassian.net/browse/HSEARCH-5092
Note the different method name -- it's so it does not clash with the one that is currently still visible to this adapter.
> HSEARCH-5092 Make `HibernateOrmSearchQueryAdapter` compatible with a future ORM 6.5 release

- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchQueryAdapter.java
https://hibernate.atlassian.net/browse/HSEARCH-5092
backport of https://github.com/hibernate/hibernate-search/pull/3985
> Backport of HSEARCH-5092 to 7.1 - Make `HibernateOrmSearchQueryAdapter` compatible with a future ORM 6.5 release

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/query/impl/Queries.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchKnnPredicate.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/PredicateRequestContext.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryBuilder.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/aggregation/impl/AggregationExtractContext.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/AbstractLuceneNestablePredicate.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneKnnPredicate.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneNestedPredicate.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/PredicateRequestContext.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneObjectProjection.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneExtractableSearchResult.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryBuilder.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryRequestContext.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/sort/impl/LuceneSearchSortCollector.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/sort/impl/SortRequestContext.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/spi/LuceneMigrationUtils.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/AbstractLuceneNestableAggregation.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/impl/AbstractLuceneDocumentValueSort.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/impl/LuceneGeoPointDistanceSort.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/impl/LuceneStandardFieldSort.java
- documentation/src/main/asciidoc/public/reference/_search-dsl-predicate.adoc
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/multitenancy/MultiTenancyBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/sharding/RoutingVectorSearchIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
https://hibernate.atlassian.net/browse/HSEARCH-5039
I thought I'd add a couple of tests and ... well. ... . .  😃 
The outer tenant filter is applied "too late". It finds similar vectors among all tenants, and only then it applies the tenant filter, returning fewer results than the user expected.
With the Elasticsearch backend, the change was much cleaner, while with the Lucene one... needed to delay converting some things to Lucene queries 😞 
I also noticed an unused method on the collector interface, so I've dropped it since it is in the impl package.
> HSEARCH-5039 Tenant filter should be a pre-filter for knn predicates

- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/multitenancy/MultiTenancyBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/sharding/RoutingVectorSearchIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5039
backport of https://github.com/hibernate/hibernate-search/pull/3992
> Backport of HSEARCH-5039 to 7.1 - Follow up on: Disable some tests for OpenSearch/Elasticsearch that do not support vectors

- ci/dependency-update/Jenkinsfile
With Lucene bumping min JDK to 21.... 🙈
> Allow dependency jobs to specify JDK version

- build/config/src/main/resources/checkstyle.xml
- documentation/src/main/asciidoc/migration/index.adoc
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingInheritanceIT.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/common/impl/HibernateOrmUtils.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/AbstractHibernateOrmLoadingStrategy.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/HibernateOrmEntityIdEntityLoadingStrategy.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/HibernateOrmNonEntityIdPropertyEntityLoadingStrategy.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoImplicitReindexingResolverBuildingHelper.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/loading/spi/PojoLoadingTypeContext.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/impl/PojoMapper.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/impl/AbstractPojoTypeManager.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/impl/PojoTypeManagerContainer.java
Hey Yoann,
I was looking into the https://discourse.hibernate.org/t/polymorphic-mass-indexing-with-discriminator/8869  to see what we can do there.
One of the problems is that we are creating the query factory from the root entity but in that case it makes ORM  join all the tables, so the idea here is to create a query factory from a most specific common supertype... 
https://hibernate.atlassian.net/browse/HSEARCH-5062
> HSEARCH-5062 Target types as precise as possible for entity loading

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5098
Bumps software.amazon.awssdk:auth from 2.24.1 to 2.25.2.
---
> HSEARCH-5098 Bump software.amazon.awssdk:auth from 2.24.1 to 2.25.2

- build/parents/build/pom.xml
Testing locally, it seems we no longer need to declare these snapshot repos as "release", so whatever bug there was in versions-maven-plugin, isn't there anymore.
More importantly, dependabot has been failing to update things like jackson lately, and I'm hoping this was the cause. See the logs [here](https://github.com/hibernate/hibernate-search/network/updates/795977249):
```
updater | 2024/03/05 02:15:44 INFO <job_795977249> Checking if com.fasterxml.jackson.core:jackson-core 2.15.2 needs updating
proxy | 2024/03/05 02:15:44 [749] GET https://oss.sonatype.org:443/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-core/maven-metadata.xml
proxy | 2024/03/05 02:15:44 [749] 200 https://oss.sonatype.org:443/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-core/ …
```
> Fix incorrect configuration of snapshots repositories

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5100
Bumps [com.google.code.gson:gson](https://github.com/google/gson) from 2.9.1 to 2.10.1.
- [Release notes](https://github.com/google/gson/releases)
- [Changelog](https://github.com/google/gson/blob/main/CHANGELOG.md)
- [Commits](https://github.com/google/gson/compare/gson-parent-2.9.1...gson-parent-2.10.1)
---
- dependency-name: com.google.code.gson:gson dependency-type: direct:production update-type: version-update:semver-minor ...
> HSEARCH-5100 Bump com.google.code.gson:gson from 2.9.1 to 2.10.1

- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendHelper.java
- integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckBackendHelper.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/multitenancy/MultiTenancyBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendHelper.java
https://hibernate.atlassian.net/browse/HSEARCH-5006
noticed test failures on aws OpenSearch: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/main/1034/pipeline/136/
and while at it -- updated the test to create an index once for the entire class rather than creating/removing it for each test
> Follow up on HSEARCH-5006 Use single-sharded indexes in tests with knn predicates

- .mvn/gradle-enterprise.xml
Because it seems to be the case when building directly from branches: instead of not setting the env variable, GitHub sets it to an empty string. That threw off our previous condition, but not the new one.
cc @marko-bekhta FYI, merging now.
> Enable remote cache storing when GITHUB_BASE_REF is set to an empty string

- .github/dependabot.yml
- since we align the version with the one used in Wildfly
> Ignore Jackson updates in dependabot config

- .github/workflows/build.yml
- CONTRIBUTING.md
- Jenkinsfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-5094
Because if we do this through the POM, the environment variable is taken
into account for build caching, which results in cache entries
contributed by CI being ignored when building locally.
> HSEARCH-5094 Follow-up: Enable testcontainers reuse on CI through workflow/pipeline config rather than the POM

- build/config/src/main/java/org/hibernate/checkstyle/report/AnnotationReportGenerator.java
- build/config/src/main/java/org/hibernate/checkstyle/report/ReportGeneratorRules.java
https://hibernate.atlassian.net/browse/HSEARCH-5094
So that Maven goal executions relying on it (e.g. checkstyle) can be cached.
> HSEARCH-5094 follow-up: HSEARCH-5094 Make sure the content of internal/incubating reports is reproducible  

- pom.xml
Because:
> a new field forceLegacyJavacApi will make the compiler goal not cacheable until bumping up the Gradle Enterprise extension to 1.21 (should be available before end of month).
I hope dependabot will open another PR to upgrade again; if so let's leave that PR open until we do the Gradle Enterprise upgrade.
> Revert maven-compiler-plugin to 3.12.1

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/provider/impl/Elasticsearch7IndexFieldTypeFactoryProvider.java
https://hibernate.atlassian.net/browse/HSEARCH-5110
> HSEARCH-5110 Error message when the version of Elasticsearch/Opensearch is too old for vector search states wrong requirements

- .github/workflows/build.yml
- Jenkinsfile
And do it synchronously (before the build ends) so that Hibernate GitHub Bot is able to list build scans immediately.
> Safely publish build scans even for pull requests 

- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateSpecificsIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5113
backport of https://github.com/hibernate/hibernate-search/pull/4067
> Backport of HSEARCH-5113 to 7.1 : Update asserts and vectors matched in knn predicates

- pom.xml
Bumps the build-dependencies group with 2 updates: org.ow2.asm:asm, [de.thetaphi:forbiddenapis](https://github.com/policeman-tools/forbidden-apis).
Updates `org.ow2.asm:asm` from 9.6 to 9.7
Updates `de.thetaphi:forbiddenapis` from 3.6 to 3.7
- [Commits](https://github.com/policeman-tools/forbidden-apis/compare/3.6...3.7)
---
- dependency-name: org.ow2.asm:asm dependency-type: direct:production update-type: version-update:semver-minor dependency-group: build-dependencies
- dependency-name: de.thetaphi:forbiddenapis dependency-type: direct:production update-type: version-update:semver-minor dependency-group: build-dependencies ...
> Bump the build-dependencies group with 2 updates

- integrationtest/mapper/orm-outbox-polling/pom.xml
- integrationtest/mapper/orm-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingDynamicShardingRebalancingIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4965
From what it seems, the recent changes to address various flaky tests addressed the issues on Windows as well. 
I've tried running these tests on my Win-env and also on my fork here: https://github.com/marko-bekhta/hibernate-search/actions/runs/8449830574/job/23144761949?pr=248 (forcing some changes to the module so that the tests will actually get executed and not skipped because of the cache). And there are no failures anymore 🤞🏻
> HSEARCH-4965 Enable outbox-polling integration tests on Windows

- Jenkinsfile
It looks like this in practice:
Anybody in the Hibernate organization is able to approve something like this.
Approval is not required for non-PR builds, or builds of PRs submitted by members of the organization, or builds of PRs explicitly triggered (through the UI) by members of the organization.
> Require approval for Jenkins builds on PRs from external contributors

- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateSpecificsIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5113
- be even more lenient in asserts
https://ge.hibernate.org/s/l4mjv5lidnebq/tests/goal/org.hibernate.search:hibernate-search-integrationtest-backend-elasticsearch:failsafe:integration-test@it/details/org.hibernate.search.integrationtest.backend.tck.search.predicate.KnnPredicateSpecificsIT$ExampleKnnSearchIT/multipleKnn_shouldClauses?top-execution=1
> Follow up on : HSEARCH-5113 Update asserts and vectors matched in knn predicates

- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateSpecificsIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5113
backport of https://github.com/hibernate/hibernate-search/pull/4080
> Backport of follow up on HSEARCH-5113 to 7.1 - Update asserts and vectors matched in knn predicates

- pom.xml
Bumps the build-dependencies group with 4 updates:
| Package | From | To |
| --- | --- | --- |
| [org.apache.maven.plugins:maven-gpg-plugin](https://github.com/apache/maven-gpg-plugin) | `3.2.1` | `3.2.2` | | [org.apache.maven.plugins:maven-compiler-plugin](https://github.com/apache/maven-compiler-plugin) | `3.12.1` | `3.13.0` | | [org.moditect:moditect-maven-plugin](https://github.com/moditect/moditect) | `1.2.0.Final` | `1.2.1.Final` | | [org.owasp:dependency-check-maven](https://github.com/jeremylong/DependencyCheck) | `9.0.10` | `9.1.0` | | [org.awaitility:awaitility](https://github.com/awaitility/awaitility) | `4.2.0` | `4.2.1` | | [com.puppycrawl.tools:checkstyle](https://github.com/checkstyle/checkstyle) | `10.14.2` | `10.15.0` |
Updates `org.apache.maven.plugins:maven-gpg-plugin` …
> Bump the build-dependencies group with 4 updates

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/container/search-backend/amazon-opensearch-serverless.Dockerfile
- build/container/search-backend/elastic.Dockerfile
- build/container/search-backend/opensearch.Dockerfile
- build/parents/build/pom.xml
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5122
https://hibernate.atlassian.net/browse/HSEARCH-5114
https://hibernate.atlassian.net/browse/HSEARCH-5121
> Backport of HSEARCH-5122/HSEARCH-5114/HSEARCH-5121 to 7.1 Add compatibility with Elasticsearch 8.13 / Add compatibility with OpenSearch 2.13.0

- .gitignore
- .mvn/develocity.xml
- .mvn/extensions.xml
- CONTRIBUTING.md
Local build scans and build caching seem to work fine... Let's merge and see if this holds for CI and remote caches :)
> Upgrade to develocity-maven-extension 1.21 / hibernate-search-develocity-extension 2.0.0

- .github/dependabot.yml
- build/parents/build/pom.xml
- pom.xml
Bumps the build-dependencies group with 3 updates: [org.apache.maven.plugins:maven-compiler-plugin](https://github.com/apache/maven-compiler-plugin), [org.apache.maven.plugins:maven-source-plugin](https://github.com/apache/maven-source-plugin), [org.jacoco:jacoco-maven-plugin](https://github.com/jacoco/jacoco).
Updates `org.apache.maven.plugins:maven-compiler-plugin` from 3.12.1 to 3.13.0
- [Release notes](https://github.com/apache/maven-compiler-plugin/releases)
- [Commits](https://github.com/apache/maven-compiler-plugin/compare/maven-compiler-plugin-3.12.1...maven-compiler-plugin-3.13.0)
Updates `org.apache.maven.plugins:maven-source-plugin` from 3.3.0 to 3.3.1
- [Commits](https://github.com/apache/maven-source-plugin/compare/maven-source-plugin-3.3.0...maven-source-plugin-3.3.1) …
> Bump the build-dependencies group with 3 updates

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5125
https://hibernate.atlassian.net/browse/HSEARCH-5114
backport of https://github.com/hibernate/hibernate-search/pull/4103
> Backport of HSEARCH-5125 to 7.1 - Test against Elasticsearch 8.13.2 / HSEARCH-5114 Revert back to Elasticsearch client 8.12.2

- .gitignore
- Jenkinsfile
- documentation/pom.xml
- documentation/src/main/asciidoc/public/reference/_compatibility.adoc
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5128
Backport of #4109 to branch 7.1.
> Backport HSEARCH-5128 to branch 7.1 - Update the supported versions of Java in the documentation

- .gitignore
- Jenkinsfile
- documentation/pom.xml
- documentation/src/main/asciidoc/public/reference/_compatibility.adoc
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5128
Backport of #4109 to branch 7.0.
> Backport HSEARCH-5128 to branch 7.0 - Update the supported versions of Java in the documentation

- .gitignore
- Jenkinsfile
- documentation/pom.xml
- documentation/src/main/asciidoc/public/reference/_compatibility.adoc
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5128
Backport of https://github.com/hibernate/hibernate-search/pull/4109 to branch 6.2.
> Backport HSEARCH-5128 to branch 6.2 - Update the supported versions of Java in the documentation

- .github/workflows/build.yml
- .mvn/develocity.xml
- Jenkinsfile
- ci/dependency-update/Jenkinsfile
```
[WARNING] The following functionality has been deprecated and will be removed in the next major release of the Develocity Maven extension: 
[WARNING] - The deprecated "GRADLE_ENTERPRISE_ACCESS_KEY" environment variable has been replaced by "DEVELOCITY_ACCESS_KEY"
```
^ noticed in the logs for both CI and GH
> Update Develocity env variable name

- util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/DatabaseContainer.java
https://www.cockroachlabs.com/docs/stable/local-testing#use-a-local-single-node-cluster-with-in-memory-storage
I tried it on `AutomaticIndexingEmbeddableIT` locally and had a 9 sec vs 12 sec execution time compared to the current command.
> Update CockroachDB configuration

- Jenkinsfile
- build/reports/pom.xml
- documentation/pom.xml
- integrationtest/mapper/orm-jakarta-batch/pom.xml
- integrationtest/mapper/orm-realbackend/pom.xml
- integrationtest/mapper/pojo-standalone-realbackend/pom.xml
- integrationtest/showcase/library/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4927
I've tried these changes here https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-marko/detail/build%2Fjacoco-agg-all/5/pipeline/ 
it seems like that worked. 
I've moved some Jacoco configurations into profiles. I think that the change makes sense, but I'll let you @yrodiere confirm if it won't be an issue for build scans.
> HSEARCH-4927 Take into account all integration tests in Sonar reports

- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/QueryStringPredicateSpecificsIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SimpleQueryStringPredicateSpecificsIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4558
From an answer in a Lucene issue it turns out that things like that in range query string can be "escaped" with additional quotes, so let's have more tests running 😃
> Follow up on HSEARCH-4558 Enable more range tests for ZoneDateTime and query string predicates

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5096
We actually wouldn't need to update the release script because of https://github.com/mojohaus/versions/commit/04afc2c4b9c98cb9ff7cf4f8e0b7d5678cf58fe7 . Since 2.12 versions plugin will automatically update the timestamp on the `version:set`. I've tested it locally and updating the version updates the timestamp as well 🥳 
And we also don't need the `notimestamp` for javadocs since https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#notimestamp 🥳 (also double checked it locally 😃)
I have tried the git plugin as well, but it is just a timestamp of the last commit, so ... since with version plugin doing all the updates for us and no need in release script update, we don't need the git plugin.
> HSEARCH-5096 Update plugin configuration for reproducible builds

- engine/src/main/java/org/hibernate/search/engine/environment/thread/impl/EmbeddedThreadProvider.java
- engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java
https://hibernate.atlassian.net/browse/HSEARCH-5132
> HSEARCH-5132 Do not directly rely on the Security Manager in EmbeddedThreadProvider

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchRangePredicate.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneQueryStringPredicate.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneNumericRangePredicate.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextRangePredicate.java
- documentation/src/main/asciidoc/public/reference/_search-dsl-predicate.adoc
- documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/RangePredicateMatchingStep.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/RangePredicateFieldMoreStepImpl.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/RangePredicateBuilder.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RangePredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RangePredicateSpecificsIT.java
- util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubSearchPredicate.java
- v5migrationhelper/engine/src/main/java/org/hibernate/search/query/dsl/impl/ConnectedMultiFieldsRangeQueryBuilder.java
https://hibernate.atlassian.net/browse/HSEARCH-4542
> HSEARCH-4542 .within() and .withinAny() for the range predicate

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessorImpl.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/reader/impl/IndexReaderProvider.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/reader/impl/NearRealTimeIndexReaderProvider.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/reader/impl/NotSharedIndexReaderProvider.java
- backend/lucene/src/test/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessorTest.java
- integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/reader/LuceneIndexSegmentFilesIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5107
https://hibernate.atlassian.net/browse/HSEARCH-5108
> HSEARCH-5107 Add a test checking segment files on various index operations

- ci/dependency-update/Jenkinsfile
Lucene 10 keeps updating the API 😃. Since there's a  change `Character[] -> char[]` now in highlighter code, let's also make it available to the users (in the Lucene 10 branch) and rebuild engine to make things work
> Rebuild engine for Lucene 10 upgrade to address API/SPI change

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/model/impl/Elasticsearch814ModelDialect.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/provider/impl/Elasticsearch814IndexFieldTypeFactoryProvider.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/mapping/impl/Elasticsearch812VectorFieldTypeMappingContributor.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/mapping/impl/Elasticsearch814VectorFieldTypeMappingContributor.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/validation/impl/Elasticsearch814PropertyMappingValidatorProvider.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/validation/impl/PropertyMappingValidator.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/AbstractPredicateSingleFieldIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateSpecificsIT.java
- pom.xml
- util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/dialect/ElasticsearchTestDialect.java
https://hibernate.atlassian.net/browse/HSEARCH-5164
https://hibernate.atlassian.net/browse/HSEARCH-5165
> HSEARCH-5164 Add Elasticsearch 8.14.0 compatibility / HSEARCH-5165 Upgrade to Elasticsearch client 8.14.0

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5191
> HSEARCH-5191 Upgrade -orm6 artifacts to Hibernate ORM 6.2.27.Final

- .github/workflows/build.yml
- Jenkinsfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- ci/performance/elasticsearch/Jenkinsfile
- ci/performance/lucene/Jenkinsfile
- ci/release/Jenkinsfile
- engine/src/main/java/org/hibernate/search/engine/environment/classpath/spi/DefaultResourceResolver.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/FloatFieldTypeDescriptor.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/JavaNetURLPropertyTypeDescriptor.java
- integrationtest/performance/pom.xml
- pom.xml
- util/common/src/main/java/org/hibernate/search/util/common/jar/impl/CodeSource.java
- util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/SystemHelper.java
https://hibernate.atlassian.net/browse/HSEARCH-5155
> HSEARCH-5155 Build with JDK 21

- integrationtest/performance/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5155
As the generation plugin does not necessarily work with the latest EA builds of the JDK.
> Follow up on HSEARCH-5155  - Use a release java version for perf tests

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingGenericMappedSuperclassIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5136
The fix itself is in ORM, but let's have a test case in Search to catch any other similar issues in the future, if any.
> HSEARCH-5136 Add a test case for: Mapped superclass with generic ID causes MassIndexer to fail

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5195
https://hibernate.atlassian.net/browse/HSEARCH-5196
Elasticsearch client upgrade
> HSEARCH-5195 Upgrade Elasticsearch client to 8.14.2 / HSEARCH-5173 Test against latest Elasticsearch 8.14.1

- Jenkinsfile
- build/parents/build/pom.xml
- build/parents/public/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5192
https://hibernate.atlassian.net/browse/HSEARCH-5193
Using the `org.jboss.logging.tools.addGeneratedAnnotation=false` to produce "reproducible" sources jar.
Update Jenkins job to test build reproducibility.
Add a profile to run a reproducible build more easily.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-search/blob/main/CONTRIBUTING.md#legal …
> HSEARCH-5192 Make Hibernate Search build produce "reproducible" sources jar / HSEARCH-5193 Add a build step to verify the build reproducibility

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5200
Bumps `version.com.fasterxml.jackson` from 2.17.1 to 2.17.2.
Updates `com.fasterxml.jackson.core:jackson-core` from 2.17.1 to 2.17.2
- [Commits](https://github.com/FasterXML/jackson-core/compare/jackson-core-2.17.1...jackson-core-2.17.2)
Updates `com.fasterxml.jackson.core:jackson-annotations` from 2.17.1 to 2.17.2
- [Commits](https://github.com/FasterXML/jackson/commits)
Updates `com.fasterxml.jackson.core:jackson-databind` from 2.17.1 to 2.17.2
- [Commits](https://github.com/FasterXML/jackson/commits)
---
- dependency-name: com.fasterxml.jackson.core:jackson-core dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: com.fasterxml.jackson.core:jackson-annotations …
> HSEARCH-5200 Bump version.com.fasterxml.jackson from 2.17.1 to 2.17.2

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5202
https://hibernate.atlassian.net/browse/HSEARCH-5203
https://github.com/hibernate/hibernate-search/pull/4226
> HSEARCH-5202 Upgrade Elasticsearch client to 8.14.3 / HSEARCH-5203 Test against latest Elasticsearch 8.14.3

- documentation/src/main/asciidoc/public/reference/_mapping-directfieldmapping.adoc
https://hibernate.atlassian.net/browse/HSEARCH-5204
These changes should fix the rendering (https://docs.asciidoctor.org/asciidoc/latest/directives/include-list-item-content/)
> HSEARCH-5204 Fix rendering of some definition lists

- README.md
https://hibernate.atlassian.net/browse/HSEARCH-5193
WDYT @yrodiere  ? 🙈 😃 Noticed this here https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/doc/TOOLS.md#4-add-reproducible-builds-badge-to-a-project-with-reproducible-releases and thought ... why not? 😃. It is a static badge so it won't change if the state on reproducible-central change but ... 😃 
For more information on licensing, please check …
> Follow up on HSEARCH-5193  - Add reproducible badge to the Readme

- Jenkinsfile
- ci/nightly/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5193
https://hibernate.zulipchat.com/#narrow/stream/132092-hibernate-search-dev/topic/Build.20reproducibility.20check
We can start with something like this, I guess?
And the test build execution here https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-marko/detail/build%2FHSEARCH-5193-move-repro-check-to-nightly/2/pipeline/
For more information on licensing, please …
> Follow up on HSEARCH-5193 - Move the reproducibility check to the nightly build

- build/parents/build/pom.xml
so that we are not affected by the Awaitility 4.2.1 upgrade having problems running on JDK 23+
Related to the https://github.com/hibernate/hibernate-search/pull/4237 upgrades.
> Downgrade test containers to 1.19

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/model/impl/OpenSearch214ModelDialect.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchKnnPredicate.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/provider/impl/OpenSearch214IndexFieldTypeFactoryProvider.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/mapping/impl/AbstractOpenSearch2VectorFieldTypeMappingContributor.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/mapping/impl/OpenSearch214VectorFieldTypeMappingContributor.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/KnnPredicateSpecificsIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
https://hibernate.atlassian.net/browse/HSEARCH-5182
This is a follow-up since not all OpenSearch versions that support vector search can do a similarity filter ... 😕 
> HSEARCH-5182 Add an OpenSearch dialect to address where knn similarity filters can be applied

- .github/workflows/build.yml
- Jenkinsfile
- the previously used `gradle-enterprise:build-scan-publish-previous` command is for the "deprecated plugin" that is now replaced with `develocity:build-scan-publish-previous`
And hopefully, this will remove the warnings like:
```
[WARNING] The artifact com.gradle:gradle-enterprise-maven-extension:jar:1.21.6 has been relocated to com.gradle:develocity-maven-extension:jar:1.21.6
```
from the logs 🤞🏻 
For more information on licensing, please …
> Use the develocity:build-scan-publish-previous to publish build scans

- integrationtest/mapper/orm-spring-uberjar/application/pom.xml
I've noticed this warning in the build logs:
> [WARNING]  Parameter 'finalName' is read-only, must not be used in configuration
- `finalName` turns out to be a read-only property, even though it does work with our current config 🤷🏻 ... what the plugin suggests is to set the final name at the build level: https://docs.spring.io/spring-boot/maven-plugin/packaging.html#packaging.examples.custom-name rather than inside of the configuration. I've removed the property entirely and just updated the `test.repackaged-jar-path` instead. 
- `outputTimestamp` is now unnecessary, as the `project.build.outputTimestamp` is used by default (the one we set in the root pom)
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 …
> Update Spring repackage configuration for uber-jar tests

- ci/dependency-update/Jenkinsfile
just in case there are any new snapshots for 9.11 branch in the future
> Allow continuing Lucene 9.11 upgrade build even if snapshot version was not updated

- CONTRIBUTING.md
- README.md
- build/parents/public/pom.xml
- documentation/src/main/asciidoc/public/getting-started/orm/index.adoc
- documentation/src/main/asciidoc/public/getting-started/standalone/index.adoc
- documentation/src/main/asciidoc/public/reference/_further-reading.adoc
- documentation/src/main/asciidoc/public/reference/_migrating.adoc
- pom.xml
It'll get redirected to https anyway, so why not give an https URL to start with ... 
> Use https for hibernate.org URLs

- documentation/src/main/asciidoc/migration/index.adoc
https://hibernate.atlassian.net/browse/HSEARCH-5187
So we don't forget to add it before the release... 
> Follow up on HSEARCH-5187 - Add a migration note on a deprecated ValueConvert enum

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/impl/ElasticsearchStringIndexFieldTypeOptionsStep.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchTextPrefixPredicate.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/impl/LuceneStringIndexFieldTypeOptionsStep.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextPrefixPredicate.java
- documentation/src/main/asciidoc/public/reference/_search-dsl-predicate.adoc
- documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
- engine/src/main/java/org/hibernate/search/engine/backend/types/IndexFieldTraits.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/PrefixPredicateFieldMoreStep.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/PrefixPredicateFieldStep.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/PrefixPredicateMatchingStep.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/PrefixPredicateOptionsStep.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/SearchPredicateFactory.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/PrefixPredicateFieldMoreStepImpl.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/PrefixPredicateFieldStepImpl.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/spi/AbstractSearchPredicateFactory.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/PredicateTypeKeys.java
- engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/PrefixPredicateBuilder.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/PrefixPredicateBaseIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/PrefixPredicateTestValues.java
- util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubSearchPredicate.java
https://hibernate.atlassian.net/browse/HSEARCH-3906
Adds a prefix predicate to the search DSL.
> HSEARCH-3906 Add prefix predicate

- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/PrefixPredicateTestValues.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
https://hibernate.atlassian.net/browse/HSEARCH-3609
> Follow up on HSEARCH-3906 Update how analyzed strings are treated for ES backend and prefix predicate in tests

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5220
https://hibernate.atlassian.net/browse/HSEARCH-5221
> HSEARCH-5220 Add Elasticsearch 8.15.0 compatibility

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/container/search-backend/amazon-opensearch-serverless.Dockerfile
- build/container/search-backend/opensearch.Dockerfile
- build/parents/build/pom.xml
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/operations/RangeAggregationDescriptor.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
- integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/LibraryShowcaseSearchIT.java
- integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/TestActiveProfilesResolver.java
https://hibernate.atlassian.net/browse/HSEARCH-5218
>   HSEARCH-5218 Add compatibility with OpenSearch 2.16.0

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5224
https://github.com/hibernate/hibernate-search/pull/4277
Bumps software.amazon.awssdk:auth from 2.26.4 to 2.27.3.
---
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-search/blob/main/CONTRIBUTING.md# …
> HSEARCH-5224 Bump software.amazon.awssdk:auth from 2.26.4 to 2.27.3

- build/container/search-backend/elastic.Dockerfile
- ci/dependency-update/Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-5222
> HSEARCH-5222 Use version snapshots of Elasticsearch tags in upgrade testing

- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/FormulaPropertyIT.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMappingPropertiesMetadataContributor.java
https://hibernate.atlassian.net/browse/HSEARCH-5226
(cherry picked from commit 801c8ac8ee9dd54bf8cd3269fa99a5d50f314f64)
> HSEARCH-5226 Ignore collecting scale on formula properties (7.1)

- Jenkinsfile
- build/parents/build/pom.xml
- mapper/orm-outbox-polling/src/main/avro/generated/org/hibernate/search/mapper/orm/outboxpolling/avro/generated/impl/PojoIndexingQueueEventPayloadDto.java
https://hibernate.atlassian.net/browse/HSEARCH-5223
I've tried the change in this job https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-marko/detail/build%2FHSEARCH-5223-add-source-update-check/3/pipeline/
I'm not sure what's going on with the Avro plugin... when I reverted the changes committed by CI and tried running a build, the Dtos were not updated. Only when I just removed them entirely did they get regenerated, and the imports changed...
so the source modification check won't catch this problem.
I thought about dropping them from git and letting them be generated into target each time, but looking at the comments here https://hibernate.atlassian.net/browse/HSEARCH-4638 .. 😖 
I thought about printing the diff if the check fails but then thought that it …
> HSEARCH-5223 Regenerate avro Dtos / add a sources-not-modified check to the build

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5227
> HSEARCH-5227 Upgrade -orm6 artifacts to Hibernate ORM 6.2.31.Final

- documentation/src/main/asciidoc/migration/index.adoc
https://hibernate.atlassian.net/browse/HSEARCH-5144
Earlier, I've added a similar note to the hibernate.org, this one is to mention it in the migration guide as probably more people read the migration guide than the version page on hibernate.org.
> Follow up on HSEARCH-5144 - Add a migration note on JBoss Logging upgrade

- pom.xml
to possibly address the
```
[INFO] --- gpg:3.1.0:sign (sign-artifacts) @ hibernate-search-bom ---
[INFO] Signing 1 file with default secret key.
gpg: signing failed: No pinentry
gpg: signing failed: No pinentry
```
> Bump version.gpg.plugin to 3.2.4 (7.1)

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5236
https://hibernate.atlassian.net/browse/HSEARCH-5237
> HSEARCH-5237 Upgrade Elasticsearch client to 8.15.1 / HSEARCH-5236 Test against latest Elasticsearch 8.15.1

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5236
https://hibernate.atlassian.net/browse/HSEARCH-5237
> Backport to 7.2 : HSEARCH-5237 Upgrade Elasticsearch client to 8.15.1 / HSEARCH-5236 Test against latest Elasticsearch 8.15.1

- documentation/src/main/asciidoc/public/reference/_indexing-massindexer.adoc
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/AbstractMassIndexingFailureIT.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/MassIndexer.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/HibernateOrmMassIndexer.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/MassIndexingOperationHandledFailureException.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoDefaultMassIndexer.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingFailSafeFailureHandlerWrapper.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/spi/PojoMassIndexer.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/massindexing/MassIndexer.java
- mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/massindexing/impl/StandalonePojoMassIndexer.java
https://hibernate.atlassian.net/browse/HSEARCH-5208
> HSEARCH-5208 Add a fail-fast configuration option to the mass indexer

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5238
https://github.com/hibernate/hibernate-search/pull/4312
Bump org.jboss.logging:jboss-logging from 3.6.0.Final to 3.6.1.Final
Bumps [org.jboss.logging:jboss-logging](https://github.com/jboss-logging/jboss-logging) from 3.6.0.Final to 3.6.1.Final.
- [Release notes](https://github.com/jboss-logging/jboss-logging/releases)
- [Commits](https://github.com/jboss-logging/jboss-logging/compare/3.6.0.Final...3.6.1.Final)
---
- dependency-name: org.jboss.logging:jboss-logging dependency-type: direct:production update-type: version-update:semver-patch ...
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache …
> HSEARCH-5238 Upgrade to JBoss logging 3.6.1.Final

- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingStreamingLoaderIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5180
it can happen that the log does not get logged, in the "allTogether" case as another thread may have already logged a more "recent" update
see https://ge.hibernate.org/s/iyug3sahpzzxg/tests/goal/org.hibernate.search:hibernate-search-integrationtest-mapper-pojo-base:failsafe:integration-test@it/details/org.hibernate.search.integrationtest.mapper.pojo.massindexing.MassIndexingStreamingLoaderIT?top-execution=1
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the …
> Follow up on: HSEARCH-5180 Update log check conditions in tests

- documentation/src/main/asciidoc/migration/index.adoc
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmPathInterpreter.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoImplicitReindexingResolverBuildingHelper.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/impl/PojoImplicitReindexingAssociationInverseSideResolverMarkingNode.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
https://hibernate.atlassian.net/browse/HSEARCH-4720
In one of the places marked to throw an exception, the code can enter the condition for valid reasons. I've tried to describe that with an example and kept the code simply returning early as before instead of throwing an exception. 
> HSEARCH-4720 Throw exceptions instead of logging warnings for failures to configure association inverse path resolution

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5243
https://github.com/hibernate/hibernate-search/pull/4319
Bump software.amazon.awssdk:auth from 2.27.3 to 2.28.2
Bumps software.amazon.awssdk:auth from 2.27.3 to 2.28.2.
---
For more information …
> HSEARCH-5243 Upgrade to AWS SDK 2.28.2

- build/parents/build/pom.xml
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingInheritanceIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5244
> HSEARCH-5244 Upgrade to Hibernate ORM 6.6.1.Final

- build/parents/build/pom.xml
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingInheritanceIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5244
> Backport of HSEARCH-5244 to 7.2  -  Upgrade to Hibernate ORM 6.6.1.Final

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5248
https://hibernate.atlassian.net/browse/HSEARCH-5247
> HSEARCH-5248 Upgrade Elasticsearch client to 8.15.2 / HSEARCH-5247 Test against latest Elasticsearch 8.15.2

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5248
https://hibernate.atlassian.net/browse/HSEARCH-5247
> Backport to 7.2: HSEARCH-5248 Upgrade Elasticsearch client to 8.15.2 / HSEARCH-5247 Test against latest Elasticsearch 8.15.2 

- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingStreamingLoaderIT.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingBatchIndexingWorkspace.java
https://hibernate.atlassian.net/browse/HSEARCH-5249
> HSEARCH-5249 Move a MassIndexingTypeGroupMonitor#indexingCompleted call to right before the indexing completed log message

- Jenkinsfile
- build/container/search-backend/amazon-opensearch-serverless.Dockerfile
- build/container/search-backend/opensearch.Dockerfile
https://hibernate.atlassian.net/browse/HSEARCH-5252
Bump opensearchproject/opensearch
Bumps the search-backend-containers group in /build/container/search-backend with 1 update: opensearchproject/opensearch.
Updates `opensearchproject/opensearch` from 2.17.0 to 2.17.1
---
- dependency-name: opensearchproject/opensearch dependency-type: direct:production update-type: version-update:semver-patch dependency-group: search-backend-containers ...
and can be relicensed under the terms of the [LGPL v2.1 …
> HSEARCH-5252 Test against the latest OpenSearch 2.17.1

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5253
> HSEARCH-5253 Upgrade -orm6 artifacts to Hibernate ORM 6.2.32.Final

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchMetricFieldAggregation.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/AbstractLuceneMetricCompensatedSumAggregation.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/AbstractLuceneMetricNumericFieldAggregation.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneAvgCompensatedSumAggregation.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneAvgNumericFieldAggregation.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneMaxNumericFieldAggregation.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneMinNumericFieldAggregation.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneSumCompensatedSumAggregation.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/aggregation/impl/LuceneSumNumericFieldAggregation.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/AbstractLuceneNumericFieldCodec.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneBigDecimalFieldCodec.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneBigIntegerFieldCodec.java
- integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
- integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/aggregation/MetricFieldAggregationsIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/aggregation/MetricNumericFieldsAggregationsIT.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/operations/MetricAggregationsTestCase.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/BigIntegerFieldTypeDescriptor.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/InstantFieldTypeDescriptor.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/LocalDateTimeFieldTypeDescriptor.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/OffsetDateTimeFieldTypeDescriptor.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/YearFieldTypeDescriptor.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/ZonedDateTimeFieldTypeDescriptor.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/values/MetricAggregationsValues.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TypeAssertionHelper.java
https://hibernate.atlassian.net/browse/HSEARCH-5230
> HSEARCH-5230 Support RAW model type with metric aggregations

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5256
As otherwise, we end up with cache misses all the time with the current config. Noticed this while looking into Develocity build cache
> HSEARCH-5256 Spotless: use a cache dir per module and not single in the root

- .github/workflows/build.yml
- .github/workflows/ci-report.yml
- .github/workflows/ci.yml
* Use `pull_request` instead of `pull_request_target`
* Move Develocity build scan publishing for untrusted code to a separate workflow
* Split caches between trusted and untrusted code
* Update secrets to use "Develocity" name instead of "Gradle Enterprise"
Opening as draft as I need to check that this actually works, and will be checking on the ORM side: https://github.com/hibernate/hibernate-orm/pull/9163
For more information on …
> Rework/simplify GH Actions jobs

- .github/workflows/ci-report.yml
since the publish job does not have a matrix
> Use JDK 21 explicitly for report publishing

- .github/workflows/ci-report.yml
- .github/workflows/ci.yml
We don't need tars, as workflow artifacts are already zipped.
This is to align on ORM: https://github.com/hibernate/hibernate-orm/pull/9173
> Don't tar build-scan-data in GitHub actions workflows

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5263
https://hibernate.atlassian.net/browse/HSEARCH-5264
> HSEARCH-5264 Upgrade to Jackson 2.18.1 / HSEARCH-5263 Upgrade to AWS SDK 2.29.2

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
- documentation/src/main/asciidoc/migration/index.adoc
- documentation/src/main/asciidoc/public/reference/_backend-elasticsearch.adoc
https://hibernate.atlassian.net/browse/HSEARCH-5045
> HSEARCH-5045 Raise various default max-connection config properties for the Elasticsearch backend

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/container/search-backend/amazon-opensearch-serverless.Dockerfile
- build/container/search-backend/opensearch.Dockerfile
- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5266
> HSEARCH-5266 Add compatibility with OpenSearch 2.18.0

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- documentation/src/main/asciidoc/public/reference/_compatibility.adoc
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5269
https://hibernate.atlassian.net/browse/HSEARCH-5270
> HSEARCH-5270 Upgrade to Elasticsearch client 8.16.0 / HSEARCH-5269   Add Elasticsearch 8.16.0 compatibility

- Jenkinsfile
- ci/dependency-update/Jenkinsfile
- ci/performance/elasticsearch/Jenkinsfile
- ci/performance/lucene/Jenkinsfile
- ci/release/Jenkinsfile
Upgrade to 1.18 to avoid buggy notifications.
See https://hibernate.zulipchat.com/#narrow/channel/132096-hibernate-user/topic/Jenkins.20Notifications
Full changeset: https://github.com/hibernate/hibernate-jenkins-pipeline-helpers/compare/1.13..1.18
Don't configure the version in Jenkinsfile so that it's easier to upgrade next time.
See https://ci.hibernate.org/manage/configure#global-untrusted-pipeline-libraries to change the (default) version globally for all projects.
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future …
> Upgrade to hibernate-jenkins-pipeline-helpers 1.18 -- and configure the version on CI instead of in Jenkinsfile

- Jenkinsfile
> Do not use "net.bytebuddy.experimental=true" on JDK 23 build

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/ElasticsearchFieldProjection.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/FieldProjectionRequestContext.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/ProjectionRequestContext.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryRequestContext.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneDistanceToFieldProjection.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneFieldProjection.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneObjectProjection.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/ProjectionRequestContext.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/FieldProjectionBaseIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5255
> Backport of HSEARCH-5255 to 7.2 - Change how projection cardinality check is done on "request"

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5274
https://hibernate.atlassian.net/browse/HSEARCH-5275
> HSEARCH-5274 Upgrade Elasticsearch client to 8.16.1 / HSEARCH-5275 Test against latest Elasticsearch 8.16.1

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5276
https://hibernate.atlassian.net/browse/HSEARCH-5277
> HSEARCH-5277 Test against latest Elasticsearch 8.15.4 / HSEARCH-5276 Upgrade Elasticsearch client to 8.15.4

- ci/dependency-update/Jenkinsfile
Since main is now based on ORM 7
> Remove Hibernate ORM 6.6 from dependency updates testing

- build/config/src/main/java/org/hibernate/search/build/report/loggers/LoggerCategoriesProcessor.java
https://hibernate.atlassian.net/browse/HV-2065
Report fields should be printed in the same order all the time. `Map.of()` struck again with its randomness 😖 
> HSEARCH-798 Make logging report reproducible

- ci/nightly/Jenkinsfile
this one slipped when others were updated 🙈 
> Use the version of hibernate-jenkins-pipeline-helpers configured on CI in nightly job

- build/parents/build/pom.xml
because of the https://github.com/apache/logging-log4j2/issues/3234
We get occasional failures: https://ge.hibernate.org/s/cgbajaw6inj6q/tests/goal/org.hibernate.search:hibernate-search-integrationtest-backend-elasticsearch:failsafe:integration-test@it/details/org.hibernate.search.integrationtest.backend.elasticsearch.client.ElasticsearchClientFactoryImplIT/uris_http%5B1%5D?top-execution=1
For more information on licensing, please check …
> Downgrade log4j to 2.24.1

- integrationtest/mapper/orm-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/outboxpolling/schema/OutboxPollingCustomEntityMappingIT.java
- integrationtest/mapper/orm-spring-uberjar/application/src/main/resources/application.yaml
- util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/DatabaseContainer.java
https://hibernate.atlassian.net/browse/HSEARCH-5281
> HSEARCH-5281 Do not use `hibernate.dialect` in test configuration

- build/config/pom.xml
- build/parents/build/pom.xml
- integrationtest/mapper/orm-jakarta-batch/pom.xml
- integrationtest/mapper/orm-jakarta-batch/src/test/java/org/hibernate/search/integrationtest/jakarta/batch/massindexing/EntityManagerFactoryRetrievalIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedLazyOnContainedSideIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedLazyOnContainingSideIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainedSideIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontaining/AutomaticIndexingOneToOneOwnedByContainingLazyOnContainingSideIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingErrorIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingFailureIT.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/common/impl/HibernateOrmUtils.java
- util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmSoftAssertions.java
- util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/SlowerLoadingListener.java
- util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/TimeoutLoadingListener.java
https://hibernate.atlassian.net/browse/HSEARCH-5284
https://hibernate.atlassian.net/browse/HSEARCH-5271
> HSEARCH-5284 Upgrade to Hibernate ORM 7.0.0.Beta3 / HSEARCH-5271 Reenable the ORM tests related to bytecode enhancement

- build/enforcer/src/main/java/org/hibernate/search/build/enforcer/JavadocSourcePathIncludesAllPublicArtifactsRule.java
- distribution/pom.xml
While really the config was missing `mapper/pojo-standalone/src/main/java` and had a redundant `mapper/lucene/src/main/java`  this PR also adds an enforcer check, and while adding it it pointed out that the generated sources aren't included. So I've added those too, just in case.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-search/blob/main/C …
> HSEARCH-5285 Add Pojo Standalone mapper Javadocs to the bundle

- distribution/pom.xml
(cherry picked from commit 12b9dda67e4de06ef84567f8b7192b4974d03a51)
> Backport of HSEARCH-5285 to 6.2 Clean up the list of sources to include in the Javadoc bundle

- distribution/pom.xml
(cherry picked from commit 12b9dda67e4de06ef84567f8b7192b4974d03a51)
> Backport of HSEARCH-5285 to 7.0 Clean up the list of sources to include in the Javadoc bundle

- distribution/pom.xml
- distribution/src/main/assembly/dist.xml
(cherry picked from commit 12b9dda67e4de06ef84567f8b7192b4974d03a51)
> Backport of HSEARCH-5285 to 7.2 Clean up the list of sources to include in the Javadoc bundle

- .github/workflows/ci.yml
- CONTRIBUTING.md
- Jenkinsfile
- MAINTAINERS.md
- ci/release/Jenkinsfile
- ci/snapshot-publish/Jenkinsfile
This should be safer. 
It requires moving the snapshot publishing to a dedicated job, but ORM already does that, so we might as well align.
I took this opportunity to clean up sections about CI in `CONTRIBUTING.md`/`MAINTAINERS.md`.
We'll need to backport this to all branches where we want to perform releases or publish snapshots...
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-search/blob/main …
> Use specific Jenkins nodes for releases

- Jenkinsfile
> Stop snapshot publishing backport to 7.0

- Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-5287
> HSEARCH-5287 Test Hibernate Search against JDK 25

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5299
Bump commons-codec:commons-codec from 1.17.1 to 1.17.2
Bumps [commons-codec:commons-codec](https://github.com/apache/commons-codec) from 1.17.1 to 1.17.2.
- [Changelog](https://github.com/apache/commons-codec/blob/master/RELEASE-NOTES.txt)
- [Commits](https://github.com/apache/commons-codec/compare/rel/commons-codec-1.17.1...rel/commons-codec-1.17.2)
---
- dependency-name: commons-codec:commons-codec dependency-type: direct:production update-type: version-update:semver-patch ...
and …
> HSEARCH-5299 Upgrade to commons-codec 1.17.2

- Jenkinsfile
- ci/release/Jenkinsfile
- ci/snapshot-publish/Jenkinsfile
backport of https://github.com/hibernate/hibernate-search/pull/4433
> Release node backport to 5.10

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5306
Bump software.amazon.awssdk:auth from 2.29.2 to 2.30.2
Bumps software.amazon.awssdk:auth from 2.29.2 to 2.30.2.
---
For more information on licensing, please check …
> HSEARCH-5306 Upgrade to AWS SDK 2.30.2

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5307
https://hibernate.atlassian.net/browse/HSEARCH-5308
> HSEARCH-5307 Upgrade Elasticsearch client to 8.17.1/ HSEARCH-5308 Test against latest Elasticsearch 8.17.1

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5310
Bump commons-codec:commons-codec from 1.17.2 to 1.18.0
Bumps [commons-codec:commons-codec](https://github.com/apache/commons-codec) from 1.17.2 to 1.18.0.
- [Changelog](https://github.com/apache/commons-codec/blob/master/RELEASE-NOTES.txt)
- [Commits](https://github.com/apache/commons-codec/compare/rel/commons-codec-1.17.2...rel/commons-codec-1.18.0)
---
- dependency-name: commons-codec:commons-codec dependency-type: direct:production update-type: version-update:semver-minor ...
and …
> HSEARCH-5310 Upgrade to commons-codec 1.18.0

- .github/dependabot.yml
- .github/hibernate-github-bot.yml
- Group GH actions updates and limit which particular actions are updateable.
- Simplify ignore patterns 
- We can skip license checks for any PRs opened by dependabot. 
- since we have more update groups that do not require JIRA keys we can include the groups in the pattern and simplify the remaining part as `.*`
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-search/blob/main/CONTRIBUTING.md#le …
> Dependabot config updates

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5315
https://hibernate.atlassian.net/browse/HSEARCH-5316
> HSEARCH-5315 Upgrade Elasticsearch client to 8.17.2 / HSEARCH-5316 Test against the latest Elasticsearch 8.17.2

- .github/dependabot.yml
as it is only used to create build reports for logging categories
> Move snakeyaml to build dependencies

- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/ExistsPredicateBaseIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5319
> HSEARCH-5319 Reduce indexing pressure in the ExistsPredicateBaseIT

- ci/dependency-update/Jenkinsfile
> Use JDK 23 to run dependency update test for Lucene 11

- integrationtest/mapper/orm-jakarta-batch/src/test/java/org/hibernate/search/integrationtest/jakarta/batch/massindexing/MassIndexingJobIT.java
- integrationtest/mapper/orm-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingEdgeCasesIT.java
- integrationtest/mapper/orm-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingEventSendingIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingEmbeddableIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingAssociationDeletionIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingGenericPolymorphicAssociationIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingPolymorphicAssociationIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingPolymorphicAssociationPropertyAccessIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingPolymorphicInverseSideAssociationIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/proxy/IndexingProcessorProxiedAssociatedEntityIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/proxy/ReindexingResolverProxiedAssociatedEntityIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToHibernateOrmQueryIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToJpaQueryIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/SearchQueryBaseIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingGraphIT.java
- util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/DataClearConfig.java
- util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmSetupHelperCleaner.java
- util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/MultitenancyTestHelperSchemaManagementTool.java
https://hibernate.atlassian.net/browse/HSEARCH-5239
Sorry this took so long, I know the update of ORM that included the necessary changes has been around for a while but whenever I was ready to come back to this I got sidetracked. Let me know what you think.
> HSEARCH-5239 Take advantage of ORM's SchemaManager.truncateMappedObjects() in tests

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5329
https://hibernate.atlassian.net/browse/HSEARCH-5330
> HSEARCH-5329 Upgrade jboss-logging-tools to 3.0.4.Final / HSEARCH-5330 Upgrade to Jackson 2.18.3

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5331
https://hibernate.atlassian.net/browse/HSEARCH-5332
> HSEARCH-5331 Upgrade Elasticsearch client to 8.17.3 / HSEARCH-5332 Test against the latest Elasticsearch 8.17.3

- Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-5335
> HSEARCH-5335 Test against latest Elasticsearch 7.17.28

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/DoubleMultiValuesToSingleValuesSource.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/LongMultiValuesToSingleValuesSource.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/TextMultiValuesToSingleValuesSource.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSortSpecificsIT.java
- lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/DoubleMultiValuesToSingleValuesSource.java
- lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/LongMultiValuesToSingleValuesSource.java
- lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/TextMultiValuesToSingleValuesSource.java
https://hibernate.atlassian.net/browse/HSEARCH-5334
We do allow accessing the same parent multiple times in these doc values, but if the advancing on child docs return false, we didn't update the current parent and as a result subsequent call with the same parent was treated as if we are working with clean values, while in reality we've already advanced the child docs and those would fail the `advanceExactParent` call...
For more …
> HSEARCH-5334 Better handle advancing to the same parent doc

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/DoubleMultiValuesToSingleValuesSource.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/LongMultiValuesToSingleValuesSource.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/TextMultiValuesToSingleValuesSource.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSortSpecificsIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5334
> Backport of HSEARCH-5334 to 7.2 - Better handle advancing to the same parent doc

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/DoubleMultiValuesToSingleValuesSource.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/LongMultiValuesToSingleValuesSource.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/docvalues/impl/TextMultiValuesToSingleValuesSource.java
- integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSortBaseIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5334
> Backport of HSEARCH-5334 to 6.2 - Better handle advancing to the same parent doc

- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5341
> HSEARCH-5341 Upgrade -orm6 artifacts to Hibernate ORM 6.2.36.Final

- build/config/pom.xml
- build/parents/build/pom.xml
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToHibernateOrmScrollableResultsIT.java
- integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingGraphIT.java
- mapper/orm-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/outboxpolling/mapping/impl/AdditionalMappingBuilder.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateOrmIntegrationBooterImpl.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateSearchPreIntegrationService.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/common/impl/HibernateOrmUtils.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMappingInitiator.java
- mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/spi/HibernateOrmSearchScrollableResultsAdapter.java
- mapper/orm/src/test/java/org/hibernate/search/mapper/orm/model/impl/AbstractHibernateOrmBootstrapIntrospectorPerReflectionStrategyTest.java
- util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/MultitenancyTestHelperSchemaManagementTool.java
https://hibernate.atlassian.net/browse/HSEARCH-5344
https://hibernate.atlassian.net/browse/HSEARCH-5346
https://hibernate.atlassian.net/browse/HSEARCH-5345
> HSEARCH-5344 Upgrade to Hibernate ORM 7.0.0.Beta5 / HSEARCH-5346 Reuse ORM's ClassDetailsRegistry and ignore the BootstrapContext#getJandexView 

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5347
https://hibernate.atlassian.net/browse/HSEARCH-5348
> HSEARCH-5347 Upgrade Elasticsearch client to 8.17.4 / HSEARCH-5348 Test against the latest Elasticsearch 8.17.4

- .github/dependabot.yml
> Add narayana and agroal spring starters to the build dependencies group

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/codec/impl/HibernateSearchKnnVectorsFormat.java
- documentation/src/main/asciidoc/migration/index.adoc
- documentation/src/main/asciidoc/public/reference/_mapping-directfieldmapping.adoc
- integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/mapping/LuceneVectorFieldIT.java
- integrationtest/mapper/pojo-standalone-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/standalone/realbackend/mapping/VectorFieldIT.java
- lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/codec/impl/HibernateSearchKnnVectorsFormat.java
> HSEARCH-5305 - adjust vector search max dimensions for Lucene backend

- integrationtest/mapper/pojo-base/src/test/java-noparameters/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/noparameters/ProjectionConstructorClassNoParametersCompilerFlagIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/annotation/processing/CustomConstructorMappingAnnotationBaseIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/annotation/processing/CustomMethodParameterMappingAnnotationBaseIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/AbstractProjectionConstructorIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorBaseIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorCompositeProjectionIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorDocumentReferenceProjectionIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorEntityProjectionIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorEntityReferenceProjectionIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorFieldProjectionIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorHighlightProjectionIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorIdProjectionIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorInnerInferredIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorObjectProjectionCycleIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorObjectProjectionIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorProjectionBindingIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ProjectionConstructorScoreProjectionIT.java
- integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/search/loading/SearchQueryEntityLoadingFallbackToProjectionConstructorIT.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/PojoMapperLog.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/ProjectionLog.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PojoMethodParameterModel.java
- mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/search/definition/binding/impl/ProjectionConstructorParameterBinder.java
https://hibernate.atlassian.net/browse/HSEARCH-5358
> HSEARCH-5358 Fail faster if an enclosing instance parameter is encountered in a projection constructor on JDK 25+

- Jenkinsfile
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
- backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5360
https://hibernate.atlassian.net/browse/HSEARCH-5361
https://hibernate.atlassian.net/browse/HSEARCH-5362
> HSEARCH-5361 Add Elasticsearch 9.0.0 compatibility

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5370
https://hibernate.atlassian.net/browse/HSEARCH-5371
> HSEARCH-5370 Upgrade to GSON 2.13.1 /  HSEARCH-5371 Upgrade to Jackson 2.19.0

- Jenkinsfile
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5374
https://hibernate.atlassian.net/browse/HSEARCH-5375
> HSEARCH-5374  Upgrade Elasticsearch client to 9.0.1 / SEARCH-5375  Test against the latest Elasticsearch 9.0.1

- .release/.gitignore
- build/reports/pom.xml
- ci/release/Jenkinsfile
- ci/snapshot-publish/Jenkinsfile
- distribution/src/main/assembly/dist.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5351
and the script for snapshots publishing through jreleaser: https://github.com/hibernate/hibernate-release-scripts/pull/39
> HSEARCH-5351 Switch to JReleaser for nexus publishing

- integrationtest/metamodel/orm-elasticsearch/src/test/java/org/hibernate/search/integrationtest/metamodel/orm/elasticsearch/FieldTypesIT.java
- integrationtest/metamodel/orm-elasticsearch/src/test/java/org/hibernate/search/integrationtest/metamodel/orm/elasticsearch/PredicateTypesIT.java
- integrationtest/metamodel/standalone-elasticsearch/src/test/java/org/hibernate/search/integrationtest/metamodel/standalone/elasticsearch/FieldTypesIT.java
- integrationtest/metamodel/standalone-elasticsearch/src/test/java/org/hibernate/search/integrationtest/metamodel/standalone/elasticsearch/PredicateTypesIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5300
> HSEARCH-5300 Adjust metamodel tests to account for backends that do not support vector search capabilities

- documentation/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5378
> HSEARCH-5378 Add numbering/copytocliboard extensions from hibernate-asciidoctor-extensions

- integrationtest/metamodel/orm-elasticsearch/src/test/java/org/hibernate/search/integrationtest/metamodel/orm/elasticsearch/FieldTypesIT.java
- integrationtest/metamodel/orm-elasticsearch/src/test/java/org/hibernate/search/integrationtest/metamodel/orm/elasticsearch/PredicateTypesIT.java
- integrationtest/metamodel/standalone-elasticsearch/src/test/java/org/hibernate/search/integrationtest/metamodel/standalone/elasticsearch/FieldTypesIT.java
- integrationtest/metamodel/standalone-elasticsearch/src/test/java/org/hibernate/search/integrationtest/metamodel/standalone/elasticsearch/PredicateTypesIT.java
https://hibernate.atlassian.net/browse/HSEARCH-5300
> HSEARCH-5300 Skip some metamodel ITs where vector search is not available

- ci/dependency-update/Jenkinsfile
As Elasticsearch 10 isn't out there yet... so no snapshots
> Remove elasticsearch-future from dependency upgrade testsing

- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/LuceneLog.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/QueryLog.java
- backend/lucene/src/main/java/org/hibernate/search/backend/lucene/orchestration/impl/LuceneSyncWorkOrchestratorImpl.java
- lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/LuceneLog.java
- lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/QueryLog.java
- lucene-next/backend/lucene/src/main/java/org/hibernate/search/backend/lucene/orchestration/impl/LuceneSyncWorkOrchestratorImpl.java
https://hibernate.atlassian.net/browse/HSEARCH-5388
> HSEARCH-5388 Warn users if their Lucene caching policy is ineffective

- .github/hibernate-github-bot.yml
- AUTHORS.txt
- CONTRIBUTING.md
- distribution/src/main/assembly/dist.xml
- documentation/src/main/asciidoc/public/reference/_credits.adoc
see https://github.com/hibernate/hibernate-orm/pull/10266
> Rename copyright.txt to AUTHORS.txt

- ci/dependency-update/Jenkinsfile
- ci/dependency-update/rules-orm7.1.xml
> Add testing of Hibernate ORM 7.1 in the dependency update job

- .github/dependabot.yml
- pom.xml
as this version is causing unnecessary trouble.
> Downgrade Eclipse compiler to 3.41

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5399
> Backport of HSEARCH-5399 to 8.0 Upgrade to Hibernate ORM 7.0.2.Final

- build/parents/build/pom.xml
- ci/release/Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-5400
> HSEARCH-5400 Use new snapshot repository / Allow controlling release stage (upload/publish)

- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5406
> Backport to 8.0 HSEARCH-5406 Upgrade to Lucene 10.2.2

- ci/dependency-update/Jenkinsfile
Since Hibernate ORM `main` requires JDK 21 to build from sources.
> Use JDK 21 to build Hibernate ORM in update job

- documentation/src/test/java/org/hibernate/search/documentation/search/aggregation/AggregationDslIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3661
> HSEARCH-3661 Follow up: Make aggregation tests less fragile when comparing double results

- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/AbstractElasticsearchBucketAggregation.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchRangeAggregation.java
- backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchTermsAggregation.java
e.g. instead of `aggs` in bucket aggregations
https://hibernate.atlassian.net/browse/HSEARCH-3661
> Follow up on HSEARCH-3661 Use `aggregations` key more consistently

- backend/elasticsearch-aws/src/main/java/org/hibernate/search/backend/elasticsearch/aws/impl/ElasticsearchAwsBeanConfigurer.java
- bom/platform-common/pom.xml
- build/parents/build/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5435
https://hibernate.atlassian.net/browse/HSEARCH-5436
> HSEARCH-5435 Upgrade Jackson to 2.19.2 / HSEARCH-5436 Upgrade to AWS SDK 2.32.10 / Adjust CDI version to match the Jakarta EE 11 versions

- MAINTAINERS.md
to point to the maven central portal instead of the nexus (oss.sonatype.org)
> Update release instructions

- bom/platform-common/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5432
> HSEARCH-5432 Upgrade hibernate-models to 1.0.1

- Jenkinsfile
- bom/platform-common/pom.xml
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5448
https://hibernate.atlassian.net/browse/HSEARCH-5449
> HSEARCH-5448 Upgrade Elasticsearch client to 9.1.1 / HSEARCH-5449 Test against the latest Elasticsearch 9.1.1

- Jenkinsfile
- bom/platform-common/pom.xml
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5453
https://hibernate.atlassian.net/browse/HSEARCH-5454
https://hibernate.atlassian.net/browse/HSEARCH-5455
> HSEARCH-5453 Upgrade Elasticsearch client to 9.1.2 / HSEARCH-5454 Test against the latest Elasticsearch 9.1.2

- Jenkinsfile
- bom/platform-common/pom.xml
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5453
https://hibernate.atlassian.net/browse/HSEARCH-5454
https://hibernate.atlassian.net/browse/HSEARCH-5455
> [8.1] HSEARCH-5453 Upgrade Elasticsearch client to 9.1.2 / HSEARCH-5454 Test against the latest Elasticsearch 9.1.2

- .github/workflows/ci-report.yml
- .github/workflows/ci.yml
> Set GitHub workflow required permissions explicitly / Determine and checkout the original target branch when publishing the build scans

- Jenkinsfile
- bom/platform-common/pom.xml
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5479
https://hibernate.atlassian.net/browse/HSEARCH-5480
> HSEARCH-5479 Test against the latest Elasticsearch 9.1.4 / HSEARCH-5480 Upgrade Elasticsearch client to 9.1.4

- Jenkinsfile
- bom/platform-common/pom.xml
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5479
https://hibernate.atlassian.net/browse/HSEARCH-5480
> [8.1] HSEARCH-5479 Test against the latest Elasticsearch 9.1.4 / HSEARCH-5480 Upgrade Elasticsearch client to 9.1.4

- bom/platform-common/pom.xml
- build/enforcer/src/main/java/org/hibernate/search/build/enforcer/DependencyManagementIncludesAllGroupIdArtifactsRule.java
https://hibernate.atlassian.net/browse/HSEARCH-5481
> HSEARCH-5481 Try using central search api in the DependencyManagementIncludesAllGroupIdArtifactsRule enforce rule

- bom/platform-common/pom.xml
- build/enforcer/src/main/java/org/hibernate/search/build/enforcer/DependencyManagementIncludesAllGroupIdArtifactsRule.java
https://hibernate.atlassian.net/browse/HSEARCH-5481
> [8.1] HSEARCH-5481 Use different search API in DependencyManagementIncludesAllGroupIdArtifactsRule

- Jenkinsfile
- bom/platform-common/pom.xml
- build/container/search-backend/elastic.Dockerfile
- build/parents/build/pom.xml
- ci/dependency-update/Jenkinsfile
- pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-5498
https://hibernate.atlassian.net/browse/HSEARCH-5499
> HSEARCH-5498 Upgrade Elasticsearch client to 9.1.5 / HSEARCH-5498 Upgrade Elasticsearch client to 9.1.5
