hibernate/hibernate-search

engine/src/main/java/org/hibernate/search/batchindexing/impl/Executors.java
infinispan/src/main/java/org/hibernate/search/infinispan/impl/AsyncDeleteExecutorService.java
infinispan/src/main/java/org/hibernate/search/infinispan/impl/DefaultAsyncDeleteExecutorServiceProvider.java
infinispan/src/main/java/org/hibernate/search/infinispan/impl/InfinispanDirectoryProvider.java
infinispan/src/main/java/org/hibernate/search/infinispan/logging/impl/Log.java
infinispan/src/main/resources/META-INF/services/org.hibernate.search.spi.ServiceProvider

https://hibernate.atlassian.net/browse/HSEARCH-1697
Will set configure async file deletes on the Infinispan Directory if it supports it

HSEARCH-1697 Enable async deleteFile operations on Infinispan Directory

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-1771
- https://hibernate.atlassian.net/browse/HSEARCH-1772

Upgrading ORM and Lucene

---

engine/src/main/java/org/hibernate/search/backend/impl/lucene/AbstractWorkspaceImpl.java
engine/src/main/java/org/hibernate/search/backend/impl/lucene/LuceneBackendResources.java
engine/src/main/java/org/hibernate/search/backend/impl/lucene/LuceneBackendTaskStreamer.java
engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/LuceneWorkVisitor.java
engine/src/main/java/org/hibernate/search/cfg/spi/IdUniquenessResolver.java
engine/src/main/java/org/hibernate/search/cfg/spi/impl/DefaultIdUniquenessResolver.java
engine/src/main/java/org/hibernate/search/store/Workspace.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
engine/src/main/resources/META-INF/services/org.hibernate.search.cfg.spi.IdUniquenessResolver
orm/src/main/java/org/hibernate/search/cfg/impl/HibernateCoreIdUniquenessResolver.java
orm/src/main/java/org/hibernate/search/cfg/impl/SearchConfigurationFromHibernateCore.java
orm/src/test/java/org/hibernate/search/test/engine/optimizations/deletebyterm/DeleteByTermTest.java

@Sanne , this only encompasses the optimization from the Hibernate Search metadata. But I need your advice, in particular on 3c273f5 as I had to create the visitor lazily. Let me know what you think.

HSEARCH-1767 Optimize delete by term

---

engine/src/main/java/org/hibernate/search/engine/impl/ConfigContext.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/main/java/org/hibernate/search/spi/SearchIntegratorBuilder.java
orm/src/test/java/org/hibernate/search/test/filter/Employee.java
orm/src/test/java/org/hibernate/search/test/filter/FilterTest.java
orm/src/test/java/org/hibernate/search/test/filter/FullTimeEmployee.java
orm/src/test/java/org/hibernate/search/test/filter/PartTimeEmployee.java
orm/src/test/java/org/hibernate/search/test/filter/RoleFilterFactory.java

First draft for [HSEARCH-1763](https://hibernate.atlassian.net/browse/HSEARCH-1763)
It will look for @FullTextFilterDef(s) in the super classes of the indexed classes.
Not sure if it makes sense, let me know.

Hsearch 1763 full text filter on mapped superclass

---

backends/jgroups/pom.xml
backends/jms/pom.xml
build-config/pom.xml
distribution/pom.xml
documentation/pom.xml
engine/pom.xml
infinispan/pom.xml
integrationtest/jms/pom.xml
integrationtest/narayana/pom.xml
integrationtest/osgi/karaf-features/pom.xml
integrationtest/osgi/karaf-it/pom.xml
integrationtest/performance/pom.xml
integrationtest/sandbox/pom.xml
integrationtest/spring/pom.xml
integrationtest/wildfly/pom.xml
legacy/pom.xml
modules/pom.xml
orm/pom.xml
pom.xml
serialization/avro/pom.xml
testing/pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-1819
- https://hibernate.atlassian.net/browse/HSEARCH-1820
- https://hibernate.atlassian.net/browse/HSEARCH-1821

Components upgrade

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-1843

HSEARCH-1843 Bump hibernate search module slot name to "5.2"

---

integrationtest/performance/src/test/java/org/hibernate/search/test/performance/TestRunnerStandalone.java
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-1858

HSEARCH-1858 Upgrade to Hibernate ORM 4.3.9.Final

---

documentation/src/main/asciidoc/advanced-features.asciidoc
orm/src/main/java/org/hibernate/search/MassIndexer.java
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-1855
- https://hibernate.atlassian.net/browse/HSEARCH-1856
- https://hibernate.atlassian.net/browse/HSEARCH-1863

Last touches for 5.2.0

---

modules/pom.xml
modules/src/main/modules/search/engine/module.xml
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-1880
- https://hibernate.atlassian.net/browse/HSEARCH-1883

Fixing Infinispan module, optionally depend on Tika

---

orm/src/test/java/org/hibernate/search/test/DefaultTestResourceManager.java
orm/src/test/java/org/hibernate/search/test/configuration/integration/HibernateSearchIntegratorTest.java

hibernate5 followup

---

pom.xml

HSEARCH-1875 Upgrade to JBoss Byteman 3.0.0

---

documentation/src/main/asciidoc/configuration.asciidoc
engine/src/main/java/org/hibernate/search/indexes/spi/DirectoryBasedIndexManager.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
engine/src/test/java/org/hibernate/search/test/backend/serialization/SerializationProviderMissingTest.java

https://hibernate.atlassian.net/browse/HSEARCH-1815

HSEARCH-1815 SerializationProvider documentation

---

orm/src/test/java/org/hibernate/search/test/query/SortTest.java

@Sanne, another fallout of the L5 migration which can go right to master already.

HSEARCH-1919 Avoid using FieldCache in SortTest

---

integrationtest/wildfly/src/test/resources/arquillian.xml
integrationtest/wildfly/src/wildflyConfig/standalone/configuration/standalone-full-testqueues.xml
pom.xml

extracting some ready parts of the JMS work
https://hibernate.atlassian.net/browse/HSEARCH-1930

HSEARCH-1930

---

orm/src/test/java/org/hibernate/search/test/directoryProvider/FSDirectoryTest.java

https://hibernate.atlassian.net/browse/HSEARCH-1949
to be merged in
- master
- 5.4

HSEARCH-1949 FSDirectoryTest is leaking file handles when run on Windows

---

engine/src/main/java/org/hibernate/search/annotations/FilterCacheModeType.java
engine/src/main/java/org/hibernate/search/query/fieldcache/impl/ClassLoadingStrategySelector.java
engine/src/main/java/org/hibernate/search/query/fieldcache/impl/DoubleFieldLoadingStrategy.java
engine/src/main/java/org/hibernate/search/query/fieldcache/impl/FieldCacheLoadingType.java
engine/src/main/java/org/hibernate/search/query/fieldcache/impl/FieldLoadingStrategy.java
engine/src/main/java/org/hibernate/search/query/fieldcache/impl/FloatFieldLoadingStrategy.java
engine/src/main/java/org/hibernate/search/query/fieldcache/impl/IntFieldLoadingStrategy.java
engine/src/main/java/org/hibernate/search/query/fieldcache/impl/LongFieldLoadingStrategy.java
engine/src/main/java/org/hibernate/search/query/fieldcache/impl/StringFieldLoadingStrategy.java
engine/src/main/java/org/hibernate/search/spatial/impl/DistanceFilter.java
engine/src/main/java/org/hibernate/search/spatial/impl/SpatialHashFilter.java

@Sanne This should fix the javadocs errors.
Could you have  a look at the link I changed? I'm not sure I've added the right class

Fixjavadocs

---

orm/src/test/java/org/hibernate/search/test/configuration/IndexEmbeddedProgrammaticallyMappedTest.java
pom.xml

This PR is targeting branch 5.4, but needs to be rebased and merge in master too.
https://hibernate.atlassian.net/browse/HSEARCH-1972

ORM 5.0.0.Final

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/ConnectedMultiFieldsTermQueryBuilder.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/Helper.java
engine/src/test/java/org/hibernate/search/test/dsl/NumericTypeWithNullEncodingTest.java
engine/src/test/java/org/hibernate/search/test/sorting/SortingTest.java

- https://hibernate.atlassian.net/browse/HSEARCH-1973
- https://hibernate.atlassian.net/browse/HSEARCH-1981

Hsearch 1973 - branch 5.4

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/ConnectedMultiFieldsTermQueryBuilder.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/Helper.java
engine/src/test/java/org/hibernate/search/test/dsl/NumericTypeWithNullEncodingTest.java
engine/src/test/java/org/hibernate/search/test/sorting/SortingTest.java

- https://hibernate.atlassian.net/browse/HSEARCH-1973
- https://hibernate.atlassian.net/browse/HSEARCH-1981

Hsearch 1973 master

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/ConnectedMultiFieldsTermQueryBuilder.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/Helper.java
engine/src/test/java/org/hibernate/search/test/dsl/NumericTypeWithNullEncodingTest.java
engine/src/test/java/org/hibernate/search/test/sorting/SortingTest.java

* https://hibernate.atlassian.net/browse/HSEARCH-1973
* https://hibernate.atlassian.net/browse/HSEARCH-1981

HSEARCH-1973 HSEARCH-1981 backport to 53

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/ConnectedMultiFieldsTermQueryBuilder.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/Helper.java
engine/src/test/java/org/hibernate/search/test/dsl/NumericTypeWithNullEncodingTest.java
engine/src/test/java/org/hibernate/search/test/sorting/SortingTest.java

* https://hibernate.atlassian.net/browse/HSEARCH-1973
* https://hibernate.atlassian.net/browse/HSEARCH-1981

HSEARCH-1973 HSEARCH-1981 backport to 5.2

---

integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/ModuleMemberRegistrationEarArchiveWithJbossDeploymentIT.java
integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/ModuleMemberRegistrationIT.java
integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/controller/MemberRegistration.java

https://hibernate.atlassian.net/browse/HSEARCH-1983

HSEARCH-1983 Check the Search version used by IT on WildFly

---

orm/src/test/java/org/hibernate/search/test/bridge/tika/TikaBridgeBlobSupportTest.java
orm/src/test/java/org/hibernate/search/test/bridge/time/JavaTimeTest.java
orm/src/test/java/org/hibernate/search/test/embedded/EmbeddedTest.java
orm/src/test/java/org/hibernate/search/test/embedded/fieldoncollection/FieldOnCollectionReindexTest.java
orm/src/test/java/org/hibernate/search/test/embedded/polymorphism/uninitializedproxy/SearchAfterUninitializedProxyEntityLoadingTest.java
orm/src/test/java/org/hibernate/search/test/engine/optimizations/mappedsuperclasscollection/InheritedCollectionFieldCollectionUpdateEventTest.java
orm/src/test/java/org/hibernate/search/test/query/initandlookup/ObjectLookupAndDatabaseRetrievalConfigurationTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2004
CI cannot complete the build when running the mariadb profile because of some tests not executing queries inside a transaction.

HSEARCH-2004 Queries executed outside a transaction in tests

---

integrationtest/wildfly/src/wildflyConfig/standalone/configuration/standalone-full-testqueues.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-2013

HSEARCH-2013 Upgrade to WildFly 10.0.0.CR2 and align configuration files

---

documentation/src/main/asciidoc/query.asciidoc
orm/src/test/java/org/hibernate/search/test/filter/BestDriversFilter.java

Documentation example fixes
- https://hibernate.atlassian.net/browse/HSEARCH-2025

HSEARCH-2025

---

documentation/src/main/asciidoc/query.asciidoc

- https://hibernate.atlassian.net/browse/HSEARCH-1964

HSEARCH-1964 Clarify documentation around should, must and must not

---

engine/src/main/java/org/hibernate/search/engine/impl/ImmutableSearchFactory.java
engine/src/main/java/org/hibernate/search/query/engine/impl/AbstractHSQuery.java
engine/src/main/java/org/hibernate/search/query/engine/impl/FacetManagerImpl.java
engine/src/main/java/org/hibernate/search/query/engine/impl/LuceneHSQuery.java

(so ES can re-use some bits of it)
I expect to be able to move some more logic there (the determination of affected classes / index managers), but I'll come to that when honing the ES-specific implementation.

HSEARCH-2036 Extracting base class for HSQuery implementations

---

backends/jgroups/pom.xml
engine/src/main/java/org/hibernate/search/engine/impl/DocumentBuilderHelper.java
engine/src/main/java/org/hibernate/search/engine/impl/FacetHandling.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/PropertyMetadata.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/TypeMetadata.java
engine/src/main/java/org/hibernate/search/engine/spi/DocumentBuilderIndexedEntity.java
engine/src/main/java/org/hibernate/search/metadata/impl/IndexedTypeDescriptorImpl.java
engine/src/main/java/org/hibernate/search/util/impl/ReflectionHelper.java
integrationtest/engine-performance/README.md
integrationtest/engine-performance/pom.xml
integrationtest/engine-performance/src/main/java/org/hibernate/search/engineperformance/EngineHolder.java
integrationtest/engine-performance/src/main/java/org/hibernate/search/engineperformance/JMHBenchmarks.java
integrationtest/engine-performance/src/main/java/org/hibernate/search/engineperformance/Launcher.java
integrationtest/engine-performance/src/main/java/org/hibernate/search/engineperformance/model/BookEntity.java
integrationtest/jms/pom.xml
integrationtest/narayana/pom.xml
integrationtest/performance/pom.xml
integrationtest/sandbox/pom.xml
orm/pom.xml
pom.xml
serialization/avro/pom.xml

New performance tests, and fixing some low hanging fruits already:
- https://hibernate.atlassian.net/browse/HSEARCH-1867
- https://hibernate.atlassian.net/browse/HSEARCH-2050
- https://hibernate.atlassian.net/browse/HSEARCH-2051
- https://hibernate.atlassian.net/browse/HSEARCH-2052
- https://hibernate.atlassian.net/browse/HSEARCH-2054

Performance

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2084

HSEARCH-2084 Upgrade to WildFly 10.0.0.Final

---

README.md
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2099

HSEARCH-2099 Upgrade to Apache Lucene 5.5.0

---

build-config/pom.xml
build-config/src/main/resources/checkstyle.xml
build-config/src/main/resources/suppressions.xml
elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchHSQueryImpl.java
elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchIndexManager.java
engine/src/main/java/org/hibernate/search/backend/configuration/impl/IndexWriterSetting.java
engine/src/main/java/org/hibernate/search/bridge/impl/BridgeFactory.java
engine/src/main/java/org/hibernate/search/cfg/Environment.java
engine/src/main/java/org/hibernate/search/metadata/FieldSettingsDescriptor.java
engine/src/main/java/org/hibernate/search/metadata/NumericFieldSettingsDescriptor.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/ConnectedMoreLikeThisQueryBuilder.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/TermQueryContext.java
engine/src/main/java/org/hibernate/search/query/engine/spi/TimeoutManager.java
engine/src/test/java/org/hibernate/search/testsupport/leakdetection/FileMonitoringDirectory.java
integrationtest/performance/src/test/java/org/hibernate/search/test/performance/scenario/TestReporter.java
orm/src/test/java/org/hibernate/search/test/query/dsl/Coffee.java
pom.xml

This pr bumps the maven-checkstyle-plugin to 2.17 and puppycrawl checkstyle to 6.15.

HSEARCH-2103 Fix Checkstyle for Java 8 syntax	

---

build-config/src/main/java/org/hibernate/checkstyle/checks/regexp/DoubleSpacesCheck.java
build-config/src/main/java/org/hibernate/checkstyle/checks/regexp/IllegalImport.java
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2140

Fix building on JDK9

---

elasticsearch/elasticsearchconfiguration/elasticsearch.yml
elasticsearch/pom.xml
elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/testutil/OrmTestRunner.java

https://hibernate.atlassian.net/browse/HSEARCH-2144

Hsearch 2144

---

elasticsearch/pom.xml
orm/src/test/java/org/hibernate/search/test/query/facet/FacetFilteringTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2132

HSEARCH-2132 Upgrade Elasticsearch to 2.2.0

---

elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendQueueProcessor.java

I don't think it makes a huge difference, but it should be a tad better, at least until the visitor contains some actual state :)

HSEARCH-2091 Caching and re-using ES index work visitor

---

elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendQueueProcessor.java

https://hibernate.atlassian.net/browse/HSEARCH-2176

HSEARCH-2176 Avoiding repeated service look-ups

---

engine/src/main/java/org/hibernate/search/backend/impl/lucene/SyncWorkProcessor.java
engine/src/test/java/org/hibernate/search/test/backend/lucene/SyncWorkProcessorShutDownTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2179

HSEARCH-2179 Hanging during shutdown of SyncWorkProcessor

---

orm/src/main/java/org/hibernate/search/query/hibernate/impl/AbstractLoader.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/CriteriaObjectInitializer.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/FullTextQueryImpl.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/Loader.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/LookupObjectInitializer.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/MultiClassesQueryLoader.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/ObjectInitializer.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/PersistenceContextObjectInitializer.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/ProjectionLoader.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/QueryLoader.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/ScrollableResultsImpl.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/SecondLevelCacheObjectInitializer.java
orm/src/test/java/org/hibernate/search/test/query/initandlookup/ObjectLookupAndDatabaseRetrievalConfigurationTest.java

see https://hibernate.atlassian.net/browse/HSEARCH-2197

HSEARCH-2197 Loading of search results produces useless garbage.

---

elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchIndexManager.java

This does not need unit tests as it's already covered by the existing tests (tests are failing in my es-analyzer branch without it).

HSEARCH-2233 Dates and numerics should never be analyzed

---

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc

[HSEARCH-2214](https://hibernate.atlassian.net/browse/HSEARCH-2214).

HSEARCH-2214 Only wait for status "yellow" after index creation

---

elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/test/ElasticsearchIT.java
engine/src/main/java/org/hibernate/search/query/engine/impl/AbstractHSQuery.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
engine/src/test/java/org/hibernate/search/test/sorting/SortingTest.java
orm/src/test/java/org/hibernate/search/test/configuration/ProgrammaticMappingTest.java
orm/src/test/java/org/hibernate/search/test/embedded/sorting/EmbeddedSortableIdFieldTest.java
orm/src/test/java/org/hibernate/search/test/query/sorting/SortTest.java

https://hibernate.atlassian.net/browse/HSEARCH-1951

HSEARCH-1951 Validate sort type used for query

---

engine/src/main/java/org/hibernate/search/cfg/spi/SearchConfiguration.java

Follows up @Sanne PR: https://github.com/hibernate/hibernate-search/pull/1082

HSEARCH-2243 Update SearchConfiguration#getProvidedServices() javadoc

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
orm/src/test/java/org/hibernate/search/test/bridge/ArrayBridgeTest.java
orm/src/test/java/org/hibernate/search/test/bridge/ArrayBridgeTestEntity.java
orm/src/test/java/org/hibernate/search/test/bridge/IterableBridgeTest.java
orm/src/test/java/org/hibernate/search/test/bridge/IterableBridgeTestEntity.java
orm/src/test/java/org/hibernate/search/test/bridge/MapBridgeTest.java
orm/src/test/java/org/hibernate/search/test/bridge/MapBridgeTestEntity.java

https://hibernate.atlassian.net/browse/HSEARCH-2046

HSEARCH-2046 Ignore IndexEmbedded attributes when used on collection of primitives

---

integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/model/Member.java
modules/src/main/modules/search/elasticsearch/module.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2234

HSEARCH-2234 Add dependency to "xml.bind" to ES JBoss Modules module.xml

---

backends/jgroups/src/test/resources/hibernate.properties
documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/cfg/ElasticsearchEnvironment.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/cfg/IndexSchemaManagementStrategy.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexManager.java
elasticsearch/src/test/resources/hibernate.properties
integrationtest/wildfly/pom.xml
integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/elasticsearch/ElasticsearchModuleMemberRegistrationIT.java
orm/src/test/java/org/hibernate/search/test/backend/SyncBackendLongWorkListStressTest.java

- https://hibernate.atlassian.net/browse/HSEARCH-2093
- https://hibernate.atlassian.net/browse/HSEARCH-2167

IndexSchemaManagementStrategy: Enum names review

---

CONTRIBUTING.md

@gunnarmorling I based this on the Validator CONTRIBUTING.md. I added a few things so if we agree on this, I'll also update the Validator CONTRIBUTING.md.

HSEARCH-2299 Add a CONTRIBUTING.md file

---

settings-example.xml

https://hibernate.atlassian.net/browse/HSEARCH-2300

HSEARCH-2300 Use Central first to get the artifacts

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2305

HSEARCH-2305 Upgrade to Apache Lucene 5.5.2

---

engine/src/main/java/org/hibernate/search/spatial/DistanceSortField.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/CriteriaObjectInitializer.java
orm/src/test/java/org/hibernate/search/test/jpa/SpatialQueryingJPATest.java
orm/src/test/java/org/hibernate/search/test/query/initandlookup/CriteriaObjectInitializerAndHierarchyInheritanceTest.java
pom.xml

Backports to 5.5

---

engine/pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2312

HSEARCH-2312 Do not require the lucene-backward-codecs dependency

---

pom.xml

For branch 5.5 exclusively.
- https://hibernate.atlassian.net/browse/HSEARCH-2315

HSEARCH-2315 Upgrade branch 5.5 to Hibernate ORM 5.0.10.Final

---

engine/src/main/java/org/hibernate/search/spatial/impl/DistanceCollector.java
engine/src/main/java/org/hibernate/search/spatial/impl/DistanceComparator.java
engine/src/main/java/org/hibernate/search/spatial/impl/DistanceFilter.java
orm/src/test/java/org/hibernate/search/test/jpa/SpatialQueryingJPATest.java
orm/src/test/java/org/hibernate/search/test/spatial/POI.java

See https://hibernate.atlassian.net/browse/HSEARCH-2322

HSEARCH-2322 Test case and fix

---

engine/src/main/java/org/hibernate/search/query/engine/impl/AbstractHSQuery.java
orm/src/test/java/org/hibernate/search/test/query/sorting/Explorer.java
orm/src/test/java/org/hibernate/search/test/query/sorting/SortOnFieldsFromCustomBridgeTest.java
orm/src/test/java/org/hibernate/search/test/query/sorting/Territory.java

https://hibernate.atlassian.net/browse/HSEARCH-2325

HSEARCH-2325 AbstractHSQuery.validateSortField validates SortFields even when lacking information

---

documentation/src/main/asciidoc/spatial.asciidoc
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/ElasticsearchProjectionConstants.java
engine/src/main/java/org/hibernate/search/engine/ProjectionConstants.java

https://hibernate.atlassian.net/browse/HSEARCH-2326

HSEARCH-2326 State the distance unit in the documentation for SPATIAL_DISTANCE

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexManager.java
engine/src/main/java/org/hibernate/search/cfg/spi/SearchConfiguration.java
engine/src/main/java/org/hibernate/search/cfg/spi/SearchConfigurationBase.java
engine/src/main/java/org/hibernate/search/engine/impl/ImmutableSearchFactory.java
engine/src/main/java/org/hibernate/search/engine/impl/IncrementalSearchConfiguration.java
engine/src/main/java/org/hibernate/search/engine/impl/MutableSearchFactory.java
engine/src/main/java/org/hibernate/search/engine/impl/MutableSearchFactoryState.java
engine/src/main/java/org/hibernate/search/engine/impl/ReflectionReplacingSearchConfiguration.java
engine/src/main/java/org/hibernate/search/spi/SearchIntegratorBuilder.java
engine/src/main/java/org/hibernate/search/spi/WorkerBuildContext.java
engine/src/main/java/org/hibernate/search/spi/impl/SearchFactoryState.java
engine/src/test/java/org/hibernate/search/testsupport/setup/WorkerBuildContextForTest.java
orm/src/main/java/org/hibernate/search/cfg/impl/SearchConfigurationFromHibernateCore.java
orm/src/test/java/org/hibernate/search/test/configuration/integration/HibernateSearchIntegratorTest.java

Just to have CI give an opinion of my additional change.

HSEARCH-2256

---

integrationtest/wildfly/pom.xml
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2342

HSEARCH-2342 Upgrade to WildFly 10.1.0.Final

---

orm/src/main/java/org/hibernate/search/hcore/util/impl/ContextHelper.java
orm/src/main/java/org/hibernate/search/jmx/impl/IndexControl.java
orm/src/test/java/org/hibernate/search/test/reader/nrtreaders/BasicNRTFunctionalityTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2343
Follows up on https://github.com/hibernate/hibernate-search/pull/1156. Just for the Jenkins build, I'll squash and merge once okay-ed.

HSEARCH-2343 Follow-up

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexManager.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/FieldHelper.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java

https://hibernate.atlassian.net/browse/HSEARCH-2352
Necessary for HSEARCH-2260.

HSEARCH-2352 Index.NO is being ignored for numeric fields (and also boolean or date fields for Elasticearch)

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexManager.java
engine/src/main/java/org/hibernate/search/indexes/impl/IndexManagerHolder.java

https://hibernate.atlassian.net/browse/HSEARCH-2373
This seems to fix the most obvious issues with "un-released" services (those one can see in any Elasticsearch test).

HSEARCH-2373 Some ES-related services are not properly released

---

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-2355

HSEARCH-2355 Document default timezone in ES query

---

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexWorkVisitor.java

https://hibernate.atlassian.net/browse/HSEARCH-2092

HSEARCH-2092 Map the optimize() operation to Elasticsearch 'force merge' requests

---

pom.xml

* https://hibernate.atlassian.net/browse/HSEARCH-2377

HSEARCH-2377 Upgrade branch 5.5 to Hibernate ORM 5.0.11.Final

---

documentation/src/main/asciidoc/getting-started.asciidoc

Fixed typo in Analyzer documentation (bad bullet points)

---

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
documentation/src/main/asciidoc/mapping.asciidoc
elasticsearch/pom.xml
engine/pom.xml
engine/src/main/java/org/hibernate/search/bridge/MetadataProvidingTikaMetadataProcessor.java
engine/src/main/java/org/hibernate/search/bridge/builtin/TikaBridge.java
engine/src/test/java/org/hibernate/search/test/bridge/builtin/TikaBridgeTest.java
engine/src/test/java/org/hibernate/search/test/util/impl/ClasspathResourceAsFile.java
orm/src/test/java/org/hibernate/search/test/bridge/tika/TikaBridgeBlobSupportTest.java
orm/src/test/java/org/hibernate/search/test/bridge/tika/TikaBridgeTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2386
I had to introduce a new interface, which I named `TikaFieldMetadataProvidingMetadataProcessor`. I'm not really happy with this name and am open to suggestions...

HSEARCH-2386 TikaMetadataProcessor cannot add sortable fields (or fields usable in Elasticsearch)

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/FieldHelper.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchImplicitProvidedIdIT.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/User.java

https://hibernate.atlassian.net/browse/HSEARCH-2431

HSEARCH-2431 NPE with projections and Elasticsearch

---

elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchDateCalendarBridgeIT.java

https://hibernate.atlassian.net/browse/HSEARCH-2438

HSEARCH-2438 Fix erroneous test failing with DST change

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/JestClient.java

https://hibernate.atlassian.net/browse/HSEARCH-2412

HSEARCH-2412 Add the target URL in Elasticsearch error messages

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
orm/src/test/java/org/hibernate/search/test/configuration/ProgrammaticMappingTest.java

This PR is based on #1197 (HSEARCH-2393), which will have to be merged first.
Relevant JIRA ticket: https://hibernate.atlassian.net/browse/HSEARCH-2429

HSEARCH-2429 Take classBridge analyzers into account with Elasticsearch

---

elasticsearch/elasticsearchconfiguration/elasticsearch.yml
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchHSQueryImpl.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexManager.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/FieldHelper.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/BridgeDefinedField.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/DocumentFieldMetadata.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/FieldMetadataBuilderImpl.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/ParseContext.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/PropertyMetadata.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/TypeMetadata.java
engine/src/main/java/org/hibernate/search/engine/spi/DocumentBuilderIndexedEntity.java
engine/src/main/java/org/hibernate/search/query/engine/impl/AbstractHSQuery.java
orm/src/test/java/org/hibernate/search/test/query/facet/Car.java
orm/src/test/java/org/hibernate/search/test/query/facet/StringFacetingTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2450
Note: the first commit was originally part of #1201 , but has been moved to a specific ticket/PR due to the amount of additional work it required (most notably fixing previously hidden bugs).

HSEARCH-2450 In internal metadata, provide access to BridgeDefinedFields through their source document field

---

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-2483

HSEARCH-2483 Upgrade Elasticsearch used for testing to 2.4.2

---

orm/src/test/java/org/hibernate/search/test/jpa/SpatialQueryingJPATest.java
orm/src/test/java/org/hibernate/search/test/util/DdlTransactionIsolatorTestingImpl.java
orm/src/test/java/org/hibernate/search/test/util/MultitenancyTestHelper.java
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2379
- https://hibernate.atlassian.net/browse/HSEARCH-2499

Upgrading ORM version, and deadlock with MariaDB tests resolved

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexManager.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexNameNormalizer.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchIndexNameConflictIT.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchJavaTimeIT.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/testutil/ElasticsearchBackendTestHelper.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/testutil/TestElasticsearchClient.java
engine/src/main/java/org/hibernate/search/indexes/spi/IndexNameNormalizer.java
engine/src/main/java/org/hibernate/search/spi/SearchIntegratorBuilder.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-2258

HSEARCH-2258 Normalized names conflict

---

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-2506

HSEARCH-2506 Add an acknowledgment section to the Elasticsearch integration docs

---

engine/src/main/java/org/hibernate/search/engine/service/impl/StandardServiceManager.java
engine/src/test/java/org/hibernate/search/test/engine/service/StandardServiceManagerTest.java
engine/src/test/java/org/hibernate/search/test/projection/ProjectionConversionTest.java

- https://hibernate.atlassian.net/browse/HSEARCH-1589
- https://hibernate.atlassian.net/browse/HSEARCH-2484

Race condition fixes and optimisations for concurrent lifecycle changes on Service instances

---

engine/src/main/java/org/hibernate/search/exception/impl/LogErrorHandler.java
orm/src/test/java/org/hibernate/search/test/errorhandling/LuceneErrorHandlingTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2529

HSEARCH-2529 Avoid NPE when logging errors on Lucene works with no related entity

---

engine/src/main/java/org/hibernate/search/bridge/builtin/ArrayBridge.java
engine/src/main/java/org/hibernate/search/engine/spi/DocumentBuilderIndexedEntity.java
engine/src/main/java/org/hibernate/search/util/impl/CollectionHelper.java
orm/src/test/java/org/hibernate/search/test/bridge/ArrayBridgeTest.java
orm/src/test/java/org/hibernate/search/test/bridge/ArrayBridgeTestEntity.java
orm/src/test/java/org/hibernate/search/test/query/facet/EmbeddedCollectionFacetingTest.java
orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2535
https://hibernate.atlassian.net/browse/HSEARCH-2510

HSEARCH-2535 and HSEARCH-2510 Backport to 5.5

---

engine/src/main/java/org/hibernate/search/engine/impl/WorkPlan.java

https://hibernate.atlassian.net/browse/HSEARCH-2540

HSEARCH-2540 Fix a misleading piece of code

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
orm/src/test/java/org/hibernate/search/test/engine/NumericDocumentIdIndexedEmbeddedTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2545
See the commit comments for details about the solution.

HSEARCH-2545 Validation of IndexedEmbedded targeting a numeric document ID fails inside a non-indexed entity

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-2573

HSEARCH-2573 Upgrade the Elasticsearch version used for tests to 2.4.4

---

backends/jgroups/src/test/resources/testing-flush-loopback.xml
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2141

Improve reliability of JGroups integration tests

---

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
documentation/src/main/asciidoc/getting-started.asciidoc
documentation/src/main/asciidoc/mapping.asciidoc
documentation/src/main/asciidoc/query.asciidoc
documentation/src/main/asciidoc/spatial.asciidoc
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchAnalyzerIT.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchSchemaCreationIT.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/GolfPlayer.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/filter/Driver.java
engine/src/main/java/org/hibernate/search/annotations/AnalyzerDef.java
engine/src/main/java/org/hibernate/search/annotations/ClassBridge.java
engine/src/main/java/org/hibernate/search/annotations/Facet.java
engine/src/main/java/org/hibernate/search/annotations/Field.java
engine/src/main/java/org/hibernate/search/annotations/FullTextFilterDef.java
engine/src/main/java/org/hibernate/search/annotations/NumericField.java
engine/src/main/java/org/hibernate/search/annotations/SortableField.java
engine/src/main/java/org/hibernate/search/annotations/Spatial.java
engine/src/test/java/org/hibernate/search/test/configuration/TypeMetadataTest.java
engine/src/test/java/org/hibernate/search/test/metadata/DocumentFieldMetadataTest.java
orm/src/test/java/org/hibernate/search/test/analyzer/Article.java
orm/src/test/java/org/hibernate/search/test/analyzer/definition/Team.java
orm/src/test/java/org/hibernate/search/test/query/facet/Car.java
orm/src/test/java/org/hibernate/search/test/spatial/UserEx.java

- https://hibernate.atlassian.net/browse/HSEARCH-2574

Allow repeatable annotations

---

orm/src/main/java/org/hibernate/search/batchindexing/impl/IdentifierConsumerDocumentProducer.java
orm/src/main/java/org/hibernate/search/batchindexing/impl/IdentifierProducer.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/CriteriaObjectInitializer.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/MultiClassesQueryLoader.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/ObjectLoaderHelper.java
orm/src/test/java/org/hibernate/search/test/query/objectloading/ObjectLoaderHelperTest.java

- https://hibernate.atlassian.net/browse/HSEARCH-2381

HSEARCH-2381 Avoid logging warnings caused by internal usage of the legacy Criteria API

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchHSQueryImpl.java

https://hibernate.atlassian.net/browse/HSEARCH-2590

HSEARCH-2590 Fix an over-allocation of memory when paging on Elasticsearch

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2595

HSEARCH-2595 Upgrade to Hibernate ORM 5.2.8.Final

---

README.md
documentation/src/main/asciidoc/configuration.asciidoc
documentation/src/main/asciidoc/getting-started.asciidoc

- https://hibernate.atlassian.net/browse/HSEARCH-2596

Hsearch 2596

---

engine/src/main/java/org/hibernate/search/analyzer/definition/impl/PropertiesBasedLuceneAnalyzerDefinitionSourceService.java
engine/src/main/java/org/hibernate/search/analyzer/definition/spi/LuceneAnalyzerDefinitionProvider.java
engine/src/main/java/org/hibernate/search/analyzer/definition/spi/LuceneAnalyzerDefinitionSourceService.java
engine/src/main/java/org/hibernate/search/analyzer/impl/LuceneEmbeddedAnalyzerStrategy.java
engine/src/main/resources/META-INF/services/org.hibernate.search.analyzer.definition.spi.LuceneAnalyzerDefinitionSourceService
engine/src/test/java/org/hibernate/search/test/analyzer/analyzerdefinitionprovider/LuceneAnalyzerDefinitionProviderTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2585

HSEARCH-2585 Allow injecting Analyzer definitions using a Service

---

orm/src/main/java/org/hibernate/search/query/hibernate/impl/MultiClassesQueryLoader.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/QueryLoader.java
orm/src/test/java/org/hibernate/search/test/statistics/StatisticsTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2630
https://hibernate.atlassian.net/browse/HSEARCH-2631

HSEARCH-2630 and HSEARCH-2631 Some uses of full text queries will corrupt object loading statistics

---

modules/src/main/assembly/dist.xml
modules/src/main/modules/es-client/module.xml
modules/src/main/modules/es-sniffer/module.xml
modules/src/main/modules/gson/module.xml
modules/src/main/modules/search/backend-jgroups/module.xml
modules/src/main/modules/search/elasticsearch/module.xml
modules/src/main/modules/search/engine/module.xml
modules/src/main/modules/search/serialization-avro/module.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2645
- https://hibernate.atlassian.net/browse/HSEARCH-2646

Refactor JBoss modules for new ES client requirements

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-2654

HSEARCH-2654 Upgrade Elasticsearch RestClient + Sniffer to 5.3.0

---

integrationtest/osgi/karaf-features/src/main/features/features.xml
integrationtest/osgi/karaf-it/pom.xml
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2685
- https://hibernate.atlassian.net/browse/HSEARCH-2686

Upgrading Hibernate ORM dependency, simpler OSGi tests

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
orm/src/test/java/NoPackageTest.java
orm/src/test/java/NotPackagedEntity.java

A trivial one which has been bugging me.
https://hibernate.atlassian.net/browse/HSEARCH-2319

HSEARCH-2319

---

engine/src/main/java/org/hibernate/search/filter/impl/ChainedFilter.java
engine/src/main/java/org/hibernate/search/spatial/impl/DistanceFilter.java
engine/src/main/java/org/hibernate/search/spatial/impl/Point.java
engine/src/main/java/org/hibernate/search/spatial/impl/SpatialHashFilter.java
orm/src/test/java/org/hibernate/search/test/filter/FilterTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2691

HSEARCH-2691 Custom filter implementations must provide proper implementations of the #equals() and #hashCode() methods.

---

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
elasticsearch/pom.xml
elasticsearch/src/test/resources/elasticsearch/5.0/configuration/elasticsearch.yml
elasticsearch/src/test/resources/elasticsearch/5.0/configuration/log4j2.properties
integrationtest/wildfly/src/test/resources/elasticsearch/5.0/configuration/elasticsearch.yml

This also improves build execution times a bit.
- https://hibernate.atlassian.net/browse/HSEARCH-2694

Reduce test verbosity and warnings

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/settings/impl/translation/AnalysisDefinitionFactory.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/settings/impl/translation/DefaultElasticsearchAnalyzerDefinitionTranslator.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/settings/impl/translation/JsonPassThroughAnalysisDefinitionFactory.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/settings/impl/translation/SimpleAnalysisDefinitionFactory.java
engine/src/main/java/org/hibernate/search/analyzer/impl/LuceneAnalyzerBuilder.java
engine/src/main/java/org/hibernate/search/bridge/impl/BridgeFactory.java
engine/src/main/java/org/hibernate/search/cfg/spi/ParameterAnnotationsReader.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
engine/src/test/java/org/hibernate/search/test/analyzer/analyzerdef/AnalyzerDefInvalidTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2606

HSEARCH-2606 Disallow conflicting usage of @Parameter

---

engine/src/main/java/org/hibernate/search/jmx/impl/JMXRegistrar.java
engine/src/main/java/org/hibernate/search/stat/Statistics.java
engine/src/main/java/org/hibernate/search/stat/impl/StatisticsImpl.java
orm/src/test/java/org/hibernate/search/test/statistics/StatisticsTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2014

HSEARCH-2014 Expose size of the indexes among statistics

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ToElasticsearch.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ToElasticsearchIT.java

https://hibernate.atlassian.net/browse/HSEARCH-2703

HSEARCH-2703 Improve boost handling when translating Lucene queries to Elasticsearch

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ToElasticsearch.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/CombiningLuceneAndElasticsearchIT.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ToElasticsearchIT.java

https://hibernate.atlassian.net/browse/HSEARCH-2709

HSEARCH-2709 Add support for converting MatchNoDocsQuery to Elasticsearch

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchHSQueryImpl.java
engine/src/main/java/org/hibernate/search/query/engine/impl/AbstractHSQuery.java
engine/src/main/java/org/hibernate/search/query/engine/impl/LuceneHSQuery.java
engine/src/test/java/org/hibernate/search/test/sharding/LogRotationExampleTest.java
orm/src/test/java/org/hibernate/search/test/shards/DirectoryProviderForQueryTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2477
~~Not to be merged immediately, I am going to do a release.~~ => Done

HSEARCH-2477 Shard filtering doesn't work with Elasticsearch queries

---

engine/src/main/java/org/hibernate/search/indexes/spi/DirectoryBasedIndexManager.java
engine/src/main/java/org/hibernate/search/query/engine/impl/LuceneHSQuery.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java

https://hibernate.atlassian.net//browse/HSEARCH-2724

HSEARCH-2724 Clarify that "directory-based" indexes are actually just "embedded Lucene" indexes

---

documentation/src/main/asciidoc/mapping.asciidoc
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-2719

HSEARCH-2719 Fix links to hibernate.onjira.com

---

elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchSchemaNamingErrorsIT.java
elasticsearch/src/test/resources/hibernate.properties
integrationtest/performance/src/test/java/org/hibernate/search/test/performance/scenario/TestScenario.java
orm/src/test/java/org/hibernate/search/test/query/sorting/SortOnFieldsFromCustomBridgeTest.java
orm/src/test/resources/hibernate.properties

- https://hibernate.atlassian.net/browse/HSEARCH-2716
- https://hibernate.atlassian.net/browse/HSEARCH-2727

Warmup: Two trivial ones

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/DefaultElasticsearchClientFactory.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/DefaultElasticsearchClientFactoryTest.java

Fix deprecation on flag discovery_scheme for https support

HSEARCH-2736 Discovery_scheme not taken in account

---

integrationtest/spring/pom.xml
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2732
- https://hibernate.atlassian.net/browse/HSEARCH-2737

Restoring the JDK9 integration tests

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/nulls/impl/Elasticsearch5MissingValueStrategy.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java

https://hibernate.atlassian.net//browse/HSEARCH-2739

HSEARCH-2739 Some error message use the indexed type and field path inconsistently

---

integrationtest/sandbox/pom.xml
integrationtest/sandbox/src/test/java/org/hibernate/search/test/performance/optimizer/OptimizerPerformanceTest.java
integrationtest/sandbox/src/test/resources/hibernate.properties

- https://hibernate.atlassian.net/browse/HSEARCH-2717
- https://hibernate.atlassian.net/browse/HSEARCH-2740

Fixing a couple of problems in the Sandbox / Performance tests

---

documentation/src/main/asciidoc/query.asciidoc

* https://hibernate.atlassian.net/browse/HSEARCH-2744

HSEARCH-2744 Improve the Simple Query String documentation

---

documentation/src/main/asciidoc/architecture.asciidoc

* https://hibernate.atlassian.net/browse/HSEARCH-2747

HSEARCH-2747 Fix some typos in the Backend section

---

orm/src/test/java/org/hibernate/search/test/query/dsl/SimpleQueryStringDSLTest.java

https://hibernate.atlassian.net//browse/HSEARCH-2751

HSEARCH-2751 SimpleQueryStringDSLTest fails on Elasticsearch 5.1

---

engine/src/main/java/org/hibernate/search/query/engine/impl/LuceneHSQuery.java
engine/src/main/java/org/hibernate/search/query/engine/impl/QueryHits.java
engine/src/test/java/org/hibernate/search/test/id/providedId/ProvidedIdTest.java

- https://hibernate.atlassian.net/browse/HSEARCH-2752

HSEARCH-2752

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-2753

HSEARCH-2753 Upgrade to Hibernate ORM 5.1.7.Final

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/DefaultElasticsearchService.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/DefaultElasticsearchServiceTest.java

https://hibernate.atlassian.net//browse/HSEARCH-2683

Follow-up on HSEARCH-2683

---

documentation/src/main/asciidoc/mapping.asciidoc
engine/src/main/java/org/hibernate/search/annotations/Indexed.java
engine/src/main/java/org/hibernate/search/indexes/interceptor/EntityIndexingInterceptor.java

another trivial one..
- https://hibernate.atlassian.net/browse/HSEARCH-2665

HSEARCH-2665 Promote IndexingInterceptor to be no longer experimental

---

documentation/src/main/asciidoc/monitoring.asciidoc
engine/src/main/java/org/hibernate/search/jmx/IndexControlMBean.java
engine/src/main/java/org/hibernate/search/jmx/impl/JMXRegistrar.java
engine/src/main/java/org/hibernate/search/stat/impl/StatisticsImpl.java
integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/HibernateSearchWithKarafIT.java
orm/src/main/java/org/hibernate/search/batchindexing/impl/SimpleIndexingProgressMonitor.java
orm/src/test/java/org/hibernate/search/test/batchindexing/IndexingGeneratedCorpusTest.java
orm/src/test/java/org/hibernate/search/test/util/progessmonitor/AssertingMassIndexerProgressMonitor.java

Two simple and relaxing ones..
I added HSEARCH-2763 as the first one was way too simple.
- https://hibernate.atlassian.net/browse/HSEARCH-2666
- https://hibernate.atlassian.net/browse/HSEARCH-2763

Reviewing IndexControlMBean and modernising statistics generation

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/processor/impl/ElasticsearchWorkProcessor.java

https://hibernate.atlassian.net//browse/HSEARCH-2767

HSEARCH-2767 Make ElasticsearchWorkProcessor use one execution context per runnable once again

---

orm/src/main/java/org/hibernate/search/query/hibernate/impl/FullTextQueryImpl.java

Fix javadoc following HSEARCH-1404

---

engine/pom.xml
orm/pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2776
- https://hibernate.atlassian.net/browse/HSEARCH-2777

noticed some outdated OSGi dependency overrides

---

documentation/src/main/asciidoc/configuration.asciidoc
documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
documentation/src/main/asciidoc/getting-started.asciidoc
documentation/src/main/asciidoc/query.asciidoc
pom.xml

in particular:
- some links were broken (out of date)
- simplified some wording - short and to the point
- toned down a bit the use of "CAUTION" which produces scary red icons.. it's clear enough that ES is experimental (and maybe it shouldn't?)

Reviewing and updating the documentation

---

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc

https://hibernate.atlassian.net//browse/HSEARCH-2787

HSEARCH-2787 Replace INFO blocks in the documentation with valid styles

---

orm/src/test/java/org/hibernate/search/test/query/objectloading/mixedhierarchy/College.java
orm/src/test/java/org/hibernate/search/test/query/objectloading/mixedhierarchy/CommunityCollege.java
orm/src/test/java/org/hibernate/search/test/query/objectloading/mixedhierarchy/EducationalInstitution.java
orm/src/test/java/org/hibernate/search/test/query/objectloading/mixedhierarchy/HighSchool.java
orm/src/test/java/org/hibernate/search/test/query/objectloading/mixedhierarchy/ObjectLoadingCrossHierarchyTest.java
orm/src/test/java/org/hibernate/search/test/query/objectloading/mixedhierarchy/PrimarySchool.java
orm/src/test/java/org/hibernate/search/test/query/objectloading/mixedhierarchy/School.java
orm/src/test/java/org/hibernate/search/test/query/objectloading/mixedhierarchy/University.java

https://hibernate.atlassian.net//browse/HSEARCH-2792

HSEARCH-2792 Rename DslCrossHierarchyTest to ObjectLoadingCrossHierarchyTest

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-2805

HSEARCH-2805 Upgrade to Checkstyle 8.0

---

elasticsearch-aws/src/main/java/org/hibernate/search/elasticsearch/aws/impl/AWSElasticsearchHttpClientConfigurer.java
elasticsearch-aws/src/main/java/org/hibernate/search/elasticsearch/aws/impl/AWSNormalization.java

Two very minor improvements on top of HSEARCH-2772

HSEARCH-2772, follow up

---

engine/src/main/java/org/hibernate/search/engine/spi/AbstractDocumentBuilder.java
engine/src/main/java/org/hibernate/search/engine/spi/DocumentBuilderIndexedEntity.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
orm/src/main/java/org/hibernate/search/FullTextQuery.java
orm/src/main/java/org/hibernate/search/FullTextSharedSessionBuilder.java
orm/src/main/java/org/hibernate/search/event/impl/FullTextIndexEventListener.java
orm/src/main/java/org/hibernate/search/impl/FullTextSharedSessionBuilderDelegator.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/AbstractLoader.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/CriteriaObjectInitializer.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/FullTextQueryImpl.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/Loader.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/MultiClassesQueryLoader.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/ObjectInitializationContext.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/ObjectLoaderBuilder.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/ObjectLoaderHelper.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/PersistenceContextObjectInitializer.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/ProjectionLoader.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/QueryLoader.java

- https://hibernate.atlassian.net/browse/HSEARCH-2808
also included a late change for this one which was already resolved:
- https://hibernate.atlassian.net/browse/HSEARCH-2770

Minor deprecations cleanup with the ORM integration

---

backends/jgroups/src/test/java/org/hibernate/search/test/jgroups/common/JGroupsCommonTest.java
backends/jgroups/src/test/java/org/hibernate/search/test/jgroups/elasticsearch/JGroupsElasticsearchIT.java
backends/jgroups/src/test/java/org/hibernate/search/test/jgroups/master/JGroupsMasterTest.java
orm/src/main/java/org/hibernate/search/query/hibernate/impl/ScrollableResultsImpl.java
orm/src/test/java/org/hibernate/search/test/configuration/ProgrammaticMappingTest.java
orm/src/test/java/org/hibernate/search/test/embedded/doubleinsert/DoubleInsertEmbeddedTest.java
orm/src/test/java/org/hibernate/search/test/engine/indexapi/PurgeTest.java
orm/src/test/java/org/hibernate/search/test/engine/worker/duplication/SpecialPerson.java
orm/src/test/java/org/hibernate/search/test/inheritance/InheritanceTest.java
orm/src/test/java/org/hibernate/search/test/query/LuceneQueryTest.java
orm/src/test/java/org/hibernate/search/test/query/criteria/MixedCriteriaTest.java
orm/src/test/java/org/hibernate/search/test/spatial/BenchWithGeonames.java
orm/src/test/java/org/hibernate/search/test/spatial/SpatialIndexingTest.java

A couple more trivial deprecations for HSEARCH-2808

HSEARCH-2808

---

documentation/src/main/asciidoc/configuration.asciidoc
documentation/src/main/asciidoc/mapping.asciidoc
documentation/src/main/asciidoc/query.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-2810

HSEARCH-2810 Micro formatting issues in documentation

---

engine/src/main/java/org/hibernate/search/query/dsl/impl/ConnectedMultiFieldsPhraseQueryBuilder.java
engine/src/main/java/org/hibernate/search/query/engine/impl/FieldNameCollector.java
engine/src/main/java/org/hibernate/search/store/spi/DirectoryHelper.java
engine/src/test/java/org/hibernate/search/test/backend/lucene/SharedReleasesLocksTest.java
engine/src/test/java/org/hibernate/search/test/dsl/MoreLikeThisTest.java
engine/src/test/java/org/hibernate/search/test/query/engine/FieldNameCollectorTest.java
engine/src/test/java/org/hibernate/search/testsupport/backend/LuceneBackendTestHelpers.java
engine/src/test/java/org/hibernate/search/testsupport/leakdetection/FileMonitoringDirectory.java
orm/src/test/java/org/hibernate/search/test/batchindexing/IndexingGeneratedCorpusTest.java
orm/src/test/java/org/hibernate/search/test/compression/CompressionTest.java
orm/src/test/java/org/hibernate/search/test/spatial/BenchWithGeonames.java

https://hibernate.atlassian.net/browse/HSEARCH-2811

Resolve some Lucene deprecations

---

engine/src/main/java/org/hibernate/search/util/impl/Closeables.java
pom.xml

3 trivial changes to fix the build on java version "9" preview `build 9+181`
https://hibernate.atlassian.net/browse/HSEARCH-2846

java 9 compatibility update

---

engine/src/main/java/org/hibernate/search/query/engine/impl/AbstractHSQuery.java
engine/src/test/java/org/hibernate/search/test/query/engine/HSQueryResultCacheClearingTest.java
engine/src/test/java/org/hibernate/search/testsupport/junit/SearchITHelper.java

Relevant JIRA tickets:
* https://hibernate.atlassian.net/browse/HSEARCH-2852
* https://hibernate.atlassian.net/browse/HSEARCH-2843
See also #1514

Backport HSEARCH-2843 to 5.7

---

engine/src/main/java/org/hibernate/search/query/engine/impl/AbstractHSQuery.java
engine/src/test/java/org/hibernate/search/test/query/engine/HSQueryResultCacheClearingTest.java
engine/src/test/java/org/hibernate/search/testsupport/junit/SearchITHelper.java

Relevant JIRA tickets:
* https://hibernate.atlassian.net/browse/HSEARCH-2852
* https://hibernate.atlassian.net/browse/HSEARCH-2843
See also #1515

Backport HSEARCH-2843 to 5.6

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-2856

HSEARCH-2856 Upgrade Elasticsearch dependencies to 5.5.2

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-2857

HSEARCH-2857 Update 5.5 branch to Hibernate ORM 5.1.10.Final

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
integrationtest/elasticsearch/pom.xml
orm/src/main/java/org/hibernate/search/event/impl/FullTextIndexEventListener.java
orm/src/test/java/org/hibernate/search/test/engine/optimizations/BridgedReverseBagCollectionUpdateEventTest.java
orm/src/test/java/org/hibernate/search/test/engine/optimizations/CollectionUpdateEventTest.java

This PR is based on #1531 , which should be merged first.
https://hibernate.atlassian.net//browse/HSEARCH-2404

HSEARCH-2404 Enable CollectionUpdateEventTest for Elasticsearch

---

integrationtest/wildfly/pom.xml
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-2881
Tested locally, tests passed.
Build in progress on Jenkins: http://ci.hibernate.org/view/Personal%20runs/job/hibernate-search-yoann-jdk9/1/

HSEARCH-2881 Re-enable Wildfly integration tests with JDK9

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/ElasticsearchRequest.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/client/RequestTest.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/DefaultElasticsearchClientFactoryTest.java
integrationtest/elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/client/ElasticsearchContentLengthIT.java

A simple one.
https://hibernate.atlassian.net/browse/HSEARCH-2883

HSEARCH-2883

---

backends/jgroups/src/main/java/org/hibernate/search/backend/jgroups/logging/impl/Log.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/logging/impl/Log.java
engine/src/main/java/org/hibernate/search/util/logging/impl/BaseHibernateSearchLogger.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
pom.xml
serialization/avro/src/main/java/org/hibernate/search/indexes/serialization/avro/logging/impl/Log.java

This is the result of looking into the metadata cost, and exploring what our code is costing in terms of native memory utilization - the areas of JVM costs in which we normally don't look.
- https://hibernate.atlassian.net/browse/HSEARCH-2887

HSEARCH-2887

---

integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/MemberRegistrationEarArchiveIT.java
integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/MemberRegistrationIT.java
integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/PackagerHelper.java

Considering this a follow up of the already merged HSEARCH-2890 pr #1549
https://hibernate.atlassian.net/browse/HSEARCH-2890 (already resolved)

Avoid some mistakes in integration test helper PackagerHelper

---

backends/jms/src/main/java/org/hibernate/search/backend/jms/spi/AbstractJMSHibernateSearchController.java
documentation/src/main/asciidoc/advanced-features.asciidoc
documentation/src/main/asciidoc/configuration.asciidoc
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
integrationtest/elasticsearch/src/test/resources/META-INF/persistence.xml
integrationtest/jms/src/test/java/org/hibernate/search/test/jms/master/MDBSearchController.java
integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/jms/controller/RegistrationMdb.java
orm/src/main/java/org/hibernate/search/orm/spi/SearchIntegratorHelper.java
orm/src/test/java/org/hibernate/search/test/jpa/IntegratorExtractionTest.java
orm/src/test/resources/META-INF/persistence.xml

https://hibernate.atlassian.net/browse/HSEARCH-2901

HSEARCH-2901 Introduce an SPI to get a SearchIntegrator from a SessionFactory

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2892
- https://hibernate.atlassian.net/browse/HSEARCH-2896

Component upgrades: Elasticsearch 5.6.2, Gson 2.8.2

---

engine/src/main/java/org/hibernate/search/util/impl/ReflectionHelper.java
engine/src/test/java/NoPackageAnnotationTest.java
engine/src/test/java/NotPackagedAnnotation.java

See [HSEARCH-2909](https://hibernate.atlassian.net/browse/HSEARCH-2909)

HSEARCH-2909 Prevent NPE for annotation w/out package

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2912

HSEARCH-2912 Reenable all integration tests on all JDK profiles

---

integrationtest/narayana/pom.xml
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2915

HSEARCH-2915 Update to Narayana 5.5.30.Final

---

documentation/src/main/asciidoc/mapping.asciidoc

https://hibernate.atlassian.net//browse/HSEARCH-2906

HSEARCH-2906 Unable to extend NumericFieldBridge

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2927
- https://hibernate.atlassian.net/browse/HSEARCH-2928

Updating WildFly to 11.0.0.Final and to latest Lucene micro fix

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2929

HSEARCH-2929 Update to Hibernate ORM 5.1.10.Final

---

integrationtest/performance/orm/pom.xml
integrationtest/wildfly/pom.xml
pom.xml

Cleaning up some technical debt in the build:
- https://hibernate.atlassian.net/browse/HSEARCH-2249
- https://hibernate.atlassian.net/browse/HSEARCH-2936
- https://hibernate.atlassian.net/browse/HSEARCH-2937
Incidentally, this gives a big speedup of the build when skipping tests. Useful during various dev cycles.

Build cleanup

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/logging/impl/ElasticsearchResponseFormatter.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/GsonStreamedEncodingTest.java
engine/src/main/java/org/hibernate/search/bridge/impl/ExtendedBridgeProvider.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/DocumentFieldMetadata.java
engine/src/main/java/org/hibernate/search/filter/impl/CachingWrapperQuery.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/MoreLikeThisBuilder.java
engine/src/main/java/org/hibernate/search/util/impl/ConcurrentReferenceHashMap.java
engine/src/test/java/org/hibernate/search/test/backend/lucene/RandomGenerator.java
engine/src/test/java/org/hibernate/search/test/engine/typehandling/BasicTypeCollectionsTest.java
engine/src/test/java/org/hibernate/search/test/id/providedId/ProvidedIdPerson.java
engine/src/test/java/org/hibernate/search/test/metadata/DescriptorTestHelper.java
engine/src/test/java/org/hibernate/search/test/searchfactory/SearchFactoryTest.java
integrationtest/osgi/karaf-it/pom.xml
integrationtest/performance/orm/pom.xml
integrationtest/spring/pom.xml
orm/src/test/java/org/hibernate/search/test/directoryProvider/MultipleSFTestCase.java
orm/src/test/java/org/hibernate/search/test/embedded/depth/WorkDoneOnEntitiesTest.java
orm/src/test/java/org/hibernate/search/test/embedded/nested/containedIn/Entity2ForDoc0.java
orm/src/test/java/org/hibernate/search/test/embedded/nested/containedIn/Entity2ForUnindexed.java
orm/src/test/java/org/hibernate/search/test/embedded/nested/containedIn/HelpItemTag.java
orm/src/test/java/org/hibernate/search/test/engine/worker/duplication/WorkSequencesTest.java
orm/src/test/java/org/hibernate/search/test/query/objectloading/TestEntity.java
orm/src/test/java/org/hibernate/search/test/spatial/BenchWithGeonames.java
pom.xml
serialization/avro/src/test/java/org/hibernate/search/test/serialization/SerializationTest.java

A ocuple more trivial cleanup changes:
- https://hibernate.atlassian.net/browse/HSEARCH-2938
- https://hibernate.atlassian.net/browse/HSEARCH-2939
- https://hibernate.atlassian.net/browse/HSEARCH-2940

Cleanup, II

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-2922

HSEARCH-2922 Upgrade Elasticsearch dependencies to 5.6.3

---

integrationtest/jsr352/src/test/java/org/hibernate/search/jsr352/massindexing/AbstractBatchIndexingIT.java
integrationtest/jsr352/src/test/java/org/hibernate/search/jsr352/massindexing/BatchIndexingJobIT.java
jsr352/core/src/test/java/org/hibernate/search/jsr352/massindexing/impl/steps/lucene/EntityReaderTest.java
jsr352/core/src/test/java/org/hibernate/search/jsr352/massindexing/impl/steps/lucene/PartitionMapperTest.java

https://hibernate.atlassian.net/browse/HSEARCH-2946

HSEARCH-2946 Simplify EntityManager closing in tests

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2948

HSEARCH-2948 Match JBoss Logging versions of WildFly 11.0.0.Final

---

documentation/src/main/asciidoc/manual-index.asciidoc

https://hibernate.atlassian.net//browse/HSEARCH-2957

HSEARCH-2957 Remove the warning "this feature is work in progress" in the JSR-352 integration documentation

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-2961

HSEARCH-2961 Downgrade the version of the MariaDB plugin

---

.travis.yml
README.md
documentation/pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-2965

HSEARCH-2965 Do not generate the PDF documentation by default

---

backends/jgroups/pom.xml
modules/src/main/assembly/dist.xml

- https://hibernate.atlassian.net/browse/HSEARCH-2974
- https://hibernate.atlassian.net/browse/HSEARCH-2975

Resolving a couple of trivial build warnings

---

engine/src/main/java/org/hibernate/search/query/engine/impl/LuceneHSQuery.java
engine/src/main/java/org/hibernate/search/query/engine/impl/QueryHits.java
engine/src/test/java/org/hibernate/search/test/facet/NoIndexedValueFacetingTest.java
engine/src/test/java/org/hibernate/search/test/id/providedId/ProvidedIdTest.java
engine/src/test/java/org/hibernate/search/testsupport/junit/SearchITHelper.java

https://hibernate.atlassian.net//browse/HSEARCH-2955

HSEARCH-2955 Faceting query fails when the facet field is not populated for any document

---

distribution/pom.xml
distribution/src/main/assembly/dist.xml
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-2986

HSEARCH-2986 Put the distribution files to upload into distribution/target/dir so that release scripts find them

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-2976

HSEARCH-2976 Upgrade to Elasticsearch 5.6.5

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-2991

HSEARCH-2991 Avoid needing jsr250-api during project build

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-2993

HSEARCH-2993 Upgrade to Byteman 4.0.0

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-2994

Upgrade to Hibernate ORM 5.2.12.Final

---

jbossmodules/testing/pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-2997

HSEARCH-2997 Ensure hibernate-search-jbossmodules-testing will not be released anymore

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-3008

HSEARCH-3008 Update to forbiddenapis to 2.4.1 to get JDK10 compatibility

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-3010

HSEARCH-3010 Update JBoss Logging to version 3.3.2.Final

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-3006
- https://hibernate.atlassian.net/browse/HSEARCH-3007

HSEARCH-3006 Make the version of the Surefire Maven plugin a property

---

documentation/pom.xml
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-3011
- https://hibernate.atlassian.net/browse/HSEARCH-3012

HSEARCH-3011 Re-enable building the documentation on all JDKs

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-3018
Good progress: now it is successfully building until it reaches the OSGi tests.

HSEARCH-3018 Update to Byteman 4.0.1: allows building on JDK10

---

documentation/src/main/asciidoc/mapping.asciidoc
engine/src/main/java/org/hibernate/search/annotations/TikaBridge.java
engine/src/main/java/org/hibernate/search/bridge/TikaParserProvider.java
engine/src/main/java/org/hibernate/search/bridge/builtin/TikaBridge.java
engine/src/main/java/org/hibernate/search/bridge/impl/TikaBridgeProvider.java
engine/src/test/java/org/hibernate/search/test/bridge/builtin/TikaBridgeTest.java

https://hibernate.atlassian.net//browse/HSEARCH-3019
Ready for review if the build succeeds.

HSEARCH-3019 Provide ability to customize parser in TikaBridge

---

orm/pom.xml
pom.xml

Remove some dead code in the pom files

---

pom.xml

* https://hibernate.atlassian.net/browse/HSEARCH-3013
* https://hibernate.atlassian.net/browse/HSEARCH-3015

HSEARCH-3013 HSEARCH-3015 Update JGroups and Classmate dependencies

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3037

HSEARCH-3037 Fix incorrect dependency in the IDEA profile leading to JBoss logging annotation processor errors

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3036

HSEARCH-3036 Upgrade to Hibernate Commons Annotations 5.0.3.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3035

HSEARCH-3035 Use source and target properties for JBoss logging processor

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-3041

HSEARCH-3041 Upgrade to Elasticsearch 5.6.8

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/TypeMetadata.java
engine/src/test/java/org/hibernate/search/test/dsl/Coffee.java
engine/src/test/java/org/hibernate/search/test/dsl/CoffeeMaker.java
engine/src/test/java/org/hibernate/search/test/dsl/SimpleQueryStringDSLTest.java

* https://hibernate.atlassian.net/browse/HSEARCH-3039

HSEARCH-3039 Register a pass through analyzer for the id field

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/main/java/org/hibernate/search/engine/metadata/impl/TypeMetadata.java
engine/src/test/java/org/hibernate/search/test/dsl/Coffee.java
engine/src/test/java/org/hibernate/search/test/dsl/CoffeeMaker.java
engine/src/test/java/org/hibernate/search/test/dsl/SimpleQueryStringDSLTest.java

https://hibernate.atlassian.net//browse/HSEARCH-3039
Waiting for the CI.

Backport HSEARCH-3039 to 5.9

---

documentation/src/main/asciidoc/mapping.asciidoc

https://hibernate.atlassian.net//browse/HSEARCH-3021

HSEARCH-3021 Document the integration to DI frameworks

---

engine/src/main/java/org/hibernate/search/engine/impl/ImmutableSearchIntegration.java

https://hibernate.atlassian.net//browse/HSEARCH-3132

HSEARCH-3132 Normalizers are not closed on shutdown

---

engine/src/main/java/org/hibernate/search/spi/impl/IndexedTypeSets.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
orm/src/main/java/org/hibernate/search/batchindexing/impl/MassIndexerImpl.java
orm/src/test/java/org/hibernate/search/test/batchindexing/SearchIndexerTest.java

https://hibernate.atlassian.net//browse/HSEARCH-3134

HSEARCH-3134 Error message in MassIndexerImpl#toRootEntities mentions "a subclass of an indexed entity" but should mention "supertype" instead

---

engine/pom.xml
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-3149
- https://hibernate.atlassian.net/browse/HSEARCH-3150

Surefire upgrade & minor OSGi fix

---

build-config/src/main/resources/forbidden-runtime.txt
build-config/src/main/resources/forbidden-tests.txt
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/settings/impl/translation/JsonPassThroughAnalysisDefinitionFactory.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/settings/impl/translation/SimpleAnalysisDefinitionFactory.java
engine/src/main/java/org/hibernate/search/engine/impl/ConfigContext.java
engine/src/main/java/org/hibernate/search/engine/impl/DefaultIndexManagerFactory.java
engine/src/main/java/org/hibernate/search/engine/service/beanresolver/spi/ReflectionBeanResolver.java
engine/src/main/java/org/hibernate/search/engine/spi/SearchMappingHelper.java
engine/src/main/java/org/hibernate/search/util/impl/ClassLoaderHelper.java
engine/src/main/java/org/hibernate/search/util/impl/ReflectionHelper.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
engine/src/test/java/org/hibernate/search/test/util/impl/ClassLoaderHelperTest.java
engine/src/test/java/org/hibernate/search/test/util/logging/LoggerInfoStreamTest.java
engine/src/test/java/org/hibernate/search/testsupport/concurrency/Poller.java
orm/src/test/java/org/hibernate/search/test/directoryProvider/FSSlaveAndMasterDPTest.java
orm/src/test/java/org/hibernate/search/test/directoryProvider/MultipleSFTestCase.java
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-3153
- https://hibernate.atlassian.net/browse/HSEARCH-3154

ForbiddenAPI update and improved compatibility with future JDKs

---

documentation/pom.xml
documentation/src/main/asciidoc/advanced-features.asciidoc
documentation/src/main/asciidoc/architecture.asciidoc
documentation/src/main/asciidoc/configuration.asciidoc
documentation/src/main/asciidoc/getting-started.asciidoc
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-3155

Documentation review

---

README.md
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3159

HSEARCH-3159 Upgrade to Hibernate ORM 5.3.0.Final

---

pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-3161

HSEARCH-3161 Clarify which LGPL version exactly in the POM file

---

integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/BootstrapFailureIT.java
integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/util/ManagementClientHelper.java
jbossmodules/orm/src/main/modules/search/jsr352/module.xml
jbossmodules/orm/src/main/modules/search/orm/module.xml
orm/src/main/java/org/hibernate/search/hcore/impl/ExtendedBeanManagerSynchronizer.java
orm/src/main/java/org/hibernate/search/hcore/impl/HibernateSearchSessionFactoryObserver.java
pom.xml

Because master is now 5.11, not 5.10.
https://hibernate.atlassian.net/browse/HSEARCH-2933
https://hibernate.atlassian.net/browse/HSEARCH-3168
https://hibernate.atlassian.net/browse/HSEARCH-3163

Backports to 5.10:  HSEARCH-3163,  HSEARCH-3168,  HSEARCH-2933

---

integrationtest/narayana/src/test/java/org/hibernate/search/test/integration/jbossjta/JBossTSIT.java
integrationtest/narayana/src/test/java/org/hibernate/search/test/integration/jbossjta/infra/NarayanaStandaloneJtaPlatform.java
pom.xml

Updating PR #1684 
- https://hibernate.atlassian.net//browse/HSEARCH-3173

HSEARCH-3173 Upgrade to ORM 5.3.1 and ByteBuddy 1.8.12

---

build-config/pom.xml
integrationtest/performance/orm/pom.xml
integrationtest/performance/orm/src/test/resources/arquillian.xml
integrationtest/wildfly/pom.xml
integrationtest/wildfly/src/test/resources/arquillian.xml
legacy/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3185
https://hibernate.atlassian.net/browse/HSEARCH-3186
https://hibernate.atlassian.net/browse/HSEARCH-3187

 HSEARCH-3185 +  HSEARCH-3186 +  HSEARCH-3187 More build fixes

---

build-config/pom.xml
integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/HibernateSearchWithKarafIT.java
integrationtest/osgi/karaf-it/src/test/resources/maven.properties
integrationtest/performance/orm/pom.xml
integrationtest/performance/orm/src/test/resources/arquillian.xml
integrationtest/wildfly/pom.xml
integrationtest/wildfly/src/test/resources/arquillian.xml
jbossmodules/pom.xml
legacy/pom.xml
pom.xml

*Warning*: #1689 should be merged to master first.

Backport build fixes to branch 5.10

---

README.md

https://hibernate.atlassian.net//browse/HSEARCH-3198

HSEARCH-3198 Strip down the README and redirect to the website for getting started information

---

integrationtest/performance/orm/pom.xml
pom.xml

- https://hibernate.atlassian.net/browse/HSEARCH-3219

Further progress on JDK9 compatibility - now almost without flags

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3224

HSEARCH-3224 Upgrade to Byteman 4.0.3

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3228
https://github.com/hibernate/gson-jbossmodules/pull/2

HSEARCH-3228 Upgrade to GSON 2.8.5

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3211
https://hibernate.atlassian.net//browse/HSEARCH-3210

HSEARCH-3211 + HSEARCH-3210 Upgrade to ORM 5.3.2 and HCANN 5.0.4

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3211
https://hibernate.atlassian.net//browse/HSEARCH-3210
#1704 should be merged first.

Backport HSEARCH-3211 + HSEARCH-3210 to branch 5.10 - Upgrade to ORM 5.3.2 and HCANN 5.0.4

---

integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/HibernateSearchWithKarafIT.java
integrationtest/osgi/karaf-it/src/test/resources/maven.properties
integrationtest/performance/orm/pom.xml
integrationtest/performance/orm/src/test/resources/arquillian.xml
integrationtest/wildfly/pom.xml
integrationtest/wildfly/src/test/resources/arquillian.xml
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3241

HSEARCH-3241 Reorganize and clarify Maven properties used to pass JVM args

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3234

HSEARCH-3234 Upgrade to ORM 5.3.3

---

.travis.yml

https://hibernate.atlassian.net//browse/HSEARCH-3240

HSEARCH-3240 Use the pre-installed JDK in the Travis build instead of trying to update it in each build

---

engine/src/main/java/org/hibernate/search/query/dsl/impl/ConnectedQueryContextBuilder.java
engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
engine/src/test/java/org/hibernate/search/test/dsl/DSLTest.java
engine/src/test/java/org/hibernate/search/test/dsl/Month.java

https://hibernate.atlassian.net//browse/HSEARCH-3233

HSEARCH-3233 Overriding an analyzer in the queryBuilder with an unknown analyzer should lead to a proper SearchException

---

.travis.yml
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3252
I had to add a few settings to the build in order to limit memory usage more accurately.

HSEARCH-3252 Avoid using _JAVA_OPTIONS in Travis builds

---

.travis.yml
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3252
Port of #1719 , which should be merged first.

Backport HSEARCH-3252 to branch 5.10 - Avoid using _JAVA_OPTIONS in Travis builds

---

legacy/pom.xml
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3337
~This is based on #1723 , which should be merged first.~ => Done

HSEARCH-3337 Generate external javadoc URLs automatically from version properties

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/test/java/org/hibernate/search/test/configuration/indexedembedded/ContainedEntityWithSpatialBridgesTest.java

https://hibernate.atlassian.net//browse/HSEARCH-3339
Just checking the CI build before I merge.
Backported from #1729

Backport HSEARCH-3339 to branch 5.9 - @SpatialBridge in "contained" entity triggers exception at bootstrap

---

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/test/java/org/hibernate/search/test/configuration/indexedembedded/ContainedEntityWithSpatialBridgesTest.java

https://hibernate.atlassian.net/browse/HSEARCH-3339

HSEARCH-3339 @SpatialBridge in "contained" entity triggers exception at bootstrap

---

documentation/pom.xml
engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java
engine/src/test/java/org/hibernate/search/test/configuration/indexedembedded/ContainedEntityWithSpatialBridgesTest.java
engine/src/test/java/org/hibernate/search/testsupport/junit/SearchITHelper.java
engine/src/test/java/org/hibernate/search/testsupport/junit/SearchIntegratorResource.java
engine/src/test/java/org/hibernate/search/testsupport/setup/SearchConfigurationForTest.java
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3342
https://hibernate.atlassian.net//browse/HSEARCH-3339
Simply some backports of internal configuration and test code, plus a backport of HSEARCH-3339 to branch 5.6.
Backported from #1729

HSEARCH-3342 + Backport HSEARCH-3339 to branch 5.6 - @SpatialBridge in "contained" entity triggers exception at bootstrap

---

legacy/pom.xml
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3343
Just checking if the CI build passes.

HSEARCH-3343 Upgrade to Hibernate ORM 5.3.6.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3345
Just checking if the CI build passes.

HSEARCH-3345 Upgrade to Hibernate ORM 5.1.15.Final

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3344
Just checking if the CI build passes.

HSEARCH-3344 Upgrade to Hibernate ORM 5.2.17.Final

---

Jenkinsfile

https://hibernate.atlassian.net//browse/HSEARCH-3346

HSEARCH-3346 Only enable Sonar analysis on select Jenkins jobs

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/BridgeUsingPropertyMarkerAccessIT.java
util/internal/test/src/main/java/org/hibernate/search/util/impl/test/annotation/TestForIssue.java

https://hibernate.atlassian.net/browse/HSEARCH-2759
https://hibernate.atlassian.net/browse/HSEARCH-2847
~This PR is based on #1740 , which should be merged first.~ => Done

HSEARCH-2759 + HSEARCH-2847 : ITs regarding how GeoPointBridge accesses entity data 

---

Jenkinsfile

https://hibernate.atlassian.net//browse/HSEARCH-3363

HSEARCH-3363 Don't try to report to Coveralls.io or SonarCloud in the Jenkinsfile when coverage data is missing

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AbstractAutomaticIndexingMultiAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingSortedMapValuesAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingSortedSetAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/smoke/AnnotationMappingSmokeIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/smoke/ProgrammaticMappingSmokeIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/AbstractFieldContainerValueExtractorIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/BridgeIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DocumentIdDefaultBridgeIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FieldBaseIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FieldContainerValueExtractorBaseIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FieldContainerValueExtractorExplicitIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FieldContainerValueExtractorImplicitIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FieldDefaultBridgeIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/smoke/AnnotationMappingSmokeIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/smoke/ProgrammaticMappingSmokeIT.java

https://hibernate.atlassian.net/browse/HSEARCH-2554
https://hibernate.atlassian.net/browse/HSEARCH-2490

HSEARCH-2554 + HSEARCH-2490 : ContainerValueExtractor tests

---

engine/src/test/java/org/hibernate/search/engine/mapper/mapping/building/impl/IndexSchemaNestingContextImplTest.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DependencyIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/spatial/AnnotationMappingGeoPointBridgeIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/test/util/StartupStubBridge.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/test/util/rule/JavaBeanMappingSetupHelper.java

https://hibernate.atlassian.net//browse/HSEARCH-2194
https://hibernate.atlassian.net//browse/HSEARCH-3212
https://hibernate.atlassian.net//browse/HSEARCH-2552
Based on #1744 , which should be merged first.
This does not change anything to the main code. The tickets were already fixed, we just needed more explicit tests.

HSEARCH-2194 +  HSEARCH-3212 +  HSEARCH-2552 Add/clarify tests for @IndexedEmbedded

---

backends/jgroups/pom.xml
integrationtest/elasticsearch/pom.xml
integrationtest/jdk9-modules/pom.xml
integrationtest/jms/pom.xml
integrationtest/jsr352/pom.xml
integrationtest/narayana/pom.xml
integrationtest/osgi/karaf-features/src/main/features/features.xml
integrationtest/osgi/karaf-it/pom.xml
integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/HibernateSearchWithKarafIT.java
integrationtest/osgi/karaf-it/src/test/resources/maven.properties
integrationtest/performance/orm/pom.xml
integrationtest/performance/sandbox/pom.xml
integrationtest/spring/pom.xml
jsr352/core/pom.xml
orm/pom.xml
orm/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3379
This PR is a backport of #1752, which should be merged first.

Backport HSEARCH-3379 to branch 5.10 - Reference the Hibernate ORM feature from the OSGi tests

---

Jenkinsfile
build-config/src/main/resources/forbidden-runtime.txt
legacy/backends/jgroups/pom.xml
legacy/integrationtest/elasticsearch/pom.xml
legacy/integrationtest/jdk9-modules/pom.xml
legacy/integrationtest/jms/pom.xml
legacy/integrationtest/jsr352/pom.xml
legacy/integrationtest/narayana/pom.xml
legacy/integrationtest/osgi/karaf-features/src/main/features/features.xml
legacy/integrationtest/osgi/karaf-it/pom.xml
legacy/integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/HibernateSearchWithKarafIT.java
legacy/integrationtest/osgi/karaf-it/src/test/resources/maven.properties
legacy/integrationtest/performance/orm/pom.xml
legacy/integrationtest/performance/sandbox/pom.xml
legacy/integrationtest/spring/pom.xml
legacy/jsr352/core/pom.xml
legacy/orm/pom.xml
legacy/orm/src/main/resources/OSGI-INF/blueprint/blueprint.xml
legacy/pom.xml
mapper/orm/pom.xml
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3379
This PR is based on #1750 , which should be merged first.

HSEARCH-3379 Reference the Hibernate ORM feature from the OSGi tests

---

.travis.yml
Jenkinsfile

https://hibernate.atlassian.net//browse/HSEARCH-3381
The external library can be found there: https://github.com/hibernate/hibernate-jenkins-pipeline-helpers
I took this opportunity to dump some knowledge I gathered during my experiments to that library's README.md.

HSEARCH-3381 Move part of the Jenkinsfile to an external, shared library

---

.travis.yml
Jenkinsfile
integrationtest/elasticsearch/pom.xml
integrationtest/elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchScrollingIT.java
integrationtest/elasticsearch/src/test/java/org/hibernate/search/elasticsearch/testutil/junit/SkipBelowElasticsearch22.java
pom.xml
travis/mariadb.sql
travis/pgsql.sql

https://hibernate.atlassian.net//browse/HSEARCH-3365
Just testing that PRs build correctly before I merge, no need to review.

Backport HSEARCH-3365 to branch 5.10 - Backport Jenkinsfile to older, still maintained branches

---

legacy/integrationtest/osgi/karaf-it/pom.xml
legacy/integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/HibernateSearchWithKarafIT.java

https://hibernate.atlassian.net//browse/HSEARCH-3396

HSEARCH-3396 Allow to use snapshot artifacts in OSGi integration tests

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/ElasticsearchExtension.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/LuceneExtension.java
engine/src/main/java/org/hibernate/search/engine/backend/document/model/dsl/IndexSchemaFieldContext.java
engine/src/main/java/org/hibernate/search/engine/backend/document/model/dsl/IndexSchemaFieldContextExtension.java
engine/src/main/java/org/hibernate/search/engine/common/dsl/impl/DslExtensionState.java
engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/SearchPredicateContainerContext.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/SearchPredicateContainerContextExtension.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/SearchPredicateContainerExtensionContext.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/SearchPredicateContainerContextImpl.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/SearchPredicateContainerExtensionContextImpl.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/spi/DelegatingSearchPredicateContainerContextImpl.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/SearchSortContainerContext.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/SearchSortContainerContextExtension.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/SearchSortContainerExtensionContext.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/impl/NonEmptySortContextImpl.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/impl/SearchSortContainerContextImpl.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/impl/SearchSortContainerExtensionContextImpl.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/spi/DelegatingSearchSortContainerContextImpl.java
engine/src/test/java/org/hibernate/search/engine/common/dsl/impl/DslExtensionStateTest.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/ExtensionIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/ExtensionIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SearchPredicateIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/SearchSortIT.java

https://hibernate.atlassian.net//browse/HSEARCH-3126

HSEARCH-3126 Search 6 groundwork - Rework the syntax when using extensions

---

backend/lucene/pom.xml
pom.xml

* https://hibernate.atlassian.net/browse/HSEARCH-3382

HSEARCH-3382 Upgrade to Lucene 7.5.0

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/spi/DifferentSessionFactoriesIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMappingImpl.java

https://hibernate.atlassian.net/browse/HSEARCH-3079

HSEARCH-3079 Throw an error when mixing different ORM SessionFactories

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/DefaultElasticsearchClient.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/DefaultElasticsearchClientFactory.java
pom.xml

* https://hibernate.atlassian.net/browse/HSEARCH-3404

HSEARCH-3404 Upgrade Elasticsearch to 6.4.2

---

integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/BridgeIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DocumentIdBaseIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/providedid/ProvidedIdIT.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/JavaBeanMappingBuilder.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/model/impl/JavaBeanPropertyModel.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/impl/ProvidedStringIdentifierMapping.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/impl/AbstractPojoModelCompositeElement.java

https://hibernate.atlassian.net//browse/HSEARCH-3406

HSEARCH-3406 Fix (and test) exceptions not being thrown because we call "log.someMethod();" instead of "throw log.someMethod();"

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexWorkVisitor.java
elasticsearch/src/main/java/org/hibernate/search/elasticsearch/logging/impl/Log.java
engine/src/test/java/org/hibernate/search/test/bridge/MultiValuedBooleanBridgeTest.java

https://hibernate.atlassian.net//browse/HSEARCH-3407

HSEARCH-3407 Boolean fields in embedded collections are not indexed properly when using Elasticsearch

---

Jenkinsfile

https://hibernate.atlassian.net//browse/HSEARCH-3411
To be backported to other branches (I'll do it).

HSEARCH-3411 Add gitter room notification for Jenkins builds

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/CountingOutputStream.java
build-config/src/main/resources/checkstyle.xml
legacy/elasticsearch/src/main/java/org/hibernate/search/elasticsearch/util/impl/CountingOutputStream.java
legacy/elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/GsonStreamedEncodingTest.java
legacy/engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/AddWorkExecutor.java
legacy/engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/ByTermUpdateWorkExecutor.java
legacy/engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/UpdateExtWorkExecutor.java
legacy/engine/src/main/java/org/hibernate/search/query/engine/impl/QueryHits.java
legacy/engine/src/main/java/org/hibernate/search/query/engine/impl/TimeoutManagerImpl.java
legacy/engine/src/main/java/org/hibernate/search/stat/impl/StatisticsImpl.java
legacy/engine/src/main/java/org/hibernate/search/store/impl/DirectoryProviderHelper.java
legacy/engine/src/test/java/org/hibernate/search/test/backend/lucene/SharedReleasesLocksTest.java
legacy/engine/src/test/java/org/hibernate/search/test/bridge/AppliedOnTypeAwareBridgeTest.java
legacy/engine/src/test/java/org/hibernate/search/test/engine/numeric/LuceneNumericFieldTest.java
legacy/engine/src/test/java/org/hibernate/search/test/engine/numeric/NumericFieldTest.java
legacy/engine/src/test/java/org/hibernate/search/test/filters/FreshReadersProvidedTest.java
legacy/engine/src/test/java/org/hibernate/search/test/id/NumericIdEncodingTest.java
legacy/engine/src/test/java/org/hibernate/search/test/projection/ProjectionConversionTest.java
legacy/engine/src/test/java/org/hibernate/search/testsupport/optimizer/LeakingOptimizer.java
legacy/engine/src/test/java/org/hibernate/search/testsupport/readerprovider/FieldSelectorLeakingReaderProvider.java
legacy/integrationtest/performance/engine-lucene/src/main/java/org/hibernate/search/engineperformance/lucene/JMHBenchmarks.java
legacy/orm/src/test/java/org/hibernate/search/test/backend/OptimizationTriggerTest.java
legacy/orm/src/test/java/org/hibernate/search/test/batchindexing/SearchIndexerTest.java
legacy/orm/src/test/java/org/hibernate/search/test/bridge/BridgeTest.java
legacy/orm/src/test/java/org/hibernate/search/test/bridge/bigdecimal/NumericBigDecimalBridgeTest.java
legacy/orm/src/test/java/org/hibernate/search/test/reader/nrtreaders/BasicNRTFunctionalityTest.java
legacy/serialization/avro/src/test/java/org/hibernate/search/test/serialization/ConcurrentServiceTest.java
legacy/serialization/avro/src/test/java/org/hibernate/search/test/serialization/ProtocolBackwardCompatibilityTest.java
legacy/serialization/avro/src/test/java/org/hibernate/search/test/serialization/SerializationTest.java

https://hibernate.atlassian.net//browse/HSEARCH-3408

HSEARCH-3408 Add a checkstyle rule to force using uppercase L for Long constants

---

Jenkinsfile

https://hibernate.atlassian.net//browse/HSEARCH-3417

HSEARCH-3417 Remove the snapshot dependencies trigger from the Jenkinsfile

---

Jenkinsfile
README.md
legacy/pom.xml
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3415

HSEARCH-3415 Upgrade Elasticsearch to 6.5.0 + make it the default

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3432

HSEARCH-3432 Upgrade to Hibernate ORM 5.1.16.Final

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3431

HSEARCH-3431 Upgrade to Hibernate ORM 5.3.7.Final

---

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
documentation/src/main/asciidoc/getting-started.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-3400

HSEARCH-3400 Use org.hibernate.search.jpa.Search in the documentation when we call getFullTextEntityManager

---

Jenkinsfile
documentation/src/main/asciidoc/configuration.asciidoc
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/processor/impl/DefaultContextualErrorHandlerTest.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/processor/impl/DefaultElasticsearchWorkBulkerTest.java
elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/DefaultElasticsearchServiceTest.java
integrationtest/performance/orm/pom.xml
integrationtest/performance/orm/src/test/resources/arquillian.xml
integrationtest/wildfly/pom.xml
integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/VersionTestHelper.java
integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/elasticsearch/ElasticsearchModuleMemberRegistrationIT.java
integrationtest/wildfly/src/test/resources/arquillian.xml
orm/src/test/java/org/hibernate/search/test/configuration/integration/HibernateSearchIntegratorTest.java
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3364
https://hibernate.atlassian.net//browse/HSEARCH-3238
https://hibernate.atlassian.net//browse/HSEARCH-3420

HSEARCH-3364 + HSEARCH-3238 + HSEARCH-3420 - Make the build fully compatible with JDK11

---

engine/src/main/java/org/hibernate/search/engine/backend/document/converter/runtime/spi/FromIndexFieldValueConvertContextImpl.java
engine/src/main/java/org/hibernate/search/engine/backend/document/converter/runtime/spi/ToIndexFieldValueConvertContextImpl.java
engine/src/main/java/org/hibernate/search/engine/common/dsl/spi/DslExtensionState.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/SearchPredicateFactoryContextImpl.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/SearchPredicateFactoryExtensionContextImpl.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/impl/SearchSortContainerContextImpl.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/impl/SearchSortContainerExtensionContextImpl.java
engine/src/test/java/org/hibernate/search/engine/common/dsl/impl/DslExtensionStateTest.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/runtime/impl/BridgeSessionContextImpl.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/runtime/impl/IdentifierBridgeToDocumentIdentifierContextImpl.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/runtime/impl/ValueBridgeToIndexedValueContextImpl.java
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3437

HSEARCH-3437 Restore the <extensions>true</extensions> for the JQAssistant plugin

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3433

Backport HSEARCH-3433 to branch 5.11 - Upgrade to Hibernate ORM 5.4.0.Final

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3433

HSEARCH-3433 Upgrade to Hibernate ORM 5.4.0.Final

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cfg/SearchBackendLuceneSettings.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendFactory.java
documentation/src/test/resources/META-INF/persistence.xml
documentation/src/test/resources/hibernate-test-lucene.properties
engine/src/main/java/org/hibernate/search/engine/backend/spi/BackendFactory.java
engine/src/main/java/org/hibernate/search/engine/backend/spi/BackendImplementor.java
engine/src/main/java/org/hibernate/search/engine/cfg/SearchBackendCommonSettings.java
engine/src/main/java/org/hibernate/search/engine/cfg/SearchEngineSettings.java
engine/src/main/java/org/hibernate/search/engine/cfg/SearchIndexCommonSettings.java
engine/src/main/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolder.java
engine/src/test/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolderTest.java
integrationtest/backend/lucene/src/test/resources/backend-tck-analysis-custom.properties
integrationtest/backend/lucene/src/test/resources/backend-tck-multi-tenancy.properties
integrationtest/backend/lucene/src/test/resources/backend-tck.properties
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/util/rule/SearchSetupHelper.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/UnusedPropertiesIT.java
integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/ManualIndexingIT.java
integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/OrmElasticsearchLibraryShowcaseIT.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/MappingSetupHelper.java

https://hibernate.atlassian.net//browse/HSEARCH-3450
https://hibernate.atlassian.net//browse/HSEARCH-3451

HSEARCH-3450 Properties improvements: consistent naming scheme + backend-scoped index defaults

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3454

HSEARCH-3454 Upgrade to Lucene 7.6.0

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/UnusedPropertiesIT.java
integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/ManualIndexingIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/monitor/impl/SimpleIndexingProgressMonitor.java
util/internal/test/src/main/java/org/hibernate/search/util/impl/test/rule/ExpectedLog4jLog.java

https://hibernate.atlassian.net//browse/HSEARCH-3462

HSEARCH-3462 SimpleIndexingProgressMonitor stops logging as soon as the number of indexed document stops being a multiple of the logging period

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchDefaultWorkSequenceBuilder.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchDefaultWorkSequenceBuilderTest.java

https://hibernate.atlassian.net//browse/HSEARCH-3053
@fax4ever As discussed on Gitter.

HSEARCH-3053 follow-up: deadlock fix

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java

https://hibernate.atlassian.net//browse/HSEARCH-3466

HSEARCH-3466 Add the number of objects in the payload in the Elasticsearch request log

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/impl/ElasticsearchSearchContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/impl/ElasticsearchSearchQueryElementCollector.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/AbstractElasticsearchSearchPredicateBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchBooleanJunctionPredicateBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchMatchAllPredicateBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchMatchIdPredicateBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchMatchPredicateBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchNestedPredicateBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchRangePredicateBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicate.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicateBuilderFactoryImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicateCollector.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicateContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchUserProvidedJsonPredicateContributor.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchTargetContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/SearchBackendContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/AbstractElasticsearchSearchSortBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/ElasticsearchDistanceSortBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/ElasticsearchFieldSortBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/ElasticsearchScoreSortBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/ElasticsearchSearchSort.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/ElasticsearchSearchSortBuilderFactoryImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchGeoPointSpatialWithinBoundingBoxPredicateBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchGeoPointSpatialWithinCirclePredicateBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchGeoPointSpatialWithinPolygonPredicateBuilder.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/DistanceToFieldSearchProjectionTest.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/MultiTenancyIT.java

https://hibernate.atlassian.net//browse/HSEARCH-3421

HSEARCH-3421 Support for ID predicates when multi-tenancy is enabled

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientFactoryImpl.java
documentation/src/main/asciidoc/getting-started.asciidoc
documentation/src/test/resources/META-INF/persistence.xml
documentation/src/test/resources/hibernate-test-elasticsearch.properties
integrationtest/backend/elasticsearch/src/test/resources/backend-tck-analysis-custom.properties
integrationtest/backend/elasticsearch/src/test/resources/backend-tck-multi-tenancy.properties
integrationtest/backend/elasticsearch/src/test/resources/backend-tck.properties

* https://hibernate.atlassian.net/browse/HSEARCH-3481
* https://hibernate.atlassian.net/browse/HSEARCH-3482

Configuration tuning

---

integrationtest/showcase/library/pom.xml
integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/OrmLibraryShowcaseIT.java
integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/OrmManualIndexingIT.java
integrationtest/showcase/library/src/test/resources/application-test.yaml

https://hibernate.atlassian.net//browse/HSEARCH-3424
Just waiting for CI.

HSEARCH-3424 Fixup: allow to run the showcase from within IDEA again

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3483

HSEARCH-3483 Upgrade to Lucene 7.7.0

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchIndexLifecycleStrategyName.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchIndexStatus.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/MultiTenancyStrategyName.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cfg/MultiTenancyStrategyName.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchAnalyzerDefinitionCreationIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchAnalyzerDefinitionMigrationIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchAnalyzerDefinitionValidationIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchIndexStatusCheckIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchNormalizerDefinitionCreationIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchNormalizerDefinitionMigrationIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchNormalizerDefinitionValidationIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchSchemaCreateStrategyIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchSchemaCreationIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchSchemaMigrationIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchSchemaValidationIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateSearchIntegrator.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/cfg/HibernateOrmIndexingStrategyName.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
util/internal/common/src/main/java/org/hibernate/search/util/impl/common/StringHelper.java

* https://hibernate.atlassian.net/browse/HSEARCH-3480
Maybe don't merge it just yet but incorporate it in our private branch so that we can test that everything is working fine before merging.
Note that I also changed things to consistently normalize the input values and log the normalized values as it's the one compared with the accepted values.

HSEARCH-3480 Rename fromExternalRepresentation() to of() in enums

---

Jenkinsfile
README.md
legacy/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3485
https://hibernate.atlassian.net/browse/HSEARCH-3484
Full build including a build with JDK12: http://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-1885/2/pipeline/66

HSEARCH-3485 + HSEARCH-3484 JDK12 compatibility

---

integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneExtensionIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/fieldtype/LuceneFieldContentIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/DocumentAssert.java

https://hibernate.atlassian.net/browse/HSEARCH-1640

HSEARCH-1640 Probe boolean field projection and internal representation

---

legacy/engine/src/main/java/org/hibernate/search/query/engine/impl/QueryFilters.java
legacy/engine/src/main/java/org/hibernate/search/query/engine/spi/HSQuery.java
legacy/engine/src/main/java/org/hibernate/search/util/impl/ConcurrentReferenceHashMap.java
legacy/engine/src/main/java/org/hibernate/search/util/impl/Executors.java
legacy/jsr352/core/src/main/java/org/hibernate/search/jsr352/massindexing/MassIndexingJob.java
legacy/orm/src/main/java/org/hibernate/search/MassIndexer.java
legacy/orm/src/main/java/org/hibernate/search/batchindexing/spi/MassIndexerWithTenant.java
legacy/orm/src/main/java/org/hibernate/search/jpa/FullTextQuery.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/MassIndexer.java
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3494

HSEARCH-3494 Allow to build the javadoc with JDK12

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3495

HSEARCH-3495 Upgrade to Hibernate ORM 5.3.8.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3500
Currently running full ITs, including in JDK10. Let's wait for the result.

HSEARCH-3500 Manage bytebuddy version following HHH-13283

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3495
https://hibernate.atlassian.net//browse/HSEARCH-3501

HSEARCH-3495 + HSEARCH-3501 - Upgrade to Hibernate ORM 5.3.8.Final

---

backend/elasticsearch/pom.xml
backend/lucene/pom.xml
engine/pom.xml
integrationtest/jdk/java-modules/pom.xml
integrationtest/jdk/java-modules/src/main/java/org/hibernate/search/integrationtest/java/module/config/MyLuceneAnalysisConfigurer.java
integrationtest/jdk/java-modules/src/main/java/org/hibernate/search/integrationtest/java/module/entity/Author.java
integrationtest/jdk/java-modules/src/main/java/org/hibernate/search/integrationtest/java/module/service/AuthorService.java
integrationtest/jdk/java-modules/src/main/resources/hibernate.properties
integrationtest/jdk/java-modules/src/test/java/org/hibernate/search/integrationtest/java/module/service/AuthorServiceIT.java
integrationtest/jdk/jdk9-modules/src/main/java/module-info.java
integrationtest/pom.xml
mapper/javabean/pom.xml
mapper/orm/pom.xml
mapper/pojo/pom.xml
pom.xml
util/common/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3514

HSEARCH-3514 Add automatic Java module names and test them

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3520
Just checking with CI.

HSEARCH-3520 Upgrade to Elasticseearch 6.6.2

---

integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DependencyIT.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/dirtiness/building/impl/PojoIndexingDependencyCollectorValueNode.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java

https://hibernate.atlassian.net//browse/HSEARCH-3489

HSEARCH-3489 Improve the error message when the inverse side of an association cannot be found by Hibernate Search

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/nonregression/massindexing/PrimitiveIdMassIndexingIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/BatchIndexingWorkspace.java

https://hibernate.atlassian.net//browse/HSEARCH-3529
Waiting for CI...

HSEARCH-3529 MassIndexer fails for entities with primitive ID type

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToJpaIT.java
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3533

HSEARCH-3533 Upgrade to Hibernate ORM 5.4.2

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3533

Backport HSEARCH-3533 to branch 5.11 - Upgrade to Hibernate ORM 5.4.2

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/ElasticsearchSearchProjectionBuilderFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/projection/impl/ElasticsearchFieldProjectionBuilderFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/projection/impl/ElasticsearchGeoPointFieldProjectionBuilderFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/projection/impl/ElasticsearchStandardFieldProjectionBuilderFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneSearchProjectionBuilderFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/projection/impl/LuceneFieldProjectionBuilderFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/projection/impl/LuceneGeoPointFieldProjectionBuilderFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/projection/impl/LuceneStandardFieldProjectionBuilderFactory.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/FieldSearchProjectionIT.java

https://hibernate.atlassian.net//browse/HSEARCH-3538

HSEARCH-3538 Disabling projection converters in projections is ignored when checking compatibility

---

distribution/pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3546

HSEARCH-3546 SearchException is missing from the javadoc

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/spi/ElasticsearchClient.java
documentation/pom.xml
engine/src/main/java/org/hibernate/search/engine/backend/document/DocumentElement.java
engine/src/main/java/org/hibernate/search/engine/backend/document/model/dsl/spi/IndexSchemaObjectNodeBuilder.java
engine/src/main/java/org/hibernate/search/engine/cfg/spi/ConfigurationProperty.java
engine/src/main/java/org/hibernate/search/engine/cfg/spi/OptionalConfigurationProperty.java
engine/src/main/java/org/hibernate/search/engine/environment/bean/BeanReference.java
engine/src/main/java/org/hibernate/search/engine/search/dsl/projection/SearchProjectionFactoryContext.java
engine/src/main/java/org/hibernate/search/engine/search/query/spi/LoadingResult.java
engine/src/main/java/org/hibernate/search/engine/search/query/spi/ProjectionHitMapper.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/search/dsl/query/SearchQueryResultDefinitionContext.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/SearchSession.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/impl/JavaBeanSearchSession.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/spi/HibernateOrmMapping.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/SearchSession.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/spi/PojoMappingDelegate.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PropertyHandleFactory.java
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3375

HSEARCH-3375 Fail the build on javadoc warnings

---

mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/monitor/MassIndexingMonitor.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/monitor/impl/SimpleIndexingProgressMonitor.java

https://hibernate.atlassian.net/browse/HSEARCH-2941

HSEARCH-2941 Use long type only in MassIndexingMonitor

---

integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/model/ImplementedInterfaceIT.java

https://hibernate.atlassian.net/browse/HSEARCH-1656

HSEARCH-1656 Test annotation on implemented interface

---

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/LocalDateTimeFieldTypeDescriptor.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/OffsetDateTimeFieldTypeDescriptor.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/ZonedDateTimeFieldTypeDescriptor.java

https://hibernate.atlassian.net/browse/HSEARCH-3547

HSEARCH-3547 Use different times to test *DateTime type

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchBooleanJunctionPredicateBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneBooleanJunctionPredicateBuilder.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/search/LuceneBoolSearchPredicateIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/BoolSearchPredicateIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3534
https://hibernate.atlassian.net/browse/HSEARCH-3535

HSEARCH-3534 HSEARCH-3535  Default value  and out of bound message for "minimumShouldMatch"

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3565

HSEARCH-3565 Upgrade to Hibernate ORM 5.3.10.Final

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AbstractAutomaticIndexingAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AbstractAutomaticIndexingMultiAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingListAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingMapKeysAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingMapValuesAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingSingleAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingSortedMapValuesAssociationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingSortedSetAssociationIT.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/dirtiness/building/impl/PojoIndexingDependencyCollectorValueNode.java

https://hibernate.atlassian.net//browse/HSEARCH-3566

HSEARCH-3566 Reindexing is not triggered when an association mentioned in an IndexingDependency.derivedFrom is updated

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/LuceneCollectors.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/LuceneCollectorsBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneDistanceToFieldProjection.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/SearchProjectionExtractContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearcher.java

https://hibernate.atlassian.net/browse/HSEARCH-3539

HSEARCH-3539 Make LuceneDistanceToFieldProjection stateless

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToHibernateOrmIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToJpaIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/BasicMassIndexingIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/Search.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMappingImpl.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchQuery.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/impl/HibernateOrmSearchSession.java

https://hibernate.atlassian.net/browse/HSEARCH-1857

HSEARCH-1857 Throw exceptions on usage of a FullTextSession whose underlying Session is closed

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/ElasticsearchIndexFieldTypeFactoryContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/ElasticsearchNativeIndexFieldTypeContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/impl/ElasticsearchIndexFieldTypeFactoryContextImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/impl/ElasticsearchNativeIndexFieldTypeContextImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/impl/LuceneIndexFieldTypeFactoryContextImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/impl/LuceneNativeIndexFieldTypeContext.java

https://hibernate.atlassian.net//browse/HSEARCH-3574

HSEARCH-3574 Rename ElasticsearchJsonStringIndexFieldTypeContext to ElasticsearchNativeIndexFieldTypeContext

---

pom.xml
reports/pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3570

HSEARCH-3570 Switch to XML format for JaCoCo reports

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/FailingBootIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateSearchIntegrator.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateSearchSessionFactoryObserver.java

https://hibernate.atlassian.net//browse/HSEARCH-3579

HSEARCH-3579 Failing to boot the ORM integration no longer throws an exception

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/builder/impl/SearchWorkBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/SearchWork.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/LuceneCollectors.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneSearchWork.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneStubWorkFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneWorkFactory.java
engine/src/main/java/org/hibernate/search/engine/search/query/ExtendedSearchQuery.java
engine/src/main/java/org/hibernate/search/engine/search/query/SearchQuery.java
engine/src/main/java/org/hibernate/search/engine/search/query/spi/AbstractSearchQuery.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryFetchIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryResultLoadingOrTransformingIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToHibernateOrmIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToJpaIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/smoke/AnnotationMappingSmokeIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/smoke/ProgrammaticMappingSmokeIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/smoke/AnnotationMappingSmokeIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/smoke/ProgrammaticMappingSmokeIT.java
integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchDocumentRepository.java
integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchDocumentRepositoryImpl.java
integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchLibraryRepository.java
integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchLibraryRepositoryImpl.java
integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchPersonRepository.java
integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchPersonRepositoryImpl.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/StubSearchQuery.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/StubSearchWork.java

https://hibernate.atlassian.net//browse/HSEARCH-3577

HSEARCH-3577 Remove support for longs when specifying the limit/offset of a Search query

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/mapping/definition/AnnotationMappingDiscoveryIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/AnnotationMappingDiscoveryIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/MarkerBaseIT.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/spatial/annotation/Latitude.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/spatial/annotation/Longitude.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/declaration/MarkerMapping.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationProcessorHelper.java

https://hibernate.atlassian.net//browse/HSEARCH-3587
Based on #1991 , which should be merged first.

HSEARCH-3587 Rename MarkerMapping#builder to MarkerMapping#marker

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ToElasticsearch.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/ConnectedMultiFieldsTermQueryBuilder.java
engine/src/main/java/org/hibernate/search/query/dsl/impl/RemoteMatchQuery.java
integrationtest/elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchDSLIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3545

HSEARCH-3545 Handle prefix_length fuzzy queries option for ES

---

integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/nonregression/mapping/definition/IndexedEmbeddedDepthIT.java

https://hibernate.atlassian.net/browse/HSEARCH-1467

HSEARCH-1467 Test IndexedEmbedded with different depths

---

documentation/src/main/asciidoc/backend-elasticsearch.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-3586

HSEARCH-3586 Document BigDecimal BigInteger ES field type format

---

mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/MassIndexer.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/MassIndexerImpl.java

https://hibernate.atlassian.net/browse/HSEARCH-2539

HSEARCH-1467 Make MassIndexer#start return a CompletableFuture

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/ElasticsearchFieldSortBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/AbstractElasticsearchJavaTimeFieldCodec.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchFieldCodec.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchInstantFieldCodec.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchLocalDateFieldCodec.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchLocalDateTimeFieldCodec.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchLocalTimeFieldCodec.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchMonthDayFieldCodec.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchOffsetDateTimeFieldCodec.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchOffsetTimeFieldCodec.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchYearFieldCodec.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchYearMonthFieldCodec.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchZonedDateTimeFieldCodec.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSearchSortIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java

https://hibernate.atlassian.net/browse/HSEARCH-3255

HSEARCH-3255 Introduce encode for sort missing java.time types

---

backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3592

HSEARCH-3592 Upgrade to Elasticsearch 7.1

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3580

HSEARCH-3580 Upgrade to Byteman 4.0.7 (branch 5.11)

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/impl/LuceneTextFieldSortBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/missing/impl/LuceneMissingValueComparatorSource.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/missing/impl/LuceneReplaceMissingSortedDocValues.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSearchSortIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/NormalizedStringFieldTypeDescriptor.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/assertion/SearchHitAssert.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/assertion/SearchHitsAssert.java

https://hibernate.atlassian.net/browse/HSEARCH-3254

HSEARCH-3254 Handle .onMissingValue().use() properly for string fields in Lucene

---

README.md
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/model/impl/Elasticsearch6ModelDialect.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch67ProtocolDialect.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/CreateIndexWork.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/DeleteWork.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/GetIndexTypeMappingWork.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/IndexExistsWork.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/IndexWork.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/PutIndexTypeMappingWork.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3611
Tested on 6.8 here: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-yoann/detail/HSEARCH-3611/5/pipeline/52

HSEARCH-3611 Add support for Elasticsearch 6.8

---

build-config/src/main/resources/forbidden-runtime.txt
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingEmbeddedIdIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/BytecodeEnhancementIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/IdentifierConsumerDocumentProducer.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/IdentifierProducer.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchQueryAdapter.java
pom.xml
util/internal/integrationtest/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/orm/OrmSetupHelper.java
util/internal/integrationtest/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/orm/SimpleSessionFactoryBuilder.java

https://hibernate.atlassian.net/browse/HSEARCH-3074

HSEARCH-3074 Avoid depending on internal Hibernate ORM types

---

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/decimalscale/DecimalScaleIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SearchPredicateIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryBaseIT.java

https://hibernate.atlassian.net//browse/HSEARCH-3626

HSEARCH-3626 Fix order requirements in various backend integration tests

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3627

HSEARCH-3627 Upgrade to Elasticsearch 6.8.1

---

backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3625

HSEARCH-3625 Upgrade to Elasticsearch 7.2.0

---

documentation/src/main/asciidoc/mapper-orm-mapping.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/searchdsl/predicate/Author.java
documentation/src/test/java/org/hibernate/search/documentation/searchdsl/projection/Author.java
documentation/src/test/java/org/hibernate/search/documentation/searchdsl/sort/Author.java
engine/src/main/java/org/hibernate/search/engine/cfg/spi/ParseUtils.java
engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java
engine/src/test/java/org/hibernate/search/engine/cfg/spi/ParseUtilsTest.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/GeoPointPropertyTypeDescriptor.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/PropertyTypeDescriptor.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/mapping/impl/BridgeResolver.java

https://hibernate.atlassian.net/browse/HSEARCH-3607

HSEARCH-3607 Support GeoPoint property without the need of a bridge or a binder

---

build-config/src/main/resources/forbidden-runtime.txt
engine/src/main/java/org/hibernate/search/engine/impl/WorkPlan.java
engine/src/main/java/org/hibernate/search/engine/spi/AbstractDocumentBuilder.java
orm/src/test/java/org/hibernate/search/test/embedded/ContainedInMultiTenancyTest.java

https://hibernate.atlassian.net//browse/HSEARCH-3647

[5.11] HSEARCH-3647 Search result lost after Session.merge on a child entity when using Multi-Tenancy

---

pom.xml

https://hibernate.atlassian.net//browse/HSEARCH-3648

HSEARCH-3648 Upgrade to Hibernate ORM 5.4.4

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/execution/impl/ElasticsearchIndexWorkPlan.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/execution/impl/LuceneIndexWorkPlan.java
documentation/src/main/asciidoc/mapper-orm-indexing-automatic.asciidoc
engine/src/main/java/org/hibernate/search/engine/backend/work/execution/spi/IndexWorkPlan.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexWorkPlanIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingBasicIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/impl/PostTransactionWorkQueueSynchronization.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoIndexedTypeWorkPlan.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoWorkPlanImpl.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/work/spi/PojoWorkPlan.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/BackendMock.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/DocumentWorkCall.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/VerifyingStubBackendBehavior.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/StubBackendBehavior.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/index/impl/StubIndexManager.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/index/impl/StubIndexWorkPlan.java

https://hibernate.atlassian.net/browse/HSEARCH-3075

HSEARCH-3075 Release WorkPlan resources when a transaction is rolled back

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingOutOfTransactionIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/event/impl/HibernateOrmListenerContextProvider.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/event/impl/HibernateSearchEventListener.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMapping.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/impl/HibernateOrmSearchSession.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/impl/SearchSessionWritePlanImpl.java

https://hibernate.atlassian.net/browse/HSEARCH-3068
Based on #2054

HSEARCH-3068 Restore support for "simulated" transaction using a Flush listener

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3663

Backport HSEARCH-3663 to branch 5.10 - Upgrade to Hibernate ORM Hibernate ORM 5.3.11.Final

---

backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3660

HSEARCH-3660 Upgrade to Elasticsearch 7.3.0

---

engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationBuilderImpl.java
engine/src/main/java/org/hibernate/search/engine/mapper/mapping/building/spi/TypeMetadataContributorProvider.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/mapping/definition/AnnotationMappingDiscoveryIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/AnnotationMappingDiscoveryIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/impl/PojoMapper.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationMappingConfigurationContextImpl.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationPojoTypeMetadataContributorFactory.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/PropertyAnnotationProcessor.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/TypeAnnotationProcessor.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/additionalmetadata/building/impl/PojoTypeAdditionalMetadataProvider.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/processing/building/impl/PojoIndexingProcessorTypeNodeBuilder.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/processing/building/impl/PojoIndexingProcessorValueNodeBuilderDelegate.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/mapper/StubMapper.java

https://hibernate.atlassian.net/browse/HSEARCH-899

HSEARCH-899 Check for illegal usage of @IndexedEmbedded

---

integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/LibraryShowcaseTransactionIT.java
integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/service/InnerTransactionRollbackService.java

https://hibernate.atlassian.net/browse/HSEARCH-1270

HSEARCH-1270 Test nested transaction flush and rollback

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3648

HSEARCH-3648 Upgrade to Hibernate ORM 5.4.4 (branch 5.11)

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-3697

HSEARCH-3697 Test Hibernate Search on JDK13 regularly on the CI

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3702

HSEARCH-3702 Upgrade to JBoss logging 3.4.0.Final

---

distribution/pom.xml
documentation/src/main/asciidoc/configuration.asciidoc
integrationtest/wildfly/pom.xml
integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/elasticsearch/ElasticsearchModuleMemberRegistrationIT.java
pom.xml

* [HSEARCH-3701](https://hibernate.atlassian.net/browse/HSEARCH-3701): Upgrade to WildFly 17.0.1.Final
* [HSEARCH-3702](https://hibernate.atlassian.net/browse/HSEARCH-3702): Upgrade to JBoss logging 3.4.0.Final

HSEARCH-3701 + HSEARCH-3702 : Upgrade to WildFly 17.0.1.Final

---

documentation/src/main/asciidoc/getting-started.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-3704

HSEARCH-3704 Use less alarming wording in warnings about 6 being work in progress

---

documentation/src/main/asciidoc/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/getting-started.asciidoc
documentation/src/main/asciidoc/mapper-orm-indexing-automatic.asciidoc
documentation/src/main/asciidoc/mapper-orm-indexing-jsr352.asciidoc
documentation/src/main/asciidoc/mapper-orm-indexing-manual.asciidoc
documentation/src/main/asciidoc/mapper-orm-indexing-massindexer.asciidoc
documentation/src/main/asciidoc/mapper-orm-indexing-optimizing.asciidoc
documentation/src/main/asciidoc/mapper-orm-indexing.asciidoc
documentation/src/main/asciidoc/mapper-orm-mapping.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexing/HibernateOrmManualIndexingIT.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexing/HibernateOrmMassIndexerIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3681
~Based on #2075, which should be merged first.~ => Done

HSEARCH-3681 Document MassIndexer

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/lowlevel/impl/FacetCountsUtils.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/search/LuceneFloatingPointInfinitySearchIT.java
util/common/src/main/java/org/hibernate/search/util/common/data/Range.java

https://hibernate.atlassian.net/browse/HSEARCH-3685

HSEARCH-3685 Always include -Infinity/+Infinity in Range.of

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3706

Backport HSEARCH-3706 to branch 5.11 - Upgrade to Hibernate ORM 5.4.5.Final

---

documentation/src/main/asciidoc/mapper-orm-mapping.asciidoc
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FieldDefaultBridgeIT.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/JavaSqlDatePropertyTypeDescriptor.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/JavaSqlTimePropertyTypeDescriptor.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/JavaSqlTimestampPropertyTypeDescriptor.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/JavaUtilDatePropertyTypeDescriptor.java
integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/expectations/DefaultValueBridgeExpectations.java
mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultJavaUtilDateValueBridge.java

https://hibernate.atlassian.net/browse/HSEARCH-3670

HSEARCH-3670 Handle sql.Date in DefaultJavaUtilDateValueBridge

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/mapping/SearchMappingIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/SearchMapping.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMapping.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateSearchContextProviderService.java

https://hibernate.atlassian.net/browse/HSEARCH-3640

HSEARCH-3640 Support get indexes/backend from mapper orm

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/MappedSuperclassIT.java

https://hibernate.atlassian.net/browse/HSEARCH-1108
I hope I got the right test case.

HSEARCH-1108 Test programmatic API @MappedSuperclass full text field

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3730

HSEARCH-3730 Upgrade to Hibernate ORM 5.4.6

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3730

Backport HSEARCH-3730 to branch 5.11 - Upgrade to Hibernate ORM 5.4.6

---

engine/src/main/java/org/hibernate/search/engine/backend/orchestration/spi/BatchingExecutor.java

https://hibernate.atlassian.net/browse/HSEARCH-3733
This should fix the problem where integration tests are stuck in an infinite wait.
I couldn't find a way to write a non-regression test, but locally executing `FieldSearchSortIT` with the Elasticsearch backend, execution hanged after ~200 executions before the batch, and not at all even after ~1000 executions after the patch.

HSEARCH-3733 BatchExecutor sometimes forgets to schedule the processor since HSEARCH-3084

---

backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3723

HSEARCH-3723 Upgrade to Elasticsearch 7.4.0

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3731

HSEARCH-3731 Upgrade to Hibernate ORM 5.3.13.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3724

HSEARCH-3724 Upgrade to Jackson 2.9.10

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3742

HSEARCH-3742 Upgrade to Hibernate ORM 5.4.7.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3742
Backport of #2130 

Backport HSEARCH-3742 to branch 5.11 - Upgrade to Hibernate ORM 5.4.7.Final

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/IndexManagerBackendContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessor.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/HibernateSearchConcurrentMergeScheduler.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/IndexWriterDelegatorImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/orchestration/impl/LuceneWriteWorkProcessor.java
backend/lucene/src/test/java/org/hibernate/search/backend/lucene/orchestration/impl/LuceneWriteWorkProcessorTest.java
engine/src/main/java/org/hibernate/search/engine/reporting/IndexFailureContext.java
engine/src/main/java/org/hibernate/search/engine/reporting/impl/LogFailureHandler.java

https://hibernate.atlassian.net/browse/HSEARCH-3741
~Based on #2125 , which should be merged first.~ => Done

HSEARCH-3741 Expose the index name in IndexFailureContext

---

Jenkinsfile

* [HSEARCH-3716](https://hibernate.atlassian.net/browse/HSEARCH-3716): Mitigate test failures caused by automatic snapshots of AWS-managed Elasticsearch service
* [HSEARCH-3732](https://hibernate.atlassian.net/browse/HSEARCH-3732): Add a timeout to the Jenkins build configuration
Just need a full build and I'll merge. I checked manually that the change do what they are supposed to do.

HSEARCH-3716 + HSEARCH-3732 Build stability improvements

---

documentation/pom.xml
documentation/src/main/asciidoc/index.asciidoc
documentation/src/main/asciidoc/search-dsl.asciidoc
legacy/documentation/src/main/asciidoc/query.asciidoc
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3750

HSEARCH-3750 Use auto-expanding entries in the documentation TOC

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/SearchWork.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/directory/impl/FileSystemUtils.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearcherImpl.java
engine/src/main/java/org/hibernate/search/engine/Version.java
engine/src/main/java/org/hibernate/search/engine/backend/orchestration/spi/BatchingExecutor.java
engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/mapping/SearchMappingBuilder.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateSearchIntegrator.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMapping.java

https://hibernate.atlassian.net/browse/HSEARCH-3693

HSEARCH-3693 Restore missing log messages from Search 5 in Search 6

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3754

HSEARCH-3754 Upgrade to Hibernate ORM 5.4.8.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3754

HSEARCH-3754 (branch 5.11) Upgrade to Hibernate ORM 5.4.8.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3758

HSEARCH-3758 Upgrade to Lucene 8.3.0

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/dsl/ElasticsearchSearchAggregationFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/dsl/impl/ElasticsearchJsonStringAggregationFinalStep.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/dsl/impl/ElasticsearchSearchAggregationFactoryImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/AbstractElasticsearchAggregation.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/AbstractElasticsearchBucketAggregation.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchSearchAggregationBuilderFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchUserProvidedJsonAggregation.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicateBuilderFactoryImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchUserProvidedJsonPredicateBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/dsl/ElasticsearchSearchSortFactory.java
build-config/src/main/resources/forbidden-tests.txt
documentation/src/main/asciidoc/search-dsl.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/aggregation/AggregationDslIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/ElasticsearchExtensionIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchClientSubmitCall.java

https://hibernate.atlassian.net/browse/HSEARCH-3662

HSEARCH-3662 Define aggregations from JSON with Elasticsearch

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3760

HSEARCH-3760 on branch 5.10 - Upgrade to Hibernate ORM 5.3.14.Final

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/ElasticsearchSearchResult.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/Elasticsearch7SearchResultExtractor.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchLoadableSearchResult.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchResultImpl.java
documentation/src/main/asciidoc/search-dsl.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/query/QueryDslIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/ElasticsearchExtensionIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3456

Hsearch 3456 Expose meta-information about the query execution (execution time, timeout, ...)

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3768
Waiting for CI and I will merge.

HSEARCH-3768 Upgrade to Byteman 4.0.9

---

integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3780

HSEARCH-3780 Fix random failures in ElasticsearchClientFactoryImplIT

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3770

HSEARCH-3770 Upgrade to elasticsearch-maven-plugin 6.15

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3781

HSEARCH-3781 Upgrade to Hibernate ORM 5.4.10.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3781

Backport HSEARCH-3781 to branch 5.11 - Upgrade to Hibernate ORM 5.4.10.Final

---

mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/HibernateOrmMappingConfigurationContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/extractor/ContainerExtractor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/extractor/ContainerExtractorConfigurationContext.java

https://hibernate.atlassian.net/browse/HSEARCH-3753

HSEARCH-3753 Mark the ContainerExtractor API as experimental

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/TransientPropertyIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmPathFilterFactory.java

https://hibernate.atlassian.net/browse/HSEARCH-3634

HSEARCH-3634 Clarify the error message when a @Transient property is missing a @IndexingDependency annotation

---

backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3782
Already built on CI: it works

HSEARCH-3782 Upgrade to Elasticsearch 7.5.0

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3790

HSEARCH-3790 Upgrade to Elasticsearch 5.6.16

---

documentation/src/main/asciidoc/mapper-orm-mapping.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-1828

HSEARCH-1828 Clarify documentation about ways to disable Hibernate Search

---

engine/src/main/java/org/hibernate/search/engine/Version.java
engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/BootstrapLogsIT.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/mapping/SearchMappingBuilder.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateSearchIntegrator.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-3795

HSEARCH-3795 Get rid of Version.logVersion()

---

documentation/src/main/asciidoc/search-dsl-predicate.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/predicate/Address.java
documentation/src/test/java/org/hibernate/search/documentation/search/predicate/Author.java
documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3793

HSEARCH-3793 Document usage of the "exists" predicate on object fields

---

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSearchSortIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3798

HSEARCH-3798 Test sorting on numeric fields without specifying missing value behavior

---

integrationtest/mapper/orm-cdi/pom.xml
integrationtest/mapper/orm-cdi/src/test/java/org/hibernate/search/integrationtest/mapper/orm/cdi/CdiIT.java
integrationtest/pom.xml
legacy/integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/cdi/CDIInjectionIT.java
legacy/integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/cdi/CDIInjectionLifecycleEventsIT.java
pom.xml
reports/pom.xml
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/BackendMock.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/ParameterizedCallBehavior.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/VerifyingStubBackendBehavior.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/StubBackendBehavior.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/index/impl/StubBackend.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/index/impl/StubBackendFactory.java

https://hibernate.atlassian.net/browse/HSEARCH-3171

HSEARCH-3171 Test using CDI beans referenced by their name

---

integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckBackendAccessor.java

https://hibernate.atlassian.net/browse/HSEARCH-3746
Will merge after the build.
I checked manually that this fixes tests expecting I/O failures on Windows.

HSEARCH-3746 IndexWorkspacePurgeIT fails on windows

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/util/impl/SloppyMath.java
pom.xml

* [HSEARCH-3799](https://hibernate.atlassian.net/browse/HSEARCH-3799): Upgrade to Lucene 8.4.1
* [HSEARCH-3817](https://hibernate.atlassian.net/browse/HSEARCH-3817): Upgrade to Elasticsearch 7.5.2

HSEARCH-3799 + HSEARCH-3817 Upgrade to Lucene 8.4.1/ES 7.5.2

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3806

Backport HSEARCH-3806 to branch 5.10 - Upgrade to Byteman 4.0.10

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3806

HSEARCH-3806 - branch 5.11 - Upgrade to Byteman 4.0.10

---

mapper/javabean/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3815

HSEARCH-3815 Stop publishing the mapper-javabean module

---

build-config/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3818
Nothing important, I'll merge as soon as the CI build passes.

HSEARCH-3818 Upgrade to checkstyle 8.29

---

engine/src/main/java/org/hibernate/search/engine/search/sort/dsl/SearchSortFactory.java

This is related to  HSEARCH-3721 changed by e9aac57256e8138d1ebdf97fdf4cbc0dea124755
The documentation was not updated at that point

SearchSortFactory documentation update

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3830

HSEARCH-3830 Upgrade to Hibernate ORM 5.4.12.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3832

HSEARCH-3832 Upgrade to Hibernate ORM 5.3.15.Final

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/directory/impl/DirectoryProviderInitializationContextImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/directory/impl/LocalFileSystemDirectoryHolder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/directory/impl/LocalFileSystemDirectoryProvider.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/directory/impl/LocalHeapDirectoryProvider.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/directory/spi/DirectoryProviderInitializationContext.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/search/LuceneSearchMultiIndexIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3833

HSEARCH-3833 Writing on different local-heap indexes will provoke LockObtainFailedException

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/BootstrapLogsIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-3828

HSEARCH-3828 Change the format of the version logged on boot

---

backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/index/admin/ElasticsearchIndexValidationAnalyzerIT.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3829

HSEARCH-3829 Upgrade to Elasticsearch 7.6

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3837

HSEARCH-3837 Fix dependency convergence error caused by the ES client dependency

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/index/impl/IndexManagerBackendContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/query/Queries.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/query/impl/Queries.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/multitenancy/impl/DiscriminatorMultiTenancyStrategy.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/multitenancy/impl/MultiTenancyStrategy.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/multitenancy/impl/NoMultiTenancyStrategy.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/impl/ElasticsearchSearchContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/execution/impl/ElasticsearchIndexWorkspace.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/AbstractLuceneDocumentBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/AbstractLuceneNonFlattenedDocumentBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneIndexEntryFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneNestedObjectDocumentBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneRootDocumentBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/common/impl/MetadataFields.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/query/impl/Queries.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/multitenancy/impl/MultiTenancyStrategy.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/execution/impl/LuceneIndexIndexer.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/execution/impl/LuceneIndexIndexingPlan.java
documentation/src/main/asciidoc/backend-lucene.asciidoc
documentation/src/main/asciidoc/concepts.asciidoc
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/sharding/ShardingExplicitIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/sharding/AbstractShardingIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/sharding/AbstractShardingRoutingKeyIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/sharding/ShardingDisabledRoutingKeyIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/sharding/ShardingHashDocumentIdIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/sharding/ShardingHashRoutingKeyIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3824

HSEARCH-3824 Automatically filter search results based on provided routing keys

---

lgtm.yml

HSEARCH-3837 Follow-up: LGTM configuration

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch64ProtocolDialect.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch67ProtocolDialect.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/syntax/search/impl/Elasticsearch60SearchSyntax.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/syntax/search/impl/Elasticsearch64SearchSyntax.java

https://hibernate.atlassian.net/browse/HSEARCH-3838

HSEARCH-3838 Use an explicit format for docvalue projections on ES 6.6

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchLinkImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
documentation/src/main/asciidoc/backend-elasticsearch.asciidoc
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3841
new settings added to get rid of the version check at start in some cases.

HSEARCH-3841 new version_check.enabled setting added

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/ElasticsearchSearchRequestTransformer.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/ElasticsearchSearchRequestTransformerContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/ElasticsearchSearchResult.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/dsl/ElasticsearchSearchQueryOptionsStep.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/HibernateOrmMappingConfigurationContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/IdentifierBindingContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/PropertyBindingContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/RoutingKeyBindingContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/TypeBindingContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/ValueBindingContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/extractor/ContainerExtractor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/extractor/ContainerExtractorConfigurationContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/RoutingKeyBinding.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/PojoElementAccessor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/PojoModelCompositeElement.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/PojoModelElement.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/PojoModelProperty.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/PojoModelType.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/PojoModelValue.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/dependency/PojoOtherEntityIndexingDependencyConfigurationContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/dependency/PojoPropertyIndexingDependencyConfigurationContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/dependency/PojoTypeIndexingDependencyConfigurationContext.java
util/common/src/main/java/org/hibernate/search/util/common/annotaion/Incubating.java

https://hibernate.atlassian.net/browse/HSEARCH-3814
I've adapted the one from Hibernate Validator.

HSEARCH-3814 Mark experimental APIs/SPIs with an @Incubating annotation

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneSimpleQueryStringPredicateBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneStringFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/impl/LuceneStringIndexFieldTypeOptionsStep.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/impl/LuceneIndexFieldType.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneSimpleQueryStringPredicateBuilderFieldState.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextMatchPredicateBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextPhrasePredicateBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextWildcardPredicateBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/parse/impl/LuceneWildcardExpressionHelper.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/PhraseSearchPredicateIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SimpleQueryStringSearchPredicateIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/WildcardSearchPredicateIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3844

HSEARCH-3844 Exception: null: java.lang.NullPointerException when use simpleQueryString()

---

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/spatial/MultivaluedSpatialIT.java

https://hibernate.atlassian.net/browse/HSEARCH-2859

HSEARCH-2859 Test multivalued spacial field

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/IndexedEmbedded.java

https://hibernate.atlassian.net/browse/HSEARCH-3796

HSEARCH-2859 Allow repeated @IndexedEmbedded

---

.gitignore
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSimpleQueryStringPredicateBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneSimpleQueryStringPredicateBuilder.java
documentation/src/main/asciidoc/search-dsl-predicate.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/SimpleQueryFlag.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/SimpleQueryStringPredicateOptionsStep.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/SimpleQueryStringPredicateFieldMoreStepImpl.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/SimpleQueryStringPredicateBuilder.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SimpleQueryStringSearchPredicateIT.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubPredicateBuilder.java

https://hibernate.atlassian.net/browse/HSEARCH-3847
Waiting for CI, but if it works, let's merge.

HSEARCH-3847 Customize enabled syntax elements in simple query strings

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/schema/management/impl/ElasticsearchIndexSchemaManager.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/schema/management/impl/LuceneIndexSchemaManager.java
documentation/src/main/asciidoc/mapper-orm-mapping.asciidoc
documentation/src/main/asciidoc/mapper-orm-schema.asciidoc
engine/src/main/java/org/hibernate/search/engine/backend/schema/management/spi/IndexSchemaManager.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerOperation.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationOperation.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/schema/management/LuceneIndexSchemaManagerOperation.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/HibernateOrmIntegrationBooterIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/schema/management/manager/SearchSchemaManagerCreateOrValidateIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/schema/management/strategy/SchemaManagementStrategyCreateOrValidateIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/schema/management/strategy/SchemaManagementStrategyDefaultIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/cfg/HibernateOrmMapperSettings.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/schema/management/SchemaManagementStrategyName.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/schema/management/SearchSchemaManager.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/schema/management/impl/SchemaManagementListener.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/schema/management/impl/SearchSchemaManagerImpl.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/schema/management/impl/PojoScopeSchemaManagerImpl.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/schema/management/spi/PojoScopeSchemaManager.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/index/StubSchemaManagementWork.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/index/impl/StubIndexSchemaManager.java

https://hibernate.atlassian.net/browse/HSEARCH-3849
Based on #2230, which should be merged first.

HSEARCH-3849 Create-or-validate schema management by default

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryBuilder.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/search/query/ElasticsearchSearchQueryIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3861

HSEARCH-3861 Elasticsearch search queries fetch the whole document source by default

---

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/DistanceSearchSortBaseIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3860
Just some problems I noticed while working on something else. Will merge as soon as CI passes.

HSEARCH-3860 Follow-up Refactor FieldSearchSortIT to enable testing more complex cases

---

integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckBackendAccessor.java

https://hibernate.atlassian.net/browse/HSEARCH-3865

HSEARCH-3865 Clean up any change to the permission of index files during tests

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/dynamicmap/DynamicMapBaseIT.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/model/impl/JavaBeanBootstrapIntrospector.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/model/impl/JavaBeanTypeModel.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmBootstrapIntrospector.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmClassRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnBootstrapIntrospector.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/PojoXClassOrdering.java
util/common/src/main/java/org/hibernate/search/util/common/reflect/spi/AbstractTypeOrdering.java

https://hibernate.atlassian.net/browse/HSEARCH-3848

HSEARCH-3848 Dynamic entities are ignored when creating a scope targeting Object.class

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/AbstractSimpleElasticsearchWork.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/BulkWork.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/work/impl/BulkWorkTest.java

https://hibernate.atlassian.net/browse/HSEARCH-3869

HSEARCH-3869 java.lang.IndexOutOfBoundsException when an Elasticsearch bulk work fails

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cfg/LuceneIndexSettings.java
documentation/src/main/asciidoc/backend-lucene.asciidoc
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/AbstractIndexWorkspaceSimpleOperationIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexWorkspacePurgeIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexWorkspaceRefreshIT.java
integrationtest/performance/backend/lucene/src/main/java/org/hibernate/search/integrationtest/performance/backend/lucene/testsupport/LuceneBackendHolder.java

https://hibernate.atlassian.net/browse/HSEARCH-3871
~Based on #2249 , which should be merged first.~ => Done

HSEARCH-3871 Always enable delayed commits in the Lucene backend

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/nonregression/model/IdClassIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DocumentIdBaseIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmEntityTypeMetadataContributor.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMetatadaContributor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-3874

HSEARCH-3874 @IdClass, even not @Indexed, leads to NPE on bootstrap

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchIndexSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/index/impl/ElasticsearchIndexManagerImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchBatchingWorkOrchestrator.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchDefaultWorkSequenceBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchSimpleWorkOrchestrator.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/resources/impl/BackendThreads.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchDefaultWorkSequenceBuilderTest.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cfg/LuceneBackendSettings.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cfg/LuceneIndexSettings.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/IndexManagerBackendContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/Shard.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/ShardHolder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/ShardingStrategyInitializationContextImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/orchestration/impl/LuceneParallelWorkOrchestratorImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/orchestration/impl/LuceneSerialWorkOrchestratorImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/orchestration/impl/LuceneSyncWorkOrchestratorImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/resources/impl/BackendThreads.java
documentation/src/main/asciidoc/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/backend-lucene.asciidoc
engine/src/main/java/org/hibernate/search/engine/backend/orchestration/spi/AbstractWorkOrchestrator.java

https://hibernate.atlassian.net/browse/HSEARCH-3575

HSEARCH-3575 Add configuration options for the size of workset queues, workset batches and Elasticsearch bulks

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchIndexSettings.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cfg/LuceneBackendSettings.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cfg/LuceneIndexSettings.java
documentation/src/main/asciidoc/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/backend-lucene.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-3879
Following Sanne's remarks on https://github.com/quarkusio/quarkus/pull/8328.

HSEARCH-3879 Clarify documentation of thread pool and indexing settings

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/impl/AbstractLuceneStandardFieldSortBuilder.java
documentation/src/main/asciidoc/search-dsl-sort.asciidoc
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSearchSortBaseIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3886

HSEARCH-3886 Missing values should be last by default in field sorts

---

documentation/src/main/asciidoc/search-dsl-query.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-3887

HSEARCH-3887 Update documentation about routing in the Search DSL

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryRequestContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryRequestContext.java
engine/src/main/java/org/hibernate/search/engine/search/loading/context/spi/LoadingContext.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryResultLoadingOrTransformingIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/stub/MapperEasyMockUtils.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/SearchQueryBaseIT.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/search/loading/context/impl/JavaBeanLoadingContext.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/context/impl/HibernateOrmLoadingContext.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/SearchWorkCall.java
util/internal/integrationtest/mapper/stub/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/stub/StubLoadingContext.java

https://hibernate.atlassian.net/browse/HSEARCH-3896

HSEARCH-3896 Verify multiple loading with the DefaultProjectionHitMapper on the same query instance

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3907
Will merge as soon as CI passes.

HSEARCH-3907 Upgrade to Hibernate ORM 5.4.15.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3908
Will merge as soon as CI passes.

HSEARCH-3908 Upgrade to Hibernate ORM 5.3.17.Final

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/LuceneSearchQuery.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/LuceneSearchResult.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneLoadableSearchResult.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchResultImpl.java
documentation/src/main/asciidoc/search-dsl-query.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/query/Book.java
documentation/src/test/java/org/hibernate/search/documentation/search/query/QueryDslIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneExtensionIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/search/LuceneSearchTopDocsMergeFieldSortIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/search/LuceneSearchTopDocsMergeScoreSortIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3911
https://hibernate.atlassian.net/browse/HSEARCH-3914

HSEARCH-3911 + HSEARCH-3914 Expose TopDocs and Sort in Lucene queries

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/index/mapping/impl/DynamicTemplateJsonAdapterFactory.java

https://hibernate.atlassian.net/browse/HSEARCH-3916

HSEARCH-3916 DynamicTemplateJsonAdapterFactory should be public

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/BytecodeEnhancementIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmBootstrapIntrospector.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmClassPropertyModel.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmClassRawTypeModel.java

https://hibernate.atlassian.net/browse/HSEARCH-3584

HSEARCH-3584 Support ORM bytecode enhancement when embeddables, mapped superclasses or entity hierarchies are involved

---

documentation/src/main/asciidoc/mapper-orm-mapping.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/reindexing/associationinverseside/Book.java
engine/src/main/java/org/hibernate/search/engine/backend/common/spi/FieldPaths.java
engine/src/main/java/org/hibernate/search/engine/backend/document/model/dsl/impl/IndexSchemaElementImpl.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/smoke/AnnotationMappingSmokeIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/smoke/ProgrammaticMappingSmokeIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FullTextFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/GenericFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/KeywordFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/NonStandardFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ScaledNumberFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/smoke/AnnotationMappingSmokeIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/smoke/ProgrammaticMappingSmokeIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/IndexedEmbedded.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/IndexedEmbeddedProcessor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/PropertyMappingIndexedEmbeddedStep.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/PropertyMappingStep.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/AbstractPropertyMappingFieldOptionsStep.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/DelegatingPropertyMappingStep.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/InitialPropertyMappingStep.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/PropertyMappingIndexedEmbeddedStepImpl.java

https://hibernate.atlassian.net/browse/HSEARCH-3097

HSEARCH-3097 Deprecate the IndexedEmbedded "prefix" feature

---

mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/FullTextField.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/PropertyMappingFullTextFieldOptionsStep.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/PropertyMappingNonFullTextFieldOptionsStep.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/PropertyMappingStandardFieldOptionsStep.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/AbstractPropertyMappingNonFullTextStandardFieldOptionsStep.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/AbstractPropertyMappingStandardFieldOptionsStep.java

https://hibernate.atlassian.net/browse/HSEARCH-3913

HSEARCH-3913 @FullTextField.aggregable doesn't do anything

---

documentation/src/main/asciidoc/search-dsl-query.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/query/Manager.java
documentation/src/test/java/org/hibernate/search/documentation/search/query/QueryDslIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToHibernateOrmIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToJpaIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/BytecodeEnhancementIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/AbstractSearchQueryEntityLoadingIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/AbstractSearchQueryEntityLoadingSingleTypeIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingBaseIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingCacheLookupIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingFetchSizeIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingGraphIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/model/singletype/EntityIdDocumentIdContainedEntity.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/model/singletype/EntityIdDocumentIdIndexedEntity.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/model/singletype/NonEntityIdDocumentIdContainedEntity.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/model/singletype/NonEntityIdDocumentIdIndexedEntity.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/context/impl/HibernateOrmLoadingContext.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/dsl/SearchLoadingOptionsStep.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/EntityGraphHint.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/EntityLoaderBuilder.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/HibernateOrmEntityIdEntityLoader.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/HibernateOrmNonEntityIdPropertyEntityLoader.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/MutableEntityLoadingOptions.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchQueryAdapter.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/BackendMock.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/ManagedAssert.java

https://hibernate.atlassian.net/browse/HSEARCH-3628

HSEARCH-3628 Finer loading options in search queries (fetch graph, ...)

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingInterruptionIT.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/VerifyingStubBackendBehavior.java

https://hibernate.atlassian.net/browse/HSEARCH-3933

HSEARCH-3933 Fix reset expectations and verify expectations met for the stub backend

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/common/impl/MetadataFields.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/projection/impl/LuceneFieldProjection.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneBigDecimalFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneBigIntegerFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneBooleanFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneByteFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneDoubleFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneFieldFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneFloatFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneGeoPointFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneInstantFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneIntegerFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneLocalDateFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneLocalDateTimeFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneLocalTimeFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneLongFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneMonthDayFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneOffsetDateTimeFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneOffsetTimeFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneShortFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneStringFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneYearFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneYearMonthFieldCodec.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneZonedDateTimeFieldCodec.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneExtensionIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/DocumentAssert.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckTestRunner.java

https://hibernate.atlassian.net/browse/HSEARCH-3939

HSEARCH-3939 Use a single field for GeoPoint storage in Lucene

---

engine/src/main/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyChecker.java
engine/src/main/java/org/hibernate/search/engine/cfg/spi/HibernateSearch5Properties.java
engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchContentLengthIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendSetupStrategy.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckBackendSetupStrategy.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendSetupStrategy.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/rule/SearchSetupHelper.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/ObsoletePropertiesIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3266

HSEARCH-3266 Ensure Hibernate Search 5 configuration files will make bootstrap fail in 6

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3957

HSEARCH-3957 Upgrade to Hibernate ORM 5.4.18.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3957

Backport HSEARCH-3957 to branch 5.11 - Upgrade to Hibernate ORM 5.4.18.Final

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/validation/impl/ElasticsearchValidationMessages.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/validation/impl/ValidationErrorCollector.java
engine/src/main/java/org/hibernate/search/engine/reporting/impl/EngineEventContextMessages.java
engine/src/main/java/org/hibernate/search/engine/reporting/spi/EventContexts.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerTestUtils.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationAliasesIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationAnalyzerIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationMappingAttributeIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationMappingBaseIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationMappingFieldTemplateIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationNormalizerIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationOperation.java

https://hibernate.atlassian.net/browse/HSEARCH-3960

HSEARCH-3960 Validation failure messages should mention that they are related to Elasticsearch schema validation

---

documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/reference/backend-lucene.asciidoc
documentation/src/main/asciidoc/reference/getting-started.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-3262
Follows up on https://github.com/hibernate/hibernate.org/pull/151

HSEARCH-3262 Add Elasticsearch compatibility policy to the documentation and/or website

---

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/SearchSortIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3961

HSEARCH-3961 Test the default sort

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/common/timing/impl/DefaultTimingSource.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/common/timing/impl/TimingSource.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/IndexManagerBackendContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/NearRealTimeIOStrategy.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/reader/impl/NearRealTimeIndexReaderProvider.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/HibernateSearchConcurrentMergeScheduler.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/IndexWriterDelegatorImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/IndexWriterProvider.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/resources/impl/BackendThreads.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/impl/LuceneSearchContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/timeout/impl/DefaultTimingSource.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/timeout/impl/LuceneCounterAdapter.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/timeout/impl/TimeoutManager.java
engine/src/main/java/org/hibernate/search/engine/environment/thread/impl/DefaultThreadProvider.java
engine/src/main/java/org/hibernate/search/engine/environment/thread/impl/SimpleThreadFactory.java

https://hibernate.atlassian.net/browse/HSEARCH-3970

HSEARCH-3970 Clean up timing-related code

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/directory/FileSystemAccessStrategyName.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/directory/impl/FileSystemAccessStrategy.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/directory/impl/LocalFileSystemDirectoryProvider.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/HibernateSearchConcurrentMergeScheduler.java
documentation/src/main/asciidoc/reference/backend-lucene.asciidoc
engine/src/test/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolderTest.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/directory/LuceneLocalFileSystemDirectoryIT.java
integrationtest/mapper/orm-cdi/src/test/java/org/hibernate/search/integrationtest/mapper/orm/cdi/CdiExtendedBeanManagerBootstrapShutdownIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/ShutdownFailureIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/UnusedPropertiesIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingCacheLookupIT.java
integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/LibraryShowcaseMassIndexingIT.java
pom.xml
util/internal/test/src/main/java/org/hibernate/search/util/impl/test/rule/ExpectedLog4jLog.java

https://hibernate.atlassian.net/browse/HSEARCH-3965

HSEARCH-3965 Upgrade to Lucene 8.6.0

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/ElasticsearchSearchQuery.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/ElasticsearchSearchScroll.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/ElasticsearchSearchScrollResult.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/dsl/impl/ElasticsearchSearchQueryOptionsStepImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchScrollImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchScrollResultImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/LuceneSearchQuery.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/LuceneSearchScroll.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/LuceneSearchScrollResult.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/dsl/impl/LuceneSearchQueryOptionsStepImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchScrollImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchScrollResultImpl.java
engine/src/main/java/org/hibernate/search/engine/search/query/ExtendedSearchFetchable.java
engine/src/main/java/org/hibernate/search/engine/search/query/ExtendedSearchScroll.java
engine/src/main/java/org/hibernate/search/engine/search/query/dsl/spi/AbstractExtendedSearchQueryOptionsStep.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/ElasticsearchExtensionIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneExtensionIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3974

HSEARCH-3974 Backend-specific extensions for scroll

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/spi/ElasticsearchRequest.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/timeout/impl/ElasticsearchTimeoutManager.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/CountWork.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/SearchWork.java

https://hibernate.atlassian.net/browse/HSEARCH-3774
~~Based on https://github.com/hibernate/hibernate-search/pull/2333 that must be merged first.~~ done!

HSEARCH-3774 Improve the timeout implementation for Elasticsearch

---

backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
documentation/src/test/java/org/hibernate/search/documentation/configuration/ElasticsearchConfigurationIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3984
Will merge as soon as CI goes green.

HSEARCH-3984 Upgrade to Elasticsearch 7.9.0

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/dsl/ElasticsearchSearchQuerySelectStep.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/dsl/ElasticsearchSearchQueryWhereStep.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/dsl/LuceneSearchQuerySelectStep.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/dsl/LuceneSearchQueryWhereStep.java
engine/src/main/java/org/hibernate/search/engine/search/query/dsl/SearchQuerySelectStep.java
engine/src/main/java/org/hibernate/search/engine/search/query/dsl/SearchQueryWhereStep.java
engine/src/main/java/org/hibernate/search/engine/search/query/dsl/impl/DefaultSearchQueryOptionsStep.java
engine/src/main/java/org/hibernate/search/engine/search/query/dsl/spi/AbstractDelegatingSearchQuerySelectStep.java
engine/src/main/java/org/hibernate/search/engine/search/query/dsl/spi/AbstractSearchQueryOptionsStep.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryLoadingOptionsIT.java
util/internal/integrationtest/mapper/stub/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/stub/GenericStubMappingScope.java

https://hibernate.atlassian.net/browse/HSEARCH-3988

HSEARCH-3988 Using search(...).select(...) drops the type of loading options and prevents their definition

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/AbstractElasticsearchIndexSchemaFieldNode.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/AbstractLuceneIndexSchemaFieldNode.java
engine/src/main/java/org/hibernate/search/engine/backend/metamodel/IndexFieldDescriptor.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/metamodel/IndexFieldDescriptorIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3980

HSEARCH-3980 Expose multiValuedInRoot in the metamodel

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientFactoryImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/spi/ElasticsearchRequest.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/schema/management/impl/ElasticsearchSchemaAccessor.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/timeout/impl/ElasticsearchTimeoutManager.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/timeout/spi/RequestDeadline.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/builder/factory/impl/Elasticsearch7WorkBuilderFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/builder/factory/impl/ElasticsearchWorkBuilderFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/CountWork.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/SearchWork.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/WaitForIndexStatusWork.java
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
engine/src/main/java/org/hibernate/search/engine/search/timeout/spi/TimeoutManager.java

https://hibernate.atlassian.net/browse/HSEARCH-2505
~~Draft since I have to check if we have to change something in our doc...~~

HSEARCH-2505 Lower the default read timeout with Elasticsearch

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/BoxedBooleanPropertyTypeDescriptor.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/BoxedBytePropertyTypeDescriptor.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/BoxedCharacterPropertyTypeDescriptor.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/BoxedDoublePropertyTypeDescriptor.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/BoxedFloatPropertyTypeDescriptor.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/PrimitiveBooleanPropertyTypeDescriptor.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/PrimitiveBytePropertyTypeDescriptor.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/PrimitiveCharacterPropertyTypeDescriptor.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/PrimitiveDoublePropertyTypeDescriptor.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/PrimitiveFloatPropertyTypeDescriptor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultBooleanIdentifierBridge.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultByteIdentifierBridge.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultCharacterIdentifierBridge.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultDoubleIdentifierBridge.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultFloatIdentifierBridge.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/mapping/impl/BridgeResolver.java

https://hibernate.atlassian.net/browse/HSEARCH-3993

HSEARCH-3993 Add default identifier bridges for types character, boolean, byte, float, double

---

documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedentities/SearchMappingIndexedEntitiesIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/mapping/SearchMappingIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/SearchMappingIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/smoke/AnnotationMappingSmokeIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/smoke/ProgrammaticMappingSmokeIT.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/entity/SearchIndexedEntity.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/log/impl/Log.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/mapping/SearchMapping.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/mapping/impl/JavaBeanIndexedTypeContext.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/mapping/impl/JavaBeanMapping.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/mapping/impl/JavaBeanTypeContextContainer.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/scope/SearchScope.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/scope/impl/JavaBeanScopeIndexedTypeContext.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/scope/impl/SearchScopeImpl.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/SearchSession.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/impl/JavaBeanSearchSession.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/impl/JavaBeanSearchSessionMappingContext.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/impl/JavaBeanSearchSessionTypeContextProvider.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/impl/JavaBeanSessionIndexedTypeContext.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/entity/SearchIndexedEntity.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/SearchMapping.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmIndexedTypeContext.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMapping.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/scope/SearchScope.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/scope/impl/HibernateOrmScopeIndexedTypeContext.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/scope/impl/SearchScopeImpl.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/scope/impl/PojoScopeDelegateImpl.java

https://hibernate.atlassian.net/browse/HSEARCH-3994

HSEARCH-3994 Expose metadata about the targeted types from SearchScope

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-3991

HSEARCH-3991 Upgrade to Lucene 8.6.2

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchIndexSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/AbstractElasticsearchIndexSchemaObjectNodeBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/ElasticsearchIndexSchemaObjectFieldNodeBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/ElasticsearchIndexSchemaRootNodeBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/index/DynamicMapping.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/index/mapping/impl/DynamicType.java
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerDynamicMappingIT.java

https://hibernate.atlassian.net/browse/HSEARCH-3122
~~Draft:~~
~~1. We need more tests: invalid name && propagation on nested object mapping~~
~~2. Documentation~~

HSEARCH-3122 Restore support for configuring "strict" mapping in Elasticsearch

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToHibernateOrmScrollableResultsIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchScrollableResultsAdapter.java

https://hibernate.atlassian.net/browse/HSEARCH-4011

HSEARCH-4011 Hibernate Search ScrollableResults should throw a JPA QueryTimeoutException instead of SearchTimeoutException

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/TransientPropertyIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/AbstractPojoIndexingDependencyCollectorValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorDisjointValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorTypeNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorValueNode.java

https://hibernate.atlassian.net/browse/HSEARCH-4009

HSEARCH-4009 PropertyBridge on property marked with @IndexingDependency(derivedFrom = ...) leads to bootstrap failure

---

documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/containerextractor/MyCollectionSizeBridge.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DocumentIdBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FieldBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FieldContainerExtractorExplicitIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FullTextFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/GenericFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/KeywordFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/NonStandardFieldIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/ScaledNumberFieldIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/impl/DefaultIdentifierBindingContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/impl/ValueBindingContextImpl.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/mapping/impl/BeanBinder.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java

https://hibernate.atlassian.net/browse/HSEARCH-3243

HSEARCH-3243 Implement safer type checking for bridge type parameters

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendFactory.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lifecycle/LuceneCleanupIT.java
util/internal/integrationtest/backend/lucene/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/lucene/directory/OpenResourceTracker.java
util/internal/integrationtest/backend/lucene/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/lucene/directory/TrackingChecksumIndexInput.java
util/internal/integrationtest/backend/lucene/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/lucene/directory/TrackingDirectory.java
util/internal/integrationtest/backend/lucene/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/lucene/directory/TrackingDirectoryHolder.java
util/internal/integrationtest/backend/lucene/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/lucene/directory/TrackingDirectoryProvider.java
util/internal/integrationtest/backend/lucene/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/lucene/directory/TrackingIndexInput.java
util/internal/integrationtest/backend/lucene/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/lucene/directory/TrackingIndexOutput.java

https://hibernate.atlassian.net/browse/HSEARCH-3986

HSEARCH-3986 Test that Hibernate Search releases all file handles on close

---

documentation/pom.xml
documentation/src/main/asciidoc/reference/getting-started.asciidoc
integrationtest/showcase/library/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4013

HSEARCH-4013 Add framework-specific bits to the getting started guide

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingIdentiferRollbackIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/event/impl/HibernateSearchEventListener.java

https://hibernate.atlassian.net/browse/HSEARCH-3985

HSEARCH-3985 Test Hibernate Search 6 indexing when hibernate.use_identifier_rollback=true

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4030

HSEARCH-4030 Upgrade to Hibernate ORM 5.4.22.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4030

Backport HSEARCH-4030 to branch 5.11 - Upgrade to Hibernate ORM 5.4.22.Final

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/multitenancy/Clock.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/multitenancy/DatabaseMultitenancyIT.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/BackendMock.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/MappingSetupHelper.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmSetupHelper.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/DdlTransactionIsolatorTestingImpl.java
util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/multitenancy/impl/MultitenancyTestHelper.java

https://hibernate.atlassian.net/browse/HSEARCH-4034

HSEARCH-4034 Add a multi-tenancy test to mapper ORM integration tests

---

legacy/integrationtest/jsr352/pom.xml
legacy/jsr352/core/pom.xml
legacy/orm/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4031
The legacy code has a dependency convergence issue now that we have a dependency to Mockito. This PR should fix it.

HSEARCH-4031 Follow-up: Move from Easymock to Mockito

---

Jenkinsfile
parents/integrationtest/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4042

HSEARCH-4042 Restore the retry() steps in the Jenkinsfile

---

Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4045
@fax4ever Your problems should be gone after you rebase your work on this branch. I tested locally and it did fix the problems.

HSEARCH-4045 Infer tools.jar location (for Byteman) correctly even when a different JVM is used for Maven and Surefire/Failsafe

---

backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4040

HSEARCH-4040 Upgrade to Elasticsearch 7.9.2

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/AbstractElasticsearchIndexSchemaFieldTemplateBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/AbstractElasticsearchIndexSchemaObjectNodeBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/ElasticsearchIndexSchemaObjectFieldNodeBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/ElasticsearchIndexSchemaRootNodeBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/ElasticsearchIndexSchemaValueFieldNodeBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexSchemaNodeContributor.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexSchemaObjectFieldNode.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexSchemaObjectFieldTemplate.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexSchemaObjectNode.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexSchemaRootNode.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/AbstractLuceneIndexSchemaFieldTemplateBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/AbstractLuceneIndexSchemaObjectNodeBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/LuceneIndexSchemaObjectFieldNodeBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/LuceneIndexSchemaRootNodeBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/LuceneIndexSchemaValueFieldNodeBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaNodeContributor.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaObjectFieldNode.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaObjectFieldTemplate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaObjectNode.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaRootNode.java
engine/src/main/java/org/hibernate/search/engine/backend/metamodel/IndexCompositeElementDescriptor.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/metamodel/IndexFieldDescriptorIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4046

HSEARCH-4046 Expose a map of static children by name in the metamodel of object fields

---

engine/src/main/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolder.java
engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedBaseIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4006

More explicit failure message when two types target the same index

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4054
Waiting for the result of the CI build.

HSEARCH-4054 Upgrade to JUnit 4.13.1

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DependencyRepeatableIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/AssociationInverseSide.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/IndexingDependency.java

https://hibernate.atlassian.net/browse/HSEARCH-4000

HSEARCH-4000 @IndexingDependency, @AssociationInverseSide should be repeatable

---

legacy/documentation/src/main/asciidoc/advanced-features.asciidoc
legacy/documentation/src/main/asciidoc/configuration.asciidoc
legacy/documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
legacy/documentation/src/main/asciidoc/getting-started.asciidoc
legacy/documentation/src/main/asciidoc/index-optimization.asciidoc
legacy/documentation/src/main/asciidoc/monitoring.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4058

HSEARCH-4058 Remove anchors to missing docs

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchScrollImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchScrollResultImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneExtractableSearchResult.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchScrollImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchScrollResultImpl.java
documentation/src/main/asciidoc/reference/search-dsl-query.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/query/QueryDslIT.java
engine/src/main/java/org/hibernate/search/engine/search/query/SearchScrollResult.java
engine/src/main/java/org/hibernate/search/engine/search/query/spi/SimpleSearchScrollResult.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/ElasticsearchExtensionIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneExtensionIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/SearchMultiIndexIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryResultLoadingOrTransformingIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryScrollIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryScrollResultLoadingIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryTimeoutIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToHibernateOrmScrollableResultsIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityChangingScrollingIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingScrollingIT.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/NextScrollWorkCall.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/StubNextScrollWorkBehavior.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/VerifyingStubBackendBehavior.java

https://hibernate.atlassian.net/browse/HSEARCH-4023

HSEARCH-4023 Expose the total hit count in scroll results

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchScrollImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearcherImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneSearcher.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneWorkFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneWorkFactoryImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/ScrollWork.java

https://hibernate.atlassian.net/browse/HSEARCH-3990

HSEARCH-3990 Optimize the retrieval of topDocs in very long Lucene scrolls

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchScrollImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearcherImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneSearcher.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneWorkFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneWorkFactoryImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/ScrollWork.java
documentation/src/main/asciidoc/reference/search-dsl-query.asciidoc
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryScrollIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java

https://hibernate.atlassian.net/browse/HSEARCH-4070

HSEARCH-4070 Lucene scroll ignores totalHitCountThreshold

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/LuceneIndexManager.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/LuceneIndexManagerImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/Shard.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/ShardHolder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessor.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessorImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/schema/management/impl/LuceneIndexSchemaManager.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/schema/management/impl/SchemaManagementIndexManagerContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/execution/impl/LuceneIndexIndexer.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/execution/impl/LuceneIndexIndexingPlan.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/execution/impl/LuceneIndexWorkspace.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/execution/impl/WorkExecutionIndexManagerContext.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/ComputeSizeInBytesWork.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneWorkFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneWorkFactoryImpl.java
documentation/src/main/asciidoc/reference/backend-lucene.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/backend/lucene/indexmanager/Book.java
documentation/src/test/java/org/hibernate/search/documentation/backend/lucene/indexmanager/LuceneGetIndexSizeIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/analysis/LuceneSimilarityIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/index/LuceneIndexManagerIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/directory/AbstractBuiltInDirectoryIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/directory/LuceneDirectorySettingsPerShardIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/directory/LuceneLocalFileSystemDirectoryIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/directory/LuceneLocalHeapDirectoryIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/directory/MultiDirectoryIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/writer/LuceneIndexWriterSettingsIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/writer/LuceneIndexWriterSettingsPerShardIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4056

HSEARCH-4056 Expose the index size from LuceneIndexManager

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/model/impl/LuceneDefaultAnalysisConfigurer.java
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/reference/backend-lucene.asciidoc
engine/src/main/java/org/hibernate/search/engine/backend/analysis/AnalyzerNames.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/configuration/AnalysisBuiltinOverrideITAnalysisConfigurer.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/configuration/AnalysisBuiltinOverrideITAnalysisConfigurer.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/analysis/AnalysisBuiltinIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/analysis/AnalysisBuiltinOverrideIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/analysis/AnalysisCustomIT.java

https://hibernate.atlassian.net/browse/HSEARCH-2584

HSEARCH-2584 Introduce some commonly used Analyzer definitions by default

---

integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/bridge/BridgeTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4021
Locally it worked, let's try on CI.

HSEARCH-4021 Avoid to log UNICODE 0xFFFF (and 0xFFFE)

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/BootstrapLogsIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4021

HSEARCH-4021 Revert implicit diamond for JDK 8

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4075
Waiting for the result of the CI build.

Backport HSEARCH-4075 to branch 5.11 - Upgrade to Hibernate Annotations 5.1.1.Final

---

documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-indexing-jsr352.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4094

HSEARCH-4094 JSR-352 documentation should mention that an additional dependency is necessary

---

documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/reference/backend-lucene.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4067

HSEARCH-4067 Remove "(default)"/"(no default)" from configuration examples in the documentation

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/NearRealTimeIOStrategy.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/timeout/impl/LuceneCounterAdapter.java
engine/src/main/java/org/hibernate/search/engine/common/timing/impl/DefaultTimingSource.java
engine/src/main/java/org/hibernate/search/engine/common/timing/spi/TimingSource.java
engine/src/main/java/org/hibernate/search/engine/search/timeout/spi/TimeoutManager.java

https://hibernate.atlassian.net/browse/HSEARCH-4069

HSEARCH-4069 Measure time more precisely when computing execution time of Lucene queries

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4103

[5.10] HSEARCH-4103 Upgrade to Hibernate ORM 5.3.19.Final

---

integrationtest/spring/pom.xml
orm/src/main/java/org/hibernate/search/impl/FullTextSessionImpl.java
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4107

[5.11] HSEARCH-4107 Session cast fails when creating a FullTextSession with Spring 2.4.0

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientFactoryImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ServerUris.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4099

HSEARCH-4099 Allow option for setting Elasticsearch connection information via full URIs

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4110
Waiting for the result of the CI build, then I'll merge.

HSEARCH-4110 Upgrade to Hibernate ORM 5.3.20.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4111

HSEARCH-4111 Upgrade to Hibernate ORM 5.4.24.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4111
Backport of #2448

Backport HSEARCH-4111 to branch 5.11 - Upgrade to Hibernate ORM 5.4.24.Final

---

documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4118

HSEARCH-4118 Fix formatting in Elasticsearch layout strategy documentation

---

documentation/src/main/asciidoc/mapping.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4119
Waiting for CI then I'll merge.

[5.11] HSEARCH-4119 Fix example for custom bridge with sortable field in documentation

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/MappedSuperclassIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FullTextFieldIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/PropertyMappingFullTextFieldOptionsStepImpl.java

https://hibernate.atlassian.net/browse/HSEARCH-4123

HSEARCH-4123 Default analyzer not applied by default on programmatic-defined full text fields

---

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/DefaultElasticsearchService.java

https://hibernate.atlassian.net/browse/HSEARCH-4128

HSEARCH-4128 Close client in case initially fails

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4131

HSEARCH-4131 Upgrade to Hibernate ORM 5.4.27.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4131

Backport HSEARCH-4131 to branch 5.11 - Upgrade to Hibernate ORM 5.4.27.Final

---

engine/src/main/java/org/hibernate/search/engine/cfg/impl/OptionalPropertyContextImpl.java
engine/src/main/java/org/hibernate/search/engine/cfg/spi/OptionalPropertyContext.java
engine/src/test/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyBeanReferenceTest.java
engine/src/test/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyInvalidSimpleValuesTest.java
engine/src/test/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyValidMissingValuesTest.java
engine/src/test/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyValidSimpleValuesTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4143
I will need this for another PR.

HSEARCH-4143 Allow value substitution when retrieving configuration property values

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/model/DuplicateGetterIT.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/model/impl/JavaBeanPropertyModel.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/model/impl/JavaBeanRawTypeModel.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmClassPropertyModel.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmClassRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/spi/ErrorCollectingPojoPropertyMetadataContributor.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/InitialPropertyMappingStep.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnBootstrapIntrospector.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnPropertyModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnRawTypeModel.java

https://hibernate.atlassian.net/browse/HSEARCH-4117

HSEARCH-4117 Better handling of duplicate getters

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4147
Nothing to review, I'll merge as soon as the build passes.

HSEARCH-4147 Upgrade to Lucene 8.8.0

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/AbstractElasticsearchReversibleSort.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/sort/impl/ElasticsearchDistanceSort.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/comparatorsource/impl/LuceneGeoPointDistanceComparatorSource.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/impl/LuceneGeoPointDistanceSort.java
documentation/src/main/asciidoc/reference/search-dsl-sort.asciidoc
engine/src/main/java/org/hibernate/search/engine/search/sort/dsl/DistanceSortMissingValueBehaviorStep.java
engine/src/main/java/org/hibernate/search/engine/search/sort/dsl/DistanceSortOptionsStep.java
engine/src/main/java/org/hibernate/search/engine/search/sort/dsl/impl/DistanceSortOptionsStepImpl.java
engine/src/main/java/org/hibernate/search/engine/search/sort/spi/DistanceSortBuilder.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/DistanceSearchSortBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/DistanceSearchSortTypeCheckingAndConversionIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/sort/StubSortBuilder.java

https://hibernate.atlassian.net/browse/HSEARCH-3863

HSEARCH-3863 Specify a replacement for missing values in distance sorts

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchIndexSettings.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerDynamicMappingIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4152
After the review I'll prepare the backport to 6.0 branch!

HSEARCH-4152 "hibernate.search.backend.dynamic_mapping" is ignored

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4154

HSEARCH-4154 Upgrade to Hibernate ORM 5.4.28.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4154

Backport HSEARCH-4154 to branch 5.11 - Upgrade to Hibernate ORM 5.4.28.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4154

Backport HSEARCH-4154 to branch 6.0 - Upgrade to Hibernate ORM 5.4.28.Final

---

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexIndexerIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4157

HSEARCH-4157 Raise the timeout on test

---

integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/AbstractBatchIndexingIT.java
integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/BatchIndexingJobIT.java
integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/EntityManagerFactoryRetrievalIT.java
integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/MassIndexingJobWithCompositeIdIT.java
integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/MassIndexingJobWithMultiTenancyIT.java
integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/RestartChunkIT.java
integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/routing/RoutingBridgeRoutingKeyIT.java
integrationtest/performance/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/performance/backend/elasticsearch/SmokeIT.java
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/engine/worker/WorkerTestCase.java

https://hibernate.atlassian.net/browse/HSEARCH-4157

HSEARCH-4157 Raise all the timeouts to make all tests working

---

engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationImpl.java
engine/src/test/java/org/hibernate/search/engine/common/impl/SearchIntegrationImplTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4159

HSEARCH-4159 Hibernate Search doesn't properly execute the backend's preStop() operation on shutdown

---

engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationImpl.java
engine/src/test/java/org/hibernate/search/engine/common/impl/SearchIntegrationImplTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4159
Will merge as soon as #2497 gets merged.

Backport HSEARCH-4159 to branch 6.0 - Hibernate Search doesn't properly execute the backend's preStop() operation on shutdown

---

util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/automaticindexing/LocalHeapQueueProcessor.java

https://hibernate.atlassian.net/browse/HSEARCH-4164
I wasn't able to reproduce the issue. However, I was able to imagine a situation in which it can theoretically happen:
* Transaction 1 happens in an application thread, creating entity instance A1.
* The `BatchingExecutor` receives the event, and delegates to `LocalHeapQueueProcessor`.
* `LocalHeapQueueProcessor` starts a batch, opens a session, loads A1, indexes it, and ends the batch.
* Meanwhile, transaction 2 happens in an application thread, updating entity instance A1.
* The `BatchingExecutor` receives the event *before it noticed that the event queue was empty.
As a result it doesn't call `LocalHeapQueueProcessor.complete()` (which would release the session), but it starts another batch.
* `LocalHeapQueueProcessor` re-uses the …

HSEARCH-4164 Fix transient failure in AbstractAutomaticIndexingMultiAssociationIT

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4169

HSEARCH-4169 Upgrade to Lucene 8.8.1

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4160

HSEARCH-4160 Upgrade to Byteman 4.0.14

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4160

Backport HSEARCH-4160 to branch 5.10 - Upgrade to Byteman 4.0.14

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicateBuilderFactoryImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/PredicateTypeKeys.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/impl/ElasticsearchStringIndexFieldTypeOptionsStep.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchTextRegexpPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneSearchPredicateBuilderFactoryImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/PredicateTypeKeys.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/impl/LuceneStringIndexFieldTypeOptionsStep.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextRegexpPredicate.java
documentation/src/main/asciidoc/reference/search-dsl-predicate.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/RegexpPredicateFieldMoreStep.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/RegexpPredicateFieldStep.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/RegexpPredicateMatchingStep.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/RegexpPredicateOptionsStep.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/SearchPredicateFactory.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/DefaultSearchPredicateFactory.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/RegexpPredicateFieldMoreStepImpl.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/RegexpPredicateFieldStepImpl.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/spi/DelegatingSearchPredicateFactory.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/RegexpPredicateBuilder.java
engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/SearchPredicateBuilderFactory.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RegexpPredicateBaseIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RegexpPredicateSpecificsIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RegexpPredicateTestValues.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubPredicateBuilder.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubSearchPredicateBuilderFactory.java

https://hibernate.atlassian.net/browse/HSEARCH-3884

HSEARCH-3884 Support Regexp queries having a regex expression predicate

---

CONTRIBUTING.md
Jenkinsfile
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
documentation/pom.xml
documentation/src/main/asciidoc/reference/getting-started.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/configuration/ElasticsearchConfigurationIT.java
integrationtest/backend/elasticsearch/pom.xml
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java
parents/integrationtest/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4170
Full build here: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-yoann/detail/HSEARCH-4170/9/pipeline

HSEARCH-4170 Upgrade to Elasticsearch 7.11

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4178

HSEARCH-4178 Upgrade to maven-checkstyle-plugin 3.1.2 and Checkstyle 8.41

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4178
See #2510

Backport HSEARCH-4178 to branch 6.0 - Upgrade to maven-checkstyle-plugin 3.1.2 and Checkstyle 8.41

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4181

HSEARCH-4181 Upgrade to Hibernate ORM 5.4.29.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4181
Backport of #2516

Backport HSEARCH-4181 to branch 6.0 - Upgrade to Hibernate ORM 5.4.29.Final

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DocumentIdBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FieldBaseIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmBasicDynamicMapPropertyMetadata.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmBasicTypeMetadataProvider.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmDynamicMapPropertyModel.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmDynamicMapRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoImplicitReindexingResolverCastedTypeNodeBuilder.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoImplicitReindexingResolverValueNodeBuilderDelegate.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/impl/PojoImplicitReindexingResolverCastedTypeNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/path/impl/BoundPojoModelPathCastedTypeNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/path/impl/BoundPojoModelPathValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/GenericContextAwarePojoGenericTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PojoGenericTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PojoRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/SyntheticPojoGenericTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/processing/building/impl/PojoIndexingProcessorCastedTypeNodeBuilder.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/processing/building/impl/PojoIndexingProcessorValueNodeBuilderDelegate.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/processing/impl/PojoIndexingProcessorCastedTypeNode.java
util/common/src/main/java/org/hibernate/search/util/common/reflect/impl/GenericTypeContext.java
util/common/src/test/java/org/hibernate/search/util/common/reflect/impl/CustomBoundedGenericType.java
util/common/src/test/java/org/hibernate/search/util/common/reflect/impl/GenericTypeContextTest.java
util/common/src/test/java/org/hibernate/search/util/common/testsupport/GenericTypeContextAssert.java

https://hibernate.atlassian.net/browse/HSEARCH-4188

HSEARCH-4188 Preserve generic type arguments when casting type models during the mapping phase

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4189
Build on all JDKs: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-yoann/detail/HSEARCH-4189/2/pipeline

HSEARCH-4189 Test Hibernate Search against JDK 17

---

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DependencyIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmDynamicMapRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/AbstractPojoIndexingDependencyCollectorDirectValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/AbstractPojoIndexingDependencyCollectorValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoImplicitReindexingResolverValueNodeBuilderDelegate.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorDisjointValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorMonomorphicDirectValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorPolymorphicDirectValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorPropertyNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorTypeNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/dependency/impl/PojoPropertyIndexingDependencyConfigurationContextImpl.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/impl/PojoModelNestedCompositeElement.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/impl/PojoModelPropertyRootElement.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/path/impl/BoundPojoModelPathCastedTypeNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/path/impl/BoundPojoModelPathOriginalTypeNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/path/impl/BoundPojoModelPathPropertyNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/path/impl/BoundPojoModelPathTypeNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/path/impl/BoundPojoModelPathValueNode.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/AbstractPojoRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PojoGenericTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PojoRawTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PojoTypeModel.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/processing/building/impl/AbstractPojoIndexingProcessorTypeNodeBuilder.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/processing/building/impl/PojoIndexingProcessorCastedTypeNodeBuilder.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/processing/building/impl/PojoIndexingProcessorOriginalTypeNodeBuilder.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/processing/building/impl/PojoIndexingProcessorValueNodeBuilderDelegate.java

https://hibernate.atlassian.net/browse/HSEARCH-4148

HSEARCH-4148 Polymorphic "derivedFrom" definition for derived properties

---

Jenkinsfile
README.md
integrationtest/wildfly/pom.xml
jenkins/performance-elasticsearch.groovy
jenkins/performance-orm.groovy
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4190
Partial backport of #2527

HSEARCH-4190 Backport Jenkinsfile improvements to 5.10

---

CONTRIBUTING.md
Jenkinsfile
README.md
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/index/layout/impl/SimpleIndexLayoutStrategy.java
build-config/src/main/resources/forbidden-runtime.txt
documentation/src/main/asciidoc/migration/index.asciidoc
documentation/src/main/asciidoc/reference/credits.asciidoc
documentation/src/main/asciidoc/reference/getting-started.asciidoc
jenkins/performance-elasticsearch.groovy
jenkins/performance-lucene.groovy

https://hibernate.atlassian.net/browse/HSEARCH-4191

HSEARCH-4191 Get rid of master/slave in Git repository, documentation where possible, etc

---

CONTRIBUTING.md
Jenkinsfile
README.md
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/index/layout/impl/SimpleIndexLayoutStrategy.java
build-config/src/main/resources/forbidden-runtime.txt
documentation/src/main/asciidoc/migration/index.asciidoc
documentation/src/main/asciidoc/reference/credits.asciidoc
documentation/src/main/asciidoc/reference/getting-started.asciidoc
jenkins/performance-elasticsearch.groovy
jenkins/performance-lucene.groovy

https://hibernate.atlassian.net/browse/HSEARCH-4191
See #2533

Backport HSEARCH-4191 to branch 6.0 - Get rid of master/slave in Git repository, documentation where possible, etc

---

CONTRIBUTING.md
Jenkinsfile
documentation/src/main/asciidoc/credits.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4191
See #2533

Backport HSEARCH-4191 to branch 5.11 - Get rid of master/slave in Git repository, documentation where possible, etc

---

CONTRIBUTING.md
Jenkinsfile
documentation/src/main/asciidoc/credits.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4191
See #2533

Backport HSEARCH-4191 to branch 5.10 - Get rid of master/slave in Git repository, documentation where possible, etc

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4196

HSEARCH-4196 Upgrade to ORM 5.4.30.Final

---

mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/HibernateOrmMassIndexingDocumentProducerInterceptor.java

https://hibernate.atlassian.net/browse/HSEARCH-4211

HSEARCH-4211 Use commits instead of rollbacks in the mass indexer

---

mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/IdentifierConsumerDocumentProducer.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/OptionallyWrapInJTATransaction.java

https://hibernate.atlassian.net/browse/HSEARCH-4211
Backport of #2544

Backport HSEARCH-4211 to branch 6.0 - Use commits instead of rollbacks in the mass indexer

---

parents/integrationtest/pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4130
Follow-up of #2539 to raise the log level of the container to WARN.

HSEARCH-4130 Raise the log level of ES container

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexModel.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/index/settings/impl/IndexSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/index/settings/impl/IndexSettingsJsonAdapterFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/scope/model/impl/ElasticsearchScopeSearchIndexesContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/impl/ElasticsearchSearchIndexContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/impl/ElasticsearchSearchIndexesContext.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/validation/impl/IndexSettingsValidator.java
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerCreationCustomSettingsIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerUpdateCustomSettingsIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationCustomSettingsIT.java
integrationtest/backend/elasticsearch/src/test/resources/custom-index-settings/max-result-window.json

https://hibernate.atlassian.net/browse/HSEARCH-3556

HSEARCH-3556 Configuration of the max window size in Elasticsearch

---

mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingTypeProcessor.java

https://hibernate.atlassian.net/browse/HSEARCH-4216

HSEARCH-4216 Fix "NullPointerException" when indexing no indexable entity

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4130

Reopen of HSEARCH-4130 Use docker for Elasticsearch IT

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4130
Backport of #2561

Backport of HSEARCH-4130 Cleanup docker containers

---

documentation/src/main/asciidoc/reference/backend-lucene.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4168

HSEARCH-4168 Document query caching configuration

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexModel.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/index/ElasticsearchIndexManager.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/index/impl/ElasticsearchIndexManagerImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/metamodel/ElasticsearchIndexDescriptor.java
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/backend/elasticsearch/indexmanager/Book.java
documentation/src/test/java/org/hibernate/search/documentation/backend/elasticsearch/indexmanager/ElasticsearchIndexManagerIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/metamodel/ElasticsearchIndexDescriptorIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4204

HSEARCH-4204 Expose the Elasticsearch index names in the metamodel API

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneMatchIdPredicate.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/MatchIdPredicateSpecificsIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4208

HSEARCH-4208 Implement the id predicate using a TermInSetQuery instead of a BooleanQuery

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4219

HSEARCH-4219  Upgrade to Hibernate ORM 5.4.31.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4219

Backport HSEARCH-4219 to branch 6.0 - Upgrade to Hibernate ORM 5.4.31.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4219

HSEARCH-4219 Upgrade to Hibernate ORM 5.4.31.Final

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendImpl.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cfg/LuceneBackendSettings.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendFactory.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/reference/backend-lucene.asciidoc
engine/src/main/java/org/hibernate/search/engine/backend/spi/BackendBuildContext.java
engine/src/main/java/org/hibernate/search/engine/backend/spi/BackendImplementor.java
engine/src/main/java/org/hibernate/search/engine/common/impl/BackendBuildContextImpl.java
engine/src/main/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolder.java
engine/src/main/java/org/hibernate/search/engine/common/impl/MappedIndexManagerFactoryImpl.java
engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationBuilderImpl.java
engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java
engine/src/main/java/org/hibernate/search/engine/mapper/mapping/building/spi/BackendsInfo.java
engine/src/main/java/org/hibernate/search/engine/mapper/mapping/building/spi/MappedIndexManagerFactory.java
engine/src/main/java/org/hibernate/search/engine/mapper/mapping/building/spi/Mapper.java
engine/src/test/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolderTest.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/work/LuceneIndexingNestedIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/multitenancy/MultiTenancyMismatchIT.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexIndexingPlanIT.java
integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/multitenant/RealBackendDatabaseMultitenancyIT.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/impl/PojoMapper.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/index/impl/StubBackend.java
util/internal/integrationtest/mapper/stub/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/stub/StubMapper.java
util/internal/test/src/main/java/org/hibernate/search/util/impl/test/AssertionAndAssumptionViolationFallThrough.java

https://hibernate.atlassian.net/browse/HSEARCH-4163

HSEARCH-4163 Enable multi-tenancy by default if it is defined in ORM

---

Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4221

HSEARCH-4221 Upgrade to Byteman 4.0.15

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4221
Backport of #2576

Backport HSEARCH-4221 to branch 5.10 - Upgrade to Byteman 4.0.15

---

.gitignore
integrationtest/mapper/orm-spring/src/test/java/org/hibernate/search/integrationtest/spring/jta/JtaAndSpringIT.java
integrationtest/mapper/orm-spring/src/test/java/org/hibernate/search/integrationtest/spring/jta/JtaAndSpringMoreComplexIT.java
integrationtest/mapper/orm-spring/src/test/java/org/hibernate/search/integrationtest/spring/jta/JtaAndSpringOutboxApplicationConfiguration.java
integrationtest/mapper/orm-spring/src/test/java/org/hibernate/search/integrationtest/spring/jta/JtaAndSpringOutboxIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxEventBackgroundExecutor.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxTableSendingPlan.java

https://hibernate.atlassian.net/browse/HSEARCH-4198

HSEARCH-4198 Transactional outbox event creation with Spring and JTA

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/AbstractElasticsearchIndexSchemaObjectNodeBuilder.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchNamedPredicate.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/AbstractLuceneIndexSchemaObjectNodeBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneNamedPredicate.java
documentation/src/main/asciidoc/reference/mapper-orm-bridge-identifierbridge.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-bridge-named-predicate.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-bridge-propertybridge.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-bridge-typebridge.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-bridge-valuebridge.asciidoc
engine/src/main/java/org/hibernate/search/engine/search/predicate/factories/NamedPredicateProviderContext.java
integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/NamedPredicateProviderContextIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4167

HSEARCH-4167 Improve parameter handling in named predicates

---

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/LuceneExtension.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/LuceneIndexScopeBuilder.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/scope/LuceneIndexScope.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/scope/impl/LuceneIndexScope.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/scope/impl/LuceneIndexScopeImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/dsl/impl/LuceneSearchQueryOptionsStepImpl.java
backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/dsl/impl/LuceneSearchQuerySelectStepImpl.java
documentation/src/main/asciidoc/reference/backend-lucene.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/backend/lucene/lowlevel/LuceneLowLevelIndexReaderIT.java
engine/src/main/java/org/hibernate/search/engine/backend/scope/IndexScopeExtension.java
engine/src/main/java/org/hibernate/search/engine/backend/scope/spi/IndexScope.java
engine/src/main/java/org/hibernate/search/engine/mapper/scope/impl/MappedIndexScopeImpl.java
engine/src/main/java/org/hibernate/search/engine/mapper/scope/spi/MappedIndexScope.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneExtensionIT.java
integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/sharding/ShardingExplicitIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/scope/ScopeExtensionIT.java
integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/scope/ScopeExtensionIT.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/scope/SearchScope.java
mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/scope/impl/SearchScopeImpl.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/scope/SearchScope.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/scope/impl/SearchScopeImpl.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/scope/impl/PojoScopeDelegateImpl.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/scope/spi/PojoScopeDelegate.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/index/impl/StubIndexScope.java
util/internal/integrationtest/mapper/stub/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/stub/GenericStubMappingScope.java

https://hibernate.atlassian.net/browse/HSEARCH-4065

HSEARCH-4065 Expose Lucene's low-level IndexReader through API

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4233

HSEARCH-4233 Upgrade to Hibernate ORM 5.5.0.Final

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/FilteringOutboxEventFinder.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingAutomaticIndexingStrategyEdgeIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingAutomaticIndexingStrategyRoutingIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxAdditionalJaxbMappingProducer.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxEvent.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxEventBackgroundExecutor.java

https://hibernate.atlassian.net/browse/HSEARCH-4229

HSEARCH-4229 Use Long for OutboxEvent identifiers

---

pom.xml

* [HSEARCH-4246](https://hibernate.atlassian.net/browse/HSEARCH-4246): Upgrade jboss-logging 3.4.2.Final
* [HSEARCH-4243](https://hibernate.atlassian.net/browse/HSEARCH-4243): Upgrade to Hibernate ORM 5.5.2.Final

HSEARCH-4243 + HSEARCH-4246 Upgrade to Hibernate ORM 5.5.2.Final and jboss-logging 3.4.2.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4241

HSEARCH-4241 Upgrade to Hibernate ORM 5.4.32.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4241
Backport of #2594

Backport HSEARCH-4241 to branch 5.11 - Upgrade to Hibernate ORM 5.4.32.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4247

HSEARCH-4247 Upgrade to Byteman 4.0.16

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4247
Backport of #2600

Backport HSEARCH-4247 to branch 5.10 - Upgrade to Byteman 4.0.16

---

CONTRIBUTING.md
Jenkinsfile
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/ElasticsearchDistributionName.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/ElasticsearchVersion.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientUtils.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java
backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchVersionTest.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientUtilsGetElasticsearchVersionTest.java
backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java
documentation/pom.xml
documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/reference/getting-started.asciidoc
documentation/src/main/asciidoc/reference/preface.asciidoc
integrationtest/backend/elasticsearch/pom.xml
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java
integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java
parents/integrationtest/pom.xml
pom.xml
util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/dialect/ElasticsearchTestDialect.java

https://hibernate.atlassian.net/browse/HSEARCH-4212

HSEARCH-4212 Official, documented compatibility with OpenSearch

---

documentation/src/main/asciidoc/reference/configuration.asciidoc
documentation/src/main/asciidoc/reference/getting-started.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4251

HSEARCH-4251 Spring boot documentation improvements

---

documentation/src/main/asciidoc/reference/configuration.asciidoc
documentation/src/main/asciidoc/reference/getting-started.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4251
Backport of #2605

Backport HSEARCH-4251 to branch 6.0 - Spring boot documentation improvements

---

Jenkinsfile

https://hibernate.atlassian.net/browse/HSEARCH-4255

HSEARCH-4255 Test Hibernate Search against JDK 18

---

documentation/src/main/asciidoc/reference/mapper-orm-indexing-jsr352.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-indexing-massindexer.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexing/Author.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexing/Book.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexing/HibernateOrmMassIndexerIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingConditionalExpressionsIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/AbstractHibernateOrmLoadingStrategy.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/ConditionalExpressionQueryFactory.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/CriteriaTypeQueryFactory.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/HibernateOrmEntityLoadingStrategy.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/HibernateOrmQueryLoader.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/HqlTypeQueryFactory.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/LoadingTypeContext.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/TypeQueryFactory.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/AbstractHibernateOrmTypeContext.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmContainedTypeContext.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmIndexedTypeContext.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmTypeContextContainer.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/MassIndexer.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/MassIndexerFilteringTypeStep.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/MassIndexerReindexParameterStep.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/ConditionalExpression.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/HibernateOrmMassIndexer.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/HibernateOrmMassIndexerFilteringTypeStep.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/HibernateOrmMassIndexerReindexParameterStep.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/HibernateOrmMassIndexingContext.java
mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoDefaultMassIndexer.java

https://hibernate.atlassian.net/browse/HSEARCH-499

HSEARCH-499 Allow to filter elements to be indexed when mass-indexing

---

documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc
documentation/src/main/asciidoc/reference/backend-lucene.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-bridge-basics.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-indexing-jsr352.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-mapping-directfieldmapping.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-mapping-geopoint.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4220

HSEARCH-4220 Remove horizontal scrolling from the reference documentation

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4260

HSEARCH-4260 Display Java version during builds

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4260
Backport of #2615

Backport HSEARCH-4260 to branch 6.0 - Display Java version during builds

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4260
Backport of #2615

Backport HSEARCH-4260 to branch 5.11 - Display Java version during builds

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4260
Backport of #2615

Backport HSEARCH-4260 to branch 5.10 - Display Java version during builds

---

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ProgressiveCharBufferWriter.java

https://hibernate.atlassian.net/browse/HSEARCH-4248

HSEARCH-4248 Remove locks from ProgressiveCharBufferWriter 

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/FilteringOutboxEventFinder.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingAutomaticIndexingStrategyLifecycleIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingOutOfOrderIdsIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/DefaultOutboxEventFinder.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxAdditionalJaxbMappingProducer.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxEvent.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxEventBackgroundExecutor.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/BackendMock.java
util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/VerifyingStubBackendBehavior.java

https://hibernate.atlassian.net/browse/HSEARCH-4228
~~Based on #2617 that must be merged first.~~ done!

HSEARCH-4228 Ensure correct processing of events even if their IDs are out of order

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingOutOfOrderIdsIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingFailureIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxAdditionalJaxbMappingProducer.java

https://hibernate.atlassian.net/browse/HSEARCH-4265

HSEARCH-4265 Fix flaky tests with MS-SQL and Oracle

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingOutOfOrderIdsIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxAdditionalJaxbMappingProducer.java

https://hibernate.atlassian.net/browse/HSEARCH-4265

HSEARCH-4265 Make sure events are outdistanced

---

util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmUtils.java

https://hibernate.atlassian.net/browse/HSEARCH-4269

HSEARCH-4269 Fix assertion error on rollback being reported before the assertion error that triggered the rollback

---

util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmUtils.java

https://hibernate.atlassian.net/browse/HSEARCH-4269
Backport of #2625 .

Backport HSEARCH-4269 to branch 6.0 - Fix assertion error on rollback being reported before the assertion error that triggered the rollback

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4262

HSEARCH-4262 Upgrade to Hibernate ORM 5.3.21.Final

---

mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/HibernateOrmSelectionEntityByIdLoader.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/HibernateOrmSelectionEntityByNonIdPropertyLoader.java

https://hibernate.atlassian.net/browse/HSEARCH-4151

HSEARCH-4151 Reuse the same Query instance when executing multiple queries during entity loading

---

documentation/src/test/java/org/hibernate/search/documentation/gettingstarted/withouthsearch/GettingStartedWithoutHibernateSearchIT.java
integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/LibraryShowcaseOutOfSyncIndexIT.java
integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/service/TestDataService.java

https://hibernate.atlassian.net/browse/HSEARCH-4193

HSEARCH-4193 Fix tests wrongly using 0-based positional parameters with ORM

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4277

HSEARCH-4277 Upgrade to Awaitily 4.1.0

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4277
Backport of #2631

Backport HSEARCH-4277 to branch 6.0 - Upgrade to Awaitily 4.1.0

---

integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/limitations/ConcurrentEmbeddedUpdateLimitationIT.java
integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingOutOfOrderIdsIT.java
integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/query/timeout/Clock.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/DefaultOutboxEventFinder.java

https://hibernate.atlassian.net/browse/HSEARCH-4281

HSEARCH-4281 Fix tests for outbox event processing using different databases

---

util/common/pom.xml
util/common/src/main/java/org/hibernate/search/util/common/data/impl/Murmur3HashFunction.java

https://hibernate.atlassian.net/browse/HSEARCH-4291

HSEARCH-4291 Remove invalid dependencies from hibernate-search-util-common

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4279

HSEARCH-4279 Upgrade to Hibernate ORM 5.5.6.Final

---

CONTRIBUTING.md
Jenkinsfile
integrationtest/backend/elasticsearch/pom.xml
parents/integrationtest/pom.xml
pom.xml

* [HSEARCH-4292](https://hibernate.atlassian.net/browse/HSEARCH-4292): Stop testing against Open Distro for Elasticsearch in local mode
* [HSEARCH-4278](https://hibernate.atlassian.net/browse/HSEARCH-4278): Test against OpenSearch 1.0.0

HSEARCH-4278 + HSEARCH-4292 Test against OpenSearch 1.0.0

---

documentation/src/main/asciidoc/reference/mapper-orm-schema.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4298

HSEARCH-4298 Fix unfinished sentence in schema management documentation

---

documentation/src/main/asciidoc/migration/index.asciidoc
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/cfg/HibernateOrmMapperSettings.java

https://hibernate.atlassian.net/browse/HSEARCH-4309

HSEARCH-4309 Document deprecated/changed API/SPI/configuration in 6.1.0.Alpha1

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingConditionalExpressionsIT.java
mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/ConditionalExpressionQueryFactory.java

https://hibernate.atlassian.net/browse/HSEARCH-4266
It seems that the test is enough and we don't need to inspect the entities loaded by Hibernate ORM, as explained in the code comment.

HSEARCH-4266 Apply type condition outside user conditionals

---

documentation/src/main/asciidoc/reference/mapper-orm-indexing-automatic.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-mapping-alternatives.asciidoc
documentation/src/main/asciidoc/reference/mapper-orm-mapping-geopoint.asciidoc
documentation/src/main/asciidoc/reference/search-dsl-predicate.asciidoc
documentation/src/main/asciidoc/reference/search-dsl-query.asciidoc

https://hibernate.atlassian.net/browse/HSEARCH-4315

HSEARCH-4315 Fix example captions in documentation

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4311

HSEARCH-4311 Upgrade to Lucene 8.9

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4329

HSEARCH-4329 Upgrade to Lucene 8.10

---

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingIdClassIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4033

HSEARCH-4033 Test mass indexing of id class entity

---

pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-4332

HSEARCH-4332 Upgrade to Hibernate ORM 5.6.0.CR1

---

mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/impl/DatabasePollingOutboxEventAdditionalJaxbMappingProducer.java

https://hibernate.atlassian.net/browse/HSEARCH-4295

HSEARCH-4295 Change some property types for outbox event

---

documentation/src/main/asciidoc/reference/mapper-orm-bridge-propertybridge.asciidoc
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/bridge/propertybridge/bridgedelement/Invoice.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/bridge/propertybridge/bridgedelement/InvoiceLineItemsSummaryBinder.java
documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/bridge/propertybridge/bridgedelement/PropertyBridgeBridgedElementIT.java

https://hibernate.atlassian.net/browse/HSEARCH-4290

HSEARCH-4290 Add an example to the documentation using ".bridgedElement().name()" in a property binder

---

engine/src/main/java/org/hibernate/search/engine/backend/orchestration/spi/SingletonTask.java
engine/src/test/java/org/hibernate/search/engine/backend/orchestration/spi/SingletonTaskTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4363

HSEARCH-4363 NPE on closing SingletonTask still running a work

---

engine/src/main/java/org/hibernate/search/engine/backend/orchestration/spi/SingletonTask.java
engine/src/test/java/org/hibernate/search/engine/backend/orchestration/spi/SingletonTaskTest.java

https://hibernate.atlassian.net/browse/HSEARCH-4363
Backport of #2699

Backport to 6.0 of HSEARCH-4363 NPE on closing SingletonTask still running a work
