hibernate/hibernate-search

engine/src/main/java/org/hibernate/search/backend/impl/lucene/ChangesetList.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/SyncWorkProcessor.java, engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java
@gustavonalle (cc @Sanne) here is the fix I am thinking of.
I don't know how to properly test that situation. I walked the code for 1.5 hours and I cannot find the reason why an empty List<LuceneWork> arrives here. It *might* be due to a different problem?
To further track this down, I also added a log to be able to detect empty lists before they go to a different thread.
My changes pass the test suite. Not sure how much of that feature was covered though.
We can apply to master when you guys are happy.
=> HSEARCH-1769 Fix NoSuchElementException error in SyncWorkProcessor

engine/src/main/java/org/hibernate/search/backend/impl/lucene/AbstractWorkspaceImpl.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/IndexWriterDelegate.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/IndexWriterHolder.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/LuceneBackendQueueTask.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/LuceneBackendTaskStreamer.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/analysis/ConcurrentlyMutableAnalyzer.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/AddWorkExecutor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/ByTermDeleteWorkExecutor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/ByTermUpdateWorkExecutor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/DeleteByQueryWorkExecutor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/DeleteExtWorkExecutor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/DeleteWorkExecutor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/FlushWorkExecutor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/LuceneWorkExecutor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/OptimizeWorkExecutor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/PurgeAllWorkExecutor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/UpdateExtWorkExecutor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/works/UpdateWorkExecutor.java, engine/src/main/java/org/hibernate/search/store/Workspace.java, engine/src/main/java/org/hibernate/search/util/impl/ScopedAnalyzer.java, orm/src/test/java/org/hibernate/search/test/errorhandling/LuceneErrorHandlingTest.java
- https://hibernate.atlassian.net/browse/HSEARCH-1908
This is all to avoid invoking
IndexWriter.addDocument( document, analyzer )
as the only option in Lucene 5 is
IndexWriter.addDocument( document )
=> HSEARCH-1908 Avoid the need to dynamically override the Analyzer to fieldname mapping

engine/src/main/java/org/hibernate/search/store/impl/DirectoryProviderHelper.java, engine/src/main/java/org/hibernate/search/store/spi/DirectoryHelper.java, engine/src/main/java/org/hibernate/search/util/impl/FileHelper.java, engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java, integrationtest/performance/pom.xml, integrationtest/performance/src/test/java/org/hibernate/search/test/performance/TestRunnerArquillian.java, integrationtest/performance/src/test/java/org/hibernate/search/test/performance/scenario/TestReporter.java, integrationtest/performance/src/test/java/org/hibernate/search/test/performance/scenario/TestScenario.java, integrationtest/performance/src/test/resources/arquillian.xml, integrationtest/wildfly/pom.xml, integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/PackagerHelper.java, integrationtest/wildfly/src/test/resources/arquillian.xml, pom.xml
- https://hibernate.atlassian.net/browse/HSEARCH-1932
- https://hibernate.atlassian.net/browse/HSEARCH-1945
I didn't figure out a way to unit test the "." path resolution which wouldn't simply test that we use the API which we use.. a more reliable test is the fact that we re-enable the performance tests, which would previously fail because of the same "." resolution issue.
See https://github.com/hibernate/hibernate-search/pull/869 for the failure.
=> Improve directory creation and validation, enable performance tests again

integrationtest/performance/src/test/java/org/hibernate/search/test/performance/TestRunnerStandalone.java, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-1946
The problem is caused by some persistence unit that are included in the testing jar.
=> HSERCH-1946 left directories after test

backends/jgroups/src/test/java/org/hibernate/search/test/jgroups/common/MultipleSessionsSearchTestCase.java, engine/src/test/java/org/hibernate/search/test/jmx/MultipleStatisticsMBeanTest.java, engine/src/test/java/org/hibernate/search/test/jmx/SimpleJNDIHelper.java, engine/src/test/java/org/hibernate/search/testsupport/TestConstants.java, integrationtest/narayana/src/test/java/org/hibernate/search/test/integration/jbossjta/JBossTSIT.java, integrationtest/performance/src/test/java/org/hibernate/search/test/performance/TestRunnerArquillian.java, integrationtest/performance/src/test/java/org/hibernate/search/test/performance/scenario/TestReporter.java, integrationtest/sandbox/src/test/java/org/hibernate/search/test/performance/reader/ReaderPerformanceTestCase.java, orm/src/test/java/org/hibernate/search/test/DefaultTestResourceManager.java, orm/src/test/java/org/hibernate/search/test/SearchTestBase.java, orm/src/test/java/org/hibernate/search/test/jmx/IndexControlMBeanTest.java, orm/src/test/java/org/hibernate/search/test/jmx/IndexControlMBeanWithSuffixTest.java, orm/src/test/java/org/hibernate/search/test/jmx/MutableSearchFactoryAndJMXTest.java, orm/src/test/java/org/hibernate/search/test/jmx/NoMBeansEnabledTest.java, serialization/avro/src/test/java/org/hibernate/search/test/serialization/ProtocolBackwardCompatibilityTest.java
- https://hibernate.atlassian.net/browse/HSEARCH-2033
Several tests leak files on Windows, in particular the JGroups tests fail as they attempt to generate an invalid path.
The useage of H2 in the Narayana integration tests leads to an attempt to delete in-use files during teardown.
=> Testsuite leaks and windows build problems

engine/src/main/java/org/hibernate/search/query/dsl/MustJunction.java, engine/src/main/java/org/hibernate/search/query/dsl/impl/BooleanQueryBuilder.java, orm/src/test/java/org/hibernate/search/test/query/dsl/DSLTest.java
- https://hibernate.atlassian.net/browse/HSEARCH-2034
Allow users of the Query DSL to disable scoring, to improve performance when the intent is just to filter by some criteria.
=> HSEARCH-2034

documentation/src/main/asciidoc/mapping.asciidoc, engine/src/main/java/org/hibernate/search/bridge/MetadataProvidingFieldBridge.java, engine/src/main/java/org/hibernate/search/cfg/Environment.java, engine/src/main/java/org/hibernate/search/engine/impl/ImmutableSearchFactory.java, engine/src/main/java/org/hibernate/search/engine/impl/MutableSearchFactory.java, engine/src/main/java/org/hibernate/search/engine/integration/impl/ExtendedSearchIntegrator.java, engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java, engine/src/main/java/org/hibernate/search/engine/metadata/impl/TypeMetadata.java, engine/src/main/java/org/hibernate/search/engine/spi/DocumentBuilderIndexedEntity.java, engine/src/main/java/org/hibernate/search/query/engine/impl/LuceneHSQuery.java, engine/src/main/java/org/hibernate/search/query/engine/impl/SortConfigurations.java, engine/src/main/java/org/hibernate/search/reader/impl/ManagedMultiReader.java, engine/src/main/java/org/hibernate/search/reader/impl/MultiReaderFactory.java, engine/src/main/java/org/hibernate/search/spatial/SpatialFieldBridge.java, engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java, engine/src/test/java/org/hibernate/search/test/sorting/ManagedMultiReaderTest.java, orm/src/test/java/org/hibernate/search/test/query/Book.java, orm/src/test/java/org/hibernate/search/test/query/sorting/Explorer.java, orm/src/test/java/org/hibernate/search/test/query/sorting/SortOnFieldsFromCustomBridgeTest.java, orm/src/test/java/org/hibernate/search/test/query/sorting/SortTest.java, orm/src/test/java/org/hibernate/search/test/query/sorting/SortWithIndexUninvertingTest.java, orm/src/test/java/org/hibernate/search/test/query/sorting/Territory.java, orm/src/test/java/org/hibernate/search/test/spatial/POI.java, orm/src/test/java/org/hibernate/search/test/spatial/SpatialSearchSortByDistanceAndPagingTest.java, orm/src/test/resources/hibernate.properties
HSEARCH-2021: Adds a new optional `FieldBridge` sub-contract which allows implementations to expose the names of the sortable fields they created; Experimental, to be evolved into more complete means of exposing related meta-data down the road
HSEARCH-2043: Adding option to fail upon uncovered sorts which is useful for testing (by users and us); Defaults to not fail atm. which may be altered later on if we want to encourage users more actively to configure all sorts
HSEARCH-2042: Minor en-passant fix which avoids index uninverting in some cases
=> HSEARCH-2021 et al.: Allowing to sort on fields contributed by custom bridges

.travis.yml
With this commit, we should be able to enable Travis on the main repo with all the integration tests running!
=> HSEARCH-2217 Move Travis build to Trusty infrastructure and use Maven wrapper

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
NOTE: this takes into account the fact that the artifact and the package has been renamed to remove the "backend" part.
=> HSEARCH-2110 Update the Elasticsearch documentation prior to release

engine/src/main/java/org/hibernate/search/query/engine/impl/AbstractHSQuery.java, orm/src/test/java/org/hibernate/search/test/query/sorting/SortTest.java
https://hibernate.atlassian.net/browse/HSEARCH-2287
Clear the cache results when sort order is changed. It's especially important when using Elasticsearch because we cache much more things.
=> HSEARCH-2287 Clear the cached results when the sort order is changed

engine/src/main/java/org/hibernate/search/annotations/ProvidedId.java, orm/src/test/java/org/hibernate/search/test/id/CompositedIdMassIndexingTest.java, orm/src/test/java/org/hibernate/search/test/id/RegistrationId.java, orm/src/test/java/org/hibernate/search/test/id/StudentEntity.java, orm/src/test/java/org/hibernate/search/test/id/StudentFieldBridge.java
- https://hibernate.atlassian.net/browse/HSEARCH-2310
And adding a test insipred from a SO question, which was triggering wrong behaviour when annotated with @ProvidedId.
N.B. the test no longer uses ProvidedId so it's more of an illustration of how it should be done correctly.
=> Deprecating @ProvidedId

engine/src/main/java/org/hibernate/search/bridge/builtin/time/impl/LocalDateBridge.java, engine/src/test/java/org/hibernate/search/testsupport/BytemanHelper.java, pom.xml
- https://hibernate.atlassian.net/browse/HSEARCH-2316
- https://hibernate.atlassian.net/browse/HSEARCH-2317
- https://hibernate.atlassian.net/browse/HSEARCH-2318
=> Some minor improvements

.gitignore, distribution/src/main/assembly/dist.xml
And additional cleanup to the distribution.
* https://hibernate.atlassian.net/browse/HSEARCH-2323
=> HSEARCH-2323 Properly ignore hibernate-noorm-release-scripts directory

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/ElasticsearchQueries.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/JestClient.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/DefaultGsonService.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchHSQueryImpl.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/GsonService.java, elasticsearch/src/main/resources/META-INF/services/org.hibernate.search.elasticsearch.impl.GsonService
Mainly because Gson holds references to ThreadLocals, so having it stored in a static variable is not desirable.
JsonParser has been moved to private static variables, though, since it does not contain any data.
https://hibernate.atlassian.net/browse/HSEARCH-2170
=> HSEARCH-2170 Convert the GsonHolder to a Service to ensure cleanup

elasticsearch/pom.xml, engine/src/test/java/org/hibernate/search/test/backend/lucene/ScheduledCommitPolicyTest.java, orm/src/test/java/org/hibernate/search/test/backend/OptimizationTriggerTest.java, orm/src/test/java/org/hibernate/search/test/backend/WorkQueueLengthConfiguredTest.java, orm/src/test/java/org/hibernate/search/test/compression/CompressionTest.java, orm/src/test/java/org/hibernate/search/test/configuration/CustomBackendTest.java, orm/src/test/java/org/hibernate/search/test/configuration/ExclusiveIndexTest.java, orm/src/test/java/org/hibernate/search/test/configuration/IndexManagerOverrideTest.java, orm/src/test/java/org/hibernate/search/test/configuration/LuceneIndexingParametersTest.java, orm/src/test/java/org/hibernate/search/test/configuration/ShardsConfigurationTest.java, orm/src/test/java/org/hibernate/search/test/directoryProvider/CustomLockProviderTest.java, orm/src/test/java/org/hibernate/search/test/directoryProvider/DirectoryLifecycleTest.java, orm/src/test/java/org/hibernate/search/test/directoryProvider/FSDirectorySelectionTest.java, orm/src/test/java/org/hibernate/search/test/directoryProvider/FSDirectoryTest.java, orm/src/test/java/org/hibernate/search/test/directoryProvider/FSSlaveAndMasterDPTest.java, orm/src/test/java/org/hibernate/search/test/directoryProvider/RamDirectoryTest.java, orm/src/test/java/org/hibernate/search/test/directoryProvider/RetryInitializeTest.java, orm/src/test/java/org/hibernate/search/test/embedded/EmbeddedTest.java, orm/src/test/java/org/hibernate/search/test/embedded/nullindexed/NullEmbeddedTest.java, orm/src/test/java/org/hibernate/search/test/engine/optimizations/IndexReaderSeeOptimizedIndexTest.java, orm/src/test/java/org/hibernate/search/test/errorhandling/ConcurrentMergeErrorHandledTest.java, orm/src/test/java/org/hibernate/search/test/filter/FilterTest.java, orm/src/test/java/org/hibernate/search/test/query/TermVectorTest.java, orm/src/test/java/org/hibernate/search/test/query/dsl/DSLTest.java, orm/src/test/java/org/hibernate/search/test/query/sorting/SortWithIndexUninvertingTest.java, orm/src/test/java/org/hibernate/search/test/shards/DirectorySelectionTest.java, orm/src/test/java/org/hibernate/search/test/similarity/SimilarityTest.java
https://hibernate.atlassian.net/browse/HSEARCH-2390
Just a PR to reorganize test exclusions and match them with the tickets I just created. Most of those tickets identify the actual issue.
I also enabled some tests that happened to pass anyway.
The patch of the pom file is a bit unreadable, sorry about that... But I guess there's no other way.
=> HSEARCH-2390 Investigate and label test exclusions in the ES module

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-2436
=> HSEARCH-2436 Reference a ZonedDateTime bug with ES 2.4.1/5.0.0 in the Elasticsearch doc

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/ElasticsearchQueries.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchHSQueryImpl.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexManager.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexWorkVisitor.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/FieldHelper.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ToElasticsearch.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchClassBridgeIT.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchIndexMappingIT.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/GolfPlayer.java
Relevant tickets:
* https://hibernate.atlassian.net/browse/HSEARCH-2437
* https://hibernate.atlassian.net/browse/HSEARCH-2439 (it's linked because I only spotted the bug when trying out ES 5)
A few changes that would facilitate the ES 5 support, and yet do not break 2.x compatibility.
=> HSEARCH-2437 Prepare the support for Elasticsearch 5 (+ HSEARCH-2439)

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchHSQueryImpl.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchIT.java
This PR is based on #1192 (HSEARCH-2396), which will have to be merged first.
Relevant JIRA ticket: https://hibernate.atlassian.net/browse/HSEARCH-2253
=> HSEARCH-2253 Remove ID sort workaround using "_uid" in Elasticsearch

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexWorkVisitor.java, engine/src/main/java/org/hibernate/search/engine/spi/DocumentBuilderIndexedEntity.java, engine/src/main/java/org/hibernate/search/query/engine/impl/AbstractHSQuery.java, engine/src/test/java/org/hibernate/search/test/dsl/SortDSLTest.java, orm/src/test/java/org/hibernate/search/test/query/sorting/Explorer.java, orm/src/test/java/org/hibernate/search/test/query/sorting/Territory.java
This PR is based on #1197 (HSEARCH-2393), which will have to be merged first.
Relevant tickets:
* https://hibernate.atlassian.net/browse/HSEARCH-2330
* https://hibernate.atlassian.net/browse/HSEARCH-2261
I implemented the solution suggested in my last comment on HSEARCH-2330. By allowing `MetadataProvidingFieldBridge`s to override the field type, we end up removing the need for users to use workarounds, such as adding a @Numeric annotation on non-numeric properties that have a custom field bridge that will generate a numeric field. Now the whole knowledge about the type resides in the custom field bridge, which seems a bit cleaner.
=> HSEARCH-2330 (+	HSEARCH-2261) Allow MetadataProvidingFieldBridges to override field type 

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchHSQueryImpl.java, orm/src/test/java/org/hibernate/search/test/query/ProjectionQueryTest.java
This PR is based on #1197 (HSEARCH-2393), so we'll have to merge that one first.
Relevant JIRA ticket: https://hibernate.atlassian.net/browse/HSEARCH-2422
=> HSEARCH-2422 Always compute scores when projecting on the score in Elasticsearch

README.md, documentation/pom.xml, documentation/src/main/asciidoc/elasticsearch-integration.asciidoc, elasticsearch/pom.xml, pom.xml
~~This PR is based on HSEARCH-2437, so we need to merge #1206 first.~~ => Merged
Relevant JIRA ticket: https://hibernate.atlassian.net/browse/HSEARCH-2384
Not sure about this one...
Actually, there already was a parameter to test against another Elasticsearch version (kinda): we only need to pass `-DtestElasticsearchVersion=<myVersion>`.
Now, I polished it a bit, notably by including the parameter in the generated doc, but there's not much to do as long as we stay on ES 2.x.
On ES 5.x though, things get a bit tricky.
First thing: we have to use maven profiles, because the plugin configuration itself will change. Most notably, some dependencies are not available in ES 5 (the DeleteQuery plugin), and the elasticsearch-maven-plugin will be in a different version. Also, we need additional …
=> HSEARCH-2384 Make the Elasticsearch version used for integration tests a build parameter

engine/src/main/java/org/hibernate/search/bridge/impl/BridgeFactory.java, engine/src/main/java/org/hibernate/search/bridge/impl/ExtendedBridgeProvider.java, engine/src/main/java/org/hibernate/search/bridge/impl/TikaBridgeProvider.java, engine/src/main/java/org/hibernate/search/bridge/impl/XMemberBridgeProviderContext.java, engine/src/main/java/org/hibernate/search/bridge/spi/BridgeProvider.java, orm/src/test/java/org/hibernate/search/test/bridge/tika/Book.java, orm/src/test/java/org/hibernate/search/test/bridge/tika/TikaBridgeBlobSupportTest.java, orm/src/test/java/org/hibernate/search/test/bridge/tika/TikaBridgeInputTypeTest.java
https://hibernate.atlassian.net/browse/HSEARCH-2494
The issue is caused by to problems:
1. ExtendedBridgeProviderContext#getReturnType returns only the contained type for arrays and collections but the TikaBridgeProvider expects the complete type.
2. TikaBridge provider should overrides the default bridge we use for arrays.
I've also added a test to check the support for URI.
=> Hsearch 2494 tika bridge bug

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/cfg/ElasticsearchEnvironment.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/cfg/IndexSchemaManagementStrategy.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexManager.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/logging/impl/Log.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/schema/impl/DefaultElasticsearchSchemaCreator.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/schema/impl/ElasticsearchSchemaCreator.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchIndexExistsCheckIT.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchSchemaValidationIT.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/testutil/TestElasticsearchClient.java
https://hibernate.atlassian.net/browse/HSEARCH-2456
It appears we were not checking that the index at least existed in some situations, and more importantly we were not waiting for the index status to reach the expected level in some situations. This PR fixes that.
=> HSEARCH-2456 Wait for index status does not raise an exception

orm/src/test/java/org/hibernate/search/test/configuration/BlogEntry.java, orm/src/test/java/org/hibernate/search/test/configuration/ProgrammaticSearchMappingFactory.java, orm/src/test/java/org/hibernate/search/test/query/facet/Car.java
Analyzer definitions are no longer duplcated in the elasticsearch.yml
(since eac1a182a25fe373ef9490cbb8f9480ab2d19869).
=> Remove obsolete comments

elasticsearch/src/test/resources/hibernate.properties, integrationtest/osgi/karaf-features/src/main/features/features.xml, integrationtest/osgi/karaf-it/pom.xml, integrationtest/spring/src/test/resources/beans.xml, integrationtest/wildfly/pom.xml, integrationtest/wildfly/src/orm-module-override/module.xml, integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/MemberRegistrationIT.java, integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/PackagerHelper.java, orm/src/main/java/org/hibernate/search/FullTextQuery.java, orm/src/main/java/org/hibernate/search/impl/FullTextSharedSessionBuilderDelegator.java, orm/src/main/java/org/hibernate/search/query/hibernate/impl/FullTextQueryImpl.java, orm/src/test/java/org/hibernate/search/test/analyzer/AnalyzerTest.java, orm/src/test/java/org/hibernate/search/test/util/DdlTransactionIsolatorTestingImpl.java, orm/src/test/java/org/hibernate/search/test/util/MultitenancyTestHelper.java, orm/src/test/resources/hibernate.properties, pom.xml
This is for 5.7 only; we could backport the first two commits (HSEARCH-2549, HSEARCH-2550).
- https://hibernate.atlassian.net/browse/HSEARCH-2380
- https://hibernate.atlassian.net/browse/HSEARCH-2549
- https://hibernate.atlassian.net/browse/HSEARCH-2550
Related:
- https://hibernate.atlassian.net/browse/HHH-11309
=> Upgrade to Hibernate ORM 5.2.6

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-2558
=> HSEARCH-2558 Remove obsolete entries from the "limitations" section of the Elasticsearch integration documentation

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/cfg/IndexSchemaManagementStrategy.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexManager.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchIndexExistsCheckIT.java
https://hibernate.atlassian.net/browse/HSEARCH-2568
To be discussed, but it feels a bit strange that the `NONE` strategy does in fact do something (check if the index exists). This PR reverts the `NONE` strategy to the pre-HSEARCH-2456 behavior of not doing anything, not even checking whether the index exists.
I'm not sure we should backport this to 5.6, though, since it's a behavior change.
=> HSEARCH-2568 Do no check that the index exists with the NONE schema management strategy

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/BackendRequest.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/BackendRequestResultAssessor.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/JestClient.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/SingleRequest.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/DefaultBackendRequestResultAssessor.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/DeleteByQueryResultAssessor.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchHSQueryImpl.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexManager.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexWorkVisitor.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/JestAPIFormatter.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/logging/impl/Log.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/schema/impl/ElasticsearchSchemaAccessor.java, elasticsearch/src/main/resources/META-INF/services/org.hibernate.search.elasticsearch.impl.JestAPIFormatter
https://hibernate.atlassian.net/browse/HSEARCH-2569
This PR brings two changes:
1. The documentation is clearer about the fact that the 'delete-by-query' plugin is required when using the "purgeAll" option on the mass indexer, and this part of the documentation is more visible.
2. Whenever a user tries to purge indexes and a 404 error occurs, the error message now mentions that the 'delete-by-query' plugin is required.
We'll probably want to backport at least the first commit to 5.6.
=> HSEARCH-2569 Make the 'delete-by-query' plugin requirement for ES clearer

engine/src/main/java/org/hibernate/search/query/engine/impl/FacetManagerImpl.java, pom.xml
- https://hibernate.atlassian.net/browse/HSEARCH-2576
=> HSEARCH-2576 FacetingManager should allocate maps lazily

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-2580
**To be backported to 5.6**. Backport for 5.6 available there: https://github.com/yrodiere/hibernate-search/tree/HSEARCH-2580-5.6
=> HSEARCH-2580 Update of the "previous.stable" property following the 5.6.0.Final release

documentation/src/main/asciidoc/elasticsearch-integration.asciidoc, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/cfg/ElasticsearchEnvironment.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/JestClient.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/logging/impl/Log.java
https://hibernate.atlassian.net/browse/HSEARCH-2453
**To be backported to 5.6.1.**
Authentication was already possible, but a bit painful, since you had to
include the username and password in the host URLs. Which meant
repeating it over and over again when using multiple URLs, and also
meant you had to URL-encode the username and password yourself.
Tests are not included, because it's a pain to automate the setup of
authentication on the ES instance used for tests. Also, I'm quite sure
we can't do it with an embedded version of ES, and I don't even know if
the licensing terms would allow it (the Shield plugin is subject to a
commercial license).
To test manually, see:
https://www.elastic.co/blog/getting-started-with-elasticsearch-ssl-native-authentication
=> HSEARCH-2453 Add dedicated configuration options for Elasticsearch authentication

modules/pom.xml, modules/src/main/assembly/dist.xml, modules/src/main/modules/lucene/module.xml, pom.xml
This is to keep things easier until we don't actually move to use the separately packaged Lucene modules.
I'm including no tests as it's a temporary measure.
- https://hibernate.atlassian.net/browse/HSEARCH-2578
=> HSEARCH-2578 Include the lucene-grouping artifact in the WildFly modules

documentation/src/main/asciidoc/mapping.asciidoc, documentation/src/main/asciidoc/query.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-2602
=> HSEARCH-2602 Recommend using MetadataProvidingFieldBridge instead of byField(String, SortField.Type) in the Sort DSL

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/dialect/impl/es2/Elasticsearch2Dialect.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/dialect/impl/es5/Elasticsearch5Dialect.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/schema/impl/Elasticsearch5SchemaTranslator.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/schema/impl/Elasticsearch5SchemaValidator.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/schema/impl/model/NormsType.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/schema/impl/model/PropertyMapping.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/util/impl/gson/ES2NormsTypeJsonAdapter.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/util/impl/gson/ES5NormsTypeJsonAdapter.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/Elasticsearch5SchemaCreationIT.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/Elasticsearch5SchemaValidationIT.java
~~This PR is based on #1329, which will have to be merged first.~~ => Done
Relevant JIRA ticket: https://hibernate.atlassian.net/browse/HSEARCH-2353
I didn't add support for this on ES2 because the syntax is not the same as in ES5, it's more complex with more options (lazy/eager loading for instance). See [the docs for ES2](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/norms.html) and [the equivalent for ES5](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/norms.html).
I'm not convinced there would be much value, but if you want I can have a look at how to support norms on ES2.
=> HSEARCH-2353 Add support for the 'norms' mapping attribute with Elasticsearch 5

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/DefaultElasticsearchClient.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/DefaultElasticsearchClientFactory.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/testutil/ImportedTestRunner.java
See also JIRA description for the explanation:
- https://hibernate.atlassian.net/browse/HSEARCH-2681
=> Resolving the timeout exceptions we've seen on CI

pom.xml
The dependency convergence problem was avoided by ORM, just in time before the release, by changing the pom structure.
- https://hibernate.atlassian.net/browse/HSEARCH-2687
=> HSEARCH-2687 Upgrade Hibernate ORM to 5.2.10.Final

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/work/impl/ClearScrollWork.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchScrollingIT.java
https://hibernate.atlassian.net/browse/HSEARCH-2688
Note: there's no need to backport this after all, as explained in comments on the JIRA ticket.
=> HSEARCH-2688 Clearing scroll IDs (when closing ScrollableResults) fails systematically with Elasticsearch

distribution/pom.xml
Follow-up on #1378 , supersedes #1379
Relevant ticket (**I reopened it**): https://hibernate.atlassian.net/browse/HSEARCH-2698
We don't produce any JAR for this module, and we produce *multiple*
artifacts, so the easier solution is to just not declare anything.
The travis build is in progress: https://travis-ci.org/yrodiere/hibernate-search/builds/225892334
I ran a quick build locally without tests and it went fine.
=> HSEARCH-2698 Make the distribution module a POM artifact, instead of a JAR artifact

distribution/src/main/assembly/dist.xml
- https://hibernate.atlassian.net/browse/HSEARCH-2699
Turns out it was a dumb mistake.
=> HSEARCH-2699 Javassist not being included in the distribution tarballs

orm/src/main/java/org/hibernate/search/jpa/FullTextQuery.java
https://hibernate.atlassian.net/browse/HSEARCH-2667
Apparently that's all there is to do: the fact that these methods were
experimental wasn't mentioned in the documentation.
=> HSEARCH-2667 Fulltext Query timeout methods should no longer be flagged as experimental

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/logging/impl/Log.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/schema/impl/Elasticsearch2SchemaTranslator.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchSchemaMetadataErrorsIT.java, orm/src/test/java/org/hibernate/search/test/engine/Location.java
https://hibernate.atlassian.net/browse/HSEARCH-2458
To be perfectly clear, this situation only arises with Elasticsearch when applying a `@NumericField` annotation on a field that uses a non-numeric default bridge, or on a field that uses a custom bridge that doesn't provide metadata. So only when users misconfigured their mapping.
=> HSEARCH-2458 Throw an exception when an Elasticsearch field has incomplete metadata

.travis.yml
added hint that the main CI is http://ci.hibernate.org/ and that Travis is supposed to be used for github forks (see https://hibernate.atlassian.net/browse/HSEARCH-2712)
=> added hint to .travis.yml about deactivated state

backends/jgroups/pom.xml, elasticsearch/pom.xml, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/DefaultElasticsearchClientFactoryTest.java, engine/pom.xml, engine/src/test/java/org/hibernate/search/test/searchfactory/SearchFactoryTest.java, engine/src/test/java/org/hibernate/search/testsupport/serialization/SerializationTestHelper.java, engine/src/test/java/org/hibernate/search/testsupport/serialization/SerializationTestHelperTest.java, integrationtest/narayana/pom.xml, integrationtest/spring/pom.xml, integrationtest/wildfly/pom.xml, orm/pom.xml, orm/src/test/java/org/hibernate/search/test/batchindexing/MassIndexerErrorReportingTest.java, orm/src/test/java/org/hibernate/search/test/configuration/integration/HibernateSearchSessionFactoryObserverTest.java, orm/src/test/java/org/hibernate/search/test/errorhandling/ErrorHandlingDuringDocumentCreationTest.java, orm/src/test/java/org/hibernate/search/test/query/facet/FacetIndexingFailureTest.java, orm/src/test/java/org/hibernate/search/test/query/initandlookup/CriteriaObjectInitializerAndHierarchyInheritanceTest.java, orm/src/test/java/org/hibernate/search/test/query/initandlookup/ObjectLookupAndDatabaseRetrievalConfigurationTest.java, orm/src/test/java/org/hibernate/search/test/query/objectloading/ObjectLoaderHelperTest.java, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-2481
Note that only the last two commits (in topological order, so "HSEARCH-2481 Do not allow the maven-failsafe-plugin to scan the whole ..." and "HSEARCH-2481 Enable Byteman-based tests with Elasticsearch") are strictly necessary.
The other commits were my first attempts at solving the issue, but since they also clean up our poms, we may as well keep them.
=> HSEARCH-2481 Byteman-based tests executed in the Elasticsearch module won't work

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-2741
A build with this patch applied can be seen here: http://ci.hibernate.org/job/hibernate-search-yoann/1/
The build still has failing tests, but it's unrelated (seems to be a charset issue). I'm working on it and will submit another PR.
=> HSEARCH-2741 Fix dependency convergence issue between MariaDB and integration tests

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexWorkVisitor.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/processor/impl/ElasticsearchWorkProcessor.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/work/impl/ES2DeleteByQueryWork.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/work/impl/ES5DeleteByQueryWork.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/work/impl/factory/Elasticsearch2WorkFactory.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/work/impl/factory/Elasticsearch5WorkFactory.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/PurgeIT.java, engine/src/main/java/org/hibernate/search/engine/impl/WorkPlan.java
This PR is based on #1444, which should be merged first.
https://hibernate.atlassian.net//browse/HSEARCH-2761
@Sanne I added non-regression tests. Stricly speaking, only "HSEARCH-2761 Always refresh indexes before performing a delete-by-query" is needed to fix the issue, but the other commits fix hidden issues (discussed in the ticket).
=> HSEARCH-2761 Elasticsearch purges may fail when purging multiple classes of the same inheritance tree in the same transaction

backends/jgroups/src/test/java/org/hibernate/search/test/jgroups/common/DynamicMasterSlaveSearchTestCase.java, orm/src/test/java/org/hibernate/search/test/DefaultTestResourceManager.java, sharedtestresources/src/main/elasticsearch-maven-plugin/5.0/configuration/jvm.options
https://hibernate.atlassian.net//browse/HSEARCH-2762 fixes a memory issue preventing from executing tests in the Windows slaves of the CI
https://hibernate.atlassian.net//browse/HSEARCH-2743 fixes the actual problem
Proof: https://jenkins.hosts.mwqe.eng.bos.redhat.com/hudson/job/hibernate-search-master-windows-temp-yrodiere/7/
=> HSEARCH-2743 JGroupsDynamicMasterElectionTest fails on Windows

integrationtest/wildfly/src/test/resources/cdi/META-INF/services/javax.enterprise.inject.spi.Extension
It's a leftover from my experimentations...
=> Remove an obsolete Java service in Wildfly/CDI integration tests

documentation/src/main/asciidoc/mapping.asciidoc
The next title has 5 "=" ("====="), and so should this one.
=> Fix the level of the "normalizers" title in the mapping documentation

integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/wildfly/cdi/CDIInjectionIT.java
https://hibernate.atlassian.net//browse/HSEARCH-2788
=> HSEARCH-2788 Remove unnecessary calls to Thread.sleep in CDI/Wildfly tests

backends/jgroups/src/test/resources/log4j.properties, elasticsearch/src/test/resources/log4j.properties
This should help debug [HSEARCH-2682](https://hibernate.atlassian.net//browse/HSEARCH-2682) (not fixed yet), which I cannot reproduce on my machine, and which I'm having trouble to reproduce on the CI through repeated builds...
=> Enable Apache HTTP and Elasticsearch RestClient logs in tests

engine/src/test/java/org/hibernate/search/test/dsl/DSLTest.java, engine/src/test/java/org/hibernate/search/testsupport/junit/SearchITHelper.java
https://hibernate.atlassian.net//browse/HSEARCH-2807
=> HSEARCH-2807 DSLTest numeric tests use order-sensitive assertions on queries without a sort

integrationtest/elasticsearch/src/test/java/org/hibernate/search/elasticsearch/testutil/TestElasticsearchClient.java, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-2809
Tests in progress on Travis + Jenkins.
=> HSEARCH-2809 Upgrade to Elasticsearch 5.5.0

elasticsearch-aws/src/main/java/org/hibernate/search/elasticsearch/aws/impl/AWSSigningRequestInterceptor.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/spi/DigestSelfSigningCapable.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/util/impl/ElasticsearchClientUtils.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/util/impl/GsonHttpEntity.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/GsonStreamedEncodingTest.java
Similar optimisations as proposed before but using a different approach, now more carefully taking into account the AWS digest requests.
Also taking into account flow control of the underlying buffers, this was a bug in the previous proposal.
https://hibernate.atlassian.net/browse/HSEARCH-2818
=> HSEARCH-2818 Optimise encoding of GSON elements into HTTP client buffers

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java, orm/src/test/java/org/hibernate/search/test/spatial/SpatialContainedInTest.java
https://hibernate.atlassian.net//browse/HSEARCH-2858
To be backported to 5.6 and 5.7. Maybe even 5.5, but I didn't try that one.
=> HSEARCH-2858 Using @ContainedIn in a @Spatial-annotated entity triggers a NullPointerException on startup

engine/src/main/java/org/hibernate/search/engine/metadata/impl/AnnotationMetadataProvider.java, orm/src/main/java/org/hibernate/search/event/impl/FullTextIndexEventListener.java, orm/src/test/java/org/hibernate/search/test/engine/optimizations/BridgedReverseBagCollectionUpdateEventTest.java, orm/src/test/java/org/hibernate/search/test/engine/optimizations/CollectionUpdateEventTest.java
https://hibernate.atlassian.net//browse/HSEARCH-2868
Please do not mark the ticket as resolved just yet: backports are needed for at least 5.7 and 5.6. I'll send PRs soon.
=> HSEARCH-2868 Collection updates may not trigger reindexing despite @ContainedIn in some circumstances

elasticsearch/pom.xml, modules/src/main/assembly/dist.xml, modules/src/main/modules/es-client/module.xml, modules/src/main/modules/es-sniffer/module.xml, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-2870
Tested on 2.2+, 5.1, 5.6: https://travis-ci.org/yrodiere/hibernate-search/builds/274503473
Test in progress on AWS (5.3): http://ci.hibernate.org/view/Personal%20runs/job/hibernate-search-master-elasticsearchAWS-yoann/12/
=> HSEARCH-2870 Test compatibility, upgrade to Elasticsearch 5.6

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/logging/impl/ElasticsearchRequestFormatter.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/logging/impl/ElasticsearchResponseFormatter.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/logging/impl/Log.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/util/impl/JsonLogHelper.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/work/impl/BulkWork.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/work/impl/SimpleBulkableElasticsearchWork.java, elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/LogTest.java
https://hibernate.atlassian.net//browse/HSEARCH-2832
This makes exceptions much shorter by removing the body of each request from the exception message.
Rationale:
* when something was wrong in the request body, Elasticsearch error messages include a snippet of what was wrong, so the request body is not strictly necessary
* in case of recurring issues, users can always enable request logging
* when a lot of exception occur, for instance because the ES server is down, or security is mis-configured, including the full body of each request leads to huge exception messages, to the point of being unreadable and consuming a significant amount of resources.
While this PR does not solve the issue completely, at least it reduces the magnitude of the problem by several factors: most requests are …
=> HSEARCH-2832 Hibernate Search produces huge stack traces when Elasticsearch request processing threads are interrupted

integrationtest/performance/engine-elasticsearch/src/main/java/org/hibernate/search/engineperformance/elasticsearch/stub/BlackholeElasticsearchClient.java
https://hibernate.atlassian.net//browse/HSEARCH-2883
To be backported to 5.8, I guess (it's not useful to users, but since we backported the previous commits for the same ticket...)
=> HSEARCH-2883 Follow-up: perfomance tests fix

integrationtest/jdk9-modules/pom.xml
I forgot to add the dependency to the database driver... Before the
HSEARCH-2905 fix, the dependency was implicitly added for every module.
Ticket (already resolved): https://hibernate.atlassian.net/browse/HSEARCH-2905
=> HSEARCH-2905 Follow-up: Fix JDK9 modules test following database profile changes

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-2927 (Update to Apache Lucene 5.5.5)
Opening a PR instead of merging the backport directly, since 5.6 was not originally marked for backport.
@Sanne any reason not to backport?
=> HSEARCH-2927 Backport to 5.6

integrationtest/jsr352/pom.xml, integrationtest/jsr352/src/test/java/org/hibernate/search/jsr352/massindexing/BatchIndexingJobIT.java, integrationtest/jsr352/src/test/java/org/hibernate/search/jsr352/massindexing/MassIndexingJobWithCompositeIdIT.java, jsr352/core/src/test/java/org/hibernate/search/jsr352/massindexing/test/entity/Person.java, jsr352/core/src/test/java/org/hibernate/search/jsr352/test/util/JobTestUtil.java
https://hibernate.atlassian.net//browse/HSEARCH-2930
https://hibernate.atlassian.net//browse/HSEARCH-2931
https://hibernate.atlassian.net//browse/HSEARCH-2932
Note: this does not fix tests on MariaDB completely, only part of it. We'll have to wait for https://hibernate.atlassian.net/browse/HSEARCH-2933[HSEARCH-2933] to be fixed before JSR-352 can work with the MariaDB JDBC driver.
=> HSEARCH-2930 + HSEARCH-2931 + HSEARCH-2932 JSR-352 test fixes

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/client/impl/ElasticsearchRequest.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ElasticsearchIndexManager.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/processor/impl/AbstractBarrierElasticsearchWorkOrchestrator.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/processor/impl/BarrierElasticsearchWorkOrchestrator.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/processor/impl/BatchingSharedElasticsearchWorkOrchestrator.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/processor/impl/ElasticsearchWorkOrchestrator.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/processor/impl/ElasticsearchWorkProcessor.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/LazyExecutorHolder.java, engine/src/main/java/org/hibernate/search/backend/impl/lucene/LuceneBackendQueueTask.java, engine/src/main/java/org/hibernate/search/util/logging/impl/BaseHibernateSearchLogger.java, engine/src/test/java/org/hibernate/search/testsupport/setup/SearchConfigurationForTest.java, integrationtest/elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/ElasticsearchIndexManagerClosingIT.java
https://hibernate.atlassian.net//browse/HSEARCH-2934
The solution I chose was to provide each index manager with its own view of the stream orchestrator, so that it can close its view when closing the index manager, which will automatically wait for pending stream works to be executed.
I could have simply added an explicit wait on the "shared" stream orchestrator, but my solution has the additional benefit of preventing new stream works to be accepted by the index manager while waiting for pending stream works to be executed.
=> HSEARCH-2934 Pending Elasticsearch streamed works may fail when stopping Hibernate Search and using the drop-and-create-and-drop strategy

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-2933
Proof the JSR-352 tests now work on MariaDB: http://ci.hibernate.org/job/hibernate-search-yoann/187/ (still a dead link because the build is pending at the moment).
=> HSEARCH-2933 Upgrade to a version of the MariaDB driver not affected by CONJ-541

integrationtest/wildfly/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-2963
I also added an EnforcerRule [_"Ban Duplicate Pom Dependency Versions"_][1] to avoid similar ambiguity in the future.
[1]: https://maven.apache.org/enforcer/enforcer-rules/banDuplicatePomDependencyVersions.html
=>  HSEARCH-2963 Remove duplicate dependency declarations

jsr352/core/pom.xml, jsr352/core/src/main/java/org/hibernate/search/jsr352/massindexing/impl/steps/lucene/EntityReader.java, jsr352/core/src/main/java/org/hibernate/search/jsr352/massindexing/impl/steps/lucene/PartitionMapper.java, jsr352/core/src/test/java/org/hibernate/search/jsr352/massindexing/impl/steps/lucene/EntityReaderTest.java, jsr352/core/src/test/java/org/hibernate/search/jsr352/massindexing/impl/steps/lucene/PartitionMapperTest.java, jsr352/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-2958
The first 2 commits transferred Mockito tests into EasyMock tests. But later, I realized that there's even no need to use mock! Using Java polymorphisme did the work, so I pushed my 3rd commit. I didn't squash them into one because I'm not sure if you want to keep the EasyMock version or the no-mock one.
=>  HSEARCH-2958 Rework Mockito tests

documentation/pom.xml, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-2967
Downsides:
1. Links to internal classes from API/SPI will be dead links. There are some, unfortunately, for example from `AbstractDocumentBuilder` to `TypeMetadata`.
2. We will have some errors in the logs (example below) because some artifacts do not have any SPI or API, so their javadoc is not generated. When times come for the aggregation, their javadoc cannot be found and this error appears. Everything works fine though, since the error is ignored.
Example of errors:
```
[ERROR] Error fetching link: /home/travis/build/yrodiere/hibernate-search/serialization/avro/target/site/apidocs/package-list. Ignored it.
```
=> HSEARCH-2967 Remove internal classes from the Javadoc

distribution/pom.xml, distribution/src/main/assembly/dist.xml
* https://hibernate.atlassian.net//browse/HSEARCH-2972 Missing provided dependencies in the distribution ZIP
* https://hibernate.atlassian.net/browse/HSEARCH-2984 Remove an unnecessary jberet dependency in the distribution module
The added dependencies are licensed under ASL2, so this should be fine.
=> HSEARCH-2972 + HSEARCH-2984 Fix dependencies in the distribution ZIP

pom.xml
Everything is now defined in the "jbossmodules" POM, and is derived from
properties set in the parent POM.
https://hibernate.atlassian.net//browse/HSEARCH-2191
=> HSEARCH-2191 follow-up: Remove the now-unused property "hibernate-search.module.slot"

documentation/src/main/asciidoc/configuration.asciidoc
https://hibernate.atlassian.net//browse/HSEARCH-2191
Simply referring to the ORM documentation for WildFly isn't enough
anymore, since with Hibernate Search we install ORM modules differently.
So we'd better explain ORM specifics as well.
=>  HSEARCH-2191 follow-up: Include ORM specifics in the WildFly configuration doc

integrationtest/jdk9-modules/src/main/java/module-info.java
Follow-up to the previous PR #1598, because the JDK9 build started to fail.
@Sanne On a related note, the Hibernate ORM team defined module names explicitly in their manifest. Maybe we should do it for Search, too? Would org.hibernate.search.* work for you?
=> Follow-up to HSEARCH-2978 - Use the new automatic module name for Hibernate ORM 5.3 in JDK9 tests

pom.xml
- https://hibernate.atlassian.net/browse/HSEARCH-3005
The required dependency was just released on Nexus. Will probably take some time to be available in central.
=> HSEARCH-3005 Upgrade to Hibernate Commons Annotations 5.0.2.Final

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3017
The dependency versions in Hibernate-core did not change.
=> HSEARCH-3017 Upgrade to Hibernate ORM 5.3.0.CR1

pom.xml
This is a plugin we're now using on Infinispan to spot CVEs in case you're interested. 
The report is saved on ```target/dependency-check-report.html``` and can be generated with 
```mvn -Powasp clean install -DskipTests=true```
=> Add profile for the maven-dependency-check plugin

documentation/src/main/asciidoc/advanced-features.asciidoc
https://hibernate.atlassian.net//browse/HSEARCH-3033
=> HSEARCH-3033 Internal links to "section-custom-similarity" in the documentation are dead

engine/src/main/java/org/hibernate/search/engine/impl/ImmutableSearchIntegration.java
=> Backport to 5.9: HSEARCH-3132 Normalizers are not closed on shutdown

integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/jsr352/massindexing/RemoteExecutionIT.java, integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/jsr352/massindexing/RestartIT.java, integrationtest/wildfly/src/test/java/org/hibernate/search/test/integration/jsr352/massindexing/test/util/ManagementClientJobTestUtil.java, integrationtest/wildfly/src/test/resources/jboss-deployment-structure-jsr352-wildflycontroller.xml
https://hibernate.atlassian.net//browse/HSEARCH-2614
Here we use WildFly's management APIs to start/restart jobs;
see https://docs.jboss.org/author/display/WFLY/Batch+%28JSR-352%29+Subsystem+Configuration#Batch%28JSR-352%29SubsystemConfiguration-DeploymentResources
=> HSEARCH-2614 JSR-352: Test starting/stopping the job using WildFly tooling (e.g. CLI) 

jbossmodules/pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3183
=> HSEARCH-3183 Remove obsolete and invalid Maven configuration in hibernate-search-jbossmodules-parent

jbossmodules/pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3183
#1687 should be merged first.
=> Backport HSEARCH-3183 to branch 5.10 - Remove obsolete and invalid Maven configuration in hibernate-search-jbossmodules-parent

integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/HibernateSearchWithKarafIT.java, integrationtest/osgi/karaf-it/src/test/resources/maven.properties, integrationtest/performance/orm/pom.xml, integrationtest/performance/orm/src/test/resources/arquillian.xml, integrationtest/wildfly/pom.xml, integrationtest/wildfly/src/test/resources/arquillian.xml, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3172
https://hibernate.atlassian.net/browse/HSEARCH-3184
https://hibernate.atlassian.net/browse/HSEARCH-3188
The first and last commits are only cleanup.
The second commit actually fixes the JaCoCo problem.
The third commit is not absolutely necessary, but it seems to make more sense that way... Also, it allows to make IDEA generate the WildFly instance by setting "Maven > Importing > Phase to be used for folders update" to "process-test-resources" in the IDEA settings, then clicking the "Generate Sources and Update Folders for All Projects" button in the Maven tool panel.
There doesn't seem to be any way to make IDEA generate the WildFly instance automatically, at least not without heavy customization of your IDEA project configuration.
=> HSEARCH-3172 + HSEARCH-3184 + HSEARCH-3188 Fix build problems affecting IDEA

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ToElasticsearch.java, engine/src/main/java/org/hibernate/search/query/dsl/BooleanJunction.java, engine/src/main/java/org/hibernate/search/query/dsl/impl/BooleanQueryBuilder.java, engine/src/main/java/org/hibernate/search/query/dsl/impl/MinimumShouldMatchContextImpl.java, engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java, engine/src/test/java/org/hibernate/search/test/dsl/BoolDSLTest.java
https://hibernate.atlassian.net//browse/HSEARCH-3197
This is a backport of work done in the Search 6 proof of concept: https://github.com/hibernate/hibernate-search-6-poc/pull/68
I think the syntax works fine even with Search 5. The only doubt I have is regarding the `.end()` syntax, which we don't have anywhere else in Search 5 and might be renamed in 6 at some point (to `.up()` for instance).
=> Backport to 5.11: HSEARCH-3197 Allow to set the minimum number of should clauses required to match for boolean predicates in the DSL

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/impl/ToElasticsearch.java, engine/src/main/java/org/hibernate/search/query/dsl/BooleanJunction.java, engine/src/main/java/org/hibernate/search/query/dsl/impl/BooleanQueryBuilder.java, engine/src/main/java/org/hibernate/search/query/dsl/impl/MinimumShouldMatchContextImpl.java, engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java, engine/src/test/java/org/hibernate/search/test/dsl/BoolDSLTest.java
https://hibernate.atlassian.net//browse/HSEARCH-3197
Backport of #1694 , which should be merged first.
=> Backport HSEARCH-3197 to branch 5.10 - Allow to set the minimum number of should clauses required to match for boolean predicates in the DSL

engine/src/main/java/org/hibernate/search/backend/impl/lucene/analysis/ConcurrentlyMutableAnalyzer.java
Checkstyle is updating one of its checks (`RightCurlyCheck`) in accordance with issue [#4022](https://github.com/checkstyle/checkstyle/issues/4022). The corresponding PR [#4247](https://github.com/checkstyle/checkstyle/pull/4247) has wercker CI failure due to an unexpected violation with Hibernate Search. 
Please have a look at [PR #4247 comment](https://github.com/checkstyle/checkstyle/pull/4247#issuecomment-400294580) and the ones that follow for further reference.
This PR formats the code so as to sync the style with the latest updates in checkstyle.
=> Formatted code to avoid validation problems with future checkstyle releases

elasticsearch/pom.xml, integrationtest/elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/Elasticsearch2IndexMappingIT.java, integrationtest/elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/Elasticsearch5IndexMappingIT.java, orm/pom.xml, pom.xml, testing/pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3226
This does not fix everything, far from it, but at least the tests now mostly pass with JDK11.
Disabling a feature of JAXB is necessary in order for the tests to run with JDK11, because this feature makes use of `sun.misc.Unsafe`. So I disabled it in tests. The feature is apparently going to be removed in the next release of JAXB, see the commit message.
In the end I had to add a dependency to javax.xml.bind in the Elasticsearch module. For now the dependency only shows up when building with JDK9 and above, which means our released JARs simply will not work with JDK11. I will try to remove the dependency as part of https://hibernate.atlassian.net/browse/HSEARCH-3237, and if I can't, we'll see what we want to do. On the bright side, we …
=> HSEARCH-3226 Add test dependencies to javax.xml.bind when building with JDK9 and above

elasticsearch/pom.xml, integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/HibernateSearchWithKarafIT.java, integrationtest/osgi/karaf-it/src/test/resources/maven.properties, integrationtest/performance/orm/pom.xml, integrationtest/performance/orm/src/test/resources/arquillian.xml, integrationtest/wildfly/pom.xml, integrationtest/wildfly/src/test/resources/arquillian.xml, orm/pom.xml, pom.xml, testing/pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3219
https://hibernate.atlassian.net//browse/HSEARCH-3224
https://hibernate.atlassian.net//browse/HSEARCH-3232
https://hibernate.atlassian.net//browse/HSEARCH-3236
https://hibernate.atlassian.net//browse/HSEARCH-3235
https://hibernate.atlassian.net//browse/HSEARCH-3226
https://hibernate.atlassian.net//browse/HSEARCH-3241
Must wait for #1711 to be merged first.
Not sure it's worth it, let's discuss this.
We want to make Search work with JDK11 ultimately, and a version of HSearch compatible with JDK11 should ship with Wildfly 14, ideally.
We have to options:
* Release a micro on the 5.10 branch and update WF14 to use that micro
* Release a 5.11.0 and update WF14 to use 5.11.0
So far, the amount of changes is not enough to justify a 5.11, so …
=> JDK11 related 5.10 backports

.travis.yml
https://hibernate.atlassian.net//browse/HSEARCH-3240
#1709 should be merged first.
=> Backport HSEARCH-3240 to branch 5.10 - Use the pre-installed JDK in the Travis build instead of trying to update it in each build

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3234
Creating this to let the CI test it.
=> Backport HSEARCH-3234 to branch 5.10 - Upgrade to ORM 5.3.3

engine/src/main/java/org/hibernate/search/query/dsl/impl/ConnectedQueryContextBuilder.java, engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java, engine/src/test/java/org/hibernate/search/test/dsl/DSLTest.java, engine/src/test/java/org/hibernate/search/test/dsl/Month.java
https://hibernate.atlassian.net//browse/HSEARCH-3233
#1714 should be merged first.
=> Backport HSEARCH-3233 to branch 5.10 - Overriding an analyzer in the queryBuilder with an unknown analyzer should lead to a proper SearchException

integrationtest/performance/orm/pom.xml, integrationtest/wildfly/pom.xml, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3248
Tested locally against JDK 9.0.4: it works.
Note the problem probably also affected JDK11, but I can't test it since other failures happen earlier in the bootstrap process.
=> HSEARCH-3248 Restore lenient illegal access checks on the client side of Arquillian during integration tests

integrationtest/performance/orm/pom.xml, integrationtest/wildfly/pom.xml, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3248
Should be merged after #1717
=> Backport HSEARCH-3248 to branch 5.10 - Restore lenient illegal access checks on the client side of Arquillian during integration tests

legacy/pom.xml
I made a mistake in ee805bb
Full build passed: http://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-yoann/detail/HSEARCH-3179/21/pipeline
=> Follow-up to HSEARCH-3179: Fix invalid OSGi version range in legacy POM

Jenkinsfile
https://hibernate.atlassian.net//browse/HSEARCH-3246
~Based on #1723 , which should be merged first.~ => Done
=> HSEARCH-3246 Generate Coveralls and Sonar reports from the Jenkinsfile instead of Travis

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3343
This is a backport of #1734 to branch 5.10.
=> Backport HSEARCH-3343 to branch 5.10 - Upgrade to Hibernate ORM 5.3.6.Final

Jenkinsfile
https://hibernate.atlassian.net//browse/HSEARCH-3341
This one is a bit embarrassing... I tested it, it should work now: I got a FAILURE notification for http://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-yoann/detail/ci-test-this-please/8/pipeline .
=> HSEARCH-3341 Do not send SUCCESS notifications when a  Jenkins pipeline build fails or is cancelled

.empty/README.md, integrationtest/backend/tck/pom.xml, pom.xml, util/internal/integrationtest/pom.xml, util/internal/test/pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3348
It's a rather ugly hack, but I couldn't find any other way. At least it should not cause much maintenance hassle.
Results of a full analysis after this patch: https://sonarcloud.io/project/activity?branch=sonartest-yrodiere&id=org.hibernate.search%3Ahibernate-search-parent&selected_date=2018-09-11T11%3A54%3A22%2B0000
To be compared with: https://sonarcloud.io/project/activity?id=org.hibernate.search%3Ahibernate-search-parent&selected_date=2018-09-11T12%3A13%3A24%2B0000
So yeah, that's quite a lot of noise we got rid of.
=> HSEARCH-3348 Consider backend TCK and test utils as test code during the Sonar analysis

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/ProxyIT.java
https://hibernate.atlassian.net//browse/HSEARCH-383
~Based on #1740, which should be merged first.~ => Done
I doubt the problem was still relevant even in Search 5, but the test makes sense, so let's just add it.
=> HSEARCH-383 Hibernate Search does not respect the @AccessType annotation in respect to @Id fields.

Jenkinsfile
https://hibernate.atlassian.net//browse/HSEARCH-3332
"PR decoration" means:
* Sonarcloud will leave a review for each push, with a comment for each issue found in the changeset (including a link to the issue on sonarcloud.io)
* A check will be added at the bottom of the PR, next to the PR build status and the review status
You can find an example of PR decoration here: https://github.com/yrodiere/hibernate-search/pull/35
History:
* I first pushed a PR with a few issues: Sonarcloud posted the first review, the Sonarcloud check was set to "Failed".
* Then Coveralls posted its own comment.
* Then I force-pushed to fix the issues: the check status was updated (to green), but unfortunately the Sonarcloud review was not updated Probably not a big deal.
* Then I force-pushed to add issues again: …
=> HSEARCH-3332 Activate GitHub pull request decoration in Sonar

Jenkinsfile, build-config/pom.xml, documentation/pom.xml, integrationtest/pom.xml, legacy/pom.xml, pom.xml, reports/pom.xml, util/internal/integrationtest/pom.xml, util/internal/integrationtest/sharedresources/pom.xml, util/internal/test/pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3340
https://hibernate.atlassian.net//browse/HSEARCH-3334
This PR is twofold:
* First, as part of HSEARCH-3340, I tried to restore something similar to nightly releases for master and maintenance branches. As it turns out, it's easier to just deploy snapshot artifacts as part of the main build, so that's what I did. Apparently the JBoss Nexus removes the older artifacts for a given snapshot version each time we deploy, so this shouldn't cause storage space issues.
* Second, since the snapshot artifact deployment is now done as part of the main build, a failing integration test could lead to a partial deployment: some artifacts are on Nexus, others are not. I had a look at HSEARCH-3334, and it turns out that just using the …
=> HSEARCH-3340 + HSEARCH-3334 Add support for snapshot releases to the Jenkinsfile

integrationtest/osgi/karaf-features/src/main/features/features.xml, integrationtest/osgi/karaf-it/pom.xml, integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/HibernateSearchWithKarafIT.java, integrationtest/osgi/karaf-it/src/test/resources/maven.properties, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3377
https://hibernate.atlassian.net/browse/HSEARCH-3151
This PR is a backport of #1750 , which should be reviewed and merged first.
After this PR, the entire build passes with JDK10, proving for good that we already had JDK10 compatibility. I ran the tests locally.
As to JDK11, there is still some work to do: [HSEARCH-3238](https://hibernate.atlassian.net/browse/HSEARCH-3238), [HSEARCH-3380](https://hibernate.atlassian.net/browse/HSEARCH-3380).
=> Backport to 5.10:  HSEARCH-3377 + HSEARCH-3151 - JDK10 build compatibility

Jenkinsfile, build-config/src/main/resources/forbidden-runtime.txt, legacy/integrationtest/osgi/karaf-features/src/main/features/features.xml, legacy/integrationtest/osgi/karaf-it/pom.xml, legacy/integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/HibernateSearchWithKarafIT.java, legacy/integrationtest/osgi/karaf-it/src/test/resources/maven.properties, legacy/pom.xml, mapper/orm/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3377
https://hibernate.atlassian.net/browse/HSEARCH-3362 
https://hibernate.atlassian.net/browse/HSEARCH-3226 (follow-up on #1708)
https://hibernate.atlassian.net/browse/HSEARCH-3151
So, this is just a matter of making the build compatible with JDK10 again, following the merge of Search 6 code into master. This also happens to solve most issues preventing the build from passing with JDK11, though [there is still some work to do](https://hibernate.atlassian.net/browse/HSEARCH-3238)
See [this build](http://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-yoann/detail/jdk10/5/pipeline/51) for a proof the JDK10 build now passes.
Note that legacy ITs also pass with JDK10, but we don't execute them in JDK10/JDK11 builds on CI. I'll send …
=>  HSEARCH-3377 +  HSEARCH-3362 +  HSEARCH-3226 + HSEARCH-3151 : JDK10 build compatibility on master branch

distribution/pom.xml, distribution/src/main/assembly/dist.xml, legacy/pom.xml, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3335
I tried to improve the configuration while I was at it, so that we don't have to explicitly list the dependencies anymore: any new dependency will be added automatically. The only updates we will have to perform manually are:
* When we add a new module
* When we add a provided dependency
* When we change the inter-module dependencies (though if we forget to update in this case, the worst thing that can happen is that some JAR will appear twice)
To test it quickly, run this:
```
mvn clean install -DskipTests -Pdist -pl distribution -am -Dmaven.javadoc.skip=true
```
The distribution bundles will be in `distribution/target/dist/`
I'm not sure if we should merge the last commit, any opinion on that? I'll copy the commit message with the …
=> HSEARCH-3335 Search 6 groundwork - Restore the distribution module

legacy/integrationtest/osgi/karaf-features/src/main/features/features.xml
https://hibernate.atlassian.net//browse/HSEARCH-3380
This is just a hack, but hopefully we'll be able to remove it, along with all the explicit dependencies to JAXB, when Hibernate ORM is fixed and we fix [HSEARCH-3376](https://hibernate.atlassian.net//browse/HSEARCH-3376)
=> HSEARCH-3380 Find a way to add JAXB modules to the OSGi feature in OSGi integration tests

integrationtest/osgi/karaf-it/pom.xml, integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/HibernateSearchWithKarafIT.java
https://hibernate.atlassian.net//browse/HSEARCH-3396
This is based on #1769 , which should be merged first.
=> Backport HSEARCH-3396 to branch 5.10 - Allow to use snapshot artifacts in OSGi integration tests

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/nonregression/automaticindexing/ContainedInTriggerUnnecessaryCollectionInitialization.java
https://hibernate.atlassian.net//browse/HSEARCH-1710
Note I added a separate package dedicated to non-regression tests, so that we can differentiate between those and actual, more complete functional tests. Hopefully that will make it easier to find the most relevant tests when we need to add a functional test: in most cases we don't want to change a non-regression tests, but we sometimes want to add tests to a functional test class.
I'm open to revisit this if you think it's unnecessary.
=> HSEARCH-1710 Child collection being unnecessarily initialized through @ContainedIn

integrationtest/osgi/karaf-features/src/main/features/features.xml
https://hibernate.atlassian.net//browse/HSEARCH-3380
Waiting for CI, then I'll merge it.
=> Backport HSEARCH-3380 to branch 5.10 - Find a way to add JAXB modules to the OSGi feature in OSGi integration tests

documentation/pom.xml, documentation/src/main/asciidoc/getting-started.asciidoc, documentation/src/test/java/org/hibernate/search/gettingstarted/example/GeoPolygonTest.java, documentation/src/test/java/org/hibernate/search/gettingstarted/model/after/Author.java, documentation/src/test/java/org/hibernate/search/gettingstarted/model/after/Book.java, documentation/src/test/java/org/hibernate/search/gettingstarted/model/before/Author.java, documentation/src/test/java/org/hibernate/search/gettingstarted/model/before/Book.java
https://hibernate.atlassian.net/browse/HSEARCH-2328
I've added a couple of entities in the "Getting Started" section to test that it works.
It's safe to exclude the related commit (https://github.com/hibernate/hibernate-search/commit/8892ed37cb847a2113c0345c9e9bcfec01e627d5) if we want to keep the doc clear.
=> HSEARCH-2328 Allow inclusion of source code in the documentation

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/gson/impl/JsonObjectAccessor.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/gson/impl/JsonObjectAccessorImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/gson/impl/RootJsonAccessor.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/projection/impl/FieldSearchProjectionImpl.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/SearchProjectionIT.java, util/internal/common/src/main/java/org/hibernate/search/util/impl/common/Contracts.java, util/internal/common/src/main/java/org/hibernate/search/util/impl/common/logging/Log.java
https://hibernate.atlassian.net//browse/HSEARCH-3259
=> HSEARCH-3259 Search 6 groundwork - Restore support for projections on fields within flattened object fields in Elasticsearch

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingBridgeIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/nonregression/automaticindexing/ContainedInThroughNonContainingIndexedType.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/BridgeIT.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DocumentIdBaseIT.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/providedid/ProvidedIdIT.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/JavaBeanMappingBuilder.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/model/impl/JavaBeanPropertyModel.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/impl/ProvidedStringIdentifierMapping.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/impl/AbstractPojoModelCompositeElement.java
https://hibernate.atlassian.net//browse/HSEARCH-2496
Based on #1794 , which should be merged first.
I only had to add a test, as this is already supported in Search 6.
=> HSEARCH-2496 Smarter dirty checking when using @ContainedIn with custom field bridges

integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedIT.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationMappingDefinitionContextImpl.java
https://hibernate.atlassian.net//browse/HSEARCH-3413
=> HSEARCH-3413 Search 6 groundwork - Restore support for implicit index name

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/MatchIdPredicateBuilderImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/SearchPredicateBuilderFactoryImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaObjectNode.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/MatchIdPredicateBuilderImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/SearchPredicateBuilderFactoryImpl.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/MatchIdPredicateContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/SearchPredicateFactoryContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/MatchIdPredicateContextImpl.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/SearchPredicateFactoryContextImpl.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/spi/DelegatingSearchPredicateFactoryContextImpl.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/MatchIdPredicateBuilder.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/SearchPredicateBuilderFactory.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/MatchIdSearchPredicateIT.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubPredicateBuilder.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubSearchPredicateBuilderFactory.java
https://hibernate.atlassian.net/browse/HSEARCH-3088
I hope it makes sense.
At the moment it only supports strings.
It looks like:
```
SearchQuery<DocumentReference> query = searchTarget.query()
.asReference()
.predicate( f -> f.id().matching( DOCUMENT_1 ).toPredicate() )
.build();
```
=> HSEARCH-3088 Query id in DSL

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/IndexOrderSortContributor.java
* https://hibernate.atlassian.net/browse/HSEARCH-3422
=> HSEARCH-3422 Use _doc to implement index order sorting on Elasticsearch

documentation/src/main/asciidoc/getting-started.asciidoc, documentation/src/main/asciidoc/mapper-pojo.asciidoc, documentation/src/main/asciidoc/todo-placeholder.asciidoc
Follows up on #1804 
I noticed the getting started guide didn't cover bridges at all, and those are a big part of what changed in Search 6, so we'd better add a minimum of documentation about them.
=> HSEARCH-3264 follow-up: Add minimal documentation for bridges

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3431
Same as #1816 , but for master (6.0) instead of 5.10.
=> HSEARCH-3431 Upgrade to Hibernate ORM 5.3.7.Final (master branch)

engine/src/main/java/org/hibernate/search/engine/cfg/impl/AbstractConfigurationProperty.java, engine/src/main/java/org/hibernate/search/engine/cfg/impl/ConvertUtils.java, engine/src/main/java/org/hibernate/search/engine/cfg/impl/DefaultedConfigurationProperty.java, engine/src/main/java/org/hibernate/search/engine/cfg/impl/DefaultedPropertyContextImpl.java, engine/src/main/java/org/hibernate/search/engine/cfg/impl/OptionalConfigurationPropertyImpl.java, engine/src/main/java/org/hibernate/search/engine/cfg/impl/OptionalPropertyContextImpl.java, engine/src/main/java/org/hibernate/search/engine/cfg/spi/ConfigurationProperty.java, engine/src/main/java/org/hibernate/search/engine/cfg/spi/OptionalConfigurationProperty.java, engine/src/main/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolder.java, engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationBuilderImpl.java, engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java, engine/src/test/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyBeanReferenceTest.java, engine/src/test/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyValidMissingValuesTest.java, engine/src/test/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolderTest.java, engine/src/test/java/org/hibernate/search/engine/test/util/AbstractBeanProviderPartialMock.java, engine/src/test/java/org/hibernate/search/engine/test/util/AbstractConfigurationPropertySourcePartialMock.java
https://hibernate.atlassian.net//browse/HSEARCH-3442
~Based on #1828 which should be merged first.~ => Done
@fax4ever As discussed, this could be a nice start if you want to review PRs on Search. Just mind the fact that the first commits are from another PRs and should not be considered.
=> HSEARCH-3442 Search 6 groundwork - Properly handle missing backend / backend type in configuration properties

pom.xml
* https://hibernate.atlassian.net/browse/HSEARCH-3470
To be backported to 5.11.
=> HSEARCH-3470 Upgrade Hibernate ORM to 5.4.1.Final

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3470
No need to review, just waiting for CI.
=> Backport HSEARCH-3470 to branch 5.11 - Upgrade Hibernate ORM to 5.4.1.Final

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/analyzer/impl/ElasticsearchAnalyzerReference.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/logging/impl/Log.java, engine/src/main/java/org/hibernate/search/analyzer/impl/LuceneAnalyzerReference.java, engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java, integrationtest/elasticsearch/src/test/java/org/hibernate/search/elasticsearch/test/CombiningLuceneAndElasticsearchIT.java, orm/src/main/java/org/hibernate/search/SearchFactory.java
https://hibernate.atlassian.net/browse/HSEARCH-3458
This will only document the limitation and enhance the error messages. The core of the problem cannot be solved in Search 5.
=> HSEARCH-3458 ClassCastException: Cannot cast ScopedElasticsearchAnalyzerReference to LuceneAnalyzerReference

Jenkinsfile, engine/src/main/java/org/hibernate/search/query/engine/impl/QueryFilters.java, engine/src/main/java/org/hibernate/search/query/engine/spi/HSQuery.java, engine/src/main/java/org/hibernate/search/util/impl/ConcurrentReferenceHashMap.java, engine/src/main/java/org/hibernate/search/util/impl/Executors.java, integrationtest/osgi/karaf-it/pom.xml, integrationtest/performance/orm/pom.xml, integrationtest/wildfly/pom.xml, jsr352/core/src/main/java/org/hibernate/search/jsr352/massindexing/MassIndexingJob.java, orm/src/main/java/org/hibernate/search/MassIndexer.java, orm/src/main/java/org/hibernate/search/batchindexing/spi/MassIndexerWithTenant.java, orm/src/main/java/org/hibernate/search/jpa/FullTextQuery.java, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3484
https://hibernate.atlassian.net//browse/HSEARCH-3485
https://hibernate.atlassian.net//browse/HSEARCH-3491
https://hibernate.atlassian.net//browse/HSEARCH-3494
Full build (including JDK12): http://ci.hibernate.org/job/hibernate-search/job/PR-1894/4/
Note that OSGi and WildFly integration tests are disabled on JDK12, because Karaf and WildFly don't work on JDK12 yet.
=> HSEARCH-3484 + HSEARCH-3485 + HSEARCH-3491: JDK12 compatibility on branch 5.11

integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/fieldtype/ElasticsearchFieldTypesIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/search/query/ElasticsearchSearchQueryIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchClientSpy.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/work/ElasticsearchIndexingIT.java
https://hibernate.atlassian.net/browse/HSEARCH-2908
Based on top of https://github.com/hibernate/hibernate-search/pull/1889.
Thus we need to merge https://github.com/hibernate/hibernate-search/pull/1889 first.
=> HSEARCH-2908 Incorrect mapping for 'java.lang.Short and java.lang.Byte' fields with Elasticsearch.

Jenkinsfile, README.md, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3493
Backport of #1897.
Note that tests don't pass, so I kept the build as experimental (= not run on CI builds except when explicitly requested).
But all the errors seem related to Byteman not supporting JDK13 yet (see https://developer.jboss.org/message/988091).
=> Backport HSEARCH-3493 to branch 5.11 - Test compatibility with JDK13

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/AbstractElasticsearchSearchPredicateBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/AbstractLuceneSearchPredicateBuilder.java, engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/BooleanJunctionPredicateContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/MatchPredicateContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/MultiFieldPredicateFieldSetContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/RangePredicateContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/SearchPredicateNoFieldContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/SearchPredicateScoreContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/SpatialPredicateContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/AbstractMultiFieldPredicateCommonState.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/BooleanJunctionPredicateContextImpl.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/MatchPredicateContextImpl.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/MatchPredicateFieldSetContextImpl.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/RangePredicateContextImpl.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/RangePredicateFieldSetContextImpl.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/SpatialPredicateContextImpl.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/SpatialWithinPredicateContextImpl.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/impl/SpatialWithinPredicateFieldSetContextImpl.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/SearchPredicateBuilder.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/BoolSearchPredicateIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/MatchSearchPredicateIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RangeSearchPredicateIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/spatial/SpatialWithinBoundingBoxSearchPredicateIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/spatial/SpatialWithinCircleSearchPredicateIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/spatial/SpatialWithinPolygonSearchPredicateIT.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubPredicateBuilder.java
https://hibernate.atlassian.net/browse/HSEARCH-3091
The assessment of missed predicate options is here: [Hibernate Search 6 - Query Predicates Comparison](https://docs.google.com/spreadsheets/d/1tLVyp5irn5SV_wVX6LKn2BxmqHewSGKsBv9a2gMlwKk/edit?usp=sharing)
~~I know I did too many commits, if you want, we could merge:~~ done!
* ~~HSEARCH-3091 Test predicate-level * with range predicate ( as one )~~
* ~~HSEARCH-3091 Handle constantScore in multi field predicates with the previous one.~~
=> HSEARCH-3091 Search 6 groundwork - Add to the predicate DSL the missing per-predicate options compared to Search 5

Jenkinsfile, integrationtest/osgi/karaf-it/pom.xml, integrationtest/performance/orm/pom.xml, integrationtest/wildfly/pom.xml, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3508
Backports:
* https://hibernate.atlassian.net//browse/HSEARCH-3238
* https://hibernate.atlassian.net//browse/HSEARCH-3420
I just launched a full build: http://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-1905/4/pipeline
=> HSEARCH-3508 test against JDK11 regularly on branch 5.10

documentation/src/main/asciidoc/mapper-orm-mapping.asciidoc, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/JavaUtilCalendarPropertyTypeDescriptor.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/JavaUtilDatePropertyTypeDescriptor.java
https://hibernate.atlassian.net//browse/HSEARCH-3509
=> HSEARCH-3509 Document the limitations of the date/time conversion in the Pojo mapper for java.util.Calendar and java.util.Date

documentation/src/main/asciidoc/mapper-orm-mapping.asciidoc, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/JavaSqlDatePropertyTypeDescriptor.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/JavaSqlTimePropertyTypeDescriptor.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/JavaSqlTimestampPropertyTypeDescriptor.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/PropertyTypeDescriptor.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultJavaSqlDateValueBridge.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultJavaSqlTimeValueBridge.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultJavaSqlTimestampValueBridge.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultJavaUtilDateValueBridge.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/impl/BridgeResolver.java
https://hibernate.atlassian.net/browse/HSEARCH-3503
It's incredible that `java.sql.Date` and even `java.sql.Time` behaves exact as `java.sql.Timestamp`.
The methods `java.sql.Date#toLocalDate`, ` java.sqlTimestamp#toLocalDateTime` and so on have a lot of issue relative to the default JVM timezones applied on the conversion.
Thus I avoided to use them or their reverse.
=> HSEARCH-3503 Add dedicated default value bridges for java.sql.Timestamp, java.sql.Date and java.sql.Time

build-config/src/main/resources/checkstyle.xml, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3515
This PR is being created because we are removing the deprecated field `cacheFile` from TreeWalker. Checker still supports it.
PR: checkstyle/checkstyle#6553
Issue: checkstyle/checkstyle#2883
Maven-checkstyle-plugin needs to be upgraded because the old versions still tried to set the `cacheFile` field even if it wasn't declared in the config.
Feel free to ask any questions.
Thanks.
=> HSEARCH-3515 Upgraded maven-checkstyle-plugin to 3.0.0

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3502
It fixes the JDK13 build: http://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-yoann/detail/tracking-jdk13-5.11/6/pipeline
=> HSEARCH-3502 Upgrade to Byteman 4.0.6

documentation/src/main/asciidoc/configuration.asciidoc, engine/src/main/java/org/hibernate/search/engine/backend/spi/BackendFactory.java, engine/src/main/java/org/hibernate/search/engine/backend/spi/BackendImplementor.java, engine/src/main/java/org/hibernate/search/engine/cfg/BackendSettings.java, engine/src/main/java/org/hibernate/search/engine/cfg/EngineSettings.java, engine/src/main/java/org/hibernate/search/engine/cfg/IndexSettings.java, engine/src/main/java/org/hibernate/search/engine/cfg/impl/EngineConfigurationUtils.java, engine/src/main/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolder.java, engine/src/main/java/org/hibernate/search/engine/common/impl/IndexManagerPartialBuildState.java, engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationBuilderImpl.java, engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java, engine/src/main/java/org/hibernate/search/engine/mapper/mapping/building/spi/MappingConfigurationCollector.java, engine/src/test/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolderTest.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/analysis/ElasticsearchAnalysisConfigurerIT.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/analysis/LuceneAnalysisConfigurerIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/rule/SearchSetupHelper.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedIT.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/Indexed.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationMappingDefinitionContextImpl.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/TypeMappingContext.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/TypeMappingContextImpl.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/MappingSetupHelper.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/mapper/StubMappingInitiator.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/mapper/StubTypeMetadataContributor.java
https://hibernate.atlassian.net//browse/HSEARCH-3521
=> HSEARCH-3521 Move index-specific configuration properties below the hibernate.search.backends.<backend name>.indexes property

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/BridgeUsingPropertyMarkerAccessIT.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/spatial/AnnotationMappingGeoPointBridgeIT.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/spatial/ProgrammaticMappingGeoPointBridgeIT.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/model/Library.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchDocumentRepositoryImpl.java, integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/OrmLibraryShowcaseIT.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/spatial/GeoPointBridgeBuilder.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/spatial/annotation/GeoPointBridge.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/spatial/impl/GeoPointBridge.java
[HSEARCH-3542](https://hibernate.atlassian.net//browse/HSEARCH-3542): Fix transient failures in OrmLibraryShowcaseIT#searchAroundMe_spatial
[HSEARCH-3543](https://hibernate.atlassian.net//browse/HSEARCH-3543): Allow to set GeoPointBridges as sortable to enable distance sorts
I need this in particular because the transient failures affect integration tests when testing against an AWS Elasticsearch service (and I'm trying to restore support for the AWS integration).
=> HSEARCH-3542 + HSEARCH-3543 Spatial-related fixes

integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/configuration/AnalysisOverrideITAnalysisConfigurer.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/configuration/AnalysisOverrideITAnalysisConfigurer.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/MatchSearchPredicateIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/configuration/OverrideAnalysisDefinitions.java
https://hibernate.atlassian.net/browse/HSEARCH-2534
~~Based on https://github.com/hibernate/hibernate-search/pull/1938.~~ not anymore
This PR just adds a test.
=> Hsearch 2534 Allow using query-only analyzer definitions with Elasticsearch

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/dsl/predicate/ElasticsearchSearchPredicateFactoryContext.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/dsl/predicate/impl/ElasticsearchJsonStringPredicateContext.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/dsl/predicate/impl/ElasticsearchSearchPredicateFactoryContextImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/dsl/sort/ElasticsearchSearchSortContainerContext.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/dsl/sort/impl/ElasticsearchSearchSortContainerContextImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicateBuilderFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicateBuilderFactoryImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/ElasticsearchSearchSortBuilderFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/sort/impl/ElasticsearchSearchSortBuilderFactoryImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/ElasticsearchIndexFieldTypeFactoryContext.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/impl/ElasticsearchIndexFieldTypeFactoryContextImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/dsl/predicate/LuceneSearchPredicateFactoryContext.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/dsl/sort/LuceneSearchSortContainerContext.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/LuceneIndexFieldTypeFactoryContext.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/impl/LuceneIndexFieldTypeFactoryContextImpl.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/ElasticsearchExtensionIT.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneExtensionIT.java
https://hibernate.atlassian.net//browse/HSEARCH-3507
I ended up going for minimal changes, so I did not fix *everything* that was mentioned in the ticket. But I think it's the best compromise between consistency and user-friendliness (because `fromJson` is definitely clearer than `byNative`, for example).
=> HSEARCH-3507 Improve consistency of naming for methods related to native Elasticsearch/Lucene features (fromJsonString, etc.)

engine/src/main/java/org/hibernate/search/query/dsl/impl/MinimumShouldMatchContextImpl.java, engine/src/main/java/org/hibernate/search/util/logging/impl/Log.java, engine/src/test/java/org/hibernate/search/test/dsl/BoolDSLTest.java
https://hibernate.atlassian.net//browse/HSEARCH-3535
Just waiting for CI.
Backport of #1944 , but just the part about HSEARCH-3535. The other part breaks backward compatibility so I'd rather not.
=> Backport HSEARCH-3535 to branch 5.11 - Parameters are inverted in minimumShouldMatch error message

Jenkinsfile, README.md, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchDialectName.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/Elasticsearch56Dialect.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/Elasticsearch60Dialect.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/Elasticsearch67Dialect.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/builder/factory/impl/Elasticsearch60WorkBuilderFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/builder/factory/impl/Elasticsearch67WorkBuilderFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/CreateIndexWork.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/GetIndexTypeMappingWork.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/PutIndexTypeMappingWork.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientUtilsGetElasticsearchVersionTest.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/dialect/Elasticsearch60TestDialect.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/dialect/Elasticsearch67TestDialect.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/dialect/Elasticsearch7TestDialect.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/dialect/ElasticsearchTestDialect.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/TestElasticsearchClient.java, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3518
For now it's a dedicated dialect, I'll change that in https://hibernate.atlassian.net/browse/HSEARCH-3563
Full build: http://ci.hibernate.org/job/hibernate-search/job/PR-1956/4/
=> HSEARCH-3518 Add support for Elasticsearch 6.7

documentation/src/main/asciidoc/backend-elasticsearch.asciidoc, documentation/src/main/asciidoc/mapper-orm-indexing.asciidoc, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/dialect/Elasticsearch5TestDialect.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/dialect/ElasticsearchTestDialect.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/indexnull/IndexNullAsValueIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/AnalyzedStringFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/BooleanFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/ByteFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/DoubleFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/FieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/FloatFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/GeoPointFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/InstantFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/IntegerFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/KeywordStringFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/LocalDateFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/LocalDateTimeFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/LocalTimeFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/LongFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/MonthDayFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/NormalizedStringFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/OffsetDateTimeFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/OffsetTimeFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/ShortFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/YearFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/YearMonthFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/ZonedDateTimeFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/expectations/IndexNullAsMatchPredicateExpectactions.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
https://hibernate.atlassian.net//browse/HSEARCH-3099
Full tests here: http://ci.hibernate.org/job/hibernate-search/job/PR-1961/9/
**Please wait for the result of this build before merging**.
=> HSEARCH-3099 follow-up: fix tests and documentation for "indexNullAs" on GeoPoint fields in ES5.6

Jenkinsfile, README.md, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientFactoryImpl.java, pom.xml
* [HSEARCH-3541](https://hibernate.atlassian.net//browse/HSEARCH-3541): Upgrade to Elasticsearch 7.0.0 (release)
* [HSEARCH-3568](https://hibernate.atlassian.net//browse/HSEARCH-3568): Upgrade to Elasticsearch 6.7.1
Full build: http://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-1964/2
=> HSEARCH-3541 + HSEARCH-3568 Upgrade to Elasticsearch 7.0.0 (release) and 6.7.1

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/esnative/PropertyMapping.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/esnative/PropertyMappingJsonAdapterFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/index/admin/impl/ElasticsearchSchemaValidatorImpl.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/fieldtype/ElasticsearchFieldTypesIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchAnalyzerDefinitionCreationIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchAnalyzerDefinitionMigrationIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchAnalyzerDefinitionValidationIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchIndexStatusCheckIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchNormalizerDefinitionCreationIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchNormalizerDefinitionMigrationIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchNormalizerDefinitionValidationIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchSchemaAttributeValidationIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchSchemaCreateStrategyIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchSchemaCreationIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchSchemaMigrationIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchSchemaValidationIT.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneDocumentModelDslIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/DocumentModelDslIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/rule/SearchSetupHelper.java
https://hibernate.atlassian.net/browse/HSEARCH-3467
~~Still in preview, since several attributes have not been tested yet:~~ done
1. Property type attributes: ~~boots~~ removed!, ~~store, null_value, fielddata, doc_values, normalizer~~ done!.
2. ~~Normalizer definition attributes: char_filter, token_filter.~~ already exists
2. ~~Analyzer definition attributes: char_filter, token_filter, tokenizer.~~ already exists
=> HSEARCH-3467 Add tests for all the attributes validated by the Elasticsearch schema validator

mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/IdentifierBridgeBindingContext.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/PropertyBridgeBindingContext.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/RoutingKeyBridgeBindingContext.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/TypeBridgeBindingContext.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/binding/ValueBridgeBindingContext.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/PojoElementAccessor.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/PojoModelCompositeElement.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/PojoModelElement.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/PojoModelProperty.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/PojoModelType.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/PojoModelValue.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/dependency/PojoOtherEntityDependencyContext.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/dependency/PojoPropertyDependencyContext.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/dependency/PojoTypeDependencyContext.java
https://hibernate.atlassian.net//browse/HSEARCH-3298
~Based on #1962 , which should be merged first.~ => Done
=> HSEARCH-3298 Mark the accessor-based entity access API and explicit reindexing declaration API in bridges as experimental

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSimpleQueryStringPredicateBuilder.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchTextMatchPredicateBuilder.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchTextPhrasePredicateBuilder.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/util/impl/AnalyzerConstants.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/impl/ScopedAnalyzer.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/analysis/impl/TokenizerChain.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneSimpleQueryStringPredicateBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneStringFieldCodec.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneTextFieldCodec.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextMatchPredicateBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextPhrasePredicateBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextRangePredicateBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/sort/impl/LuceneTextFieldSortBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/util/impl/AnalyzerConstants.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/util/impl/AnalyzerUtils.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/configuration/AnalysisCustomITAnalysisConfigurer.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/configuration/AnalysisCustomITAnalysisConfigurer.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/analysis/AnalysisCustomIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3536
@yrodiere as you found out Analyzer.normalize method works only if we use the Lucene's 'CustomAnalyzer.builder'.
I think that our analyzers don't. So they have to override them to work as 'CustomAnalyzer' does.
In a second commit I renamed the utility classes, we can drop it.
=> HSEARCH-3536 Use Analyzer.normalize instead of our own code for normalization

integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/nonregression/mapping/definition/IndexNullAsOnNumericContainer.java
https://hibernate.atlassian.net//browse/HSEARCH-2663
Based on #1974, which should be merged first.
Just a non-regression test checking we don't have this problem in Search 6 anymore.
=> HSEARCH-2663 Null handling for elements in container bridges isn't consistent with non-container bridges

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/dsl/query/ElasticsearchSearchQueryContext.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/dsl/query/impl/ElasticsearchSearchQueryContextImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/ElasticsearchSearchFetchable.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/ElasticsearchSearchQuery.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/dsl/query/LuceneSearchQueryContext.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/dsl/query/impl/LuceneSearchQueryContextImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/LuceneSearchFetchable.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/LuceneSearchQuery.java, documentation/src/main/asciidoc/getting-started.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/gettingstarted/withhsearch/withanalysis/GettingStartedWithAnalysisIT.java, documentation/src/test/java/org/hibernate/search/documentation/gettingstarted/withhsearch/withoutanalysis/GettingStartedWithoutAnalysisIT.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/directfieldmapping/HibernateOrmSimpleMappingIT.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/entityindexmapping/HibernateOrmIndexedIT.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexing/HibernateOrmAutomaticIndexingIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/DslConverterIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/ProjectionConverterIT.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/query/SearchQueryContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/query/spi/AbstractExtendedSearchQueryContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/query/spi/AbstractSearchQueryContext.java, engine/src/main/java/org/hibernate/search/engine/search/query/ExtendedSearchFetchable.java, engine/src/main/java/org/hibernate/search/engine/search/query/SearchFetchable.java, engine/src/main/java/org/hibernate/search/engine/search/query/SearchQuery.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryFetchIT.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchDocumentRepositoryImpl.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchLibraryRepositoryImpl.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchPersonRepositoryImpl.java
[HSEARCH-3572](https://hibernate.atlassian.net//browse/HSEARCH-3572): Add fetch methods to terminal steps of the query DSL
~Based on #1983 ([HSEARCH-3577](https://hibernate.atlassian.net//browse/HSEARCH-3577)), which should be merged first.~ => Done
To see how this improves APIs, have a look at `IndexSearchDocumentRepositoryImpl.java` or `org.hibernate.search.documentation.gettingstarted.withhsearch.withoutanalysis.GettingStartedWithoutAnalysisIT#test`
=> HSEARCH-3572 Add fetch methods to terminal steps of the query DSL

integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneExtensionIT.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/DocumentAssert.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/BytecodeEnhancementIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmBasicPropertyMetadata.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmBasicTypeMetadata.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmBootstrapIntrospector.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmPropertyModel.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmRawTypeModel.java, pom.xml, util/internal/integrationtest/orm/pom.xml, util/internal/integrationtest/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/orm/OrmSetupHelper.java, util/internal/integrationtest/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/orm/SimpleSessionFactoryBuilder.java
https://hibernate.atlassian.net//browse/HSEARCH-3581
@gsmet The test seems to pass. event though I had to disable some parts due to what is probably bugs in Hibernate ORM. I'm looking for more things to test at this point. Any idea?
~I'll try to reproduce and report the ORM bugs once we're done with this.~ => Created https://hibernate.atlassian.net//browse/HSEARCH-3584
~Could you try this in Quarkus? I suspect it won't work as is, because I need reflection on the read methods added by the enhancer, and I do not think it is enabled by default in GraalVM. But maybe there's an easy way for you to enable it?~ Confirmed by @gsmet, it works.
=> [PREVIEW] HSEARCH-3581 Indexing entities whose bytecode was enhanced by Hibernate ORM fails to load lazy properties

Jenkinsfile, engine/src/main/java/org/hibernate/search/engine/backend/document/model/dsl/impl/IndexSchemaElementImpl.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/query/SearchQueryResultContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/query/SearchQueryResultDefinitionContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/query/spi/AbstractSearchQueryResultDefinitionContext.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingBridgeExplicitReindexingFunctionalIT.java, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3582
I took this opportunity to improve the Jenkinsfile a little bit, allowing to run the build in an arbitrary environment using a new "ENVIRONMENT_FILTER" parameter. I used it to run only the part of the build checking that the eclipse compiler works fine, see here: http://ci.hibernate.org/job/hibernate-search-yoann/job/HSEARCH-3582/25/
=> HSEARCH-3582 Make the build compatible with Eclipse

orm/src/main/java/org/hibernate/search/query/hibernate/impl/FullTextQueryImpl.java, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3595
Backport of #2002 , which should be merged first.
=> Backport HSEARCH-3595 to branch 5.11 - Upgrade to Hibernate ORM 5.4.3.Final

engine/src/main/java/org/hibernate/search/engine/search/dsl/predicate/MatchIdPredicateContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/SearchSortFactoryContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/impl/DefaultSearchSortFactoryContext.java, engine/src/main/java/org/hibernate/search/engine/search/dsl/sort/spi/DelegatingSearchSortFactoryContext.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/ElasticsearchExtensionIT.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneExtensionIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/CompositeSearchSortIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/SearchSortIT.java
Just some fixes for problems I noticed while working on the documentation.
* [HSEARCH-3616](https://hibernate.atlassian.net//browse/HSEARCH-3616): Accept Collection<?> instead of Collection<Object>  in the ID predicate
* [HSEARCH-3617](https://hibernate.atlassian.net//browse/HSEARCH-3617): Search 6 groundwork - Remove the by(SearchSort) method from the sort DSL
=> HSEARCH-3616 + HSEARCH-3617 DSL fixes

documentation/src/main/asciidoc/search-dsl.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/directfieldmapping/HibernateOrmSimpleMappingIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/converter/DslConverterIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/converter/ProjectionConverterIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/predicate/Author.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/predicate/Book.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/predicate/EmbeddableGeoPoint.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/predicate/Genre.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/predicate/PredicateDslIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/projection/Author.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/projection/Book.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/projection/EmbeddableGeoPoint.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/projection/Genre.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/projection/ProjectionDslIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/query/Book.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/query/QueryDslIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/sort/Author.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/sort/Book.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/sort/EmbeddableGeoPoint.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/sort/Genre.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/sort/SortDslIT.java, documentation/src/test/java/org/hibernate/search/documentation/testsupport/BackendSetupStrategy.java, documentation/src/test/java/org/hibernate/search/documentation/testsupport/ElasticsearchSimpleMappingAnalysisConfigurer.java, documentation/src/test/java/org/hibernate/search/documentation/testsupport/LuceneSimpleMappingAnalysisConfigurer.java
https://hibernate.atlassian.net//browse/HSEARCH-3597
Based on #2012, which should be merged first.
The easiest way to review this PR is probably to build the documentation and then read the "Searching" section:
```
mvn clean install -DskipTests -pl documentation -am
xdg-open ./documentation/target/asciidoctor/en-US/html_single/index.html
```
=> HSEARCH-3597 Document all available predicates/sorts/projections and query DSL basics

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/impl/ElasticsearchGeoPointIndexFieldTypeContext.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/LuceneCollectorsBuilder.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/projection/ProjectionDslIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/spatial/AbstractSpatialWithinSearchPredicateIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/spatial/DistanceSearchProjectionIT.java
https://hibernate.atlassian.net//browse/HSEARCH-3618
Turns out there were two very different problems, but leading to the same symptoms.
A full build is running right now to check other versions of Elasticsearch: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-yoann/detail/HSEARCH-3618/6/
=> HSEARCH-3618 Distance projection may lead to missing hits in the Lucene and Elasticsearch backends

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/codec/impl/LuceneGeoPointFieldCodec.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/spatial/DistanceSearchSearchableSortableIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3230
Actually I think that the issue is out of date.
Anyway I take the change to add some tests. Maybe too many. I think I could merge them into the current ones.
About all the integration tests pass splitting: 
~~~ java
if ( searchable ) {
documentBuilder.addField( new LatLonPoint( absoluteFieldPath, value.getLatitude(), value.getLongitude() ) );
}
if ( sortable ) {
documentBuilder.addField( new LatLonDocValuesField( absoluteFieldPath, value.getLatitude(), value.getLongitude() ) );
}
~~~
I was wrong. All the integration tests pass, with the exception that ones on `exists` predicate.
Anyway I tried to optimize a bit field creations. It is possible that a more significant optimization it is possible changing a bit the implementation of …
=> HSEARCH-3230 Clarify the behavior of Lucene GeoPoint field codecs with respect to searchable/sortable/projectable

mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PojoRuntimeIntrospector.java
https://hibernate.atlassian.net//browse/HSEARCH-3067
It turns out that notion is obsolete.
There are remnants in the legacy code in
`org.hibernate.search.spi.InstanceInitializer#initializeCollection`
for example, but all implementations are no-op as of
8bc0e23.
Judging from that commit's message, this initialization was only useful
when dealing detached collections, and "we don't have to" do it anymore.
It was an SPI, but as far as I can tell it wasn't useful in any know
integration, so let's remove it for now and restore it if someone asks
for it (nicely).
=> HSEARCH-3067 Remove the notion of explicit initialization of lazy collection/map/array in PojoRuntimeIntrospector

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/nonregression/automaticindexing/ContainedInThroughNonContainingIndexedTypeIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/nonregression/automaticindexing/ContainedInTriggerUnnecessaryCollectionInitializationIT.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/nonregression/mapping/definition/IndexNullAsOnNumericContainerIT.java, integrationtest/pom.xml, jqassistant/rules.xml
https://hibernate.atlassian.net//browse/HSEARCH-2473
I tested the new JQAssistant rules locally by adding tests with the wrong suffix: it worked.
=> HSEARCH-2473 Get test naming practices straight

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3637
Not tested locally, let's wait for the CI build before merging.
I had a look at the release notes, there's nothing that should impact us.
=> HSEARCH-3637 Upgrade to Lucene 8.1.1

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientUtils.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/ElasticsearchResponseFormatter.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/AbstractSimpleBulkableElasticsearchWork.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/AbstractSimpleElasticsearchWork.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/BulkWork.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendFactory.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java, engine/src/main/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolder.java, engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationBuilderImpl.java, engine/src/main/java/org/hibernate/search/engine/reporting/impl/RootFailureCollector.java, engine/src/test/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolderTest.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/analysis/ElasticsearchAnalysisConfigurerIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapFailureIT.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/analysis/LuceneAnalysisConfigurerIT.java, util/common/src/main/java/org/hibernate/search/util/common/reporting/EventContext.java
https://hibernate.atlassian.net//browse/HSEARCH-3621
~Based on #2038, which should be merged first.~ => Done
In short, this:
```
org.hibernate.search.util.common.SearchException: HSEARCH000520: Hibernate Search bootstrap failed. Failures:
ORM mapping: 
type 'com.acme.model.Type1': 
index 'IndexName1': 
failures: 
- HSEARCH400080: Failed to detect the Elasticsearch version running on the cluster.
type 'com.acme.model.Type2': 
index 'IndexName2': 
failures: 
- HSEARCH400080: Failed to detect the Elasticsearch version running on the cluster.
at org.hibernate.search.engine.reporting.impl.RootFailureCollector.checkNoFailure(RootFailureCollector.java:56)
at org.hibernate.search.engine.common.impl.SearchIntegrationBuilderImpl.prepareBuild(SearchIntegrationBuilderImpl.java:170)
```
is now …
=> HSEARCH-3621 Clarify the error message when the Elasticsearch cluster cannot be reached upon startup

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3646
I had a look at the release notes: no backward incompatible change that would affect us, some performance improvements. The upgrade is safe.
=> HSEARCH-3646 Upgrade to Lucene 8.2

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/nonregression/automaticindexing/IndexingProcessorProxiedAssociatedEntityIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/nonregression/automaticindexing/ReindexingResolverProxiedAssociatedEntityIT.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/dirtiness/impl/PojoImplicitReindexingResolverOriginalTypeNode.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/processing/impl/PojoIndexingProcessorTypeNode.java
https://hibernate.atlassian.net//browse/HSEARCH-3643
=> HSEARCH-3643 Entities should be unproxied before getting field values when indexing

Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-3658
Will run the full IT suite and merge if it passes.
=> HSEARCH-3658 Upgrade to AWS Elasticsearch Service 6.7 in the Jenkinsfile

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextFieldPredicateBuilderFactory.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextWildcardPredicateBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/parse/impl/LuceneWildcardExpressionHelper.java, documentation/src/main/asciidoc/search-dsl.asciidoc, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/search/LuceneNormalizeWildcardExpressionsIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SimpleQueryStringSearchPredicateIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/WildcardSearchPredicateIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3612
Tested locally for all Elasticsearch supported profiles: the behavior seems consistent among all of them.
=> HSEARCH-3612 Normalize the terms to match in wildcard/prefix predicates

documentation/src/main/asciidoc/mapper-orm-indexing-automatic.asciidoc, documentation/src/main/asciidoc/mapper-orm-indexing-explicit.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexing/HibernateOrmExplicitIndexingIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/SearchSessionWritePlan.java
https://hibernate.atlassian.net/browse/HSEARCH-3656
@fax4ever Could you review this today, please? I'd like to put it in today's release.
=> HSEARCH-3656 Update mapper ORM documentation chapter: writeplan API process is no longer necessary

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/ExplainWork.java
https://hibernate.atlassian.net/browse/HSEARCH-3651
Tests for multiple versions of Elasticearch are in progress: https://ci.hibernate.org/job/hibernate-search-personal-yoann/job/HSEARCH-3651/3/
=> HSEARCH-3651 Do not specify a type in Elasticsearch _explain requests

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3659
Build testing all versions of Elasticsearch (shouldn't matter, but just in case): https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-yoann/detail/HSEARCH-3659/2/pipeline
=> HSEARCH-3659 Manage the version of Jackson to the latest available version

pom.xml, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/assertion/SearchHitsAssert.java
https://hibernate.atlassian.net/browse/HSEARCH-3686
Eclipse build in progress here: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2073/3/pipeline
=> HSEARCH-3686 Upgrade to a staging version of ECJ 3.19.0 to work around Eclipse compiler bugs in 3.18.0

Jenkinsfile, integrationtest/mapper/orm-envers/pom.xml, integrationtest/mapper/orm-envers/src/test/java/org/hibernate/search/integrationtest/mapper/orm/envers/EnversIT.java, integrationtest/pom.xml, legacy/orm/src/test/java/org/hibernate/search/test/envers/SearchAndEnversIntegrationTest.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmBootstrapIntrospector.java, pom.xml, reports/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3667
=> HSEARCH-3667 Envers compatibility

integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexNullAsErrorIT.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/PropertyTypeDescriptor.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/testsupport/types/StringPropertyTypeDescriptor.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/impl/DefaultStringIdentifierBridge.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/mapping/impl/BridgeResolver.java
https://hibernate.atlassian.net/browse/HSEARCH-3690
=> HSEARCH-3690 Add a default identifier bridge for type String

documentation/src/main/asciidoc/getting-started.asciidoc, documentation/src/main/asciidoc/search-dsl.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/gettingstarted/withhsearch/withanalysis/GettingStartedWithAnalysisIT.java, documentation/src/test/java/org/hibernate/search/documentation/gettingstarted/withhsearch/withoutanalysis/GettingStartedWithoutAnalysisIT.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/directfieldmapping/HibernateOrmSimpleMappingIT.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/entityindexmapping/HibernateOrmIndexedIT.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexing/HibernateOrmAutomaticIndexingIT.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/routing/HibernateOrmRoutingIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/aggregation/AggregationDslIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/converter/DslConverterIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/converter/ProjectionConverterIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/predicate/PredicateDslIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/projection/ProjectionDslIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/query/Book.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/query/QueryDslIT.java, documentation/src/test/java/org/hibernate/search/documentation/searchdsl/sort/SortDslIT.java
[HSEARCH-3615](https://hibernate.atlassian.net/browse/HSEARCH-3615): Document the query DSL in details
~Based on #2069 , which should be merged first.~ => Done
=> HSEARCH-3615 Document the query DSL in details

Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-3697
=> Backport HSEARCH-3697 to branch 5.11 - Test Hibernate Search on JDK13 regularly on the CI

documentation/src/main/asciidoc/backend-elasticsearch.asciidoc, documentation/src/main/asciidoc/backend-lucene.asciidoc, documentation/src/main/asciidoc/concepts.asciidoc, documentation/src/main/asciidoc/getting-started.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/analysis/AdvancedElasticsearchAnalysisConfigurer.java, documentation/src/test/java/org/hibernate/search/documentation/analysis/AdvancedLuceneAnalysisConfigurer.java, documentation/src/test/java/org/hibernate/search/documentation/analysis/AnalysisIT.java, documentation/src/test/java/org/hibernate/search/documentation/analysis/MyElasticsearchAnalysisConfigurer.java, documentation/src/test/java/org/hibernate/search/documentation/analysis/MyLuceneAnalysisConfigurer.java, documentation/src/test/java/org/hibernate/search/documentation/gettingstarted/withhsearch/withanalysis/MyElasticsearchAnalysisConfigurer.java, documentation/src/test/java/org/hibernate/search/documentation/gettingstarted/withhsearch/withanalysis/MyLuceneAnalysisConfigurer.java, documentation/src/test/java/org/hibernate/search/documentation/testsupport/ElasticsearchBackendConfiguration.java, documentation/src/test/java/org/hibernate/search/documentation/testsupport/ElasticsearchSimpleMappingAnalysisConfigurer.java, documentation/src/test/java/org/hibernate/search/documentation/testsupport/LuceneSimpleMappingAnalysisConfigurer.java, documentation/src/test/resources/analysis/elasticsearch-simple.properties, documentation/src/test/resources/analysis/lucene-simple.properties, integrationtest/jdk/java-modules/src/main/java/org/hibernate/search/integrationtest/java/module/config/MyElasticsearchAnalysisConfigurer.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/analysis/ElasticsearchLibraryAnalysisConfigurer.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/analysis/LuceneLibraryAnalysisConfigurer.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/MappingSetupHelper.java
* [HSEARCH-3674](https://hibernate.atlassian.net/browse/HSEARCH-3674): Document analysis
* [HSEARCH-3675](https://hibernate.atlassian.net/browse/HSEARCH-3675): Document core concepts
=> HSEARCH-3674 + HSEARCH-3675 Document analysis and core concepts

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingBridgeExplicitReindexingFunctionalIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/event/impl/HibernateSearchEventListener.java, pom.xml
* [HSEARCH-3706](https://hibernate.atlassian.net/browse/HSEARCH-3706): Upgrade to Hibernate ORM 5.4.5.Final
* [HSEARCH-3665](https://hibernate.atlassian.net/browse/HSEARCH-3665): Use the method AutoFlushEvent#isFlushRequired to filter auto flush events
=> HSEARCH-3665 + HSEARCH-3706 Upgrade to Hibernate ORM 5.4.5.Final

integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/spatial/AnnotationMappingGeoPointBindingIT.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/spatial/ProgrammaticMappingGeoPointBindingIT.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/spatial/impl/GeoPointBridge.java
https://hibernate.atlassian.net/browse/HSEARCH-3691
Documentation seems to be already updated.
IMHO we don't need to test that having a such binding does not work anymore. Usually I'm a big fan of having a test for everything, but not in this case (we have removed some code, not added it).
Anyway, we could add it anytime.
=> HSEARCH-3691 Remove the ability to use @GeoPointBinding on properties of type GeoPoint

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3713
Identified at checkstyle/checkstyle#7088
Checkstyle is looking to remove some deprecated methods and our CI noticed that you are not on the latest maven-checkstyle-plugin which is still using some deprecated methods.
=> HSEARCH-3713 upgrade maven-checkstyle-plugin to 3.1.0

Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-3653
I ran a full build here: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-yoann/detail/HSEARCH-3653/6/pipeline/25
(the AWS failures are unrelated, see https://hibernate.atlassian.net/browse/HSEARCH-3716)
=> HSEARCH-3653 Run Elasticsearch in JDK11 by default in the Jenkinsfile

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/esnative/impl/PropertyMapping.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/esnative/impl/PropertyMappingJsonAdapterFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/index/admin/impl/ElasticsearchSchemaValidatorImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/impl/ElasticsearchStringIndexFieldTypeOptionsStep.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchTextFieldPredicateBuilderFactory.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/dsl/impl/LuceneStringIndexFieldTypeOptionsStep.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextFieldPredicateBuilderFactory.java, documentation/src/main/asciidoc/mapper-orm-mapping.asciidoc, engine/src/main/java/org/hibernate/search/engine/backend/types/dsl/StringIndexFieldTypeOptionsStep.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/management/ElasticsearchSchemaAttributeValidationIT.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneDocumentModelDslIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/document/DocumentModelDslIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/MatchSearchPredicateIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/PhraseSearchPredicateIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SimpleQueryStringSearchPredicateIT.java, integrationtest/mapper/pojo/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/FullTextFieldIT.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/FullTextField.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationProcessorProvider.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/PropertyMappingFullTextFieldOptionsStep.java, mapper/pojo/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/PropertyMappingFullTextFieldOptionsStepImpl.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/document/model/StubIndexSchemaNode.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/types/dsl/impl/StubStringIndexFieldTypeOptionsStep.java
https://hibernate.atlassian.net/browse/HSEARCH-3042
~~Preview because:~~
~~1. Still need a test using a `ANALYZER_NGRAM` ( common case for having a search analyzer )~~ done!
~~2. Try what happens if we try to override a normalizer instead...~~ done!
~~3. Still missing multi-indexes compatibility check tests~~ done!
~~4. Documentation~~ done!
=> HSEARCH-3042 Allow the definition of one "search" analyzer per field as part of the mapping

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchParallelWorkProcessor.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchParallelWorkProcessorTest.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchSerialWorkProcessorTest.java
https://hibernate.atlassian.net/browse/HSEARCH-3727
Mainly useful for HSEARCH-3110 (restore support for ErrorHandler).
=> HSEARCH-3727 Elasticsearch orchestrators do not wait for single-work worksets to finish with ElasticsearchParallelWorkProcessor

engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationBuilderImpl.java, engine/src/main/java/org/hibernate/search/engine/common/spi/SearchIntegrationBuilder.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateOrmIntegrationBooterImpl.java
https://hibernate.atlassian.net/browse/HSEARCH-3734
Turns out we were passing a `propertySource` that was not masked ("hibernate.search." removed) to the introspector, which expected it to be masked. This PR solves the problem.
Not adding tests because I simply don't know how to check that method handles are not used.
=> HSEARCH-3734 Configuration property hibernate.search.reflection.strategy is ignored

Jenkinsfile, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3738
Targeting branch 5.11 only, since we don't use Byteman in 6.0 (master) for now.
Build on JDK14: https://ci.hibernate.org/job/hibernate-search/job/PR-2129/9/
=> HSEARCH-3738 Upgrade to Byteman 4.0.8

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchDefaultWorkSequenceBuilder.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchParallelWorkProcessor.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchSerialWorkProcessor.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchDefaultWorkSequenceBuilderTest.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchParallelWorkProcessorTest.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/orchestration/impl/ElasticsearchSerialWorkProcessorTest.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexIndexingPlanIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3726
~Based on #2121 , which should be merged first.~ => Done
=> HSEARCH-3726 Exceptions are not propagated from the Elasticsearch backend to the mapper when using IndexingPlan or automatic indexing

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/UnusedPropertiesIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingMonitorIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/BatchCoordinator.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/BatchIndexingWorkspace.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/FailureHandledRunnable.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/IdentifierConsumerDocumentProducer.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/IdentifierProducer.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/MassIndexerImpl.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/MassIndexingNotifier.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/OptionallyWrapInJTATransaction.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/StatelessSessionAwareRunnable.java
[HSEARCH-3728](https://hibernate.atlassian.net/browse/HSEARCH-3728): All background operations should propagate exceptions from the mapper to the user thread
~Based on #2125 , which should be merged first.~ => Done
All operations are already tested and already behave this way, except the mass indexer. So this is only about the mass indexer.
=> HSEARCH-3728 All background operations should propagate exceptions from the mapper to the user thread

Jenkinsfile, integrationtest/backend/tck/pom.xml, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/BooleanFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/ByteFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/DoubleFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/FloatFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/IntegerFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/LongFieldTypeDescriptor.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/types/ShortFieldTypeDescriptor.java, integrationtest/pom.xml, integrationtest/showcase/library/pom.xml, pom.xml, util/internal/integrationtest/pom.xml, util/internal/test/pom.xml
* [HSEARCH-3486](https://hibernate.atlassian.net/browse/HSEARCH-3486): Upgrade to forbiddenApis 2.7 and configure JDK12/13 signatures
* [HSEARCH-3743](https://hibernate.atlassian.net/browse/HSEARCH-3743): Generate Java 13/14 bytecode for tests when building with JDK13/14
* [HSEARCH-3744](https://hibernate.atlassian.net/browse/HSEARCH-3744): Upgrade integration tests to Spring 2.2.0
Full build: https://ci.hibernate.org/job/hibernate-search-personal-yoann/job/jdk14/20/
Just creating this for archive, so that we have a link to the changeset. Will merge immediately.
=> HSEARCH-3486 + HSEARCH-3743 + HSEARCH-3744 JDK14 support

documentation/src/main/asciidoc/configuration.asciidoc, engine/src/main/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyChecker.java, engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationPartialBuildStateImpl.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/UnusedPropertiesIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3755
=> HSEARCH-3755 Configuration property checking displays the wrong name for the property controlling its behavior

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/scope/model/impl/ElasticsearchFailingFieldCompatibilityChecker.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/scope/model/impl/ElasticsearchFailingIdCompatibilityChecker.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/scope/model/impl/ElasticsearchScopeModel.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/scope/model/impl/ElasticsearchScopedIndexRootComponent.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchMatchIdPredicateBuilder.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicateBuilderFactoryImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/scope/model/impl/LuceneFailingFieldCompatibilityChecker.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/scope/model/impl/LuceneFailingIdCompatibilityChecker.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/scope/model/impl/LuceneScopeModel.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/scope/model/impl/LuceneScopedIndexRootComponent.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneMatchIdPredicateBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneSearchPredicateBuilderFactoryImpl.java, engine/src/main/java/org/hibernate/search/engine/search/common/ValueConvert.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/MatchIdPredicateMatchingStep.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/MatchIdPredicateMatchingStepImpl.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/MatchIdPredicateBuilder.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/MatchIdSearchPredicateIT.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubPredicateBuilder.java
https://hibernate.atlassian.net/browse/HSEARCH-3764
=> HSEARCH-3764 Allow disabling conversion in the ID predicate

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/bridge/builtin/impl/ElasticsearchCalendarBridge.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/bridge/builtin/impl/ElasticsearchDateBridge.java, orm/src/test/java/org/hibernate/search/test/bridge/BridgeTest.java
https://hibernate.atlassian.net/browse/HSEARCH-3767
=> HSEARCH-3767 Elasticsearch date/time bridges throw NPE on projections

elasticsearch/src/main/java/org/hibernate/search/elasticsearch/bridge/builtin/impl/ElasticsearchCalendarBridge.java, elasticsearch/src/main/java/org/hibernate/search/elasticsearch/bridge/builtin/impl/ElasticsearchDateBridge.java, orm/src/test/java/org/hibernate/search/test/bridge/BridgeTest.java
https://hibernate.atlassian.net/browse/HSEARCH-3767
Waiting for #2154 to be merged.
=> Backport HSEARCH-3767 to branch 5.10 - Elasticsearch date/time bridges throw NPE on projections

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryImpl.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/ElasticsearchExtensionIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3783
=> HSEARCH-3783 query.explain() with the Elasticsearch backend fails when using projections or multi-tenancy

documentation/src/main/asciidoc/backend-elasticsearch.asciidoc, documentation/src/main/asciidoc/backend-lucene.asciidoc, documentation/src/main/asciidoc/mapper-orm-mapping.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-3418
=> HSEARCH-3418 Document that Instants are truncated to the millisecond when indexed

jsr352/jberet/src/main/java/org/hibernate/search/jsr352/jberet/impl/HibernateSearchJobXmlResolver.java
In reference of `org.jberet.spi.JobXmlResolver` it's defined that a resolver that is not responsible should return `null` instead of throwing a runtime exception. The exception prevent that further available resolver will be consider.
```
/**
* Locates the job XML and creates a stream to the contents.
*
* @param jobXml      the name of the job XML with a {@code .xml} suffix
* @param classLoader the class loader for the application
*
* @return a stream of the job XML or {@code null} if the job XML content was not found
*
* @throws java.io.IOException if an error occurs creating the stream
*/
```
=> HSEARCH-3801 Hibernate Search blocks loading of non hibernate batch jobs

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/work/impl/CountWork.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckTestRunner.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryTimeoutIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3802
=> HSEARCH-3802 query.fetchTotalHitCounts always fails when setting a timeout with Elasticsearch

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/esnative/impl/PropertyMappingJsonAdapterFactory.java
https://hibernate.atlassian.net/browse/HSEARCH-3819
I encountered the problem while working on something else.
I checked this solves the problem on my other branch, but I don't think it's worth an automated test. A lot of tests will fail in case of regression anyway, at least once my other branch is merged.
=> HSEARCH-3819 JsonSyntaxException when validating or migrating an Elasticsearch schema with a geo_point field with null_value

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3830
Backport of #2203.
=> Backport HSEARCH-3830 to branch 5.11 - Upgrade to Hibernate ORM 5.4.12.Final

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/AbstractLuceneDocumentBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/AbstractLuceneNonFlattenedDocumentBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneNestedObjectDocumentBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/impl/LuceneRootDocumentBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/common/impl/MetadataFields.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/work/impl/LuceneExplainWork.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/lowlevel/writer/LuceneIndexWriterCommitIT.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneIndexContentUtils.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/work/LuceneIndexingNestedIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexingFieldTypesIT.java
* [HSEARCH-3834](https://hibernate.atlassian.net/browse/HSEARCH-3834): Nested documents are never deleted
* [HSEARCH-3835](https://hibernate.atlassian.net/browse/HSEARCH-3835): Remove the unused "__HSEARCH_root_index_name" and "__HSEARCH_root_id" fields from nested documents
Based on #2212 , which should be merged first.
=> HSEARCH-3834 + HSEARCH-3835 Adjust index fields in nested documents

Jenkinsfile, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3843
Turns out the latest upgrade of ORM fixed the few problems we had.
Will merge as soon as the CI build succeeds.
Successful build on JDK15: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-yoann/detail/jdk15/4/pipeline/27
=> HSEARCH-3843 Test Hibernate Search with JDK15 regularly

documentation/src/main/asciidoc/mapper-orm-indexing-massindexer.asciidoc, documentation/src/main/asciidoc/mapper-orm-schema.asciidoc, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingFailureIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingBaseIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureCustomBackgroundFailureHandlerIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureCustomMassIndexingFailureHandlerIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureDefaultBackgroundFailureHandlerIT.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/service/AdminService.java, integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/LibraryShowcaseBaseIT.java, integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/LibraryShowcaseMassIndexingIT.java, integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/LibraryShowcaseMassIndexingManualSchemaManagementIT.java, integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/LibraryShowcaseOutOfSyncIndexIT.java, integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/LibraryShowcaseTransactionIT.java, integrationtest/showcase/library/src/test/resources/application-test.yaml, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/MassIndexer.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/BatchCoordinator.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/MassIndexerImpl.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/scope/impl/SearchScopeImpl.java
https://hibernate.atlassian.net/browse/HSEARCH-3751
Based on #2230 , which should be merged first.
=> HSEARCH-3751 dropAndCreateSchema() as an alternative to purge() in the MassIndexer

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3858
Checkstyle is looking to remove some deprecated methods and CI noticed that you are not on the latest maven-checkstyle-plugin which is still using some deprecated methods.
Issue: checkstyle/checkstyle/issues/7190
PR: checkstyle/checkstyle#7778
=> HSEARCH-3858 upgrade maven-checkstyle-plugin to 3.1.1

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/query/impl/FuzzyQueryBuilder.java, pom.xml
* [HSEARCH-3867](https://hibernate.atlassian.net/browse/HSEARCH-3867): Upgrade to Lucene 8.5.0
* [HSEARCH-3870](https://hibernate.atlassian.net/browse/HSEARCH-3870): Upgrade to Elasticsearch 7.6.1
=> HSEARCH-3867 + HSEARCH-3870 Upgrade to Lucene 8.5.0 / ES 7.6.1

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/scope/model/impl/ElasticsearchDifferentNestedObjectCompatibilityChecker.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/scope/model/impl/ElasticsearchScopeModel.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/AbstractElasticsearchSearchNestedPredicateBuilder.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicateBuilderFactoryImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/scope/model/impl/LuceneDifferentNestedObjectCompatibilityChecker.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/scope/model/impl/LuceneScopeModel.java
https://hibernate.atlassian.net/browse/HSEARCH-3883
I didn't add a test because it turns out that the code triggering the NPE [was relying on unsupported behavior](https://discourse.hibernate.org/t/hibernate-search-6-0-0-beta6-simplequerydsl-breaking/3977/6?u=yrodiere), but I think this cleanup is a good think regardless. We can ask ourselves whether we want to officially support that use case later.
=> HSEARCH-3883 NullPointerException when building a SimpleQueryString predicate

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/AbstractElasticsearchBucketAggregation.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/AbstractElasticsearchNestableAggregation.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchRangeAggregation.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchTermsAggregation.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/facet/impl/TextMultiValueFacetCounts.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/aggregation/SingleFieldAggregationBaseIT.java
* [HSEARCH-3893](https://hibernate.atlassian.net/browse/HSEARCH-3893): Elasticsearch aggregations return the count of nested (leaf) documents
* [HSEARCH-3894](https://hibernate.atlassian.net/browse/HSEARCH-3894): Lucene text aggregations count nested documents twice when they include the same term multiple times
=> HSEARCH-3893 + HSEARCH-3894 Bugfixes for aggregations on fields in nested documents

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/scope/model/impl/ElasticsearchScopeModel.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/impl/ElasticsearchSearchContext.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/ElasticsearchSearchQuery.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/scope/model/impl/LuceneScopeModel.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/impl/LuceneSearchContext.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/LuceneSearchQuery.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryImpl.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/ElasticsearchExtensionIT.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/LuceneExtensionIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3897
https://hibernate.atlassian.net/browse/HSEARCH-3898
I created the follow up (not solved here): HSEARCH-3899.
To use the entity id instead of the document id for the same API.
=> HSEARCH-3898 Change the explain API so that the type name is used

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/annotation/processing/CustomPropertyMappingAnnotationBaseIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/annotation/processing/CustomTypeMappingAnnotationBaseIT.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationPojoTypeMetadataContributorFactory.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/MappingAnnotatedElement.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/MappingAnnotatedProperty.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/MappingAnnotatedType.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/MappingAnnotationProcessorContext.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/PropertyMappingAnnotationProcessorContext.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/TypeMappingAnnotationProcessorContext.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/AbstractMappingAnnotationProcessorContext.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/AnnotationProcessorProvider.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/MappingAnnotationProcessorUtils.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/PropertyMappingAnnotationProcessorContextImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/TypeMappingAnnotationProcessorContextImpl.java
https://hibernate.atlassian.net/browse/HSEARCH-3901
Turns out we cannot use markers, or the existing `PojoModelElement` which relies on markers, because markers are derived from mapping annotations; essentially it's a problem of circular dependency.
Anyway, I managed to expose the annotations directly, which should be good enough.
=> HSEARCH-3901 Expose metadata about the annotated type in the context passed to PropertyMappingAnnotationProcessor/TypeMappingAnnotationProcessor

.travis.yml, util/internal/integrationtest/sharedresources/src/main/elasticsearch-maven-plugin/5.0/configuration/jvm.options, util/internal/integrationtest/sharedresources/src/main/elasticsearch-maven-plugin/6.0/configuration/jvm.options, util/internal/integrationtest/sharedresources/src/main/elasticsearch-maven-plugin/7.0/configuration/jvm.options
* [HSEARCH-3912](https://hibernate.atlassian.net/browse/HSEARCH-3912): Increase the amount of RAM assigned to Elasticsearch in integration tests
* [HSEARCH-3915](https://hibernate.atlassian.net/browse/HSEARCH-3915): Upgrade to the Ubuntu Bionic environment in .travis.yml
I verified the Travis build still works here: https://travis-ci.org/github/yrodiere/hibernate-search/jobs/684298909
=> HSEARCH-3912 + HSEARCH-3915 Increase the amount of RAM assigned to Elasticsearch in integration tests

documentation/src/main/asciidoc/backend-lucene.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-3275
This is just a bit of documentation. As I explained in a comment on the ticket, the concerns regarding resolution and stability of the implementations are no longer valid.
=> HSEARCH-3275 Document resolution of GeoPoint indexing for Lucene

Jenkinsfile, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java, documentation/src/test/java/org/hibernate/search/documentation/configuration/MyConfigurationIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java, pom.xml
* [HSEARCH-3918](https://hibernate.atlassian.net/browse/HSEARCH-3918): Upgrade to Elasticsearch 7.7.0
* [HSEARCH-3919](https://hibernate.atlassian.net/browse/HSEARCH-3919): Add test configuration to test AWS Elasticsearch Service 7.4
AWS build in progress here: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-yoann/detail/HSEARCH-3918/3/pipeline
=> HSEARCH-3918 + HSEARCH-3919 Upgrade to Elasticsearch 7.7.0 and AWS ES 7.4

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/automaticindexing/DefaultReindexOnUpdateIT.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/mapping/SearchMappingBuilder.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoImplicitReindexingResolverBuildingHelper.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/impl/PojoMapper.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/spi/AbstractPojoMappingInitiator.java
https://hibernate.atlassian.net/browse/HSEARCH-3842
@fax4ever Thanks to this, you shouldn't have to use `ReindexOnUpdate` in Infinispan at all, except in one specific place to set the default to `NO`.
=> HSEARCH-3842 Expose a global option to use ReindexOnUpdate.NO as a default

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/dynamicmap/DynamicMapBaseIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/common/impl/HibernateOrmUtils.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmIndexedTypeContext.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/EntityLoadingCacheLookupStrategyImplementor.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/HibernateOrmEntityIdEntityLoader.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/HibernateOrmLoadingIndexedTypeContext.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/HibernateOrmNonEntityIdPropertyEntityLoader.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/PersistenceContextLookupStrategy.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/PersistenceContextThenSecondLevelCacheLookupStrategy.java
* [HSEARCH-3925](https://hibernate.atlassian.net/browse/HSEARCH-3925): Move away from session.byId for entity loading
And because it came naturally from the changes in this PR:
* [HSEARCH-3772](https://hibernate.atlassian.net/browse/HSEARCH-3772): Allow mapping the document id to non-entity-id properties for ORM's dynamic-map entity types
This PR is based on #2291 ([HSEARCH-962](https://hibernate.atlassian.net/browse/HSEARCH-962)), which must be merged first.
=> HSEARCH-3925 Move away from session.byId for entity loading (+ HSEARCH-3772)

integrationtest/mapper/orm-cdi/src/test/java/org/hibernate/search/integrationtest/mapper/orm/cdi/CdiBeanResolutionIT.java, integrationtest/mapper/orm-cdi/src/test/java/org/hibernate/search/integrationtest/mapper/orm/cdi/CdiExtendedBeanManagerBootstrapShutdownIT.java, integrationtest/mapper/orm-cdi/src/test/java/org/hibernate/search/integrationtest/mapper/orm/cdi/StubExtendedBeanManager.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/ShutdownFailureIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateOrmBeanContainerBeanProvider.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateOrmIntegrationBooterImpl.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateSearchIntegrator.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateSearchSessionFactoryObserver.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
* [HSEARCH-3937](https://hibernate.atlassian.net/browse/HSEARCH-3937): Error messages on boot/shutdown are hidden or unclear when using an EnvironmentSynchronizer
* [HSEARCH-3938](https://hibernate.atlassian.net/browse/HSEARCH-3938): HibernateOrmIntegrationBooterImpl confuses the startup event for a shutdown event, and vice-versa
=> HSEARCH-3937 + HSEARCH-3938 Fix bootstrap when using an EnvironmentSynchronizer

documentation/src/main/asciidoc/backend-elasticsearch.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-3953
=> HSEARCH-3953 Document that zero-downtime reindexing is only doable if the schema did not change (for now)

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/GsonHttpEntity.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/orchestration/impl/LuceneSerialWorkOrchestratorImpl.java, backend/lucene/src/test/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/LoggerInfoStreamTest.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/PredicateScoreStep.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SearchPredicateIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryResultLoadingOrTransformingIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/ValueWrapper.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingBridgeExplicitDependenciesIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingBridgeExplicitReindexingBaseIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/ObsoletePropertiesIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingCacheLookupIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/PropertyBridgeBaseIT.java, jqassistant/rules.xml, legacy/pom.xml, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/event/impl/HibernateSearchEventListener.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMetatadaContributor.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/scope/impl/SearchScopeImpl.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/dsl/impl/HibernateOrmSearchQuerySelectStepImpl.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/SearchSession.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/impl/HibernateOrmSearchSession.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/impl/LazyInitSearchSession.java, mapper/orm/src/test/java/org/hibernate/search/mapper/orm/model/impl/AbstractHibernateOrmBootstrapIntrospectorPerReflectionStrategyTest.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/IndexedEmbedded.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/IndexedEmbeddedProcessor.java, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-2206
This essentially fixes existing deprecations (not related to Lucene APIs) and makes the build fail if we ever rely on deprecated code again.
=> HSEARCH-2206 Avoid using deprecated Lucene APIs in internals

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/providedid/ProvidedIdIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/AbstractPojoIndexingOperationIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/PojoIndexingAddIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/PojoIndexingAddOrUpdateIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/PojoIndexingDeleteIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/PojoIndexingPurgeIT.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/work/SearchIndexer.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/work/SearchIndexingPlan.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/work/impl/SearchIndexerImpl.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/work/impl/SearchIndexingPlanImpl.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/event/impl/HibernateSearchEventListener.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/IdentifierConsumerDocumentProducer.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/work/impl/SearchIndexingPlanImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/impl/PojoIndexedTypeManager.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/AbstractPojoTypeIndexingPlan.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoContainedTypeIndexingPlan.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoIndexedTypeIndexingPlan.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoIndexerImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoIndexingPlanImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoTypeIndexer.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoWorkIndexedTypeContext.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/spi/PojoIndexer.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/spi/PojoIndexingPlan.java
https://hibernate.atlassian.net/browse/HSEARCH-3891
~~draft since I haven't added the tests~~ done!
=> HSEARCH-3891 Allow POJO mapper implementations to pass explicit routing keys when indexing

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/ElasticsearchSearchQueryImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchScroll.java, documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc, documentation/src/main/asciidoc/reference/search-dsl-query.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/search/projection/ProjectionDslIT.java, documentation/src/test/java/org/hibernate/search/documentation/search/query/QueryDslIT.java, engine/src/main/java/org/hibernate/search/engine/search/query/SearchFetchable.java, engine/src/main/java/org/hibernate/search/engine/search/query/SearchScroll.java, engine/src/main/java/org/hibernate/search/engine/search/query/dsl/spi/AbstractSearchQueryOptionsStep.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/SearchMultiIndexIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryScrollIT.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/assertion/SearchHitsAssert.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/assertion/SearchResultAssert.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/BackendMock.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/NextScrollWorkCall.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/ScrollWorkCall.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/VerifyingStubBackendBehavior.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/StubBackendBehavior.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/StubSearchQuery.java
* [HSEARCH-3976](https://hibernate.atlassian.net/browse/HSEARCH-3976): Document scrolling
* [HSEARCH-3977](https://hibernate.atlassian.net/browse/HSEARCH-3977): Scroll always targets all indexes
=> HSEARCH-3976 + HSEARCH-3977 Documentation and bugfix for scrolling

documentation/src/main/asciidoc/reference/mapper-orm-mapping-alternatives.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-mapping.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/alternative/alternativebinder/AlternativeBinderIT.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/alternative/alternativebinder/BlogEntry.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/alternative/alternativebinder/Language.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/alternative/alternativebinder/LanguageAlternativeBinderDelegate.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/alternative/alternativebinder/MultiLanguageField.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/bridge/propertybridge/parameter/PropertyBridgeParameterIT.java, documentation/src/test/java/org/hibernate/search/documentation/testsupport/ElasticsearchSimpleMappingAnalysisConfigurer.java, documentation/src/test/java/org/hibernate/search/documentation/testsupport/LuceneSimpleMappingAnalysisConfigurer.java, documentation/src/test/resources/AlternativeBinderIT/dictionary_de.txt, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/alternative/AlternativeBinderIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/alternative/Language.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/alternative/LanguageAlternativeBinderDelegate.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/alternative/MultiLanguageField.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/alternative/impl/AlternativeBinderImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/alternative/impl/AlternativeDiscriminatorBinderImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/annotation/AlternativeDiscriminator.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/annotation/processor/impl/AlternativeDiscriminatorProcessor.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/programmatic/AlternativeBinder.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/programmatic/AlternativeBinderDelegate.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/programmatic/AlternativeDiscriminatorBinder.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/builtin/programmatic/AlternativeValueBridge.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/PropertyMappingStep.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/DelegatingPropertyMappingStep.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/InitialPropertyMappingStep.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/impl/PojoModelNestedCompositeElement.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/impl/PojoPropertyElementAccessor.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/impl/PojoRootElementAccessor.java
https://hibernate.atlassian.net/browse/HSEARCH-3311
I also included an experimental implementation, annotated with `@Incubating`. I think it's worth it, be it only to reduce the amount of code users need to write.
I believe the solution will evolve in the future, in particular if we address [HSEARCH-3903](https://hibernate.atlassian.net/browse/HSEARCH-3903). But for the time being... it works.
=> HSEARCH-3311 Test (and document) alternatives to analyzer discriminators in Search 6

Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-4005
=> HSEARCH-4005 Test Hibernate Search against Elasticsearch 7.7 on AWS

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/annotation/processing/CustomPropertyMappingAnnotationBaseIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/annotation/processing/CustomTypeMappingAnnotationBaseIT.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/impl/JavaBeanTypeConfigurationContributor.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMetatadaContributor.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationMappingConfigurationContextImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationPojoTypeMetadataContributorFactory.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/MappingAnnotatedElement.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/MappingAnnotatedProperty.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/MappingAnnotationProcessorContext.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/AbstractMappingAnnotationProcessorContext.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/PropertyMappingAnnotationProcessorContextImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/processing/impl/TypeMappingAnnotationProcessorContextImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/ProgrammaticMappingConfigurationContextImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/TypeMappingStepImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/impl/PojoMappingConfigurationContextImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/spi/AbstractPojoMappingInitiator.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/spi/PojoMappingConfigurationContext.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/spi/PojoMappingConfigurationContributor.java, util/common/src/main/java/org/hibernate/search/util/common/reporting/EventContext.java, util/common/src/main/java/org/hibernate/search/util/common/reporting/EventContextElement.java
* [HSEARCH-4003](https://hibernate.atlassian.net/browse/HSEARCH-4003): Automatically expand repeatable annotations in MappingAnnotatedElement
* [HSEARCH-4002](https://hibernate.atlassian.net/browse/HSEARCH-4002): Expose the type of a property for a given ContainerExtractorPath in MappingAnnotatedProperty
* [HSEARCH-4004](https://hibernate.atlassian.net/browse/HSEARCH-4004): Expose an eventContext from MappingAnnotationProcessorContext
Necessary for the Search 5 compatibility layer.
=> HSEARCH-4002 + HSEARCH-4003 + HSEARCH-4004 MappingAnnotatedElement improvements

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingNonUniqueDocumentIdIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/loading/impl/HibernateOrmNonEntityIdPropertyEntityLoader.java
https://hibernate.atlassian.net/browse/HSEARCH-4007
=> HSEARCH-4007 Throw an exception when the document ID turns out to be non-unique when loading entities during a search query

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToHibernateOrmScrollableResultsIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchScrollableResultsAdapter.java
https://hibernate.atlassian.net/browse/HSEARCH-4008
=> HSEARCH-4008 Hibernate Search ScrollableResults.getRowNumber() returns Integer.MAX_VALUE instead of -1 when after the last element

documentation/pom.xml, documentation/src/main/asciidoc/reference/getting-started.asciidoc, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3995
=> HSEARCH-3995 Add Lucene/Elasticsearch versions to the "Compatibility" section of the documentation

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearcherImpl.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/search/LuceneNoLimitSearchIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3947
=> HSEARCH-3947 Avoid creating huge arrays for collectors when a query does not have an upper bound limit

documentation/src/main/asciidoc/reference/mapper-orm-mapping-identifiermapping.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-4014
=> HSEARCH-4014 Document support for Character, Byte, Boolean, Float, Double as document identifiers

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/query/impl/ExplicitDocIdSetIterator.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/query/impl/ExplicitDocIdsQuery.java
https://hibernate.atlassian.net/browse/HSEARCH-4017
=> HSEARCH-4017 Don't scan index leaves that don't contain topdocs when applying projections

engine/src/main/java/org/hibernate/search/engine/search/loading/spi/DefaultProjectionHitMapper.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/stub/MapperEasyMockUtils.java
https://hibernate.atlassian.net/browse/HSEARCH-4016
=> HSEARCH-4016 Avoid call to loader.loadBlocking(<empty list>) when there are no entities to load

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/LuceneIndexSchemaObjectFieldNodeBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/LuceneIndexSchemaRootNodeBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/LuceneIndexSchemaValueFieldNodeBuilder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexModel.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaNodeCollector.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaObjectFieldTemplate.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/scope/model/impl/LuceneScopeSearchIndexesContext.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/ExtractionRequirements.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/LuceneCollectors.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/impl/LuceneSearchIndexesContext.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchQueryBuilder.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/search/LuceneSearchTopDocsMergeScoreSortIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryFetchIT.java
* [HSEARCH-4019](https://hibernate.atlassian.net/browse/HSEARCH-4019): Avoid adding a TotalHitCountCollector to Lucene queries unless absolutely necessary
* [HSEARCH-4018](https://hibernate.atlassian.net/browse/HSEARCH-4018): Avoid filtering out nested documents in Lucene queries when we know there are none
* [HSEARCH-3917](https://hibernate.atlassian.net/browse/HSEARCH-3917): Use TopScoreDocCollector when a descending score sort is requested explicitly
These pages are mostly about executing as little as possible for each hit, when collecting the topdocs.
Together, these patches bring significant performance improvements in @gustavonalle 's performance test that repeatedly and concurrently executes projections for a `MatchAllDocsQuery` on an index of 500,000 documents.
Note there aren't …
=> HSEARCH-3917 + HSEARCH-4018 + HSEARCH-4019 Performance improvements for queries matching many documents

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryFetchIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4019
This should fix this kind of failures: https://ci.hibernate.org/job/hibernate-search/job/master/863/testReport/junit/org.hibernate.search.integrationtest.backend.tck.search.query/SearchQueryFetchIT(elasticsearch-aws-7_7-it-elasticsearch)/Non_default_environments___elasticsearch_aws_7_7___fetch_offset_limit_defaultSort_3/
I'll start an AWS build and merge if the build passes.
=> HSEARCH-4019 Follow-up: fix tests for sharded indexes (AWS Elasticsearch Service in particular)

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingAssociationDeletionIT.java, integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/embedded/EmbeddedTest.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/impl/PojoIndexedTypeManager.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/AbstractPojoTypeIndexingPlan.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoContainedTypeIndexingPlan.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoIndexedTypeIndexingPlan.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoIndexingPlanImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoWorkContainedTypeContext.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoWorkIndexedTypeContext.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoWorkTypeContext.java
https://hibernate.atlassian.net/browse/HSEARCH-3999
I ended up disabling resolution of entities to reindex when a contained entity is deleted. It's a much smaller change than it sounds, since:
* In most cases, resolution of entities to reindex from a deleted entity will not work correctly (you'll get a `LazyInitializationException`).
* Even when it works, you'll need to update the other side of the relevant associations in order for the deleted entity to no longer appear in documents of index-embedding entities... so the index-embedding entities would have been reindexed anyway (because the association changed).
As a matter of fact, all our tests still pass even after this change. And we no longer have a `LazyInitializationException` when deleting contained entities.
=> HSEARCH-3999 Deletion of contained entity whose elementCollection is indexed-embedded in the containing entity leads to LazyInitializationException

Jenkinsfile, util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/ElasticsearchTestHostConnectionConfiguration.java
https://hibernate.atlassian.net/browse/HSEARCH-4026
=> HSEARCH-4026 Raise timeout for reaching yellow status when testing on AWS Elasticsearch Service

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/nonregression/model/IdClassIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmIndexedTypeContext.java
https://hibernate.atlassian.net/browse/HSEARCH-4025
=> HSEARCH-4025 Support Indexing entities with @IdClass if they have an explicit @DocumentId

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/Elasticsearch7SearchResultExtractor.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearchScrollImpl.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryScrollIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryTimeoutIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java, util/internal/integrationtest/mapper/stub/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/stub/BulkIndexer.java
* [HSEARCH-4028](https://hibernate.atlassian.net/browse/HSEARCH-4028): Elasticsearch's SearchResultTotal incorrectly reports an exact count after a timeout
* [HSEARCH-4027](https://hibernate.atlassian.net/browse/HSEARCH-4027): ScrollResult.timedOut() sometimes returns false even though a timeout occurred with Lucene
* [HSEARCH-3785](https://hibernate.atlassian.net/browse/HSEARCH-3785): Test soft timeout ( limiting fetching ) on Elasticsearch
=> HSEARCH-3785 + HSEARCH-4027 + HSEARCH-4028 Timeout tests and fixes

util/internal/integrationtest/sharedresources/src/main/elasticsearch-maven-plugin/5.0/configuration/jvm.options, util/internal/integrationtest/sharedresources/src/main/elasticsearch-maven-plugin/6.0/configuration/jvm.options, util/internal/integrationtest/sharedresources/src/main/elasticsearch-maven-plugin/7.0/configuration/jvm.options
https://hibernate.atlassian.net/browse/HSEARCH-4038
=> HSEARCH-4038 Assign more memory to the JVM used to run Elasticsearch locally in tests

integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java
https://hibernate.atlassian.net/browse/HSEARCH-2836
As it turns out:
* The Elasticsearch client no longer enforces a request timeout.
* Our own request timeout is only enforced when the user asks for it explicitly, typically for search queries.
As a result, the problem mentioned in this ticket no longer exists.
I added a few tests to demonstrate that even when the REST client is clogged up with many pending requests, the new requests won't incur a read timeout (because the read timeout starts when the request is actually sent).
They will incur a request timeout, but that's working as intended, since the request timeout is opt-in.
=> HSEARCH-2836 Timeouts start when the request is submitted to the client, leading to systematic timeout when client is under heavy load

integrationtest/showcase/library/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4024
According to [this page](https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started.html#:~:text=Spring%20Boot%202.3.,Spring%20Framework%205.2.) the new version of Spring Boot should support JDK-14.
=> HSEARCH-4024 Upgrade integration tests to the latest version of Spring Boot

documentation/pom.xml, documentation/src/main/asciidoc/migration/index.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-indexing-manual.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-mapping-reindexing.asciidoc, documentation/src/main/asciidoc/reference/search-dsl-query.asciidoc, documentation/src/main/assembly/dist.xml, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexing/HibernateOrmManualIndexingIT.java, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-3283
The goal was to have an extensive guide, and, well... it's extensive.
@fax4ever: maybe I should merge right away? Proof-reading this will take you a very long time...
=> HSEARCH-3283 Add an extensive migration guide to the documentation to help users migrate from Search 5 to Search 6

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/ExtractionRequirements.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/LuceneCollectors.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/search/LuceneSearchTopDocsTotalHitCountOnMatchAllDocsIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryBaseIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryScrollIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4068
This PR is based on #2414 , which should be merged first.
After this patch, when a user runs a `MatchAllDocsQuery` (and there are no nested documents), we automatically set the `totalHitCountThreshold` to 0 and compute the total hit count in constant time.
What's interesting about this? Well, if the user requested a sort by descending score, we are now able to skip non-competitive hits. Which means for example that if the index contains 500,000 documents and the user requested the first 10, we will go through 10 hits instead of 500,000.
Judging from performance tests in Infinispan, the impact on performance is not huge, but still not negligible.
Search 5.11:
```
[Done in 60.010000s] 1 node(s), 10 thread(s) per node: Query 90th: 3.850239, …
```
=> HSEARCH-4068 Skip non-competitive hits when running a MatchAllDocsQuery with descending score sort with Lucene

distribution/pom.xml, pom.xml
* [HSEARCH-4063](https://hibernate.atlassian.net/browse/HSEARCH-4063): Upgrade all publicly exposed dependencies to their latest available version
* [HSEARCH-4055](https://hibernate.atlassian.net/browse/HSEARCH-4055): Add the mapper-pojo-base module to the javadoc
=> HSEARCH-4055 + HSEARCH-4063 Build fix and upgrades

integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchDocumentRepositoryImpl.java
Yet another follow-up on https://hibernate.atlassian.net/browse/HSEARCH-4021
This is necessary to avoid failures such as [this one](https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2420/1/tests)
=> HSEARCH-4021 Flush after a purge in tests to ensure the purge is visible from tests

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4075
This is especially important to support newer versions of Hibernate ORM,
which will rely on methods introduced in this version of HCANN.
This version of HCANN is apparently backwards compatible, so users
should still be able to rely on older versions of ORM, as long as *we*
refrain from using newer methods introduced in HCANN 5.1.1.Final.
Waiting for the CI build to pass, then I'll merge.
=> HSEARCH-4075 Upgrade to Hibernate Annotations 5.1.1.Final

backend/lucene/src/test/java/org/hibernate/search/backend/lucene/lowlevel/writer/impl/LoggerInfoStreamTest.java, util/internal/integrationtest/v5migrationhelper/src/main/java/org/hibernate/search/test/util/impl/ExpectedLog4jLog.java, util/internal/test/src/main/java/org/hibernate/search/util/impl/test/rule/ExpectedLog4jLog.java, util/internal/test/src/main/java/org/hibernate/search/util/impl/test/rule/log4j/Log4j2ConfigurationAccessor.java, util/internal/test/src/main/java/org/hibernate/search/util/impl/test/rule/log4j/LogChecker.java
* [HSEARCH-4078](https://hibernate.atlassian.net/browse/HSEARCH-4078): Fix transient failure in LibraryShowcaseMassIndexingIT
* [HSEARCH-4077](https://hibernate.atlassian.net/browse/HSEARCH-4077): Avoid extra logging when using ExpectedLog4jLog
This should fix the build for the master branch, in particular.
=> HSEARCH-4077 + HSEARCH-4078 Avoid extra logging when using ExpectedLog4jLog

documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc, documentation/src/main/asciidoc/reference/backend-lucene.asciidoc, documentation/src/main/asciidoc/reference/components/explanation-warning.asciidoc, documentation/src/main/asciidoc/reference/index.asciidoc, documentation/src/main/asciidoc/reference/limitations.asciidoc, documentation/src/main/asciidoc/reference/search-dsl-projection.asciidoc, documentation/src/main/asciidoc/reference/search-dsl-query.asciidoc, documentation/src/main/asciidoc/reference/troubleshooting.asciidoc, integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/limitations/ConcurrentEmbeddedUpdateLimitationIT.java, util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/JPAPersistenceRunner.java, util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/NativePersistenceRunner.java, util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/OrmUtils.java, util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/PersistenceRunner.java
* [HSEARCH-4076](https://hibernate.atlassian.net/browse/HSEARCH-4076): Document loggers
* [HSEARCH-4064](https://hibernate.atlassian.net/browse/HSEARCH-4064): Add warnings in the documentation about concurrent updates to the same entity in a clustered application
=> HSEARCH-4064 + HSEARCH-4076 Document limitations and troubleshooting

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/query/impl/Elasticsearch7SearchResultExtractor.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/extraction/impl/LuceneCollectors.java, engine/src/main/java/org/hibernate/search/engine/cfg/spi/ConvertUtils.java, engine/src/main/java/org/hibernate/search/engine/search/query/spi/SimpleSearchResult.java, engine/src/main/java/org/hibernate/search/engine/search/query/spi/SimpleSearchResultTotal.java, engine/src/main/java/org/hibernate/search/engine/search/timeout/spi/TimeoutManager.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingBaseIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/search/loading/SearchQueryEntityLoadingMultipleTypesIT.java, util/common/src/main/java/org/hibernate/search/util/common/impl/TimeHelper.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/SearchWorkCall.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/VerifyingStubBackendBehavior.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/timeout/impl/StubTimeoutManager.java
* [HSEARCH-4080](https://hibernate.atlassian.net/browse/HSEARCH-4080): Lucene total hit count is wrongly considered exact on timeout
* [HSEARCH-4079](https://hibernate.atlassian.net/browse/HSEARCH-4079): Search query always times out when timeout is lower than 1ms
~Based on #2421 , which should be merged first.~ => Done
=> HSEARCH-4079 + HSEARCH-4080 Query timeout fixes

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchBackendSettings.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientFactoryImpl.java, documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4051
=> HSEARCH-4051 Restore support for configuring a path prefix for Elasticsearch backend

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchIndexSettings.java, documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc, documentation/src/test/resources/META-INF/persistence.xml, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendSetupStrategy.java, integrationtest/jdk/java-modules/src/main/resources/hibernate.properties, integrationtest/mapper/orm-batch-jsr352/src/test/resources/META-INF/persistence.xml, integrationtest/showcase/library/src/test/resources/application-test-elasticsearch.yaml, util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/ElasticsearchBackendConfiguration.java
https://hibernate.atlassian.net/browse/HSEARCH-4101
=> HSEARCH-4101 Change default required status for Elasticsearch indexes to "yellow"

integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationMappingAttributeIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationMappingBaseIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3821
I also spent some time searching for some cases to cover [JsonElementEquivalence#isObjectEquivalent](https://sonarcloud.io/code?id=org.hibernate.search%3Ahibernate-search-parent&selected=org.hibernate.search%3Ahibernate-search-parent%3Abackend%2Felasticsearch%2Fsrc%2Fmain%2Fjava%2Forg%2Fhibernate%2Fsearch%2Fbackend%2Felasticsearch%2Fvalidation%2Fimpl%2FJsonElementEquivalence.java).
But I didn't find a case for which we have to compare JSON objects, according to the use cases we have had so far.
=> HSEARCH-3821 Improve test coverage for Elasticsearch schema validation

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/DelegationWrapper.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToHibernateOrmSessionIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToJpaEntityManagerIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/hibernateormapis/ToSearchSessionFromSessionProxyIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingBaseIT.java, integrationtest/showcase/library/pom.xml, integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/LibraryShowcaseSessionProxyIT.java, integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/session/SessionTest.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/Search.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/common/impl/HibernateOrmUtils.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/session/impl/DelegatingSearchSession.java, pom.xml, v5migrationhelper/orm/src/main/java/org/hibernate/search/impl/FullTextSessionImpl.java
* [HSEARCH-4106](https://hibernate.atlassian.net/browse/HSEARCH-4106): Force tests to execute with JUnit 4
* [HSEARCH-4108](https://hibernate.atlassian.net/browse/HSEARCH-4108): Search.session() does not work with session proxies 
* [HSEARCH-4107](https://hibernate.atlassian.net/browse/HSEARCH-4107): Session cast fails when creating a FullTextSession with Spring 2.4.0
=> HSEARCH-4106 + HSEARCH-4107 + HSEARCH-4108 Session proxy fixes

documentation/src/main/asciidoc/reference/limitations.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-bridge-basics.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-bridge-identifierbridge.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-bridge-index-field-dsl.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-bridge-propertybridge.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-bridge-routingbridge.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-bridge-typebridge.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-bridge-valuebridge.asciidoc
* [HSEARCH-4113](https://hibernate.atlassian.net/browse/HSEARCH-4113): Document that serializing the indexing plan is not supported
* [HSEARCH-4074](https://hibernate.atlassian.net/browse/HSEARCH-4074): Clarify how to pick a bridge type in the documentation
=> HSEARCH-4074 + HSEARCH-4113 Clarify how to pick a bridge type in the documentation

engine/src/main/java/org/hibernate/search/engine/cfg/impl/MapConfigurationPropertySource.java, engine/src/main/java/org/hibernate/search/engine/cfg/impl/SystemConfigurationPropertySource.java, engine/src/main/java/org/hibernate/search/engine/cfg/spi/AllAwareConfigurationPropertySource.java, engine/src/main/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyChecker.java, engine/src/test/java/org/hibernate/search/engine/cfg/AbstractAllAwareConfigurationPropertySourceTest.java, engine/src/test/java/org/hibernate/search/engine/cfg/MapConfigurationPropertySourceTest.java, engine/src/test/java/org/hibernate/search/engine/cfg/SystemConfigurationPropertySourceTest.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/UnusedPropertiesIT.java, util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/ElasticsearchTestHostConnectionConfiguration.java, util/internal/test/src/main/java/org/hibernate/search/util/impl/test/rule/log4j/LogChecker.java
https://hibernate.atlassian.net/browse/HSEARCH-4116
=> HSEARCH-4116 Ignore empty, blank or null configuration properties when detecting unused properties

documentation/src/main/asciidoc/migration/index.asciidoc
* [HSEARCH-4129](https://hibernate.atlassian.net/browse/HSEARCH-4129): Mention More Like This queries in the migration guide
* [HSEARCH-4127](https://hibernate.atlassian.net/browse/HSEARCH-4127): Update out of date dependency versions in migration guide
=> HSEARCH-4127 + HSEARCH-4129 Migration guide fixes

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AbstractAutomaticIndexingAssociationIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AssociationModelPrimitives.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/AutomaticIndexingSingleAssociationIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/multi/AutomaticIndexingListAssociationIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/multi/AutomaticIndexingMapKeysAssociationIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/multi/AutomaticIndexingMapValuesAssociationIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/multi/AutomaticIndexingSortedMapValuesAssociationIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/multi/AutomaticIndexingSortedSetAssociationIT.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/AbstractPojoTypeIndexingPlan.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoIndexedTypeIndexingPlan.java
https://hibernate.atlassian.net/browse/HSEARCH-4137
=> HSEARCH-4137 Reindexing is skipped when a contained entity change follows a change that is irrelevant to indexing

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/model/DuplicateGetterIT.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/model/impl/JavaBeanPropertyModel.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/model/impl/JavaBeanRawTypeModel.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmClassPropertyModel.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmClassRawTypeModel.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/building/spi/ErrorCollectingPojoPropertyMetadataContributor.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/programmatic/impl/InitialPropertyMappingStep.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnBootstrapIntrospector.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnPropertyModel.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnRawTypeModel.java
https://hibernate.atlassian.net/browse/HSEARCH-4117
See #2472 . 
I'll backport it after all, because the changes seem relatively safe, and the error is cryptic enough that we've had multiple reports of this bug.
The SPI changes are a bit annoying, but AFAIK only Infinispan will be affected, and we'll be able to handle that.
Will merge as soon as the build passes.
=> Backport HSEARCH-4117 to branch 6.0 - "AssertionFailure: Unexpected duplicate key" when an entity has two getters for the same property

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessorImpl.java, backend/lucene/src/test/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessorTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4161
=> HSEARCH-4161 LuceneIndexManager.computeSizeInBytes() may fail if a file is deleted while computing size

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessorImpl.java, backend/lucene/src/test/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessorTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4161
Must be merged after #2499
=> Backport HSEARCH-4161 to branch 6.0 - LuceneIndexManager.computeSizeInBytes() may fail if a file is deleted while computing size

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/BackRefPropertyIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/JpaIdAsDocumentIdIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/model/SyntheticPropertyIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMetatadaContributor.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmBasicTypeMetadataProvider.java
https://hibernate.atlassian.net/browse/HSEARCH-4156
=> HSEARCH-4156 Hibernate Search incorrectly adds synthetic Hibernate ORM properties to the metamodel, ultimately leading to a bootstrap failure

mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoIndexedTypeIndexingPlan.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoIndexingPlanImpl.java, util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/automaticindexing/LocalHeapQueueIndexingEvent.java, util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/automaticindexing/LocalHeapQueueProcessor.java
* [HSEARCH-4165](https://hibernate.atlassian.net/browse/HSEARCH-4165): Avoid duplicate event sending when using PojoIndexingQueueEventSendingPlan
* [HSEARCH-4164](https://hibernate.atlassian.net/browse/HSEARCH-4164): Fix transient failure in AbstractAutomaticIndexingMultiAssociationIT
Follow-up on #2501 
Still unable to reproduce the issue locally... Let's see if it happens on CI when building this PR.
=> HSEARCH-4164 + HSEARCH-4165 Fix transient failure in AbstractAutomaticIndexingMultiAssociationIT

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cache/QueryCachingConfigurationContext.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cache/QueryCachingConfigurer.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cache/impl/LuceneQueryCachingContext.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cfg/LuceneBackendSettings.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendFactory.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/orchestration/impl/LuceneSyncWorkOrchestratorImpl.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/cache/LuceneQueryCacheConfigurerIT.java
https://hibernate.atlassian.net/browse/HSEARCH-3880
The extension allows you to define a custom implementation for QueryCache and QueryCachingPolicy. 
**Definitions are possible:** 
- Define with JPA parametr:
```
hibernate.search.backends.portal.cache.query_cache_provider=PortalQueryCachingPolicyProvider.class
hibernate.search.backends.portal.cache.query_caching_policy_provider=PortalQueryCachingPolicyProvider.class
```
Exemple custom implementation for QueryCache and QueryCachingPolicy:
```java
public class PortalQueryCacheProvider  implements QueryCacheProvider {
public QueryCache getQueryCache(BackendBuildContext context, ConfigurationPropertySource properties, Version luceneVersion) {
final int maxCachedQueries = 1000;
// min of 32MB or 5% of the heap size
final long maxRamBytesUsed …
```
=> HSEARCH-3880 Add query cache and query cache policy definition

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingConcurrentModificationInSameTypeIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/dynamicmap/DynamicMapBaseIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingErrorIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/AbstractMassIndexingFailureIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingBaseIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingComplexHierarchyIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingEmbeddedIdIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingInterruptionIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingMonitorIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingNonEntityIdDocumentIdIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingPrimitiveIdIT.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/BackendMock.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/DocumentKey.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/DocumentWorkCall.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/VerifyingStubBackendBehavior.java
https://hibernate.atlassian.net/browse/HSEARCH-4172
Should also fix https://hibernate.atlassian.net/browse/HSEARCH-4164
=> HSEARCH-4172 Ignore relative ordering of works on different documents in BackendMock

documentation/pom.xml, documentation/src/test/java/org/hibernate/search/documentation/configuration/ElasticsearchConfigurationIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java, parents/integrationtest/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4174
See #2508 ; I'm not upgrading to ES 7.11 in Search 6.0, but I still wanted to backport the small POM refactoring.
=> Backport HSEARCH-4174 to branch 6.0 - Reorganize Elasticsearch version properties in POM

engine/src/main/java/org/hibernate/search/engine/search/timeout/spi/TimeoutManager.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryBaseIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4183
=> HSEARCH-4183 SearchResult.took() returns incorrect, very large value with the Lucene backend

engine/src/main/java/org/hibernate/search/engine/search/timeout/spi/TimeoutManager.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryBaseIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4183
Backport of #2515
=> Backport HSEARCH-4183 to branch 6.0 - SearchResult.took() returns incorrect

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/PojoIndexingPlanBaseIT.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/impl/PojoImplicitReindexingResolverDirtinessFilterNode.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/impl/PojoImplicitReindexingResolverNode.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/impl/PojoImplicitReindexingResolverRootContext.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/AbstractPojoTypeIndexingPlan.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/work/impl/PojoIndexedTypeIndexingPlan.java
https://hibernate.atlassian.net/browse/HSEARCH-4184
=> HSEARCH-4184 A contained entity with only irrelevant changes may mistakenly trigger reindexing

mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/SearchSession.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/impl/JavaBeanSearchSession.java
https://hibernate.atlassian.net/jira/software/c/projects/HSEARCH/issues/HSEARCH-4185
Fix cast type when searching in mapper-javabean.
```java
SearchResult<Book> result /*not cast*/ = session.search( scope )
.where( (t) -> t.matchAll() )
.fetchAll();
```
=> HSEARCH-4185 Fix cast type when searching in mapper-javabean.

Jenkinsfile
https://hibernate.atlassian.net/browse/HSEARCH-4189
Backport of #2526
Build for all JDKs: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-yoann/detail/HSEARCH-4189-6.0/2/pipeline
=> Backport HSEARCH-4189 to branch 6.0 - Test Hibernate Search against JDK 17

Jenkinsfile, README.md, integrationtest/wildfly/pom.xml, jenkins/performance-elasticsearch.groovy, jenkins/performance-orm.groovy, pom.xml
* [HSEARCH-4190](https://hibernate.atlassian.net/browse/HSEARCH-4190): Backport Jenkinsfile improvements to 5.10/5.11
* [HSEARCH-4189](https://hibernate.atlassian.net/browse/HSEARCH-4189): Test Hibernate Search against JDK 17
Backport of #2526
=> Backport HSEARCH-4189 + HSEARCH-4190 to branch 5.11 - Test Hibernate Search against JDK 17

README.md
https://hibernate.atlassian.net/browse/HSEARCH-4207
It's really just a clarification, as source file headers already state that.
See https://github.com/hibernate/hibernate-orm/discussions/3903
=> HSEARCH-4207 Clarify in README that Hibernate Search is licensed under LGPL v2.1 *or later*

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4213
=> HSEARCH-4213 Upgrade to Jackson 2.12.x

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4213
Backport of #2547
=> Backport HSEARCH-4213 to branch 6.0 - Upgrade to Jackson 2.12.x

mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/SearchSession.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/impl/JavaBeanSearchSession.java
Session activity information is missing. This is very important if the previously opened session was opened by another code fragment in the same transaction. Elsewhere, the same session is accessed without knowing if a session shutdown was programmatically performed before. 
https://hibernate.atlassian.net/browse/HSEARCH-4215
Use case:
```java
String key = "some key";
if (key != null && TransactionHelper.isInTx()) {
session = SearchTransactionUtil.get(key);
}
if (session == null || !session.isOpen()) {
SearchMapping mapping = createMapping(unit, type, owner);
session = mapping.createSessionWithOptions().
loading((options) -> {
.........
}).build();
SearchTransactionUtil.put(key, session);
}
return session;                        
```
=> HSEARCH-4215 Add information about session activity.

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchLinkImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchClientSpy.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/rule/SearchSetupHelper.java
https://hibernate.atlassian.net/browse/HSEARCH-4214
Related: https://github.com/quarkusio/quarkus/pull/16655
=> HSEARCH-4214 hibernate.search.backend.version_check.enabled should be evaluated on backend startup

CONTRIBUTING.md, Jenkinsfile, integrationtest/backend/elasticsearch/pom.xml, parents/integrationtest/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4195
There aren't any binaries for OpenSearch yet, so I falled back to Open Distro for Elasticsearch. Moving to OpenSearch later should be trivial, though.
I will do the move to OpenSearch and document compatibility in another ticket: https://hibernate.atlassian.net/browse/HSEARCH-4212
=> HSEARCH-4195 Add continuous integration for OpenSearch / Open Distro for Elasticsearch

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchLinkImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchClientSpy.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/rule/SearchSetupHelper.java
https://hibernate.atlassian.net/browse/HSEARCH-4214
Backport of #2550
=> Backport HSEARCH-4214 to branch 6.0 - hibernate.search.backend.version_check.enabled should be evaluated on backend startup

integrationtest/backend/elasticsearch/pom.xml, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/categories/RequiresSingleModelDialectForMajorVersion.java
https://hibernate.atlassian.net/browse/HSEARCH-4214
Follow-up to #2550
=> HSEARCH-4214 follow-up: fix tests on Elasticsearch 5.6

integrationtest/backend/elasticsearch/pom.xml, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/categories/RequiresSingleModelDialectForMajorVersion.java
https://hibernate.atlassian.net/browse/HSEARCH-4214
Backport of #2557
=> HSEARCH-4214 follow-up (backport to 6.0): fix tests on Elasticsearch 5.6

backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java, parents/integrationtest/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4201
I didn't create a different slot for ES 7.12, I added it to the ES 7.11.
If we need a different slot ,this pull request must be changed.
=> HSEARCH-4201 Upgrade to Elasticsearch 7.12

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexModel.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/index/ElasticsearchIndexManager.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/index/impl/ElasticsearchIndexManagerImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/metamodel/ElasticsearchIndexDescriptor.java, documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/backend/elasticsearch/indexmanager/Book.java, documentation/src/test/java/org/hibernate/search/documentation/backend/elasticsearch/indexmanager/ElasticsearchIndexManagerIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/metamodel/ElasticsearchIndexDescriptorIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4204
=> Backport of HSEARCH-4204 Expose the Elasticsearch index names in the metamodel API

engine/src/main/java/org/hibernate/search/engine/backend/orchestration/spi/SingletonTask.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxEventBackgroundExecutor.java
https://hibernate.atlassian.net/browse/HSEARCH-4223
This fixes problems when testing Hibernate Search against ORM 5.5.
Will merge as soon as the build passes.
=> HSEARCH-4223 Outbox event background executor should stop as soon as Hibernate Search stops

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/outbox/OutboxPollingAutomaticIndexingStrategyLifecycleIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/outbox/OutboxPollingOutOfOrderIdsIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4202
Given the three cases provided by the description of the issue, only the second case seems not to be working...
Let's check that on review...
=> HSEARCH-4202 Test eventual consistency of outbox events in the wrong order

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/localheapqueue/LocalHeapQueueAutomaticIndexingStrategyBaseIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/FilteringOutboxEventFinder.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingAutomaticIndexingStrategyBaseIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingAutomaticIndexingStrategyEdgeIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingAutomaticIndexingStrategyLifecycleIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingAutomaticIndexingStrategyRoutingIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingNoProcessingIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/OutboxPollingOutOfOrderIdsIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/RoutedIndexedEntity.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/strategy/outbox/StatusRoutingBridge.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxEventBackgroundExecutor.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/outbox/impl/OutboxEventProcessingPlan.java
https://hibernate.atlassian.net/browse/HSEARCH-4230
=> HSEARCH-4230 Preserve the relative order of events for a given entity even in the case of retries

integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexIndexerIT.java, integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/AbstractBatchIndexingIT.java, integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/BatchIndexingJobIT.java, integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/EntityManagerFactoryRetrievalIT.java, integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/MassIndexingJobWithCompositeIdIT.java, integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/MassIndexingJobWithMultiTenancyIT.java, integrationtest/mapper/orm-batch-jsr352/src/test/java/org/hibernate/search/integrationtest/batch/jsr352/massindexing/RestartChunkIT.java, integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/routing/RoutingBridgeRoutingKeyIT.java, integrationtest/performance/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/performance/backend/elasticsearch/SmokeIT.java, integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/engine/worker/WorkerTestCase.java
https://hibernate.atlassian.net/browse/HSEARCH-4157
I just had a failure while working on the 6.0 branch, so let's backport these fixes.
=> Backport HSEARCH-4157 to branch 6.0 - Investigate timeout error on IndexIndexerIT

engine/src/main/java/org/hibernate/search/backend/impl/InTransactionWorkQueueSynchronization.java, engine/src/main/java/org/hibernate/search/backend/impl/PerTransactionWorker.java, engine/src/main/java/org/hibernate/search/backend/impl/PostTransactionWorkQueueSynchronization.java, engine/src/main/java/org/hibernate/search/util/impl/ConcurrentReferenceHashMap.java, orm/src/main/java/org/hibernate/search/event/impl/FullTextIndexEventListener.java, orm/src/test/java/org/hibernate/search/test/engine/NoTransactionTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4225
This bug is not relevant to Hibernate Search 6, since we don't rely on weak-reference hashmaps there (we simply store everything in the session).
=> HSEARCH-4225 Memory leak (SessionImpl) when updating index without transaction

mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingEntityLoadingRunnable.java
https://hibernate.atlassian.net/browse/HSEARCH-3878
I didn't have time to run full performance tests, but I did examine how it improves the behavior of backend executors.
Below are Gantt charts of the indexing batches handled by the backend during mass indexing. Each swimlane is an executor, and each "task" is a batch, with the color of each task ranging from dark red (few documents) to light green (many documents).
I generated this data by mass indexing in the [Hibernate Search Wikipedia demo](https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-elasticsearch-wikipedia). The application indexed approximately 35000 entites, a lot of which are quite text-heavy (Wikipedia pages).
(for future reference, here was the command I executed: `logs2gantt --regex …
=> HSEARCH-3878 Maximize utilization of database connections during mass indexing

backend/elasticsearch-aws/src/main/java/org/hibernate/search/backend/elasticsearch/aws/impl/ElasticsearchAwsBeanConfigurer.java, backend/elasticsearch-aws/src/main/java/org/hibernate/search/backend/elasticsearch/aws/impl/ElasticsearchAwsHttpClientConfigurer.java, backend/elasticsearch-aws/src/main/java/org/hibernate/search/backend/elasticsearch/aws/impl/ElasticsearchAwsStaticCredentialsProvider.java, backend/elasticsearch-aws/src/main/java/org/hibernate/search/backend/elasticsearch/aws/spi/ElasticsearchAwsCredentialsProvider.java
https://hibernate.atlassian.net/browse/HSEARCH-4250
=> HSEARCH-4250 Deprecate ElasticsearcAwsCredentialsProvider and make it extend a new ElasticsearchAwsCredentialsProvider

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingCachingIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/HibernateOrmMassIndexingContext.java
https://hibernate.atlassian.net/browse/HSEARCH-4272
=> HSEARCH-4272 Restore the previous default of CacheMode.IGNORE in the mass indexer

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingInterruptionIT.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/rule/CallQueue.java
https://hibernate.atlassian.net/browse/HSEARCH-4296
Backport of #2639 .
=> Backport HSEARCH-4296 to branch 6.0 - Make sure assertion errors in background threads caused by unexpected works will fail a test

engine/pom.xml, engine/src/main/java/org/hibernate/search/engine/Version.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/BootstrapLogsIT.java, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4307
Backport to 6.0: #2657
=> HSEARCH-4307 Hibernate Search version detection doesn't work on native images

jakarta/parents/internal/pom.xml, jakarta/pom.xml, jakarta/util/internal/integrationtest/pom.xml, parents/integrationtest/pom.xml, parents/internal/pom.xml, pom.xml, util/internal/integrationtest/pom.xml, util/internal/test/pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4240
This creates a separate parent POM for internal, non-integration-test artifacts.
This is needed for internal util modules, in particular:
those modules share a lot of characteristics with integration test
modules, but they definitely should be compiled with -release 8
so that we can freely reuse them when testing against JDK 8.
Integration tests, on the other hand, may be compiled with -release 11.
=> HSEARCH-4240 Follow-up: fix testing on JDK8

integrationtest/mapper/orm-coordination-database-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/databasepolling/FilteringOutboxEventFinder.java, mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/cluster/impl/DatabasePollingAgentAdditionalJaxbMappingProducer.java, mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/cluster/impl/DefaultAgentRepository.java, mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/event/impl/DatabasePollingOutboxEventAdditionalJaxbMappingProducer.java, mapper/orm-coordination-database-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/databasepolling/event/impl/DefaultOutboxEventFinder.java
https://hibernate.atlassian.net/browse/HSEARCH-4360
=> HSEARCH-4360 Use conflict-free entity names for entities added by the database-polling coordination strategy

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureCustomBackgroundFailureHandlerIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureCustomMassIndexingFailureHandlerIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingFailureDefaultBackgroundFailureHandlerIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingFailureCustomBackgroundFailureHandlerIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingFailureCustomMassIndexingFailureHandlerIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingFailureDefaultBackgroundFailureHandlerIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/operations/AbstractPojoIndexingProcessorFailureIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/operations/AbstractPojoReindexingResolutionFailureIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/operations/PojoIndexingAddIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/operations/PojoIndexingAddOrUpdateIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/operations/PojoIndexingDeleteIT.java, mapper/javabean/src/main/java/org/hibernate/search/mapper/javabean/session/impl/JavaBeanSearchSession.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoImplicitReindexingResolverPropertyNodeBuilder.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/impl/PojoImplicitReindexingResolverPropertyNode.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/common/annotation/impl/SearchProcessingWithContextException.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/processing/building/impl/PojoIndexingProcessorPropertyNodeBuilder.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/processing/impl/PojoIndexingProcessorPropertyNode.java, util/common/src/main/java/org/hibernate/search/util/common/logging/impl/Log.java, util/common/src/main/java/org/hibernate/search/util/common/reflect/impl/FieldValueReadHandle.java, util/common/src/main/java/org/hibernate/search/util/common/reflect/impl/MethodHandleValueReadHandle.java, util/common/src/main/java/org/hibernate/search/util/common/reflect/impl/MethodValueReadHandle.java, util/internal/test/src/main/java/org/hibernate/search/util/impl/test/ExceptionMatcherBuilder.java
https://hibernate.atlassian.net/browse/HSEARCH-4366
This simply adds context to exception thrown during processing, i.e. like this:
```
org.hibernate.search.util.common.SearchException: HSEARCH700083: Exception while building document for entity 'RootEntity#1': Simulated failure
Context: path '.containedNoContainer<no value extractors>.containedInContainer'
```
The path representation is far from perfect, but that's a more general problem. I'd say it's better than nothing: at least it gives a general idea of where the problem is in user code.
=> HSEARCH-4366 Add context to exceptions thrown during processing of POJOs (for indexing or reindexing resolution)

documentation/src/main/asciidoc/reference/search-dsl-predicate.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-4376
=> HSEARCH-4376 Document Elasticsearch normalizing regexps as a bug

documentation/src/main/asciidoc/reference/coordination.asciidoc, integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingShardingBaseIT.java, integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingStaticShardingIncompatibleConfigurationIT.java, integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingStaticShardingInvalidConfigurationIT.java, integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingStaticShardingUnevenShardsIT.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/HibernateOrmMapperOutboxPollingSettings.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/impl/OutboxPollingCoordinationStrategy.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/logging/impl/Log.java
* [HSEARCH-4372](https://hibernate.atlassian.net/browse/HSEARCH-4372): Simplify sharding configuration and move it to hibernate.search.coordination.event_processor.* properties
Based on #2713 , which should be merged first.
=> HSEARCH-4372 Simplify sharding configuration and move it to hibernate.search.coordination.event_processor.* properties

integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/model/AbstractInterfaceIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4385
=> HSEARCH-4385 Test that annotations on interfaces are correctly detected even when no implementation is known by HSearch

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/query/impl/LuceneSearcherImpl.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/query/SearchQueryFetchIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4401
=> HSEARCH-4401 Lucene backend ignores limit when offset + limit is higher than Integer.MAX_VALUE instead of reporting that it cannot handle it

.github/dependabot.yml, pom.xml
* [HSEARCH-4406](https://hibernate.atlassian.net/browse/HSEARCH-4406): Upgrade to jruby-complete 9.3.2.0
* [HSEARCH-4405](https://hibernate.atlassian.net/browse/HSEARCH-4405): Upgrade to log4j 2.15
=> HSEARCH-4405 + HSEARCH-4406 Upgrade to log4j 2.15, jruby-complete 9.3.2.0

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchRangeAggregation.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchFieldCodec.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchLongFieldCodec.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java, documentation/src/test/java/org/hibernate/search/documentation/testsupport/BackendConfigurations.java, documentation/src/test/resources/index-settings-for-tests/4-shards.json, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerStatusCheckIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendHelper.java, integrationtest/backend/elasticsearch/src/test/resources/index-settings-for-tests/1-shards.json, integrationtest/backend/elasticsearch/src/test/resources/index-settings-for-tests/2-shards.json, integrationtest/backend/elasticsearch/src/test/resources/index-settings-for-tests/3-shards.json, integrationtest/backend/elasticsearch/src/test/resources/index-settings-for-tests/4-shards.json, integrationtest/backend/elasticsearch/src/test/resources/index-settings-for-tests/5-replicas.json, integrationtest/backend/elasticsearch/src/test/resources/index-settings-for-tests/rare-periodic-refresh.json, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckBackendHelper.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendHelper.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/work/IndexWorkspaceRefreshIT.java, integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/testsupport/BackendConfigurations.java, integrationtest/mapper/orm-realbackend/src/test/resources/index-settings-for-tests/64-shards.json, parents/integrationtest/pom.xml, pom.xml, util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/rule/TestElasticsearchClient.java
* [HSEARCH-4397](https://hibernate.atlassian.net/browse/HSEARCH-4397): Switch to elastic/elasticsearch:* rather than the root elasticsearch:* for container images used in testing
* [HSEARCH-4396](https://hibernate.atlassian.net/browse/HSEARCH-4396): Upgrade to Elasticsearch client 7.16.0
* [HSEARCH-4340](https://hibernate.atlassian.net/browse/HSEARCH-4340): Run tests against Elasticsearch 7.16
=> HSEARCH-4340 + HSEARCH-4396 + HSEARCH-4397 Run tests against Elasticsearch 7.16

.github/dependabot.yml, pom.xml
* [HSEARCH-4416](https://hibernate.atlassian.net/browse/HSEARCH-4416): Upgrade to log4j 2.16.0
* [HSEARCH-4409](https://hibernate.atlassian.net/browse/HSEARCH-4409): Upgrade build dependencies to the latest version
=> HSEARCH-4409 + HSEARCH-4416 Upgrade build dependencies to the latest version

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4416
Partial backport of #2789
=> Backport HSEARCH-4416 to branch 6.0 - Upgrade to log4j 2.16.0

documentation/pom.xml, documentation/src/main/asciidoc/reference/coordination.asciidoc, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/HibernateOrmMapperOutboxPollingSettings.java
* [HSEARCH-4408](https://hibernate.atlassian.net/browse/HSEARCH-4408): Fix syntax highlighting for code example not working anymore in 6.0/6.1 documentation
* [HSEARCH-4391](https://hibernate.atlassian.net/browse/HSEARCH-4391): Fix images not being displayed in the documentation
* [HSEARCH-4389](https://hibernate.atlassian.net/browse/HSEARCH-4389): Remove mentions of hibernate.search.coordination.event_processor.shards.static from the documentation
=> HSEARCH-4389 + HSEARCH-4391 + HSEARCH-4408 Documentation fixes

documentation/pom.xml
* [HSEARCH-4408](https://hibernate.atlassian.net/browse/HSEARCH-4408): Fix syntax highlighting for code example not working anymore in 6.0/6.1 documentation
* [HSEARCH-4391](https://hibernate.atlassian.net/browse/HSEARCH-4391): Fix images not being displayed in the documentation
Backport of #2791
=> Backport HSEARCH-4391 + HSEARCH-4408 to branch 6.0 - Documentation fixes

.github/dependabot.yml, pom.xml
* [HSEARCH-4424](https://hibernate.atlassian.net/browse/HSEARCH-4424): Upgrade to latest version of build dependencies
* [HSEARCH-4422](https://hibernate.atlassian.net/browse/HSEARCH-4422): Upgrade to Jackson 2.13.1
* [HSEARCH-4421](https://hibernate.atlassian.net/browse/HSEARCH-4421): Upgrade to Log4j 2.17.1
* [HSEARCH-4420](https://hibernate.atlassian.net/browse/HSEARCH-4420): Upgrade to Lucene 8.11.1
=> HSEARCH-4420 + HSEARCH-4421 + HSEARCH-4422 + HSEARCH-4424 Dependency upgrades

CONTRIBUTING.md, Jenkinsfile, integrationtest/backend/elasticsearch/pom.xml, parents/integrationtest/pom.xml, pom.xml
* [HSEARCH-4413](https://hibernate.atlassian.net/browse/HSEARCH-4413): Run tests against Elasticsearch 7.16.2
* [HSEARCH-4411](https://hibernate.atlassian.net/browse/HSEARCH-4411): Run tests against Elasticsearch 7.16 by default instead of 7.10
* [HSEARCH-4410](https://hibernate.atlassian.net/browse/HSEARCH-4410): Upgrade to Elasticsearch client 7.16.2
=> HSEARCH-4410 + HSEARCH-4411 + HSEARCH-4413 Upgrade to Elasticsearch client 7.16.2

util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/rule/log4j/LogChecker.java
https://hibernate.atlassian.net/browse/HSEARCH-4434
=> HSEARCH-4434 Avoid unnecessary synchronization in ExpectedLog4jLog

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchLinkImpl.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java, integrationtest/backend/elasticsearch/src/test/resources/bootstrap-it/custom-mapping.json, integrationtest/backend/elasticsearch/src/test/resources/bootstrap-it/custom-settings.json
https://hibernate.atlassian.net/browse/HSEARCH-4435
=> HSEARCH-4435 Custom Elasticsearch settings/mapping require the backend to be started

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendImpl.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/logging/impl/Log.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/custom/ElasticsearchCustomIndexMappingIT.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/custom/ElasticsearchCustomIndexSettingsIT.java, integrationtest/backend/elasticsearch/src/test/resources/custom-index-mapping/not-parsable.json, integrationtest/backend/elasticsearch/src/test/resources/custom-index-mapping/unknown-parameter.json
https://hibernate.atlassian.net/browse/HSEARCH-4438
=> HSEARCH-4438 More detailed error message for syntax errors in custom mapping/settings file

.github/workflows/contributor-build.yml
https://hibernate.atlassian.net/browse/HSEARCH-4437
=> HSEARCH-4437 Fix very long Maven download timeouts when building with GitHub Actions

jakarta/parents/integrationtest/pom.xml, jakarta/parents/internal/pom.xml, jakarta/parents/public/pom.xml, orm6/parents/integrationtest/pom.xml, orm6/parents/internal/pom.xml, orm6/parents/public/pom.xml, pom.xml
* [HSEARCH-4449](https://hibernate.atlassian.net/browse/HSEARCH-4449): Upgrade to slf4j 1.7.33
* [HSEARCH-4448](https://hibernate.atlassian.net/browse/HSEARCH-4448): Upgrade to JBoss logging 3.4.3.Final
* [HSEARCH-4446](https://hibernate.atlassian.net/browse/HSEARCH-4446): Upgrade to Elasticsearch client 7.16.3
* [HSEARCH-4430](https://hibernate.atlassian.net/browse/HSEARCH-4430): Upgrade to latest version of build dependencies
=> HSEARCH-4430 + HSEARCH-4446 + HSEARCH-4448 + HSEARCH-4449 Dependency upgrades

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/gson/spi/GsonClasses.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/index/analysis/impl/AbstractCompositeAnalysisDefinition.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/gson/spi/GsonClassesTest.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/HibernateOrmMapperOutboxPollingSettings.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/mapping/spi/HibernateOrmMapperOutboxPollingClasses.java, mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/HibernateOrmMapperOutboxPollingSettingsTest.java, mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/mapping/spi/HibernateOrmMapperOutboxPollingClassesTest.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/cfg/HibernateOrmMapperSettings.java, util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/jar/JandexUtils.java
* [HSEARCH-4451](https://hibernate.atlassian.net/browse/HSEARCH-4451): Allow null tenant IDs in HibernateOrmMapperOutboxPollingSettings#coordinationKey
* [HSEARCH-4450](https://hibernate.atlassian.net/browse/HSEARCH-4450): Expose list of outbox-polling classes requiring reflection through an SPI
=> HSEARCH-4450 + HSEARCH-4451 Various improvements for integrators

documentation/src/main/asciidoc/migration/index.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-4441
=> HSEARCH-4441 Fix call to purge() in migration guide so that it compiles

mapper/orm/src/main/java/org/hibernate/search/mapper/orm/loading/impl/AbstractHibernateOrmSelectionEntityLoader.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchQueryAdapter.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/spi/HibernateOrmSearchQueryHints.java, orm6/mapper/orm/ant-src-changes.patch, orm6/v5migrationhelper/orm/ant-src-changes.patch, v5migrationhelper/orm/src/main/java/org/hibernate/search/query/hibernate/impl/FullTextQueryImpl.java
https://hibernate.atlassian.net/browse/HSEARCH-4458
=> HSEARCH-4458 Accept both Java EE and Jakarta EE flavours of all query hints

Jenkinsfile, parents/public/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4415
Backport of #2856
=> Backport HSEARCH-4415 to branch 6.0 - Sign published artifacts

build/config/src/main/java/org/hibernate/checkstyle/checks/regexp/DoubleSpacesCheck.java, pom.xml
* [HSEARCH-4468](https://hibernate.atlassian.net/browse/HSEARCH-4468): Upgrade to slf4j 1.7.35
* [HSEARCH-4467](https://hibernate.atlassian.net/browse/HSEARCH-4467): Upgrade build dependencies to the latest version
* [HSEARCH-4465](https://hibernate.atlassian.net/browse/HSEARCH-4465): Upgrade -orm6 artifacts to Hibernate ORM 6.0.0.CR1 (**follow-up** on #2866)
=> HSEARCH-4465 + HSEARCH-4467 + HSEARCH-4468 Upgrade dependencies

documentation/src/main/asciidoc/reference/mapper-orm-mapping-indexedembedded.asciidoc, documentation/src/main/asciidoc/reference/search-dsl-projection.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/structure/flattened/Author.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/structure/flattened/Book.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/structure/flattened/IndexedEmbeddedStructureFlattenedIT.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/structure/nested/Author.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/structure/nested/Book.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/structure/nested/IndexedEmbeddedStructureNestedIT.java
* [HSEARCH-4470](https://hibernate.atlassian.net/browse/HSEARCH-4470): Add mapping code examples to the documentation of @IndexedEmbedded.structure
* [HSEARCH-4464](https://hibernate.atlassian.net/browse/HSEARCH-4464): Document that custom bridges or projection converters are not applied to fields for source()/document() projections
=> HSEARCH-4464 + HSEARCH-4470 Documentation improvements

Jenkinsfile
* [HSEARCH-4478](https://hibernate.atlassian.net/browse/HSEARCH-4478): Run tests against AWS OpenSearch service
* [HSEARCH-3244](https://hibernate.atlassian.net/browse/HSEARCH-3244): Simplify configuration of AWS Elasticsearch endpoints in the Jenkins CI
=> HSEARCH-3244 + HSEARCH-4478 Simplify AWS testing config and run tests against AWS OpenSearch service

v5migrationhelper/engine/src/main/java/org/hibernate/search/query/dsl/RangeMatchingContext.java
Didn't open an issue in Jira for it.
Related Issue- https://github.com/checkstyle/checkstyle/issues/11268
Related PR- https://github.com/checkstyle/checkstyle/pull/11270
Every member class or interface declaration in the body of an interface declaration is implicitly public and static. See [JLS](https://docs.oracle.com/javase/specs/jls/se17/html/jls-9.html#jls-9.5) for more info.
=> HSEARCH-4479 Remove redundant public modifier reported by checkstyle

Jenkinsfile, jenkins/performance-elasticsearch.groovy, jenkins/release.groovy
* [HSEARCH-4472](https://hibernate.atlassian.net/browse/HSEARCH-4472): Move the release job to a separate Jenkinsfile
* [HSEARCH-3244](https://hibernate.atlassian.net/browse/HSEARCH-3244): Simplify configuration of AWS Elasticsearch endpoints in the Jenkins CI
=> Backport HSEARCH-3244 + HSEARCH-4472 to branch 6.0 - Jenkinsfile improvements

Jenkinsfile, jenkins/release.groovy
* [HSEARCH-4472](https://hibernate.atlassian.net/browse/HSEARCH-4472): Move the release job to a separate Jenkinsfile
* [HSEARCH-3244](https://hibernate.atlassian.net/browse/HSEARCH-3244): Simplify configuration of AWS Elasticsearch endpoints in the Jenkins CI
=> Backport HSEARCH-3244 + HSEARCH-4472 to branch 5.10 - Jenkinsfile improvements

backend/elasticsearch-aws/src/main/java/org/hibernate/search/backend/elasticsearch/aws/impl/AwsSigningRequestInterceptor.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/client/impl/GsonHttpEntityTest.java, pom.xml
* [HSEARCH-4486](https://hibernate.atlassian.net/browse/HSEARCH-4486): Upgrade to slf4j 1.7.36
* [HSEARCH-4485](https://hibernate.atlassian.net/browse/HSEARCH-4485): Upgrade to GSON 2.9.0
* [HSEARCH-4481](https://hibernate.atlassian.net/browse/HSEARCH-4481): Upgrade to elasticsearch-rest-client 8.0.0
=> HSEARCH-4481 + HSEARCH-4484 + HSEARCH-4485 + HSEARCH-4486 Dependency upgrades

CONTRIBUTING.md, Jenkinsfile, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/protocol/impl/Elasticsearch81ProtocolDialect.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/syntax/search/impl/Elasticsearch7SearchSyntax.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/syntax/search/impl/Elasticsearch81SearchSyntax.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/syntax/search/impl/ElasticsearchSearchSyntax.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/aggregation/impl/ElasticsearchRangeAggregation.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchFieldCodec.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/codec/impl/ElasticsearchLongFieldCodec.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java, integrationtest/backend/elasticsearch/pom.xml, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerUpdateCustomMappingIT.java, integrationtest/backend/elasticsearch/src/test/resources/custom-index-mapping/source-enabled.json, parents/integrationtest/pom.xml, pom.xml
* [HSEARCH-4497](https://hibernate.atlassian.net/browse/HSEARCH-4497): Run tests against Elasticsearch 8.0.1
* [HSEARCH-4505](https://hibernate.atlassian.net/browse/HSEARCH-4505): Add compatibility with Elasticsearch 8.1.0
=> HSEARCH-4497 + HSEARCH-4505 Add compatibility with Elasticsearch 8.1.0

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4512
Backport of #2947 to branch 6.1.
=> Backport HSEARCH-4512 to branch 6.1 - Upgrade to Hibernate ORM 5.6.7.Final

pom.xml
* [HSEARCH-4517](https://hibernate.atlassian.net/browse/HSEARCH-4517): Run tests against Elasticsearch 8.1.1
* [HSEARCH-4516](https://hibernate.atlassian.net/browse/HSEARCH-4516): Upgrade to Elasticsearch client 8.1.1
=> HSEARCH-4516 + HSEARCH-4517 Upgrade to Elasticsearch client 8.1.1 and run tests against Elasticsearch 8.1.1

pom.xml
* [HSEARCH-4518](https://hibernate.atlassian.net/browse/HSEARCH-4518): Upgrade to Jackson-databind 2.13.2.1
Follows up on https://github.com/hibernate/hibernate-search/pull/2895, https://github.com/hibernate/hibernate-search/pull/2902, https://github.com/hibernate/hibernate-search/pull/2904, #2913, #2931, #2941, #2954
=> HSEARCH-4484 + HSEARCH-4518 Upgrade build dependencies + Jackson-databind to the latest version

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchMatchNonePredicate.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSearchPredicateBuilderFactory.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneMatchNonePredicate.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneSearchPredicateBuilderFactory.java, documentation/src/main/asciidoc/reference/search-dsl-predicate.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/MatchNonePredicateFinalStep.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/SearchPredicateFactory.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/MatchNonePredicateFinalStepImpl.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/spi/AbstractSearchPredicateFactory.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/MatchNonePredicateBuilder.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/spi/SearchPredicateBuilderFactory.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/MatchNonePredicateSpecificsIT.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubSearchPredicate.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/stub/backend/search/predicate/impl/StubSearchPredicateBuilderFactory.java
https://hibernate.atlassian.net/browse/HSEARCH-4489
- add matchNone() to DSL
- update documentation to mention new predicate
I wasn't able to think of some simple yet, at the same time, meaningful use case for this new predicate, hence if anyone has some suggestions would be happy to add more tests around it.
=> HSEARCH-4489 Add matchNone() predicate

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4523
Backport of #2970 to branch 6.1.
=> Backport HSEARCH-4523 to branch 6.1 - Upgrade -orm6 artifacts to Hibernate ORM 6.0.0.Final

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4524
=> HSEARCH-4524 Upgrade Elasticsearch client to 8.1.2 and test against Elasticsearch 8.1.2

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/sort/impl/ElasticsearchDistanceSort.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/sort/impl/ElasticsearchStandardFieldSort.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/DistanceSortDynamicFieldIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSortDynamicFieldIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4531
=> HSEARCH-4531 Sort on dynamic field that has never been indexed yet fails on Elasticsearch

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/sort/impl/ElasticsearchDistanceSort.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/sort/impl/ElasticsearchStandardFieldSort.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/DistanceSortDynamicFieldIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSortDynamicFieldIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4531
Backport of #2987
=> Backport HSEARCH-4531 to branch 6.1 - Sort on dynamic field that has never been indexed yet fails on Elasticsearch

integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSearchSortTypeCheckingAndConversionIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSortDynamicFieldIT.java, util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/dialect/Elasticsearch5TestDialect.java, util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/dialect/Elasticsearch68TestDialect.java
https://hibernate.atlassian.net/browse/HSEARCH-4534
Backport of #2989.
=> Backport HSEARCH-4534 to branch 6.1 - Fix random failures for tests involving dynamic BigDecimal/BigInteger fields with Elasticsearch

integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSortDynamicFieldIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/FieldSortTypeCheckingAndConversionIT.java, util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/dialect/Elasticsearch5TestDialect.java, util/internal/integrationtest/backend/elasticsearch/src/main/java/org/hibernate/search/util/impl/integrationtest/backend/elasticsearch/dialect/Elasticsearch68TestDialect.java
https://hibernate.atlassian.net/browse/HSEARCH-4534
I managed to reproduce the problem on Elasticsearch 6.8, but not on 7.2 or 8.1. So I'll go ahead and assume this was a bug in 6.x that was fixed in 7.0, 7.1 or 7.2.
Though I couldn't find the relevant issue/PR on Elasticsearch's GitHub repository...
=> HSEARCH-4534 Fix random failures for tests involving dynamic BigDecimal/BigInteger fields with Elasticsearch

CONTRIBUTING.md, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4525
=> HSEARCH-4525 Fix generation of Avro sources with Intellij IDEA

integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingBaseIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingRoutingBridgeConditionalIndexingIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingRoutingBridgeRoutingKeyIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/operations/AbstractPojoIndexingOperationIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/operations/AbstractPojoIndexingPlanOperationBaseIT.java, mapper/orm-coordination-outbox-polling/src/main/avro/schema.avsc, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/avro/impl/EventPayloadFromDtoConverterUtils.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/avro/impl/EventPayloadSerializationUtils.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/avro/impl/EventPayloadToDtoConverterUtils.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/logging/impl/Log.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/runtime/impl/RoutingBridgeDocumentRouter.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/route/DocumentRoutesDescriptor.java, util/common/src/main/java/org/hibernate/search/util/common/impl/Contracts.java, util/common/src/main/java/org/hibernate/search/util/common/logging/impl/Log.java
* [HSEARCH-4538](https://hibernate.atlassian.net/browse/HSEARCH-4538): Provided routes with null "currentRoute" may lead to a null previousRoutes, exposing the mapper to NPE
* [HSEARCH-4537](https://hibernate.atlassian.net/browse/HSEARCH-4537): NPE with outbox-polling coordination strategy when routing prevents indexing
=> HSEARCH-4537 + HSEARCH-4538 NPE with outbox-polling coordination strategy when routing prevents indexing

integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingBaseIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingRoutingBridgeConditionalIndexingIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/AutomaticIndexingRoutingBridgeRoutingKeyIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/operations/AbstractPojoIndexingOperationIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/work/operations/AbstractPojoIndexingPlanOperationBaseIT.java, mapper/orm-coordination-outbox-polling/src/main/avro/schema.avsc, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/avro/impl/EventPayloadFromDtoConverterUtils.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/avro/impl/EventPayloadSerializationUtils.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/avro/impl/EventPayloadToDtoConverterUtils.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/logging/impl/Log.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/bridge/runtime/impl/RoutingBridgeDocumentRouter.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/route/DocumentRoutesDescriptor.java, util/common/src/main/java/org/hibernate/search/util/common/impl/Contracts.java, util/common/src/main/java/org/hibernate/search/util/common/logging/impl/Log.java
* [HSEARCH-4538](https://hibernate.atlassian.net/browse/HSEARCH-4538): Provided routes with null "currentRoute" may lead to a null previousRoutes, exposing the mapper to NPE
* [HSEARCH-4537](https://hibernate.atlassian.net/browse/HSEARCH-4537): NPE with outbox-polling coordination strategy when routing prevents indexing
Backport of #2994 to branch 6.1.
=> Backport HSEARCH-4537 + HSEARCH-4538 to branch 6.1 - NPE with outbox-polling coordination strategy when routing prevents indexing

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchSimpleQueryStringPredicate.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/predicate/impl/ElasticsearchTextRegexpPredicate.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/search/predicate/impl/LuceneSimpleQueryStringPredicate.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/types/predicate/impl/LuceneTextRegexpPredicate.java, documentation/src/main/asciidoc/reference/search-dsl-predicate.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/RegexpPredicateSpecificsIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/SimpleQueryStringPredicateSpecificsIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4536
Backport of #2993 to branch 6.1.
=> Backport HSEARCH-4536 to branch 6.1 - .flags(Collections.emptySet()) doesn't disable all flags as expected for SimpleQueryPredicate

jakarta/mapper/orm/pom.xml, orm6/mapper/orm/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4540
Backport of #3007 to branch 6.1.
=> Backport HSEARCH-4540 to branch 6.1 - Upgrade to the latest version of Jakarta dependencies in -orm6/-jakarta artifacts

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4543
Backport of #3009 to branch 6.1
=> Backport HSEARCH-4543 to branch 6.1 - Upgrade to Hibernate ORM 5.6.8.Final

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/facet/impl/TextMultiValueFacetCounts.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/aggregation/TermsAggregationSpecificsIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4544
Backport of #3011 to branch 6.1.
=> Backport HSEARCH-4544 to branch 6.1 - OutOfMemoryError when defining aggregation on text field with .maxTermCount(<very large value>)

pom.xml
* [HSEARCH-4555](https://hibernate.atlassian.net/browse/HSEARCH-4555): Upgrade to JBoss logging 3.5.0.Final
Follows up on https://github.com/hibernate/hibernate-search/pull/2895, https://github.com/hibernate/hibernate-search/pull/2902, https://github.com/hibernate/hibernate-search/pull/2904, #2913, #2931, #2941, #2954, #2293 #2983, #3021
=> HSEARCH-4484 + HSEARCH-4555 Upgrade dependencies

CONTRIBUTING.md, Jenkinsfile, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/syntax/search/impl/Elasticsearch81SearchSyntax.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java, integrationtest/backend/elasticsearch/pom.xml, parents/integrationtest/pom.xml, pom.xml
* [HSEARCH-4560](https://hibernate.atlassian.net/browse/HSEARCH-4560): Upgrade to Elasticsearch client 8.2.0
* [HSEARCH-4559](https://hibernate.atlassian.net/browse/HSEARCH-4559): Add compatibility with Elasticsearch 8.2.0
=> HSEARCH-4559 + HSEARCH-4560 Add compatibility with Elasticsearch 8.2.0

CONTRIBUTING.md, Jenkinsfile, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java, integrationtest/backend/elasticsearch/pom.xml, parents/integrationtest/pom.xml, pom.xml
* [HSEARCH-4564](https://hibernate.atlassian.net/browse/HSEARCH-4564): Run tests against AWS OpenSearch Service 1.2 instead of 1.1
* [HSEARCH-4562](https://hibernate.atlassian.net/browse/HSEARCH-4562): Add compatibility with OpenSearch 2.0
* [HSEARCH-4561](https://hibernate.atlassian.net/browse/HSEARCH-4561): Add compatibility with OpenSearch 1.3
=> HSEARCH-4561 + HSEARCH-4562 + HSEARCH-4564 Add compatibility with OpenSearch 1.3 + 2.0

.github/dependabot.yml, pom.xml
* [HSEARCH-4570](https://hibernate.atlassian.net/browse/HSEARCH-4570): Upgrade -orm6 artifacts to HCANN 6.0.1.Final
* [HSEARCH-4569](https://hibernate.atlassian.net/browse/HSEARCH-4569): Upgrade -orm6 artifacts to Hibernate ORM 6.0.1.Final
Backport of #3039 to branch 6.1
=> Backport HSEARCH-4569 + HSEARCH-4570 to branch 6.1 - Upgrade -orm6 artifacts to Hibernate ORM 6.0.1.Final

backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/IndexManagerBackendContext.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/LuceneIndexManagerImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/Shard.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/ShardHolder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/index/impl/ShardingStrategyInitializationContextImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/logging/impl/Log.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/directory/impl/LocalHeapDirectoryHolder.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessorImpl.java, backend/lucene/src/test/java/org/hibernate/search/backend/lucene/lowlevel/index/impl/IndexAccessorTest.java, engine/src/main/java/org/hibernate/search/engine/backend/index/spi/IndexManagerImplementor.java, engine/src/main/java/org/hibernate/search/engine/backend/spi/SavedState.java, engine/src/main/java/org/hibernate/search/engine/common/impl/IndexManagerNonStartedState.java, engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationBuilder.java, engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationImpl.java, engine/src/main/java/org/hibernate/search/engine/common/impl/SearchIntegrationPartialBuildStateImpl.java, engine/src/main/java/org/hibernate/search/engine/common/resources/spi/SavedState.java, engine/src/main/java/org/hibernate/search/engine/common/spi/SearchIntegration.java, engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java, engine/src/main/java/org/hibernate/search/engine/reporting/spi/RootFailureCollector.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/index/LuceneIndexRestartFromPreviousIntegrationIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/rule/SearchSetupHelper.java, util/common/src/main/java/org/hibernate/search/util/common/impl/AbstractCloser.java, util/common/src/main/java/org/hibernate/search/util/common/impl/SuppressingCloser.java, util/common/src/main/java/org/hibernate/search/util/common/spi/ClosingOperator.java
https://hibernate.atlassian.net/browse/HSEARCH-4566
draft => ~~I'm going to add a test~~ => done but ~~the test does not pass (still draft!)~~ => done
limited => with this contribution the promise:
> While Hibernate Search is restarting, the old Hibernate Search instance can be used.
won't be addressed
=> HSEARCH-4566 SPI for "hot" restart that allows compatible schema changes with Lucene without losing data in local-heap indexes

integrationtest/showcase/library/src/test/java/org/hibernate/search/integrationtest/showcase/library/LibraryShowcaseMassIndexingIT.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoMassIndexingLoggingMonitor.java
https://hibernate.atlassian.net/browse/HSEARCH-4483
- include the "between-iterations" speed as part of logged info
=> HSEARCH-4483 Update mass-indexing log message format

documentation/src/main/asciidoc/reference/coordination.asciidoc, integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingCustomEntityMappingIT.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/HibernateOrmMapperOutboxPollingSettings.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cfg/spi/HibernateOrmMapperOutboxPollingSpiSettings.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/cluster/impl/OutboxPollingAgentAdditionalJaxbMappingProducer.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/event/impl/OutboxPollingOutboxEventAdditionalJaxbMappingProducer.java, mapper/orm-coordination-outbox-polling/src/main/java/org/hibernate/search/mapper/orm/coordination/outboxpolling/logging/impl/Log.java, orm6/integrationtest/mapper/orm/ant-src-changes.patch, orm6/mapper/orm-coordination-outbox-polling/ant-src-changes.patch
https://hibernate.atlassian.net/browse/HSEARCH-4533
- define a set of properties for catalog/schema/tables names for
agent and outbox events
- make mapping producers to consider introduced properties
- make sure that statement inspector doesn't pick up keys on partial matches
I didn't find any "programmatic configuration" capability, only through the properties, or have I missed something ?
Also, I wasn't sure how to test with the custom schema/catalog. Simply specifying something doesn't work out of the box as it throws an exception that the underlying H2 doesn't have such schema. And I haven't yet dug deep to figure out how the `backendMock` and `ormSetupHelper` internals are working. Could you maybe point me to a sample where tests are using various schemas?
=> HSEARCH-4533 Introduce customizing properties for outbox polling

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/index/mapping/impl/RoutingTypeJsonAdapter.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/gson/spi/GsonParsingTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4580
=> HSEARCH-4580 "_routing" in custom Elasticsearch schema leads to "JsonIOException: JSON document was not fully consumed."

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/lowlevel/index/mapping/impl/RoutingTypeJsonAdapter.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/gson/spi/GsonParsingTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4580
Backport of #3046 to branch 6.1
=> Backport HSEARCH-4580 to branch 6.1 - "_routing" in custom Elasticsearch schema leads to "JsonIOException: JSON document was not fully consumed."

pom.xml
* [HSEARCH-4581](https://hibernate.atlassian.net/browse/HSEARCH-4581): Upgrade to Jackson 2.13.3
Follows up on https://github.com/hibernate/hibernate-search/pull/2895, https://github.com/hibernate/hibernate-search/pull/2902, https://github.com/hibernate/hibernate-search/pull/2904, #2913, #2931, #2941, #2954, #2293 #2983, #3021, #3028, #3041
=> HSEARCH-4484 + HSEARCH-4581 Upgrade dependencies

integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/nested/ProjectionAndOrderByNestedIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/FieldProjectionAndSortNestedIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4584
Turns out this was already fixed on `main` by #2955
=> HSEARCH-4584 Projection and sort on the same nested field fails with the Lucene Backend

integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/sync/OutOfSyncIndexIT.java, integrationtest/mapper/orm-realbackend/src/test/java/org/hibernate/search/integrationtest/mapper/orm/realbackend/util/BookCreatorUtils.java
Follows up on #3054 .
@marko-bekhta You may be interested in the first commit. I missed that during my review, otherwise I would have told you Hibernate Search has a built-in feature to make indexing synchronous :) We generally only use that in tests, because performance is bad, but it's *very* useful for tests.
=> HSEARCH-4571 Follow-up to fix tests

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/impl/AbstractElasticsearchStandardIndexFieldTypeOptionsStep.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/types/dsl/impl/ElasticsearchGeoPointIndexFieldTypeOptionsStep.java, documentation/src/main/asciidoc/migration/index.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-mapping-directfieldmapping.asciidoc, documentation/src/main/asciidoc/reference/search-dsl-projection.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedentities/SearchMappingIndexedEntitiesIT.java, engine/src/main/java/org/hibernate/search/engine/backend/types/Projectable.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/util/ElasticsearchTckBackendFeatures.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/testsupport/util/LuceneTckBackendFeatures.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/metamodel/IndexValueFieldTypeDescriptorBaseIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/DistanceProjectionMultiValuedBaseIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/DistanceProjectionSingleValuedBaseIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/DistanceProjectionTypeCheckingAndConversionIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/FieldProjectionMultiValuedBaseIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/FieldProjectionSingleValuedBaseIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/projection/FieldProjectionTypeCheckingAndConversionIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/sort/DistanceSortTypeCheckingAndConversionIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/spatial/DistanceSearchableSortableIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/model/singlefield/SingleFieldIndexBinding.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/testsupport/util/TckBackendFeatures.java
https://hibernate.atlassian.net/browse/HSEARCH-4575
- change the default behavior of projectable for ES
- extend Tck helper to expose the projectable defaults for backends
- update documentation
Haven't seen anything "updatable" on `SearchProjectionFactory` javadoc.
=> HSEARCH-4575 Make fields projectable by default for ES

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/cfg/ElasticsearchIndexSettings.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/impl/ElasticsearchBackendImpl.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/cfg/LuceneBackendSettings.java, backend/lucene/src/main/java/org/hibernate/search/backend/lucene/impl/LuceneBackendFactory.java, documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc, documentation/src/main/asciidoc/reference/backend-lucene.asciidoc, documentation/src/main/asciidoc/reference/configuration.asciidoc, documentation/src/main/asciidoc/reference/mapper-orm-mapping-programmatic.asciidoc, engine/src/main/java/org/hibernate/search/engine/cfg/package-info.java, engine/src/main/java/org/hibernate/search/engine/cfg/spi/ConvertUtils.java, engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java, engine/src/test/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyBeanReferenceTest.java, engine/src/test/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyInvalidSimpleValuesTest.java, engine/src/test/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyValidSimpleValuesTest.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/analysis/ElasticsearchAnalysisConfigurerIT.java, integrationtest/backend/lucene/src/test/java/org/hibernate/search/integrationtest/backend/lucene/analysis/LuceneAnalysisConfigurerIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/mapping/definition/HibernateOrmSearchMappingConfigurerIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/cfg/HibernateOrmMapperSettings.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/mapping/impl/HibernateOrmMappingInitiator.java, util/internal/integrationtest/mapper/orm/src/main/java/org/hibernate/search/util/impl/integrationtest/mapper/orm/SimpleSessionFactoryBuilder.java
https://hibernate.atlassian.net/browse/HSEARCH-4594
=> HSEARCH-4594 Allow multi-valued bean references for configurers defined in configuration properties

pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4596
Backport of #3074 to branch 6.1.
=> Backport HSEARCH-4596 to branch 6.1 - Upgrade to Hibernate ORM 6.0.2.Final for -orm6 artifacts

backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/work/execution/impl/ElasticsearchIndexIndexingPlanExecutionTest.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/work/impl/BulkWorkTest.java, backend/lucene/src/test/java/org/hibernate/search/backend/lucene/orchestration/impl/LuceneBatchedWorkProcessorTest.java, backend/lucene/src/test/java/org/hibernate/search/backend/lucene/work/execution/impl/LuceneIndexIndexingPlanExecutionTest.java, engine/src/test/java/org/hibernate/search/engine/cfg/spi/ConfigurationPropertyBeanReferenceTest.java, engine/src/test/java/org/hibernate/search/engine/common/impl/IndexManagerBuildingStateHolderTest.java, engine/src/test/java/org/hibernate/search/engine/mapper/mapping/building/impl/ConfiguredIndexSchemaManagerNestingContextTest.java, pom.xml
* [HSEARCH-4599](https://hibernate.atlassian.net/browse/HSEARCH-4599): Upgrade to Elasticsearch client 8.2.2 and test against Elasticsearch 8.2.2
* [HSEARCH-4598](https://hibernate.atlassian.net/browse/HSEARCH-4598): Upgrade to Reactive Streams 1.0.4
Follows up on https://github.com/hibernate/hibernate-search/pull/2895, https://github.com/hibernate/hibernate-search/pull/2902, https://github.com/hibernate/hibernate-search/pull/2904, #2913, #2931, #2941, #2954, #2293 #2983, #3021, #3028, #3041, #3052, #3066
=> HSEARCH-4484 + HSEARCH-4598 + HSEARCH-4599 Upgrade dependencies

documentation/src/main/asciidoc/reference/mapper-orm-bridge-index-field-dsl.asciidoc, documentation/src/main/asciidoc/reference/search-dsl-predicate.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-4597
Apparently there was only the one, and a missing period.
I used this regexp to look for more:
```
^(?!\s*[*/\[=:.@]|.*\||hibernate.search|spring.jpa).*[a-z]\n(?!\s*[a-z0-1\*"(<`>]|\.\.\.|--|\d\.|Hibernate|Unicode)
```
=> HSEARCH-4597 Fix unfinished sentences in the documentation

parents/integrationtest/pom.xml, pom.xml, util/internal/integrationtest/jbatch-runtime/src/main/resources/META-INF/services/batch-config.properties
* [HSEARCH-4610](https://hibernate.atlassian.net/browse/HSEARCH-4610): Upgrade to Elasticsearch client 8.2.3 and test against Elasticsearch 8.2.3
* [HSEARCH-4609](https://hibernate.atlassian.net/browse/HSEARCH-4609): Upgrade to Lucene 8.11.2
* [HSEARCH-4608](https://hibernate.atlassian.net/browse/HSEARCH-4608): Upgrade to the latest version of Jakarta dependencies in -orm6/-jakarta artifacts
=> HSEARCH-4484 + HSEARCH-4608 + HSEARCH-4609 + HSEARCH-4610 Upgrade dependencies

engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java, engine/src/main/java/org/hibernate/search/engine/reporting/spi/RootFailureCollector.java, engine/src/test/java/org/hibernate/search/engine/mapper/mapping/building/impl/ConfiguredIndexSchemaManagerNestingContextTest.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/DependencyIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/mapping/definition/IndexedEmbeddedBaseIT.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/AbstractPojoIndexingDependencyCollectorDirectValueNode.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/DerivedDependencyWalkingInfo.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorMonomorphicDirectValueNode.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorNode.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorPolymorphicDirectValueNode.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/building/impl/PojoIndexingDependencyCollectorPropertyNode.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/automaticindexing/impl/PojoImplicitReindexingResolverMultiNode.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/processing/impl/PojoIndexingProcessorMultiNode.java, util/common/src/main/java/org/hibernate/search/util/common/data/impl/LinkedNode.java, util/common/src/main/java/org/hibernate/search/util/common/impl/ToStringTreeBuilder.java, util/common/src/main/java/org/hibernate/search/util/common/logging/impl/ToStringTreeMultilineFormatter.java, util/common/src/test/java/org/hibernate/search/util/common/data/impl/LinkedNodeTest.java, util/common/src/test/java/org/hibernate/search/util/common/impl/ToStringTreeBuilderTest.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/util/impl/integrationtest/common/reporting/FailureReportChecker.java
* [HSEARCH-4565](https://hibernate.atlassian.net/browse/HSEARCH-4565): Cyclic dependency detection for IndexingDependency(derivedFrom = ...) does not detect "buried" cycles
* [HSEARCH-4611](https://hibernate.atlassian.net/browse/HSEARCH-4611): Improve exception and log messages involving multi-valued elements
=> HSEARCH-4565 + HSEARCH-4611 Cyclic dependency detection for IndexingDependency(derivedFrom = ...) does not detect "buried" cycles

pom.xml
* [HSEARCH-4540](https://hibernate.atlassian.net/browse/HSEARCH-4540): Upgrade to the latest version of Jakarta dependencies in -orm6/-jakarta artifacts
For HSEARCH-4540, follows up on #3007.
For HSEARCH-4484, follows up on https://github.com/hibernate/hibernate-search/pull/2895, https://github.com/hibernate/hibernate-search/pull/2902, https://github.com/hibernate/hibernate-search/pull/2904, #2913, #2931, #2941, #2954, #2293 #2983, #3021, #3028, #3041, #3052, #3066, #3083, #3092, #3100, #3110.
=> HSEARCH-4484 + HSEARCH-4540 Upgrade dependencies

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchBooleanPredicate.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/search/predicate/impl/ElasticsearchMatchNonePredicate.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/BoolPredicateSpecificsIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4619
=> HSEARCH-4619 Inconsistent behavior of boolean predicate when not adding any clause

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java, parents/integrationtest/pom.xml, pom.xml, util/internal/test/common/src/main/java/org/hibernate/search/util/impl/test/rule/log4j/LogChecker.java
* [HSEARCH-4623](https://hibernate.atlassian.net/browse/HSEARCH-4623): Upgrade to Elasticsearch client 8.3.0
* [HSEARCH-4622](https://hibernate.atlassian.net/browse/HSEARCH-4622): Add compatibility with Elasticsearch 8.3.0
=> HSEARCH-4622 + HSEARCH-4623 Add compatibility with Elasticsearch 8.3.0 + Upgrade to Elasticsearch client 8.3.0

.github/dependabot.yml, pom.xml
* [HSEARCH-4631](https://hibernate.atlassian.net/browse/HSEARCH-4631): Upgrade to Elasticsearch client 8.3.2 and test against Elasticsearch 8.3.2
* [HSEARCH-4628](https://hibernate.atlassian.net/browse/HSEARCH-4628): Upgrade to Hibernate ORM 5.6.10.Final
For HSEARCH-4484, follows up on https://github.com/hibernate/hibernate-search/pull/2895, https://github.com/hibernate/hibernate-search/pull/2902, https://github.com/hibernate/hibernate-search/pull/2904, #2913, #2931, #2941, #2954, #2293 #2983, #3021, #3028, #3041, #3052, #3066, #3083, #3092, #3100, #3110, #3118.
=> HSEARCH-4484 + HSEARCH-4628 + HSEARCH-4631 Upgrade dependencies

mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java, orm6/documentation/ant-src-changes.patch, orm6/mapper/orm/ant-src-changes.patch, pom.xml
* [HSEARCH-4635](https://hibernate.atlassian.net/browse/HSEARCH-4635): Prepare -orm6 artifacts for changes coming in Hibernate ORM 6.1.2.Final
* [HSEARCH-4627](https://hibernate.atlassian.net/browse/HSEARCH-4627): Upgrade to Hibernate ORM 6.1.1.Final for -orm6 artifacts
=> HSEARCH-4627 + HSEARCH-4635 Upgrade to Hibernate ORM 6.1.1.Final for -orm6 artifacts

documentation/src/main/asciidoc/migration/index.asciidoc, mapper/orm/src/test/java/org/hibernate/search/mapper/orm/model/impl/HibernateOrmBootstrapIntrospectorAnnotationReadingTest.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/impl/AnnotationMappingConfigurationContextImpl.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/hcann/spi/AbstractPojoHCAnnBootstrapIntrospector.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/model/spi/PojoBootstrapIntrospector.java, mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/model/impl/StandalonePojoBootstrapIntrospector.java, util/common/src/main/java/org/hibernate/search/util/common/reflect/spi/MemberValueHandleFactory.java, util/common/src/main/java/org/hibernate/search/util/common/reflect/spi/MethodHandleValueHandleFactory.java, util/common/src/main/java/org/hibernate/search/util/common/reflect/spi/ValueReadHandleFactory.java
* [HSEARCH-4637](https://hibernate.atlassian.net/browse/HSEARCH-4637): Document API/SPI changes for 6.2.0.Alpha1
* [HSEARCH-4636](https://hibernate.atlassian.net/browse/HSEARCH-4636): Document behavior change in the migration guide for boolean predicates with no clause with the Elasticsearch backend
=> HSEARCH-4636 + HSEARCH-4637 Update migration guide for 6.2

integrationtest/backend/elasticsearch/pom.xml, integrationtest/backend/lucene/pom.xml, integrationtest/mapper/orm-coordination-outbox-polling/pom.xml, jakarta/integrationtest/mapper/orm-coordination-outbox-polling/pom.xml, jakarta/parents/integrationtest/pom.xml, jakarta/parents/internal/pom.xml, jakarta/parents/public/pom.xml, orm6/integrationtest/mapper/orm-coordination-outbox-polling/pom.xml, orm6/parents/integrationtest/pom.xml, orm6/parents/internal/pom.xml, orm6/parents/public/pom.xml, pom.xml
* [HSEARCH-4649](https://hibernate.atlassian.net/browse/HSEARCH-4649): Fix "File name too long" errors when creating test reports
* [HSEARCH-4648](https://hibernate.atlassian.net/browse/HSEARCH-4648): Restore execution of many automatic indexing tests when testing outbox polling
Follows up on #3150
=> HSEARCH-4648 + HSEARCH-4649 Follow-up: orm6/jakarta integration test fixes

integrationtest/backend/elasticsearch/pom.xml, integrationtest/backend/lucene/pom.xml, integrationtest/mapper/orm-coordination-outbox-polling/pom.xml, jakarta/integrationtest/mapper/orm-coordination-outbox-polling/pom.xml, jakarta/parents/integrationtest/pom.xml, jakarta/parents/internal/pom.xml, jakarta/parents/public/pom.xml, orm6/integrationtest/mapper/orm-coordination-outbox-polling/pom.xml, orm6/parents/integrationtest/pom.xml, orm6/parents/internal/pom.xml, orm6/parents/public/pom.xml, pom.xml
* [HSEARCH-4649](https://hibernate.atlassian.net/browse/HSEARCH-4649): Fix "File name too long" errors when creating test reports
* [HSEARCH-4648](https://hibernate.atlassian.net/browse/HSEARCH-4648): Restore execution of many automatic indexing tests when testing outbox polling
Follows up on #3151
=> Backport HSEARCH-4648 + HSEARCH-4649 to branch 6.1 - Follow-up: orm6/jakarta integration test fixes

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/validation/impl/LeafValidator.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/validation/impl/PropertyMappingValidator.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationMappingAttributeIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4652
=> HSEARCH-4652 Schema validation fails if search analyzer is set explicitly to the same value as the analyzer

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/validation/impl/LeafValidator.java, backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/validation/impl/PropertyMappingValidator.java, integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/schema/management/ElasticsearchIndexSchemaManagerValidationMappingAttributeIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4652
Backport of #3158 to branch 6.1
=> Backport HSEARCH-4652 to branch 6.1 - Schema validation fails if search analyzer is set explicitly to the same value as the analyzer

engine/src/main/java/org/hibernate/search/engine/logging/impl/Log.java, engine/src/main/java/org/hibernate/search/engine/reporting/spi/RootFailureCollector.java, engine/src/test/java/org/hibernate/search/engine/reporting/spi/RootFailureCollectorTest.java, util/common/src/main/java/org/hibernate/search/util/common/data/impl/InsertionOrder.java, util/common/src/test/java/org/hibernate/search/util/common/data/impl/InsertionOrderTest.java
https://hibernate.atlassian.net/browse/HSEARCH-4654
Best reviewed commit by commit.
See the second commit for the actual fix, with an explanation of the problem in the commit message.
See the third commit for a reproducer of the problem (in a unit test).
The last commit is not strictly necessary, but I think it's a good idea nevertheless, because it will prevent deadlocks from ever happening again in `RootFailureCollector`
cc @gsmet
=> HSEARCH-4654 Deadlock in RootFailureCollector when exceeding the failure limit (100) with concurrent failures from different threads

pom.xml
* [HSEARCH-4661](https://hibernate.atlassian.net/browse/HSEARCH-4661): Upgrade to JBeret 1.4.8.Final
* [HSEARCH-4660](https://hibernate.atlassian.net/browse/HSEARCH-4660): Upgrade to GSON 2.9.1
* [HSEARCH-4659](https://hibernate.atlassian.net/browse/HSEARCH-4659): Upgrade to Avro 1.11.1
* [HSEARCH-4642](https://hibernate.atlassian.net/browse/HSEARCH-4642): Upgrade build dependencies to the latest version
For [HSEARCH-4642](https://hibernate.atlassian.net/browse/HSEARCH-4642), folllows up on #3146, #3148, #3157
=> HSEARCH-4642 + HSEARCH-4659 + HSEARCH-4660 + HSEARCH-4661 Upgrade dependencies

pom.xml
For [HSEARCH-4642](https://hibernate.atlassian.net/browse/HSEARCH-4642), folllows up on #3146, #3148, #3157, #3176
=> HSEARCH-4642 Upgrade build dependencies to the latest version

documentation/src/main/asciidoc/migration/index.asciidoc
https://hibernate.atlassian.net/browse/HSEARCH-4665
=> HSEARCH-4665 Fix Asciidoc formatting of the migration guide

documentation/src/main/asciidoc/reference/backend-elasticsearch.asciidoc, documentation/src/main/asciidoc/reference/backend-lucene.asciidoc, documentation/src/main/asciidoc/reference/compatibility.asciidoc, documentation/src/main/asciidoc/reference/components/field-aggregation-important.asciidoc, documentation/src/main/asciidoc/reference/components/field-projection-important.asciidoc, documentation/src/main/asciidoc/reference/components/field-sort-important.asciidoc, documentation/src/main/asciidoc/reference/indexing-massindexer.asciidoc, documentation/src/main/asciidoc/reference/mapping-directfieldmapping.asciidoc, documentation/src/main/asciidoc/reference/search-dsl-aggregation.asciidoc, documentation/src/main/asciidoc/reference/search-dsl-projection.asciidoc, documentation/src/main/asciidoc/reference/search-dsl-sort.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/analysis/AnalysisIT.java, documentation/src/test/java/org/hibernate/search/documentation/analysis/DefaultOverridingElasticsearchAnalysisConfigurer.java, documentation/src/test/java/org/hibernate/search/documentation/analysis/DefaultOverridingLuceneAnalysisConfigurer.java, documentation/src/test/resources/analysis/elasticsearch-default-override.properties, documentation/src/test/resources/analysis/lucene-default-override.properties, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/mapping/definition/annotation/FullTextField.java
* [HSEARCH-4658](https://hibernate.atlassian.net/browse/HSEARCH-4658): Document the syntax of conditions passed to the mass indexer
* [HSEARCH-4653](https://hibernate.atlassian.net/browse/HSEARCH-4653): Document built-in analyzers and how to override them
* [HSEARCH-4646](https://hibernate.atlassian.net/browse/HSEARCH-4646): Document that Spring Boot may create a (wrong) Elasticsearch client just because Hibernate Search adds the Elasticsearch client to the classpath
* [HSEARCH-4554](https://hibernate.atlassian.net/browse/HSEARCH-4554): Update documentation of default credentials provider chain for Elasticsearch AWS
* [HSEARCH-4551](https://hibernate.atlassian.net/browse/HSEARCH-4551): Make the mapping requirements of sorts/projections/aggregations more visible in the documentation
=> HSEARCH-4551 + HSEARCH-4554 + HSEARCH-4646 + HSEARCH-4653 + HSEARCH-4658 Documentation improvements

documentation/src/main/asciidoc/reference/indexing-massindexer.asciidoc, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/massindexing/MassIndexingBaseIT.java, integrationtest/mapper/pojo-base/src/test/java/org/hibernate/search/integrationtest/mapper/pojo/massindexing/MassIndexingBaseIT.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/logging/impl/Log.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/impl/PojoDefaultMassIndexer.java, mapper/pojo-base/src/main/java/org/hibernate/search/mapper/pojo/massindexing/spi/PojoMassIndexer.java, mapper/pojo-standalone/src/main/java/org/hibernate/search/mapper/pojo/standalone/massindexing/MassIndexer.java
- https://hibernate.atlassian.net/browse/HSEARCH-4612
Hey! I thought that it would also be good to log a message if someone enables two settings at the same time, but wasn't sure about the log level... not much else to add about the changes 😃 
Also is this something that we should document in the migration guide? Or as in the end, the results are still the same we don't want to clutter the doc?
=> HSEARCH-4612 Disable purgeAllOnStart by default in MassIndexer when dropAndCreateSchemaOnStart is enabled

documentation/src/main/asciidoc/reference/search-dsl-predicate.asciidoc, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/bridge/namedpredicate/SkuIdentifierBinder.java, documentation/src/test/java/org/hibernate/search/documentation/mapper/orm/indexedembedded/structure/flattened/IndexedEmbeddedStructureFlattenedIT.java, documentation/src/test/java/org/hibernate/search/documentation/search/paths/FieldPathsIT.java, documentation/src/test/java/org/hibernate/search/documentation/search/predicate/PredicateDslIT.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/GenericSimpleBooleanOperatorPredicateClausesStep.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/SearchPredicateFactory.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/SimpleBooleanOperatorPredicateClausesCollector.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/SimpleBooleanOperatorPredicateClausesStep.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/SimpleBooleanOperatorPredicateOptionsStep.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/impl/SimpleBooleanOperatorPredicateClausesStepImpl.java, engine/src/main/java/org/hibernate/search/engine/search/predicate/dsl/spi/AbstractSearchPredicateFactory.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/AndPredicateBaseIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/AndPredicateSpecificsIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/OrPredicateBaseIT.java, integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/search/predicate/OrPredicateSpecificsIT.java
https://hibernate.atlassian.net/browse/HSEARCH-4601
Hi!
So, I went back to this PR and I hope I got it right this time after my initial botching.
I have added support for basic n-ary or(...) / and(...) constructs _à la_
```
f.or( f.match().field("foo").matching("val1"),
f.match().field("bar").matching("val2") )
f.and( f.match().field("foo").matching("val1"),
f.match().field("bar").matching("val2") )
```
I haven't yet added builder-style constructs with `.add(...)` and `with(...)`.
I guess that should be done.
I haven't updated the documentation yet either.
Before I take the next step, is this going in the right direction?  ;-)
I have added new tests in `BoolPredicateSpecificsIT`, as they are more or less cloned from `bool()` ones.
This makes the file name not very relevant...
Shall I add …
=> HSEARCH-4601 Syntactic sugar for OR/AND predicates

backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactory.java, backend/elasticsearch/src/test/java/org/hibernate/search/backend/elasticsearch/dialect/impl/ElasticsearchDialectFactoryTest.java, parents/integrationtest/pom.xml, pom.xml
* [HSEARCH-4681](https://hibernate.atlassian.net/browse/HSEARCH-4681): Add compatibility with Elasticsearch 8.4
* [HSEARCH-4680](https://hibernate.atlassian.net/browse/HSEARCH-4680): Upgrade to Elasticsearch client 8.4
=> HSEARCH-4680 + HSEARCH-4681 Upgrade to Elasticsearch 8.4

integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/BootstrapLogsIT.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/bootstrap/impl/HibernateSearchPreIntegrationService.java, mapper/orm/src/main/java/org/hibernate/search/mapper/orm/cfg/spi/HibernateOrmMapperSpiSettings.java
https://hibernate.atlassian.net/browse/HSEARCH-4503
~~Draft until we know for sure which property key we'll want to use; see https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/INFO.20messages.20on.20native-image~~ => Jboss-threads went with `jboss.log-version`, so we're going to go with that. See https://github.com/jbossas/jboss-threads/pull/120/files#diff-f7179ffcce5656c32a94e972f59059723d7d9d1c53bc3274c1d7bdda0b6a212aR61
=> HSEARCH-4503 Disable version logging through system properties

pom.xml
* [HSEARCH-4697](https://hibernate.atlassian.net/browse/HSEARCH-4697): Upgrade to Jackson 2.13.4
* [HSEARCH-4642](https://hibernate.atlassian.net/browse/HSEARCH-4642): Upgrade build dependencies to the latest version
=> HSEARCH-4642 + HSEARCH-4697 Upgrade dependencies

integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/FilteringOutboxEventFinder.java, integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingEdgeCasesIT.java, integrationtest/mapper/orm-coordination-outbox-polling/src/test/java/org/hibernate/search/integrationtest/mapper/orm/coordination/outboxpolling/automaticindexing/OutboxPollingAutomaticIndexingOutOfOrderIdsIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedEagerOnBothSidesIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedLazyOnContainedSideIT.java, integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/automaticindexing/association/bytype/onetoone/ownedbycontained/AutomaticIndexingOneToOneOwnedByContainedLazyOnContainingSideIT.java, pom.xml
https://hibernate.atlassian.net/browse/HSEARCH-4707
Backport of #3256 to branch 6.1.
=> Backport HSEARCH-4707 to branch 6.1 - Upgrade to Hibernate ORM 5.6.12.Final
